### ISSUE TITLE
Data for a subobject of SMWExtInfo cannot be added to SMW_Sandbox:SMWExtInfo

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#1250]
This came up upon rebuilding data at sandbox.smw.o

```text
[909d1df6] [no req]   MWException from line 640 of /.../w/extensions/SemanticMediaWiki/includes/SemanticData.php: Data for a subobject of SMWExtInfo cannot be added to SMW_Sandbox:SMWExtInfo.
Backtrace:
#0 /.../w/extensions/SemanticMediaWiki/includes/SemanticData.php(326): SMW\SemanticData->addSubSemanticData(SMWContainerSemanticData)
#1 /.../w/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(224): SMW\SemanticData->addPropertyObjectValue(SMW\DIProperty, SMWDIContainer)
#2 /.../w/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(195): SMW\AskParserFunction->createQueryProfile(SMWQuery, string, integer)
#3 /.../w/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(133): SMW\AskParserFunction->doFetchResultsForRawParameters(array)
#4 /.../w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(252): SMW\AskParserFunction->parse(array)
#5 [internal function]: SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string)
#6 /.../w/includes/parser/Parser.php(3771): call_user_func_array(Closure, array)
#7 /.../w/includes/parser/Parser.php(3505): Parser->callParserFunction(PPFrame_DOM, string, array)
#8 /.../w/includes/parser/Preprocessor_DOM.php(1169): Parser->braceSubstitution(array, PPFrame_DOM)
#9 /.../w/includes/parser/Parser.php(3322): PPFrame_DOM->expand(PPNode_DOM, integer)
#10 /.../w/includes/parser/Parser.php(1231): Parser->replaceVariables(string)
#11 /.../w/includes/parser/Parser.php(434): Parser->internalParse(string)
#12 /.../w/extensions/SemanticMediaWiki/includes/ContentParser.php(202): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#13 /.../w/extensions/SemanticMediaWiki/includes/ContentParser.php(147): SMW\ContentParser->fetchFromParser()
#14 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(136): SMW\ContentParser->parse()
#15 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(119): SMW\MediaWiki\Jobs\UpdateJob->needToParsePageContentBeforeUpdate()
#16 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(88): SMW\MediaWiki\Jobs\UpdateJob->doPrepareForUpdate()
#17 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(57): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#18 /.../w/extensions/SemanticMediaWiki/src/SQLStore/ByIdDataRebuildDispatcher.php(171): SMW\MediaWiki\Jobs\UpdateJob->run()
#19 /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(247): SMW\SQLStore\ByIdDataRebuildDispatcher->dispatchRebuildFor(integer)
#20 /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(147): SMW\Maintenance\DataRebuilder->doRebuildAll()
#21 /.../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(141): SMW\Maintenance\DataRebuilder->rebuild()
#22 /.../w/maintenance/doMaintenance.php(103): SMW\Maintenance\RebuildData->execute()
#23 /.../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(174): require_once(string)
#24 {main}
```

**Comment by mwjames** [comment]
> /.../w/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(133): SMW\AskParserFunction->doFetchResultsForRawParameters(array)
/

Interesting [0] doesn't seem to exists, so why would the `Parser` try to resolve a #ask query?

[0] http://sandbox.semantic-mediawiki.org/wiki/Special:Browse/SMW_Sandbox:SMWExtInfo

**Comment by mwjames** [comment]
Search for the page returns with `2 KB (312 words)`

![image](https://cloud.githubusercontent.com/assets/1245473/10976212/e2f45712-83ea-11e5-95d9-315cd62715b6.png)

but once you click the link I get 

![image](https://cloud.githubusercontent.com/assets/1245473/10976236/ff79840c-83ea-11e5-90ae-08e34ab02c9e.png)

**Comment by mwjames** [comment]
> [909d1df6] [no req]   MWException from line 640 of /.../w/extensions/SemanticMediaWiki/includes/SemanticData.php: Data for a subobject of SMWExtInfo cannot be added to SMW_Sandbox:SMWExtInfo.
Backtrace:
#0 /.../w/extensions/SemanticMediaWiki/includes/SemanticData.php(326): SMW\SemanticData->addSubSemanticData(SMWContainerSemanticData)

As for the exception, this is correct because the `SemanticData` subject and subobject subject don't match [0], so nothing is wrong with the exception here. The question lies within the `SMW_Sandbox:SMWExtInfo` title object.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/SemanticData.php#L639-L640

**Comment by kghbln** [comment]
A I know what happend. Hold on.

**Comment by kghbln** [comment]
So what happend is: Upon setup I set 
```php
$wgMetaNamespace = "SMW Sandbox";
```
which is bu... and added some pages to the project namespace. At a later stage I realized the mess I made and correctly switchen to
```php
$wgMetaNamespace = "SMW_Sandbox";
```
but forgot to move the respective page to the fixed namespace. I think it is not the task of SMW to cater for this sort of mess, so we are cool here.
