### ISSUE TITLE
PHP7 test failures

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1378]
Already caught and fixed 16ddfd8.

```
Semantic MediaWiki: 2.4-alpha (SMWSQLStore3, mysql)
MediaWiki:          1.26.2 (MediaWiki vendor autoloader)

Execution date:     2016-01-18 00:00

PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

Runtime:        PHP 7.0.2
```

remaining issues are:

```
There were 2 failures:

1) SMW\Tests\MediaWiki\Api\ApiQueryResultFormatterTest::testSetIndexedTagNameException
Failed asserting that exception of type "ReflectionException" matches expected exception "InvalidArgumentException". Message
was: "Invocation of method SMW\MediaWiki\Api\ApiQueryResultFormatter::setIndexedTagName() failed" at
#0 ...\extensions\SemanticMediaWiki\tests\phpunit\Unit\MediaWiki\Api\ApiQueryResultFormatterTest.php(49)
: ReflectionMethod->invoke(Object(SMW\MediaWiki\Api\ApiQueryResultFormatter), Array, NULL)
#1 [internal function]: SMW\Tests\MediaWiki\Api\ApiQueryResultFormatterTest->testSetIndexedTagNameException()
#2 ...\vendor\phpunit\phpunit\src\Framework\TestCase.php(908): ReflectionMethod->invokeArgs(Object(SMW\T
ests\MediaWiki\Api\ApiQueryResultFormatterTest), Array)
#3 ...\vendor\phpunit\phpunit\src\Framework\TestCase.php(768): PHPUnit_Framework_TestCase->runTest()
#4 ...\vendor\phpunit\phpunit\src\Framework\TestResult.php(612): PHPUnit_Framework_TestCase->runBare()
#5 ...\vendor\phpunit\phpunit\src\Framework\TestCase.php(724): PHPUnit_Framework_TestResult->run(Object(
SMW\Tests\MediaWiki\Api\ApiQueryResultFormatterTest))
#6 ...\vendor\phpunit\phpunit\src\Framework\TestSuite.php(747): PHPUnit_Framework_TestCase->run(Object(P
HPUnit_Framework_TestResult))
#7 ...\vendor\phpunit\phpunit\src\Framework\TestSuite.php(747): PHPUnit_Framework_TestSuite->run(Object(
PHPUnit_Framework_TestResult))
#8 ...\vendor\phpunit\phpunit\src\Framework\TestSuite.php(747): PHPUnit_Framework_TestSuite->run(Object(
PHPUnit_Framework_TestResult))
#9 ...\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(440): PHPUnit_Framework_TestSuite->run(Object(PH
PUnit_Framework_TestResult))
#10 ...\vendor\phpunit\phpunit\src\TextUI\Command.php(149): PHPUnit_TextUI_TestRunner->doRun(Object(PHPU
nit_Framework_TestSuite), Array)
#11 ...\vendor\phpunit\phpunit\src\TextUI\Command.php(100): PHPUnit_TextUI_Command->run(Array, true)
#12 ...\tests\phpunit\phpunit.php(250): PHPUnit_TextUI_Command::main()
#13 {main}.

2) SMW\Tests\MediaWiki\Api\BrowseBySubjectTest::testExecuteForInvalidSubjectThrowsException
Failed asserting that exception of type "TypeError" matches expected exception "Exception".

--
```

**Comment by JeroenDeDauw** [comment]
Might be solved by stuff like #1380. However it's odd that something that used to throw an exception now throws a TypeError. I would think that something throwing a TypeError in PHP7 would have caused warnings/errors in PHP 5.x.
