### ISSUE TITLE
"SMW_DI_Number.php: Initialization value '' is not a number" when running rebuildData.php

### ISSUE THREAD

**Issue by agharbeia** [SemanticMediaWiki/SemanticMediaWiki#1628]
### Setup and configuration

- SMW version: 2.3.1
- MW version: 1.26.3
- DB (MySQL etc.): MariaDB

### Issue

Running `rebuildData.php` on our wiki runs fine until ID 1120 when I get:
(1019/5123) Processing ID 1020 ...
[8bd9b487] [no req]   SMW\DataItemException from line 26 of /var/www/arabdigitalexpression.org/wiki/mediawiki-1.26.3/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Number.php: Initialization value '' is not a number.
Backtrace:
```
#0 /.../extensions/SemanticMediaWiki/includes/datavalues/SMW_DV_Number.php(293): SMWDINumber->__construct(NULL)
#1 /.../extensions/SemanticMediaWiki/includes/datavalues/SMW_DV_Number.php(121): SMWNumberValue->convertToMainUnit(NULL, string)
#2 /.../extensions/SemanticMediaWiki/includes/datavalues/SMW_DataValue.php(179): SMWNumberValue->parseUserValue(string)
#3 /.../extensions/SemanticMediaWiki/src/DataValueFactory.php(97): SMWDataValue->setUserValue(string, boolean)
#4 /.../extensions/SemanticMediaWiki/src/DataValueFactory.php(146): SMW\DataValueFactory::newTypeIdValue(string, string, boolean, SMW\DIProperty, SMW\DIWikiPage)
#5 /.../extensions/SemanticMediaWiki/src/DataValueFactory.php(200): SMW\DataValueFactory::newPropertyObjectValue(SMW\DIProperty, string, boolean, SMW\DIWikiPage)
#6 /.../extensions/SemanticMediaWiki/src/InTextAnnotationParser.php(341): SMW\DataValueFactory->newPropertyValue(string, string, boolean, SMW\DIWikiPage)
#7 /.../extensions/SemanticMediaWiki/src/InTextAnnotationParser.php(315): SMW\InTextAnnotationParser->addPropertyValue(array, string, boolean)
#8 /.../extensions/SemanticMediaWiki/src/InTextAnnotationParser.php(252): SMW\InTextAnnotationParser->process(array)
#9 [internal function]: SMW\InTextAnnotationParser->preprocess(array)
#10 /.../extensions/SemanticMediaWiki/src/InTextAnnotationParser.php(137): preg_replace_callback(string, string, string)
#11 /.../extensions/SemanticMediaWiki/src/MediaWiki/Hooks/InternalParseBeforeLinks.php(110): SMW\InTextAnnotationParser->parse(string)
#12 /.../extensions/SemanticMediaWiki/src/MediaWiki/Hooks/InternalParseBeforeLinks.php(62): SMW\MediaWiki\Hooks\InternalParseBeforeLinks->performUpdate()
#13 /.../extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(206): SMW\MediaWiki\Hooks\InternalParseBeforeLinks->process()
#14 [internal function]: SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks\{closure}(Parser, string, StripState)
#15 /.../includes/Hooks.php(201): call_user_func_array(Closure, array)
#16 /.../includes/parser/Parser.php(1254): Hooks::run(string, array)
#17 /.../includes/parser/Parser.php(444): Parser->internalParse(string)
#18 /.../extensions/SemanticMediaWiki/includes/ContentParser.php(202): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#19 /.../extensions/SemanticMediaWiki/includes/ContentParser.php(147): SMW\ContentParser->fetchFromParser()
#20 /.../extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(136): SMW\ContentParser->parse()
#21 /.../extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(119): SMW\MediaWiki\Jobs\UpdateJob->needToParsePageContentBeforeUpdate()
#22 /.../extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(88): SMW\MediaWiki\Jobs\UpdateJob->doPrepareForUpdate()
#23 /.../extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(57): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#24 /.../extensions/SemanticMediaWiki/src/SQLStore/ByIdDataRebuildDispatcher.php(171): SMW\MediaWiki\Jobs\UpdateJob->run()
#25 /.../extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(247): SMW\SQLStore\ByIdDataRebuildDispatcher->dispatchRebuildFor(integer)
#26 /.../extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(147): SMW\Maintenance\DataRebuilder->doRebuildAll()
#27 /.../extensions/SemanticMediaWiki/maintenance/rebuildData.php(141): SMW\Maintenance\DataRebuilder->rebuild()
#28 /.../maintenance/doMaintenance.php(103): SMW\Maintenance\RebuildData->execute()
#29 /.../extensions/SemanticMediaWiki/maintenance/rebuildData.php(174): require_once(string)
#30 {main}
```
I get the same error with several other subsequent IDs. How can I get to know the pages causing these errors? Is this the MW page ID from the database?

**Comment by JeroenDeDauw** [comment]
Thanks for reporting this issue

**Comment by kghbln** [comment]
Have a look at the [object id lookup page](https://www.semantic-mediawiki.org/wiki/Help:Object_ID_lookup) to find out more about the transgressing id. Perhaps you could post the result.

**Comment by mwjames** [comment]
> #0 /var/www/arabdigitalexpression.org/wiki/mediawiki-1.26.3/extensions/SemanticMediaWiki/includes/datavalues/SMW_DV_Number.php(293): SMWDINumber->__construct(NULL)
#1 /var/www/arabdigitalexpression.org/wiki/mediawiki-1.26.3/extensions/SemanticMediaWiki/includes/datavalues/SMW_DV_Number.php(121): SMWNumberValue->convertToMainUnit(NULL, string)

I was unable to reproduce the error through normal means but since `NULL` caused the issue here it is now explicitly checked #1633.

**Comment by mwjames** [comment]
> Have a look at the object id lookup page to find out more about the transgressing id

As for ID's lookup, see my comments in https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1433#issue-138582126 (relates to 2.4).
