### ISSUE TITLE
InvalidArgumentException from line 217 of /.../w/vendor/onoi/blob-store/src/BlobStore.php: Expected the id to be a string

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1724]
### Setup and configuration

- PHP 	5.6.11-1ubuntu3.4 (apache2handler)
- MySQL 	5.6.30-0ubuntu0.15.10.1
- MediaWiki 	1.25.6 (01b4001) 21:49, 20 May 2016
- Semantic MediaWiki	2.4.0 (61b7da6) 06:23, 9 July 2016

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
Exception encountered, of type "InvalidArgumentException"
[d2f46bcf] /w/index.php?title=Demo:London&action=submit InvalidArgumentException from line 217 of /.../w/vendor/onoi/blob-store/src/BlobStore.php: Expected the id to be a string
Backtrace:
#0 /.../w/vendor/onoi/blob-store/src/BlobStore.php(195): Onoi\BlobStore\BlobStore->getKey(integer)
#1 /.../w/extensions/SemanticMediaWiki/src/CachedPropertyValuesPrefetcher.php(58): Onoi\BlobStore\BlobStore->delete(string)
#2 /.../w/extensions/SemanticMediaWiki/src/EventListenerRegistry.php(79): SMW\CachedPropertyValuesPrefetcher->resetCacheFor(SMW\DIWikiPage)
#3 [internal function]: SMW\EventListenerRegistry->SMW\{closure}(Onoi\EventDispatcher\DispatchContext)
#4 /.../w/vendor/onoi/event-dispatcher/src/Listener/GenericCallbackEventListener.php(62): call_user_func_array(Closure, array)
#5 /.../w/vendor/onoi/event-dispatcher/src/Dispatcher/GenericEventDispatcher.php(122): Onoi\EventDispatcher\Listener\GenericCallbackEventListener->execute(Onoi\EventDispatcher\DispatchContext)
#6 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/NewRevisionFromEditComplete.php(124): Onoi\EventDispatcher\Dispatcher\GenericEventDispatcher->dispatch(string, Onoi\EventDispatcher\DispatchContext)
#7 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/NewRevisionFromEditComplete.php(75): SMW\MediaWiki\Hooks\NewRevisionFromEditComplete->doProcess()
#8 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(222): SMW\MediaWiki\Hooks\NewRevisionFromEditComplete->process()
#9 [internal function]: SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks\{closure}(WikiPage, Revision, boolean, User)
#10 /.../w/includes/Hooks.php(207): call_user_func_array(Closure, array)
#11 /.../w/includes/page/WikiPage.php(1830): Hooks::run(string, array)
#12 [internal function]: WikiPage->doEditContent(WikitextContent, string, integer, boolean, NULL, string)
#13 /.../w/includes/page/Article.php(2016): call_user_func_array(array, array)
#14 /.../w/includes/EditPage.php(1921): Article->__call(string, array)
#15 /.../w/includes/EditPage.php(1921): Article->doEditContent(WikitextContent, string, integer, boolean, NULL, string)
#16 /.../w/includes/EditPage.php(1305): EditPage->internalAttemptSave(array, boolean)
#17 /.../w/includes/EditPage.php(539): EditPage->attemptSave(array)
#18 /.../w/includes/actions/EditAction.php(56): EditPage->edit()
#19 /.../w/includes/actions/SubmitAction.php(40): EditAction->show()
#20 /.../w/includes/MediaWiki.php(463): SubmitAction->show()
#21 /.../w/includes/MediaWiki.php(269): MediaWiki->performAction(Article, Title)
#22 /.../w/includes/MediaWiki.php(634): MediaWiki->performRequest()
#23 /.../w/includes/MediaWiki.php(482): MediaWiki->main()
#24 /.../w/index.php(41): MediaWiki->run()
#25 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

**Comment by mwjames** [comment]
See https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1713#issuecomment-231796662
