### ISSUE TITLE
SQLStore fails with "The value "0" is not a valid dataitem ID."

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1914]
### Setup and configuration

- SMW version: 2.4.1
- MW version: 1.27.1
- DB (MySQL etc.): MariaDb

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
[8b8b7bb9e9177ec7ab372f26] /wiki/Attribut:Has_population MWException from line 224 of /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php: The value "0" is not a valid dataitem ID.

Backtrace:

#0 /.../w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_Sql3StubSemanticData.php(151): SMWSQLStore3->getDataItemHandlerForDIType(integer)
#1 /.../w/extensions/SemanticForms/includes/SF_FormLinker.php(92): SMWSql3StubSemanticData->getPropertyValues(SMW\DIProperty)
#2 /.../w/extensions/SemanticForms/includes/SF_FormLinker.php(341): SFFormLinker::getPagePropertiesOfPage(Title)
#3 [internal function]: SFFormLinker::setBrokenLink(DummyLinker, Title, array, string, array, NULL)
#4 /.../w/includes/Hooks.php(195): call_user_func_array(string, array)
#5 /.../w/includes/Linker.php(252): Hooks::run(string, array)
#6 /.../w/includes/parser/LinkHolderArray.php(420): Linker::link(Title, string, array, array, array)
#7 /.../w/includes/parser/LinkHolderArray.php(271): LinkHolderArray->replaceInternal(string)
#8 /.../w/includes/parser/Parser.php(5301): LinkHolderArray->replace(string)
#9 /.../w/includes/parser/Parser.php(1314): Parser->replaceLinkHolders(string)
#10 /.../w/includes/parser/Parser.php(449): Parser->internalParseHalfParsed(string, boolean, boolean)
#11 /.../w/includes/content/WikitextContent.php(331): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#12 /.../w/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#13 /.../w/includes/poolcounter/PoolWorkArticleView.php(140): AbstractContent->getParserOutput(Title, integer, ParserOptions)
#14 /.../w/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#15 /.../w/includes/page/Article.php(666): PoolCounterWork->execute()
#16 /.../w/extensions/SemanticMediaWiki/includes/articlepages/SMW_OrderedListPage.php(86): Article->view()
#17 /.../w/includes/actions/ViewAction.php(44): SMWOrderedListPage->view()
#18 /.../w/includes/MediaWiki.php(503): ViewAction->show()
#19 /.../w/includes/MediaWiki.php(288): MediaWiki->performAction(SMWPropertyPage, Title)
#20 /.../w/includes/MediaWiki.php(745): MediaWiki->performRequest()
#21 /.../w/includes/MediaWiki.php(519): MediaWiki->main()
#22 /.../w/index.php(43): MediaWiki->run()
#23 {main}

```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

http://sandbox.semantic-mediawiki.org/wiki/Attribut:Has_population

**Comment by mwjames** [comment]
@kghbln Not sure but maybe this error is the consequence of the switch from 2.5-alpha back to 2.4.1 where the DB finds itself in an imbalanced state. Anyway, #1915 tries to take precautionary measures to handle this more gracefully.

**Comment by kghbln** [comment]
> Not sure but maybe this error is the consequence of the switch from 2.5-alpha back to 2.4.1 where the DB finds itself in an imbalanced state.

This seems like a likely cause. This should not really happen in production still it is good to know that there is a safe-fail. :)
