### ISSUE TITLE
Exception from line 151 of MemcachedBagOStuff.php: Key contains invalid characters

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticMediaWiki#1931]
### Setup and configuration

- SMW version: 2.4.1
- MW version: 1.27.0-rc.0 (f465524)
- DB: MySQL 5.1.73

### Issue
Exception from line 151 of /var/www/html/w/includes/libs/objectcache/MemcachedBagOStuff.php: Key contains invalid characters

Line 151 of MemcachedBagOStuff.php throws an error if the cache key contains anything but ASCII characters, so it is apparently supposed to be a feature.

### Stack trace
```
[maintenance]# php rebuildData.php -d 100 --ignore-exceptions --no-cache -v

Running for storage: SMWSQLStore3

Removing table entries (marked for deletion).

.............................................Exception encountered, of type "Exception"
[470fdde19df57e183827d2e7] [no req]   Exception from line 151 of /var/www/html/w/includes/libs/objectcache/MemcachedBagOStuff.php: Key contains invalid characters: WANCache:v:my_wiki:interwiki:création_de_la_fiche_smog_sol_ela3_mecaph_20/0_indice_a
Backtrace:
#0 /var/www/html/w/includes/libs/objectcache/MemcachedPhpBagOStuff.php(56): MemcachedBagOStuff->validateKeyEncoding(string)
#1 /var/www/html/w/includes/libs/objectcache/WANObjectCache.php(259): MemcachedPhpBagOStuff->getMulti(array)
#2 /var/www/html/w/includes/libs/objectcache/WANObjectCache.php(216): WANObjectCache->getMulti(array, array, array)
#3 /var/www/html/w/includes/libs/objectcache/WANObjectCache.php(807): WANObjectCache->get(string, NULL, array)
#4 /var/www/html/w/includes/libs/objectcache/WANObjectCache.php(779): WANObjectCache->doGetWithSetCallback(string, integer, Closure, array)
#5 /var/www/html/w/includes/interwiki/Interwiki.php(256): WANObjectCache->getWithSetCallback(string, integer, Closure)
#6 /var/www/html/w/includes/interwiki/Interwiki.php(101): Interwiki::load(string)
#7 /var/www/html/w/includes/interwiki/Interwiki.php(74): Interwiki::fetch(string)
#8 /var/www/html/w/includes/title/MediaWikiTitleCodec.php(290): Interwiki::isValidInterwiki(string)
#9 /var/www/html/w/includes/Title.php(3337): MediaWikiTitleCodec->splitTitleString(string, integer)
#10 /var/www/html/w/includes/Title.php(332): Title->secureAndSplit()
#11 /var/www/html/w/includes/Title.php(287): Title::newFromTextThrow(string, integer)
#12 /var/www/html/w/extensions/SemanticMediaWiki/includes/datavalues/SMW_DV_WikiPage.php(123): Title::newFromText(string, integer)
#13 /var/www/html/w/extensions/SemanticMediaWiki/includes/datavalues/SMW_DataValue.php(171): SMWWikiPageValue->parseUserValue(string)
#14 /var/www/html/w/extensions/SemanticMediaWiki/src/DataValueFactory.php(123): SMWDataValue->setUserValue(string, boolean)
#15 /var/www/html/w/extensions/SemanticMediaWiki/src/DataValueFactory.php(172): SMW\DataValueFactory->newDataValueByType(string, string, boolean, SMW\DIProperty, SMW\DIWikiPage)
#16 /var/www/html/w/extensions/SemanticMediaWiki/src/DataValueFactory.php(229): SMW\DataValueFactory->newDataValueByProperty(SMW\DIProperty, string, boolean, SMW\DIWikiPage)
#17 /var/www/html/w/extensions/SemanticMediaWiki/includes/parserhooks/SetParserFunction.php(82): SMW\DataValueFactory->newDataValueByText(string, string, boolean, SMW\DIWikiPage)
#18 /var/www/html/w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(377): SMW\SetParserFunction->parse(SMW\ParserParameterProcessor)
#19 [internal function]: SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string)
#20 /var/www/html/w/includes/parser/Parser.php(3801): call_user_func_array(Closure, array)
#21 /var/www/html/w/includes/parser/Parser.php(3536): Parser->callParserFunction(PPTemplateFrame_DOM, string, array)
#22 /var/www/html/w/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPTemplateFrame_DOM)
#23 /var/www/html/w/includes/parser/Parser.php(1240): PPFrame_DOM->expand(PPNode_DOM)
#24 /var/www/html/w/includes/parser/Parser.php(602): Parser->internalParse(string, boolean, PPTemplateFrame_DOM)
#25 /var/www/html/w/extensions/PageTools/PageTools.class.php(144): Parser->recursiveTagParse(string, PPTemplateFrame_DOM)
#26 [internal function]: PageTools::renderDeflate(string, array, Parser, PPTemplateFrame_DOM)
#27 /var/www/html/w/includes/parser/Parser.php(4246): call_user_func_array(string, array)
#28 /var/www/html/w/includes/parser/Preprocessor_DOM.php(1260): Parser->extensionSubstitution(array, PPTemplateFrame_DOM)
#29 /var/www/html/w/includes/parser/Preprocessor_DOM.php(1626): PPFrame_DOM->expand(PPNode_DOM, integer)
#30 /var/www/html/w/includes/parser/Parser.php(3675): PPTemplateFrame_DOM->cachedExpand(string, PPNode_DOM)
#31 /var/www/html/w/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPFrame_DOM)
#32 /var/www/html/w/includes/parser/Parser.php(3350): PPFrame_DOM->expand(PPNode_DOM, integer)
#33 /var/www/html/w/includes/parser/Parser.php(1243): Parser->replaceVariables(string)
#34 /var/www/html/w/includes/parser/Parser.php(441): Parser->internalParse(string)
#35 /var/www/html/w/extensions/SemanticMediaWiki/includes/ContentParser.php(202): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#36 /var/www/html/w/extensions/SemanticMediaWiki/includes/ContentParser.php(147): SMW\ContentParser->fetchFromParser()
#37 /var/www/html/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(135): SMW\ContentParser->parse()
#38 /var/www/html/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(118): SMW\MediaWiki\Jobs\UpdateJob->needToParsePageContentBeforeUpdate()
#39 /var/www/html/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(87): SMW\MediaWiki\Jobs\UpdateJob->doPrepareForUpdate()
#40 /var/www/html/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(56): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#41 /var/www/html/w/extensions/SemanticMediaWiki/src/SQLStore/ByIdDataRebuildDispatcher.php(191): SMW\MediaWiki\Jobs\UpdateJob->run()
#42 /var/www/html/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(412): SMW\SQLStore\ByIdDataRebuildDispatcher->dispatchRebuildFor(string)
#43 /var/www/html/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(226): SMW\Maintenance\DataRebuilder->deleteMarkedSubjects(SMW\SQLStore\ByIdDataRebuildDispatcher)
#44 /var/www/html/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(167): SMW\Maintenance\DataRebuilder->doRebuildAll()
#45 /var/www/html/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(149): SMW\Maintenance\DataRebuilder->rebuild()
#46 /var/www/html/w/maintenance/doMaintenance.php(103): SMW\Maintenance\RebuildData->execute()
#47 /var/www/html/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(197): require_once(string)
#48 {main}
[maintenance]#
```

**Comment by mwjames** [comment]
> Exception from line 151 of /var/www/html/w/includes/libs/objectcache/MemcachedBagOStuff.php: Key contains invalid characters

As far as I'm concerned, this is not a bug in a sense that SMW should do anything about it since it is caused by `MemcachedBagOStuff` while trying to create a `Title::newFromText(string, integer)` on something like `my_wiki:interwiki:création_de_la_fiche_smog_sol_ela3_mecaph_20/0_indice_a`. (I'm guessing `é` being the culprit here).

> Line 151 of MemcachedBagOStuff.php throws an error if the cache key contains anything but ASCII characters

... and the World only understands ASCII.

>[maintenance]# php rebuildData.php -d 100 --ignore-exceptions --no-cache -v
>  `#43 /var/www/html/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(226): SMW\Maintenance\DataRebuilder->deleteMarkedSubjects(SMW\SQLStore\ByIdDataRebuildDispatcher)`

You may try changing [0] from `$byIdDataRebuildDispatcher->dispatchRebuildFor( $id );` to `$this->doExecuteFor( $byIdDataRebuildDispatcher, $id );` which should catch the exception when option `--ignore-exceptions` is used.

I changed the way the disposal operation works in 2.5 (#1938) with the consequence that it no longer relies on a `Title` interaction at the execution point that caused the issue above.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Maintenance/DataRebuilder.php#L412

**Comment by kghbln** [comment]
So the solution will be to move on to SMW 2.5+ since #1938 provides the fix? If yes, this one could be closed.

**Comment by mwjames** [comment]
>So the solution will be to move on to SMW 2.5+ since #1938 provides the fix?

The suggested change from above was added to the 2.4.x branch.

Apart from that, you can still run into an exception due to MW's `MemcachedBagOStuff` implementation but it should not halt the rebuildData process when `--ignore-exceptions` is used. From an extension point if view, the Title creation should not fail at this point and as a consumer of  `Title::newFromText` nothing we can do about it.

I created https://phabricator.wikimedia.org/T148958 just for the record.

**Comment by mwjames** [comment]
To be clear we don't fix the exception itself, we just catch the exception to avoid an interruption during the rebuild process.

**Comment by s7eph4n** [comment]
Thanks!

**Comment by kghbln** [comment]
> The suggested change from above was added to the 2.4.x branch.

Cool!

**Comment by mwjames** [comment]
> I created https://phabricator.wikimedia.org/T148958 just for the record.

This got solved after six month of reporting the issue. Maybe I should apply the same policy on fixing any reported fatal error!

**Comment by kghbln** [comment]
> This got solved after six month of reporting the issue. Maybe I should apply the same policy on fixing any reported fatal error!

Considering the time between releases nowadays the fix will happily roll out to the public in October. To be fair. That just makes it a year. Hardy har har.
