### ISSUE TITLE
Duplicate entry `smw_prop_stats` (SMW\SQLStore\PropertyStatisticsTable::insertUsageCount)

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#198]
While performing some tests I came across:

A database query error has occurred. This may indicate a bug in the software.
Query:
INSERT INTO `smw_prop_stats` (usage_count,p_id) VALUES ('0','51')
Function: SMW\SQLStore\PropertyStatisticsTable::insertUsageCount
Error: 1062 Duplicate entry '51' for key 'p_id' (localhost)
### Backtrace:

```
#0 ..\includes\db\Database.php(1091): DatabaseBase->reportQueryError('Duplicate entry...', 1062, 'INSERT  INTO `s...', 'SMW\SQLStore\Pr...', false)
#1 ..\includes\db\Database.php(1888): DatabaseBase->query('INSERT  INTO `s...', 'SMW\SQLStore\Pr...')
#2 ..\extensions\SemanticMediaWiki\includes\storage\SQLStore\PropertyStatisticsTable.php(163): DatabaseBase->insert('smw_prop_stats', Array, 'SMW\SQLStore\Pr...')
#3 ..\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_Sql3SmwIds.php(472): SMW\SQLStore\PropertyStatisticsTable->insertUsageCount(51, 0)
#4 ..\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_Sql3SmwIds.php(559): SMWSql3SmwIds->makeDatabaseId('Pellentesque', 106, '', '', true, 'Pellentesque', false)
#5 ..\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3_Writers.php(248): SMWSql3SmwIds->makeSMWPropertyID(Object(SMW\DIProperty))
#6 ..\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3_Writers.php(400): SMWSQLStore3Writers->preparePropertyTableInserts(13, Object(SMW\SemanticData), Object(DatabaseMysqli))
#7 ..\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3_Writers.php(159): SMWSQLStore3Writers->preparePropertyTableUpdates(13, Object(SMW\SemanticData), Object(DatabaseMysqli))
#8 ..\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3_Writers.php(87): SMWSQLStore3Writers->doFlatDataUpdate(Object(SMW\SemanticData), Object(DatabaseMysqli))
#9 ..\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3.php(318): SMWSQLStore3Writers->doDataUpdate(Object(SMW\SemanticData))
#10 ..\extensions\SemanticMediaWiki\includes\storage\SMW_Store.php(208): SMWSQLStore3->doDataUpdate(Object(SMW\SemanticData))
#11 ..\extensions\SemanticMediaWiki\includes\StoreUpdater.php(174): SMW\Store->updateData(Object(SMW\SemanticData))
#12 ..\extensions\SemanticMediaWiki\includes\StoreUpdater.php(138): SMW\StoreUpdater->updateStore(true)
#13 ..\extensions\SemanticMediaWiki\includes\StoreUpdater.php(97): SMW\StoreUpdater->performUpdate(Object(WikiPage))
#14 ..\extensions\SemanticMediaWiki\includes\UpdateObserver.php(65): SMW\StoreUpdater->runUpdater()
#15 ..\extensions\SemanticMediaWiki\includes\BaseObserver.php(41): SMW\UpdateObserver->runStoreUpdater(Object(SMW\ParserData))
#16 ..\extensions\SemanticMediaWiki\includes\ObservableSubject.php(117): SMW\BaseObserver->update(Object(SMW\ObservableSubjectDispatcher))
#17 ..\extensions\SemanticMediaWiki\includes\ObservableSubject.php(96): SMW\ObservableSubject->notify()
#18 ..\extensions\SemanticMediaWiki\includes\ParserData.php(229): SMW\ObservableSubject->setState('runStoreUpdater')
#19 ..\extensions\SemanticMediaWiki\includes\hooks\ParserAfterTidy.php(99): SMW\ParserData->updateStore()
#20 ..\extensions\SemanticMediaWiki\includes\hooks\ParserAfterTidy.php(48): SMW\ParserAfterTidy->performUpdate(Object(Title))
#21 ..\extensions\SemanticMediaWiki\includes\Setup.php(432): SMW\ParserAfterTidy->process()
#22 [internal function]: SMW\Setup->SMW\{closure}(Object(Parser), '<p><a 
```
### Solution

Instead of

```
return $this->dbConnection->insert(
    $this->table,
    array(
        'usage_count' => $value,
        'p_id' => $propertyId,
    ),
    __METHOD__
);
```

use `update` to avoid the duplicate error as the update should take care of either updating the existing row or insert a new one.

```
return $this->dbConnection->update(
    $this->table,
    array(
        'usage_count' => $value,
        'p_id' => $propertyId,
    ),
    array(
        'p_id' => $propertyId
    ),
    __METHOD__
);
```

**Comment by mwjames** [comment]
If the issue reappears then a new issue should be create with some information on how to replicate it.
