### ISSUE TITLE
MySQL 5.7 causes "SELECT list; this is incompatible with DISTINCT"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#2078]
### Setup and configuration

- MediaWiki 	1.27.1 (8c593e7) 23:49, 26 October 2016
- PHP 	7.0.8-0ubuntu0.16.04.3 (apache2handler)
- MySQL 	5.7.16-0ubuntu0.16.04.1
- Semantic MediaWiki 2.4.3 (https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/6661acdd8c8420a7e07c178aad47590d086c83d6) as well as master (https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/fd8ea67a7c66aa58513b3b67ee24b4182504dc09)

### Issue
During the server upgrade [from Ubuntu 15.10 to Ubuntu 16.04.1](https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/1) the database server was also upgraded from version 5.6 to 5.7 which now results in:
```
Exception encountered, of type "RuntimeException"
[273d99a4e9af388f22675441] /wiki/Semantic_MediaWiki RuntimeException from line 186 of /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Database.php: A database error has occurred. Did you forget to run maintenance/update.php after upgrading? See: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
```
### Query error
```
Query: SELECT DISTINCT t6.smw_id AS id,t6.smw_title AS t,t6.smw_namespace AS ns,t6.smw_iw AS iw,t6.smw_subobject AS so,t6.smw_sortkey AS sortkey FROM `smw_object_ids` AS t6 INNER JOIN `smw_di_time` AS t1 ON t6.smw_id=t1.s_id INNER JOIN `smw_fpt_lcode` AS t3 ON t1.s_id=t3.s_id INNER JOIN `smw_di_blob` AS t4 ON t1.s_id=t4.s_id WHERE (t1.p_id='80' AND ((t3.o_hash='en')) AND ((t4.o_hash='false') AND t4.p_id='48542')) AND t6.smw_iw!=':smw' AND t6.smw_iw!=':smw-delete' AND t6.smw_iw!=':smw-redi' ORDER BY t1.o_sortkey DESC LIMIT 9
Function: SMW\SQLStore\QueryEngine\QueryEngine::getInstanceQueryResult
Error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'DB0231020151216.t1.o_sortkey' which is not in SELECT list; this is incompatible with DISTINCT (localhost)
```

### Backtrace 0
```
#0 /.../w/includes/db/Database.php(901): DatabaseBase->reportQueryError('Expression #1 o...', 3065, 'SELECT DISTINC...', 'SMW\\SQLStore\\Qu...', false)
#1 /.../w/includes/db/Database.php(1234): DatabaseBase->query('SELECT DISTINC...', 'SMW\\SQLStore\\Qu...')
#2 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Database.php(177): DatabaseBase->select('`smw_object_ids...', 'DISTINCT t6.smw...', '(t1.p_id='80' A...', 'SMW\\SQLStore\\Qu...', Array, Array)
#3 /.../w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(427): SMW\MediaWiki\Database->select('`smw_object_ids...', 'DISTINCT t6.smw...', '(t1.p_id='80' A...', 'SMW\\SQLStore\\Qu...', Array)
#4 /.../w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(233): SMW\SQLStore\QueryEngine\QueryEngine->getInstanceQueryResult(Object(SMWQuery), 6)
#5 /.../w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(402): SMW\SQLStore\QueryEngine\QueryEngine->getQueryResult(Object(SMWQuery))
#6 /.../w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(392): SMWSQLStore3->fetchQueryResult(Object(SMWQuery))
#7 /.../w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(455): SMWSQLStore3->getQueryResult(Object(SMWQuery))
#8 /.../w/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(193): SMWQueryProcessor::getResultFromQuery(Object(SMWQuery), Array, 2, 1)
#9 /.../w/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(113): SMW\AskParserFunction->doFetchResultsForRawParameters(Array)
#10 /.../w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(277): SMW\AskParserFunction->parse(Array)
#11 /.../w/includes/parser/Parser.php(3817): SMW\ParserFunctionFactory->SMW\{closure}(Object(Parser), '[[News date::+]...', '?news date=', 'sort=news date', 'order=desc', 'format=template', 'template=news l...', 'limit=4', 'searchlabel= <b...')
#12 /.../w/includes/parser/Parser.php(3552): Parser->callParserFunction(Object(PPFrame_DOM), 'ask', Array)
#13 /.../w/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(Array, Object(PPFrame_DOM))
#14 /.../w/includes/parser/Parser.php(3366): PPFrame_DOM->expand(Object(DOMElement), 0)
#15 /.../w/includes/parser/Parser.php(1248): Parser->replaceVariables('<div style="max...')
#16 /.../w/includes/parser/Parser.php(446): Parser->internalParse('<div style="max...')
#17 /.../w/includes/StubObject.php(105): Parser->parse('<div style="max...', Object(Title), Object(ParserOptions), true, true, 47602)
#18 /.../w/includes/StubObject.php(129): StubObject->_call('parse', Array)
#19 /.../w/includes/content/WikitextContent.php(331): StubObject->__call('parse', Array)
#20 /.../w/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Object(Title), 47602, Object(ParserOptions), true, Object(ParserOutput))
#21 /.../w/includes/poolcounter/PoolWorkArticleView.php(139): AbstractContent->getParserOutput(Object(Title), 47602, Object(ParserOptions))
#22 /.../w/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#23 /.../w/includes/page/Article.php(666): PoolCounterWork->execute()
#24 /.../w/includes/actions/ViewAction.php(44): Article->view()
#25 /.../w/includes/MediaWiki.php(503): ViewAction->show()
#26 /.../w/includes/MediaWiki.php(288): MediaWiki->performAction(Object(Article), Object(Title))
#27 /.../w/includes/MediaWiki.php(745): MediaWiki->performRequest()
#28 /.../w/includes/MediaWiki.php(519): MediaWiki->main()
#29 /.../w/index.php(43): MediaWiki->run()
#30 {main}
```
### Backtrace 1
```
#0 /.../w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(427): SMW\MediaWiki\Database->select(string, string, string, string, array)
#1 /.../w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(233): SMW\SQLStore\QueryEngine\QueryEngine->getInstanceQueryResult(SMWQuery, integer)
#2 /.../w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(402): SMW\SQLStore\QueryEngine\QueryEngine->getQueryResult(SMWQuery)
#3 /.../w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(392): SMWSQLStore3->fetchQueryResult(SMWQuery)
#4 /.../w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(455): SMWSQLStore3->getQueryResult(SMWQuery)
#5 /.../w/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(193): SMWQueryProcessor::getResultFromQuery(SMWQuery, array, integer, integer)
#6 /.../w/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php(113): SMW\AskParserFunction->doFetchResultsForRawParameters(array)
#7 /.../w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(277): SMW\AskParserFunction->parse(array)
#8 /.../w/includes/parser/Parser.php(3817): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string, string, string, string)
#9 /.../w/includes/parser/Parser.php(3552): Parser->callParserFunction(PPFrame_DOM, string, array)
#10 /.../w/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPFrame_DOM)
#11 /.../w/includes/parser/Parser.php(3366): PPFrame_DOM->expand(DOMElement, integer)
#12 /.../w/includes/parser/Parser.php(1248): Parser->replaceVariables(string)
#13 /.../w/includes/parser/Parser.php(446): Parser->internalParse(string)
#14 /.../w/includes/StubObject.php(105): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#15 /.../w/includes/StubObject.php(129): StubObject->_call(string, array)
#16 /.../w/includes/content/WikitextContent.php(331): StubObject->__call(string, array)
#17 /.../w/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#18 /.../w/includes/poolcounter/PoolWorkArticleView.php(139): AbstractContent->getParserOutput(Title, integer, ParserOptions)
#19 /.../w/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#20 /.../w/includes/page/Article.php(666): PoolCounterWork->execute()
#21 /.../w/includes/actions/ViewAction.php(44): Article->view()
#22 /.../w/includes/MediaWiki.php(503): ViewAction->show()
#23 /.../w/includes/MediaWiki.php(288): MediaWiki->performAction(Article, Title)
#24 /.../w/includes/MediaWiki.php(745): MediaWiki->performRequest()
#25 /.../w/includes/MediaWiki.php(519): MediaWiki->main()
#26 /.../w/index.php(43): MediaWiki->run()
#27 {main}
```

**Comment by kghbln** [comment]
@mwjames @JeroenDeDauw I had to pull SMW from sm-w.o to get at least the wiki up. Any hotfix appreciated.

**Comment by mwjames** [comment]
> I had to pull SMW from sm-w.o to get at least the wiki up

This is a MySQL bug apparently caused by `ONLY_FULL_GROUP_BY` as mentioned in:

* https://github.com/Piwigo/Piwigo/issues/376
* https://github.com/Elgg/Elgg/issues/8121
* https://github.com/doctrine/doctrine2/issues/5622
* Likely related to http://bugs.mysql.com/bug.php?id=79291where they talk about " ... Knowing that we wouldn't satisfy 100% of existing and new users. Overall we want to be marching towards SQL compliance (which implies getting stricter)."
* Using `10.1.19-MariaDB` (as drop-in replacement for MySQL 5.7) does not show above issue

> hotfix appreciated.

You could try the following change in 2.4* [0] and replace:
` ( $dbType == 'postgres' ? ( ( $sortfields ? ',' : '' ) . $sortfields ) : '' ),`
with
` ( $sortfields ? ', ' . $sortfields : ''),`

As to why this isn't caught in Travis because all jobs run on Precise and with it on MySQL 5.6. If you wanted to test MySQL 5.7 then you would need:

- https://gist.github.com/BenMorel/d981f25ead0926a0cb6d
- https://docs.travis-ci.com/user/trusty-ci-environment/
- https://docs.travis-ci.com/user/database-setup/

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.4.x/src/SQLStore/QueryEngine/QueryEngine.php#L425

**Comment by kghbln** [comment]
> As to why this isn't caught in Travis because all jobs run on Precise and with it on MySQL 5.6

Is where a reason why we are not testing against 16.04?

**Comment by kghbln** [comment]
Ah, ok this environment is still somehow borked. Kinda sad though.

**Comment by kghbln** [comment]
@mwjames I'm afraid there is still a worry. :( I was just trying to do a full data refresh on s-mw.o:

(316/50617)     Finished processing ID 321* (Help:Count_format)
A database query error has occurred.
Query: UPDATE  `smw_object_ids` SET smw_sortkey = 'Embedded format#This new version is a minor release and provides bugfixes for the current 2.4 branch of Semantic MediaWiki. Please refer to the help page on [[Help:Installation 2.x|installing]] Semantic MediaWiki to get detailed instructions on how to install or upgrade.;en' WHERE smw_id = '50856'
Function: SMWSql3SmwIds::makeDatabaseId
Error: 1406 Data too long for column 'smw_sortkey' at row 1 (localhost)

**Comment by mwjames** [comment]
> Error: 1406 Data too long for column 'smw_sortkey' at row 1 (localhost)

WTF ..., this is going to be a goose chase with no system to test against.

**Comment by kghbln** [comment]
> WTF ..., this is going to be a goose chase with no system to test against.

Looks like it. :( This is probably an issue with the [embedded format](https://www.semantic-mediawiki.org/wiki/Help:Embedded_format)

**Comment by mwjames** [comment]
> Looks like it. :( This is probably an issue with the embedded format

No

>Error: 1406 Data too long for column 

- http://stackoverflow.com/questions/15949038/error-code-1406-data-too-long-for-column-mysql

I;m wild guessing and I think the sorkey is tooooooooo long (which got truncated in prev. version) and now just falls flat.

You need to change it by hand since I cannot test this.

- Find [0] and
- Add those with a plus

```
 		if ( $id == 0 ) {
 			$sortkey = $sortkey ? $sortkey : ( str_replace( '_', ' ', $title ) );
 			$sequenceValue = $db->nextSequenceValue( $this->getIdTable() . '_smw_id_seq' ); // Bug 42659
 
+			$sortkey = substr( $sortkey, 0, 254 );
+
 			$db->insert(
 				self::TABLE_NAME,
 				array(
 					'smw_id' => $sequenceValue,
 					'smw_title' => $title,
@@ -681,10 +683,13 @@ class SMWSql3SmwIds {
 			if ( $fetchHashes ) {
 				$this->setPropertyTableHashesCache( $id, null );
 			}
 
 		} elseif ( $sortkey !== '' && $sortkey != $oldsort ) {
+
+			$sortkey = substr( $sortkey, 0, 254 );
+
 			$db->update(
 				self::TABLE_NAME,
 				array( 'smw_sortkey' => $sortkey ),
 				array( 'smw_id' => $id ),
 				__METHOD__
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.4.x/includes/storage/SQLStore/SMW_Sql3SmwIds.php#L644-L687

**Comment by mwjames** [comment]
> Should I open a separate issue for this?

Yes.

**Comment by kghbln** [comment]
> Yes.

Done with: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2089
