### ISSUE TITLE
PropertyStatisticsTable failed with "Error: 1264 Out of range value for column 'usage_count'"

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#2345]
### Setup and configuration

- SMW version: 2.5.0
- MW version: 1.29.0-alpha
- PHP version: 3.18.1 (srv)
- DB (MySQL etc.): 10.0.29-MariaDB-0ubuntu0.16.04.1

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
Fatal error: Uncaught exception 'DBQueryError' with message 'A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: UPDATE  `bw_smw_prop_stats` SET usage_count = usage_count - '1' WHERE p_id = '22'
Function: SMW\SQLStore\PropertyStatisticsTable::addToUsageCount
Error: 1264 Out of range value for column 'usage_count' at row 1 (127.0.0.1:3306)
' in /srv/mediawiki/workdir/includes/libs/rdbms/database/Database.php:1061
Stack trace:
#0 /srv/mediawiki/workdir/includes/libs/rdbms/database/Database.php(919): Database->reportQueryError()
#1 /srv/mediawiki/workdir/includes/libs/rdbms/database/Database.php(1545): Database->query()
#2 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Database.php(426): Database->update()
#3 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/PropertyStatisticsTable.php(135): SMW\MediaWiki\Database->update()
#4 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/PropertyStatisticsTable.php(169): SMW\SQLStore\PropertyStatisticsTable->addToUsageCount()
#5 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Writers.php(356): SMW\SQLStore\PropertyStatisticsTable->addToUsageCounts()
#6 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Writers.php(265): SMWSQLStore3Writers->writePropertyTableUpdates()
#7 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Writers.php(160): SMWSQLStore3Writers->doFlatDataUpdate()
#8 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(265): SMWSQLStore3Writers->doDataUpdate()
#9 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(218): SMWSQLStore3->doDataUpdate()
#10 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/includes/StoreUpdater.php(218): SMW\Store->updateData()
#11 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/includes/StoreUpdater.php(142): SMW\StoreUpdater->doRealUpdate()
#12 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/includes/StoreUpdater.php(96): SMW\StoreUpdater->doPerformUpdate()
#13 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/includes/ParserData.php(359): SMW\StoreUpdater->doUpdate()
#14 (): Closure$SMW\ParserData::updateStore()
#15 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/DeferredCallableUpdate.php(219): call_user_func()
#16 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/DeferredCallableUpdate.php(245): SMW\DeferredCallableUpdate->doUpdate()
#17 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/includes/ParserData.php(371): SMW\DeferredCallableUpdate->pushUpdate()
#18 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(178): SMW\ParserData->updateStore()
#19 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(140): SMW\MediaWiki\Jobs\UpdateJob->updateStore()
#20 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(112): SMW\MediaWiki\Jobs\UpdateJob->needToParsePageContentBeforeUpdate()
#21 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(80): SMW\MediaWiki\Jobs\UpdateJob->doPrepareForUpdate()
#22 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(61): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#23 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/EntityRebuildDispatcher.php(198): SMW\MediaWiki\Jobs\UpdateJob->run()
#24 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(307): SMW\SQLStore\EntityRebuildDispatcher->startRebuildWith()
#25 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(266): SMW\Maintenance\DataRebuilder->doExecuteFor()
#26 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(168): SMW\Maintenance\DataRebuilder->doRebuildAll()
#27 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/maintenance/rebuildData.php(151): SMW\Maintenance\DataRebuilder->rebuild()
#28 /srv/mediawiki/workdir/maintenance/doMaintenance.php(119): SMW\Maintenance\RebuildData->execute()
#29 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): include()
#30 {main}
Set $wgShowDBErrorBacktrace = true; at the bottom of LocalSettings.php to show detailed debugging information
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

Unsure. First observed in error logs, then again when running `php extensions/SemanticMediaWiki/maintenance/rebuildData.php -v`

Additional info: I am running MariaDB in strict mode.

```
MariaDB [translatewiki_net]> select * from bw_smw_prop_stats where p_id = 22;
+------+-------------+
| p_id | usage_count |
+------+-------------+
|   22 |           0 |
+------+-------------+
```

**Comment by kghbln** [comment]
Thank you for reporting!

**Comment by mwjames** [comment]
> Additional info: I am running MariaDB in strict mode.

Yes, in non-strict mode only a warning is issued making the query (update) work without failing, yet with the strict mode being enabled the update will emit an error [0] .

We actually want [1] to happen for all negative values but in strict mode that fails therefore the only viable solution without incurring another DB read would be to:

```
@@ -121,20 +121,29 @@ class PropertyStatisticsTable implements PropertyStatisticsStore, LoggerAwareInt
 
 		if ( $value == 0 ) {
 			return true;
 		}
 
-		return $this->connection->update(
-			$this->table,
-			array(
-				'usage_count = usage_count ' . ( $value > 0 ? '+ ' : '- ' ) . $this->connection->addQuotes( abs( $value ) ),
-			),
-			array(
-				'p_id' => $propertyId
-			),
-			__METHOD__
-		);
+		try {
+			$this->connection->update(
+				$this->table,
+				array(
+					'usage_count = usage_count ' . ( $value > 0 ? '+ ' : '- ' ) . $this->connection->addQuotes( abs( $value ) ),
+				),
+				array(
+					'p_id' => $propertyId
+				),
+				__METHOD__
+			);
+		} catch ( \DBQueryError $e ) {
+			// #2345 Do nothing as it most likely an "Error: 1264 Out of range
+			// value for column" in strict mode
+			// As an unsigned int, we expected it to be 0
+			$this->setUsageCount( $propertyId, 0 );
+		}
+
+		return true;
 	}
```

[0] https://dev.mysql.com/doc/refman/5.7/en/out-of-range-and-overflow.html "If strict SQL mode is enabled, MySQL rejects the out-of-range value with an error, and the insert fails, in accordance with the SQL standard."

[1]  https://dev.mysql.com/doc/refman/5.7/en/out-of-range-and-overflow.html "If the result of such an operation is used to update an UNSIGNED integer column, the result is clipped to the maximum value for the column type, or clipped to 0 ... error occurs and the column remains unchanged."
