### ISSUE TITLE
TransactionProfiler spams with "TRUNCATE TABLE smw_new"

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2436]
### Setup and configuration

- SMW version: all
- MW version: 1.28/1.29
- PHP version: all

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
query-m: TRUNCATE TABLE smw_new [TRX#f380cd]
#0 ...\mw-master\includes\libs\rdbms\TransactionProfiler.php(218): Wikimedia\Rdbms\TransactionProfiler->reportExpectationViolated('writes', 'query-m: TRUNCA...')
#1 ...\mw-master\includes\libs\rdbms\database\Database.php(979): Wikimedia\Rdbms\TransactionProfiler->recordQueryCompletion('query-m: TRUNCA...', 1493489625.2314, true, 0)
#2 ...\mw-master\includes\libs\rdbms\database\Database.php(891): Wikimedia\Rdbms\Database->doProfiledQuery('TRUNCATE TABLE ...', 'TRUNCATE /* SMW...', true, 'SMW\\SQLStore\\Qu...')
#3 ...\mw-master\extensions\SemanticMediaWiki\src\MediaWiki\Database.php(302): Wikimedia\Rdbms\Database->query('TRUNCATE TABLE ...', 'SMW\\SQLStore\\Qu...', false)
#4 ...\mw-master\extensions\SemanticMediaWiki\src\SQLStore\QueryEngine\HierarchyTempTableBuilder.php(185): SMW\MediaWiki\Database->query('TRUNCATE TABLE ...', 'SMW\\SQLStore\\Qu...')
#5 ...\mw-master\extensions\SemanticMediaWiki\src\SQLStore\QueryEngine\HierarchyTempTableBuilder.php(130): SMW\SQLStore\QueryEngine\HierarchyTempTableBuilder->buildTempTableFor('`t4`', '('125')', '`smw_fpt_subc`', 10)
#6 ...\mw-master\extensions\SemanticMediaWiki\src\SQLStore\QueryEngine\QuerySegmentListProcessor.php(297): SMW\SQLStore\QueryEngine\HierarchyTempTableBuilder->createHierarchyTempTableFor('class', '`t4`', '('125')')
#7 ...\mw-master\extensions\SemanticMediaWiki\src\SQLStore\QueryEngine\QuerySegmentListProcessor.php(239): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->resolveHierarchyForSegment(Object(SMW\SQLStore\QueryEngine\QuerySegment))
#8 ...\mw-master\extensions\SemanticMediaWiki\src\SQLStore\QueryEngine\QuerySegmentListProcessor.php(123): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->doResolveBySegment(Object(SMW\SQLStore\QueryEngine\QuerySegment))
#9 ...\mw-master\extensions\SemanticMediaWiki\src\SQLStore\QueryEngine\QuerySegmentListProcessor.php(123): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->doResolveBySegment(Object(SMW\SQLStore\QueryEngine\QuerySegment))
#10 ...\mw-master\extensions\SemanticMediaWiki\src\SQLStore\QueryEngine\QuerySegmentListProcessor.php(181): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->doResolveBySegment(Object(SMW\SQLStore\QueryEngine\QuerySegment))
#11 ...\mw-master\extensions\SemanticMediaWiki\src\SQLStore\QueryEngine\QuerySegmentListProcessor.php(123): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->doResolveBySegment(Object(SMW\SQLStore\QueryEngine\QuerySegment))
#12 ...\mw-master\extensions\SemanticMediaWiki\src\SQLStore\QueryEngine\QuerySegmentListProcessor.php(112): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->doResolveBySegment(Object(SMW\SQLStore\QueryEngine\QuerySegment))
#13 ...\mw-master\extensions\SemanticMediaWiki\src\SQLStore\QueryEngine\QueryEngine.php(201): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->doResolveQueryDependenciesById(0)
#14 ...\mw-master\extensions\SemanticMediaWiki\src\Query\Result\CachedQueryResultPrefetcher.php(265): SMW\SQLStore\QueryEngine\QueryEngine->getQueryResult(Object(SMWQuery))
#15 ...\mw-master\extensions\SemanticMediaWiki\src\MediaWiki\Hooks\HookRegistry.php(605): SMW\Query\Result\CachedQueryResultPrefetcher->getQueryResult(Object(SMWQuery))
#16 ...\mw-master\includes\Hooks.php(186): SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks\{closure}(Object(SMWSQLStore3), Object(SMWQuery), NULL, Object(SMW\SQLStore\QueryEngine\QueryEngine))
#17 ...\mw-master\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3.php(317): Hooks::run('SMW::Store::Bef...', Array)
#18 ...\mw-master\extensions\SemanticMediaWiki\includes\query\SMW_QueryProcessor.php(422): SMWSQLStore3->getQueryResult(Object(SMWQuery))
#19 ...\mw-master\extensions\SemanticMediaWiki\src\ParserFunctions\AskParserFunction.php(236): SMWQueryProcessor::getResultFromQuery(Object(SMWQuery), Array, 2, 1001)
#20 ...\mw-master\extensions\SemanticMediaWiki\src\ParserFunctions\AskParserFunction.php(141): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(Array)
#21 ...\mw-master\extensions\SemanticMediaWiki\src\ParserFunctionFactory.php(298): SMW\ParserFunctions\AskParserFunction->parse(Array)
#22 ...\mw-master\includes\parser\Parser.php(3408): SMW\ParserFunctionFactory->SMW\{closure}(Object(Parser), '[[Property:+]][...', '?Has descriptio...', '?Has type', 'class=datatable', '@control=slider', 'limit=50', 'offset=0')
#23 ...\mw-master\includes\parser\Parser.php(3128): Parser->callParserFunction(Object(PPFrame_DOM), 'ask', Array)
#24 ...\mw-master\includes\parser\Preprocessor_DOM.php(1199): Parser->braceSubstitution(Array, Object(PPFrame_DOM))
#25 ...\mw-master\includes\parser\Parser.php(2942): PPFrame_DOM->expand(Object(DOMElement), 0)
#26 ...\mw-master\includes\parser\Parser.php(1297): Parser->replaceVariables('{{#ask:[[Proper...')
#27 ...\mw-master\includes\parser\Parser.php(451): Parser->internalParse('{{#ask:[[Proper...')
#28 ...\mw-master\includes\StubObject.php(113): Parser->parse('{{#ask:[[Proper...', Object(Title), Object(ParserOptions), true, true, NULL)
#29 ...\mw-master\includes\StubObject.php(139): StubObject->_call('parse', Array)
#30 ...\mw-master\includes\content\WikitextContent.php(330): StubObject->__call('parse', Array)
#31 ...\mw-master\includes\content\AbstractContent.php(497): WikitextContent->fillParserOutput(Object(Title), NULL, Object(ParserOptions), true, Object(ParserOutput))
#32 ...\mw-master\includes\api\ApiParse.php(272): AbstractContent->getParserOutput(Object(Title), NULL, Object(ParserOptions))
#33 ...\mw-master\includes\api\ApiMain.php(1578): ApiParse->execute()
#34 ...\mw-master\includes\api\ApiMain.php(545): ApiMain->executeAction()
#35 ...\mw-master\includes\api\ApiMain.php(516): ApiMain->executeActionWithErrorHandling()
#36 ...\mw-master\api.php(83): ApiMain->execute()
```

Reason is that `Database::setTransactionProfiler` got removed in https://github.com/wikimedia/mediawiki/commit/5c681e438fd162ac6b140e07e15f2dbc1393a775 and we are no longer able to modify those expectations.

Tracked  in https://phabricator.wikimedia.org/T145947.

**Comment by mwjames** [comment]
Someone took care of it with https://gerrit.wikimedia.org/r/351120.

**Comment by kghbln** [comment]
> Someone took care of it with https://gerrit.wikimedia.org/r/351120.

[MW 1.30+ only](https://phabricator.wikimedia.org/T145947)
