### ISSUE TITLE
Exception thrown with an uncommited database transaction ... MWCallableUpdate::doUpdate: transaction round 'SMW\MediaWiki\Jobs\UpdateJob::run' already started

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2486]
### Setup and configuration

- SMW version: any
- MW version: 1.29+
- PHP version: any
- DB (MySQL etc.): any

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
[Bug56269] Exception thrown with an uncommited database transaction: [bf15bc4350f627484425b01b] /mw-master/index.php/Lorem_ipsum   Wikimedia\Rdbms\DBTransactionError from line 200 of ...\mw-master\includes\libs\rdbms\lbfactory\LBFactory.php: MWCallableUpdate::doUpdate: transaction round 'SMW\MediaWiki\Jobs\UpdateJob::run' already started.
#0 ...\mw-master\includes\deferred\DeferredUpdates.php(265): Wikimedia\Rdbms\LBFactory->beginMasterChanges(string)
#1 ...\mw-master\includes\deferred\DeferredUpdates.php(228): DeferredUpdates::runUpdate(MWCallableUpdate, Wikimedia\Rdbms\LBFactorySimple, integer)
#2 ...\mw-master\includes\deferred\DeferredUpdates.php(136): DeferredUpdates::execute(array, string, integer)
#3 ...\mw-master\includes\deferred\DeferredUpdates.php(95): DeferredUpdates::doUpdates(string)
#4 ...\mw-master\includes\deferred\DeferredUpdates.php(119): DeferredUpdates::addUpdate(MWCallableUpdate, integer)
#5 ...\mw-master\includes\libs\objectcache\BagOStuff.php(216): DeferredUpdates::addCallableUpdate(Closure)
#6 ...\mw-master\includes\libs\objectcache\BagOStuff.php(183): BagOStuff->trackDuplicateKeys(string)
#7 ...\mw-master\includes\parser\Preprocessor.php(110): BagOStuff->get(string)
#8 ...\mw-master\includes\parser\Preprocessor_DOM.php(152): Preprocessor->cacheGetTree(string, integer)
#9 ...\mw-master\includes\parser\Parser.php(2889): Preprocessor_DOM->preprocessToObj(string, integer)
#10 ...\mw-master\includes\parser\Parser.php(4121): Parser->preprocessToDom(string)
#11 ...\mw-master\includes\parser\Parser.php(1339): Parser->formatHeadings(string, string, boolean)
#12 ...\mw-master\includes\parser\Parser.php(451): Parser->internalParse(string)
#13 ...\mw-master\includes\StubObject.php(113): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#14 ...\mw-master\includes\StubObject.php(139): StubObject->_call(string, array)
#15 ...\mw-master\includes\content\WikitextContent.php(330): StubObject->__call(string, array)
#16 ...\mw-master\includes\content\AbstractContent.php(497): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#17 ...\mw-master\extensions\SemanticMediaWiki\includes\ContentParser.php(183): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#18 ...\mw-master\extensions\SemanticMediaWiki\includes\ContentParser.php(144): SMW\ContentParser->fetchFromContent()
#19 ...\mw-master\extensions\SemanticMediaWiki\src\MediaWiki\Jobs\UpdateJob.php(133): SMW\ContentParser->parse()
#20 ...\mw-master\extensions\SemanticMediaWiki\src\MediaWiki\Jobs\UpdateJob.php(117): SMW\MediaWiki\Jobs\UpdateJob->needToParsePageContentBeforeUpdate()
#21 ...\mw-master\extensions\SemanticMediaWiki\src\MediaWiki\Jobs\UpdateJob.php(85): SMW\MediaWiki\Jobs\UpdateJob->doPrepareForUpdate()
#22 ...\mw-master\extensions\SemanticMediaWiki\src\MediaWiki\Jobs\UpdateJob.php(66): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#23 ...\mw-master\includes\jobqueue\JobRunner.php(289): SMW\MediaWiki\Jobs\UpdateJob->run()
#24 ...\mw-master\includes\jobqueue\JobRunner.php(189): JobRunner->executeJob(SMW\MediaWiki\Jobs\UpdateJob, Wikimedia\Rdbms\LBFactorySimple, BufferingStatsdDataFactory, integer)
#25 ...\mw-master\includes\MediaWiki.php(973): JobRunner->run(array)
#26 ...\mw-master\includes\MediaWiki.php(959): MediaWiki->triggerSyncJobs(integer, MediaWiki\Logger\LegacyLogger)
#27 ...\mw-master\includes\MediaWiki.php(911): MediaWiki->triggerJobs()
#28 ...\mw-master\includes\MediaWiki.php(731): MediaWiki->restInPeace(string)
#29 ...\mw-master\includes\MediaWiki.php(750): MediaWiki->{closure}()
#30 ...\mw-master\includes\MediaWiki.php(554): MediaWiki->doPostOutputShutdown(string)
#31 ...\mw-master\index.php(43): MediaWiki->run()
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

Is tracked in https://phabricator.wikimedia.org/T165714 and not much we can do here because `BagOStuff::trackDuplicateKeys` breaks the transaction and ultimately throws an `Exception`.

**Comment by mwjames** [comment]
This issue is expected to be solved, and for those who care for history, see:

- https://phabricator.wikimedia.org/T165714 
- https://phabricator.wikimedia.org/T154425 with this one spinning my head. If it weren't for a different issue I worked on while testing something else it would have deployed a regression "... The regression is due to a pre-existing bug being exposed with transaction rounds ..."
