### ISSUE TITLE
InvalidArgumentException from line 271 of /../w/includes/Title.php: $text must be a string.

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3094]
### Setup and configuration

- MediaWiki | 1.30.0 (4c97eee)02:35, 3. Mär. 2018
- PHP | 7.0.27-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.0.0-alpha (d958586) 16:09, 25. Mär. 2018

### Issue
When trying to block a user the following issue is emitted:
```
InvalidArgumentException from line 271 of /../w/includes/Title.php: $text must be a string.
```

### Stack trace
```
#0 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/UserChange.php(66): Title::newFromText(User, integer)
#1 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(884): SMW\MediaWiki\Hooks\UserChange->process(User)
#2 /../w/includes/Hooks.php(177): SMW\MediaWiki\Hooks\HookRegistry->newBlockIpComplete(Block, User, NULL)
#3 /../w/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#4 /../w/includes/specials/SpecialBlock.php(794): Hooks::run(string, array)
#5 /../w/includes/specials/SpecialBlock.php(992): SpecialBlock::processForm(array, RequestContext)
#6 /../w/includes/htmlform/HTMLForm.php(669): SpecialBlock->onSubmit(array, HTMLForm)
#7 /../w/includes/htmlform/HTMLForm.php(561): HTMLForm->trySubmit()
#8 /../w/includes/htmlform/HTMLForm.php(576): HTMLForm->tryAuthorizedSubmit()
#9 /../w/includes/specialpage/FormSpecialPage.php(155): HTMLForm->show()
#10 /../w/includes/specialpage/SpecialPage.php(522): FormSpecialPage->execute(string)
#11 /../w/includes/specialpage/SpecialPageFactory.php(578): SpecialPage->run(string)
#12 /../w/includes/MediaWiki.php(287): SpecialPageFactory::executePath(Title, RequestContext)
#13 /../w/includes/MediaWiki.php(851): MediaWiki->performRequest()
#14 /../w/includes/MediaWiki.php(523): MediaWiki->main()
#15 /../w/index.php(43): MediaWiki->run()
#16 {main}
```

### Steps to reproduce
https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Bloquer/HymanBresnahan6

**Comment by mwjames** [comment]
> #0 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/UserChange.php(66): Title::newFromText(User, integer)
#1 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(884): SMW\MediaWiki\Hooks\UserChange->process(User)

Caused by #3061.

**Comment by mwjames** [comment]
Apparently `Block::getTraget` can return `User|string` so this needs to be checked.

**Comment by kghbln** [comment]
Affirmative. After the fix everything is working again according to my field test. Thanks a lot.
