### ISSUE TITLE
 DBUnexpectedError with a PostgreSQL database

### ISSUE THREAD

**Issue by abretaud** [SemanticMediaWiki/SemanticMediaWiki#3172]
### Setup and configuration

- SMW version: 2.5.6
- MW version: 1.28.1
- PHP version: 7.0.20
- DB system (MySQL, Blazegraph, etc.) and version: postgresql 9.5

_Note that it is **required** to provide the setup and configuration information. If you believe to have detected a regression after updating your software please also provide information about your previous setup as well. **In any case only this information will enable us to allocate appropriate review time.** Thank you for you help._

### Issue
_Please describe the issue as best as you can and also fill in the following two sections if applicable._

Hi,
I'm trying to use SemanticMediaWiki but I get the following error (stack trace below) when trying to display a page. I guess it could be a problem related to postgresql?

### Stack trace
Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and/or outputs:

```
[77d91a41214d56b9a47188ca] /index.php/xxxxxxxx DBUnexpectedError from line 2824 of /var/www/mediawiki/includes/libs/rdbms/database/Database.php: DatabasePostgres::reportQueryError: Expected mass rollback of all peer databases (DBO_TRX set).

Backtrace:

#0 /var/www/mediawiki/includes/libs/rdbms/database/DatabasePostgres.php(246): Database->rollback(string)
#1 /var/www/mediawiki/includes/libs/rdbms/database/Database.php(912): DatabasePostgres->reportQueryError(string, string, string, string, boolean)
#2 /var/www/mediawiki/includes/libs/rdbms/database/Database.php(1254): Database->query(string, string)
#3 /var/www/mediawiki/includes/libs/rdbms/database/Database.php(1322): Database->select(string, array, array, string, array, array)
#4 /var/www/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Database.php(335): Database->selectRow(string, array, array, string, array, array)
#5 /var/www/mediawiki/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_Sql3SmwIds.php(418): SMW\MediaWiki\Database->selectRow(string, array, array, string)
#6 /var/www/mediawiki/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_Sql3SmwIds.php(326): SMWSql3SmwIds->getDatabaseIdAndSort(string, integer, string, string, string, boolean, boolean)
#7 /var/www/mediawiki/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_Sql3SmwIds.php(595): SMWSql3SmwIds->getSMWPageIDandSort(string, integer, string, string, string, boolean, boolean)
#8 /var/www/mediawiki/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php(215): SMWSql3SmwIds->getSMWPageID(string, integer, string, string, boolean)
#9 /var/www/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/DirectEntityLookup.php(64): SMWSQLStore3Readers->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#10 /var/www/mediawiki/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(213): SMW\SQLStore\EntityStore\DirectEntityLookup->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#11 /var/www/mediawiki/extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(154): SMWSQLStore3->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty)
#12 /var/www/mediawiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php(304): SMW\Store->getRedirectTarget(SMW\DIProperty)
#13 /var/www/mediawiki/extensions/SemanticMediaWiki/includes/datavalues/SMW_DV_Property.php(215): SMW\DIProperty->getRedirectTarget()
#14 /var/www/mediawiki/extensions/SemanticMediaWiki/includes/datavalues/SMW_DataValue.php(181): SMWPropertyValue->parseUserValue(string)
#15 /var/www/mediawiki/extensions/SemanticMediaWiki/src/DataValueFactory.php(147): SMWDataValue->setUserValue(string, boolean)
#16 /var/www/mediawiki/extensions/SemanticMediaWiki/src/DataValueFactory.php(293): SMW\DataValueFactory->newDataValueByType(string, string, boolean, NULL, SMW\DIWikiPage)
#17 /var/www/mediawiki/extensions/SemanticMediaWiki/src/DataValueFactory.php(215): SMW\DataValueFactory->newPropertyValueByLabel(string, boolean, SMW\DIWikiPage)
#18 /var/www/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctions/SetParserFunction.php(85): SMW\DataValueFactory->newDataValueByText(string, string, boolean, SMW\DIWikiPage)
#19 /var/www/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(397): SMW\ParserFunctions\SetParserFunction->parse(SMW\ParserParameterProcessor)
#20 /var/www/mediawiki/includes/parser/Parser.php(3374): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string)
#21 /var/www/mediawiki/includes/parser/Parser.php(3098): Parser->callParserFunction(PPFrame_DOM, string, array)
#22 /var/www/mediawiki/includes/parser/Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPFrame_DOM)
#23 /var/www/mediawiki/includes/parser/Parser.php(2912): PPFrame_DOM->expand(DOMElement, integer)
#24 /var/www/mediawiki/includes/parser/Parser.php(1265): Parser->replaceVariables(string)
#25 /var/www/mediawiki/includes/parser/Parser.php(441): Parser->internalParse(string)
#26 /var/www/mediawiki/includes/content/WikitextContent.php(330): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#27 /var/www/mediawiki/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#28 /var/www/mediawiki/includes/poolcounter/PoolWorkArticleView.php(139): AbstractContent->getParserOutput(Title, integer, ParserOptions)
#29 /var/www/mediawiki/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#30 /var/www/mediawiki/includes/page/Article.php(650): PoolCounterWork->execute()
#31 /var/www/mediawiki/includes/actions/ViewAction.php(71): Article->view()
#32 /var/www/mediawiki/includes/MediaWiki.php(495): ViewAction->show()
#33 /var/www/mediawiki/includes/MediaWiki.php(289): MediaWiki->performAction(Article, Title)
#34 /var/www/mediawiki/includes/MediaWiki.php(851): MediaWiki->performRequest()
#35 /var/www/mediawiki/includes/MediaWiki.php(512): MediaWiki->main()
#36 /var/www/mediawiki/index.php(43): MediaWiki->run()
#37 {main}
```

### Steps to reproduce
_It is recommend to use the [sandbox](https://sandbox.semantic-mediawiki.org) to demonstrate the observed issue, otherwise provide us with a simple reproducible use case._

I was able to reproduce this error with a fresh mediawiki instance using docker. I use a custom image (https://github.com/abretaud/docker-mediawiki/blob/master/Dockerfile, https://quay.io/repository/abretaud/mediawiki) based on https://hub.docker.com/r/kristophjunge/mediawiki/.
The database is using the [standard postgres image](https://hub.docker.com/_/postgres/), version 9.5

Tell me if you need any other info

**Comment by abretaud** [comment]
Ok, in case anyone is already looking at it, I modified `/var/www/mediawiki/includes/libs/rdbms/database/DatabasePostgres.php(246)` to disable rollback and catch the real error, it looks like this:

```
Query: SELECT smw_id,smw_sortkey FROM "smw_object_ids" WHERE smw_title = 'Left_end_position' AND smw_namespace = '102' AND smw_iw = '' AND smw_subobject = '' LIMIT 1
Function: SMWSql3SmwIds::getDatabaseIdAndSort
Error: 42P01 ERROR: relation "smw_object_ids" does not exist
LINE 1: ...IdAndSort 172.30.0.4 */ smw_id,smw_sortkey FROM "smw_objec...
```

So I probably failed to install the extension correctly!?

**Comment by abretaud** [comment]
Sorry for the noise. I just needed to add the `--skip-external-dependencies` option to `maintenance/update.php`
