### ISSUE TITLE
mediawiki maintenance script install.php not working with semantic mediawiki

### ISSUE THREAD

**Issue by streiml** [SemanticMediaWiki/SemanticMediaWiki#3341]
### Setup and configuration

- SMW version: 2.5.5
- MW version: 1.27.4
- PHP version: 7.0.7
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB 10.0.35

### Issue
Hello,

it seems the maintenance script install.php of mediawiki ist not working if semantic mediawiki ist installed:
010d0d5cdc76c2b878435458] [no req] DBAccessError from line 36 of /srv/www/vhosts/mediawiki/MediaWiki/includes/db/loadbalancer/LBFactoryFake.php: Mediawiki tried to access the database via wfGetDB(). This is not allowed.
Backtrace:
#0 /srv/www/vhosts/mediawiki/MediaWiki/includes/GlobalFunctions.php(3167): LBFactoryFake->getMainLB(boolean)
#1 /srv/www/vhosts/mediawiki/MediaWiki/includes/GlobalFunctions.php(1294): wfGetLB()
#2 /srv/www/vhosts/mediawiki/MediaWiki/includes/GlobalFunctions.php(1273): wfReadOnlyReason()
#3 /srv/www/vhosts/mediawiki/MediaWiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(149): wfReadOnly()
#4 /srv/www/vhosts/mediawiki/MediaWiki/includes/Hooks.php(195): SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks\{closure}(Parser, string)
#5 /srv/www/vhosts/mediawiki/MediaWiki/includes/parser/Parser.php(1393): Hooks::run(string, array)
#6 /srv/www/vhosts/mediawiki/MediaWiki/includes/parser/Parser.php(455): Parser->internalParseHalfParsed(string, boolean, boolean)
#7 /srv/www/vhosts/mediawiki/MediaWiki/includes/cache/MessageCache.php(1108): Parser->parse(string, Title, ParserOptions, boolean)
#8 /srv/www/vhosts/mediawiki/MediaWiki/includes/Message.php(1159): MessageCache->parse(string, Title, boolean, boolean, Language)
#9 /srv/www/vhosts/mediawiki/MediaWiki/includes/Message.php(824): Message->parseText(string)
#10 /srv/www/vhosts/mediawiki/MediaWiki/includes/Message.php(880): Message->toString()
#11 /srv/www/vhosts/mediawiki/MediaWiki/includes/installer/CliInstaller.php(179): Message->parse()
#12 /srv/www/vhosts/mediawiki/MediaWiki/includes/installer/CliInstaller.php(162): CliInstaller->getMessageText(array)
#13 /srv/www/vhosts/mediawiki/MediaWiki/includes/installer/Installer.php(440): CliInstaller->showMessage(string, string)
#14 /srv/www/vhosts/mediawiki/MediaWiki/maintenance/install.php(139): Installer->doEnvironmentChecks()
#15 /srv/www/vhosts/mediawiki/MediaWiki/maintenance/doMaintenance.php(103): CommandLineInstaller->execute()
#16 /srv/www/vhosts/mediawiki/MediaWiki/maintenance/install.php(162): require_once(string)
#17 {main}

### Steps to reproduce
Extract MediaWiki 1.27 and install SemanticMediaWiki with composer. Then run the script maintenance/install.php.

**Comment by JeroenDeDauw** [comment]
Does this error happen when SMW is not loaded? Maybe your MW DB config is wrong.

---

Relevant code:

```php
class LBFactory_Fake extends LBFactory {
	function __construct( $conf ) {}

	function newMainLB( $wiki = false) {
		throw new DBAccessError;
	}
	function getMainLB( $wiki = false ) {
		throw new DBAccessError;
	}
	function newExternalLB( $cluster, $wiki = false ) {
		throw new DBAccessError;
	}
	function &getExternalLB( $cluster, $wiki = false ) {
		throw new DBAccessError;
	}
	function forEachLB( $callback, $params = array() ) {}
}

class DBAccessError extends MWException {
	function __construct() {
		parent::__construct( "Mediawiki tried to access the database via wfGetDB(). This is not allowed." );
	}
}
```

No longer exists in MW master.

**Comment by mwjames** [comment]
> 010d0d5cdc76c2b878435458] [no req] DBAccessError from line 36 of
> /srv/www/vhosts/mediawiki/MediaWiki/includes/db/loadbalancer/LBFactoryFake.php:
> Mediawiki tried to access the database via wfGetDB(). This is not allowed.
> Backtrace:

> /srv/www/vhosts/mediawiki/MediaWiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(149):
> wfReadOnly()
> #4 /srv/www/vhosts/mediawiki/MediaWiki/includes/Hooks.php(195):

We do fetch the necessary exception
`\MediaWiki\Services\ServiceDisabledException` and hereby making a
judgement that the DB is not available but apparently that isn't
enough, so try changing:

```
@@ -145,11 +145,11 @@ class HookRegistry {

 			// MediaWiki\Services\ServiceDisabledException from line 340 of
 			// ...\ServiceContainer.php: Service disabled: DBLoadBalancer
 			try {
 				$isReadOnly = wfReadOnly();
-			} catch( \MediaWiki\Services\ServiceDisabledException $e ) {
+			} catch( \Exception $e ) {
 				$isReadOnly = true;
 			}
```

Cheers

**Comment by streiml** [comment]
Thank you for your fast reply! 

@JeroenDeDauw: i want to create the database config and setup with this script via cli, so it does not already exist.

@mwjames: I changed this line in  'extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php' and now the script is running. There is only an error left at the end of the database init as you can see in the output. 

PHP 7.0.7 is installed.
Warning: Could not find APCu, XCache or WinCache.
Object caching is not enabled.
Found GD graphics library built-in.
Image thumbnailing will be enabled if you enable uploads.
Found the Git version control software: /usr/bin/git.
Warning: No --scriptpath specified, using default: /wiki.
Using server URL "/wiki".
Warning: Your default directory for uploads (/srv/www/vhosts/mediawiki/at.gv.noe.abb-wiki-t/app/images/) is not checked for vulnerability
to arbitrary script execution during the CLI install.
Using the intl PECL extension for Unicode normalization.
The environment has been checked.
You can install MediaWiki.
Setting up database
done
Creating tables
done
Creating database user
done
Populating default interwiki table
done
Initializing statistics
done
Generating secret keys
done
Prevent running unneeded updates
done
Creating administrator user account
done
Creating main page with default content
Could not insert main page: A database error has occurred. Did you forget to run maintenance/update.php after upgrading?  See: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
Query: SELECT  smw_id  FROM `smw_object_ids`   WHERE smw_title = 'Main_Page' AND smw_namespace = '0' AND smw_iw =  AND smw_subobject =   LIMIT 1
Function: SMWSql3SmwIds::getIDFor
Error: 1146 Table 'noewiki_abb.smw_object_ids' doesn't exist (mysql.test.noel.gv.at)

**Comment by mwjames** [comment]
> @mwjames: I changed this line in 'extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php' and now the script is running. There is only an error left at the end of the database init as you can see in the output.

The check for wfReadOnly relates to #2434 (as backport) but it seems
the `MediaWiki\Services\ServiceDisabledException` doesn't exist in MW
1.27.

> Could not insert main page: A database error has occurred. Did you forget to run maintenance/update.php after upgrading? See: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
Query: SELECT smw_id FROM smw_object_ids WHERE smw_title = 'Main_Page'
AND smw_namespace = '0' AND smw_iw = AND smw_subobject = LIMIT 1
Function: SMWSql3SmwIds::getIDFor
Error: 1146 Table 'noewiki_abb.smw_object_ids' doesn't exist
(mysql.test.noel.gv.at)

"... Manual:Upgrading#Run_the_update_script " the installation manual
has a note on requiring to run  "maintenance/update.php" otherwise no
tables are created and eventually will fail with "Error: 1146 Table
'noewiki_abb.smw_object_ids' doesn't exist ".

**Comment by mwjames** [comment]
> #11 /srv/www/vhosts/mediawiki/MediaWiki/includes/installer/CliInstaller.php(179): Message->parse()
#12 /srv/www/vhosts/mediawiki/MediaWiki/includes/installer/CliInstaller.php(162):
CliInstaller->getMessageText(array)
#13 /srv/www/vhosts/mediawiki/MediaWiki/includes/installer/Installer.php(440):
CliInstaller->showMessage(string, string)

I just realized that this to be using the `CliInstaller`
(maintenance/installer.php) which works slightly differently than the
`WebInstaller` and can access SMW before the extension tables have
been created (hence the error above), to prevent that from happening
the best I can think of is to extend:

```
@@ -61,10 +61,16 @@ class LinksUpdateConstructed implements
LoggerAwareInterface {
 	 *
 	 * @return true
 	 */
 	public function process( LinksUpdate $linksUpdate ) {

+		// When running as part of the install don't try to access the DB
+		// or update the Store
+		if ( defined( 'MEDIAWIKI_INSTALL' ) ) {
+			return true;
+		}
```

**Comment by streiml** [comment]
Thank you, I patched both files and now the script is working! Will the bugfix be available in version 2.5.5?

extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php:
                        try {
                                $isReadOnly = wfReadOnly();
                        } catch( \Exception $e ) {
//                      } catch( \MediaWiki\Services\ServiceDisabledException $e ) {
                                $isReadOnly = true;
                        }

extensions/SemanticMediaWiki/src/MediaWiki/Hooks/LinksUpdateConstructed.php:
        public function process( LinksUpdate $linksUpdate ) {
                // When running as part of the install don't try to access the DB
                // or update the Store
                if ( defined( 'MEDIAWIKI_INSTALL' ) ) {
                        return true;
                }
                $this->applicationFactory = ApplicationFactory::getInstance();

**Comment by kghbln** [comment]
> Thank you, I patched both files and now the script is working! 

Thanks a lot for testing and veryfing.

> Will the bugfix be available in version 2.5.5?

No, since we are already at version 2.5.7. ;) However this patch could be applied to 2.5.x. I suspect that 3.0.x requires different code changes.

**Comment by streiml** [comment]
okay, would be a good idea to use a newer version ;)

**Comment by kghbln** [comment]
@mwjames I guess SMW 2.5.x and master need different patches?

**Comment by mwjames** [comment]
>  If yes I could at least do the patch for 2.5.x as suggested here.

I would appreciate that.
