### ISSUE TITLE
RSS format: "SMW_QueryProcessor.php": Class 'SMW\Query\ResultFormatNotFoundException' not found

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#3479]
### Setup and configuration

- SMW version: 3.0.0-rc.1
- MW version: 1.31.1 
- PHP version: 7.0.32
- MySQL version: 5.7.23

### Issue
When clicking on RSS [in this page](https://www.semantic-mediawiki.org/wiki/Special:Ask/cl:YzpdUNEKgzAM_KDRdShuUOiLG3uS7RuqjVqIrbR1sr9f6uYQITRwubtcw4qSFaU4sOKWKjuxBbiqCJ3zb_GAORBqIgw7SqVsN6kOCGicBiHA7hg_rSYvsW7gLL9vcJbl1fNa8UEZi6oGlBzNYKLMufMavNQQGh6cj3Kj4q5tAyRS6_ygoqR0I6ZBAOWb_uvEsstS5x4QzcjykuQvAzM1h2RO3S6micc1tGpC2uP--GkGn_43TjWa0INOl7D0xN6kMf5OcORrgDUl0eMH), we get an `Internal error: Fatal exception of type "Error"`. 

I do not think it's a regression, I am just reporting the bug now.

```
[74ae217943e7d28e7df4a061] /wiki/Special:Ask/cl:YzpdkNFqwzAMRT9oeCoJfTH4ZR17ChusX6DGSmJwbCPLlP79lKWFUhC2fH2uLvaKIUW8UHQQwxrE9ZDZEztPdYSaWdw3XavpDh6FIE9TpQ2aMq8ojmuFSsjjsg_5PZ_B04Qtqi-rK-3mKzHpVtolhrqQ1z4kXWQJ23XENDec6R2E1hI16ZGquIA5fmjZN3P83Ko77MJJuTnzzd7ZoOYXZLgPVmHMnqyl9EI8vc4-EsD0X0-66frh5zRAYRK5FQ5JnHAjaEk_CQv9n_4A Error from line 435 of /../w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php: Class 'SMW\Query\ResultFormatNotFoundException' not found
```

## Backtrace:
```
#0 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(302): SMWQueryProcessor::getResultPrinter(string, integer)
#1 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(169): SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#2 /../w/includes/specialpage/SpecialPage.php(522): SMW\MediaWiki\Specials\SpecialAsk->execute(string)
#3 /../w/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(string)
#4 /../w/includes/MediaWiki.php(288): SpecialPageFactory::executePath(Title, RequestContext)
#5 /../w/includes/MediaWiki.php(861): MediaWiki->performRequest()
#6 /../w/includes/MediaWiki.php(524): MediaWiki->main()
#7 /../w/index.php(42): MediaWiki->run()
#8 {main}
```

**Comment by kghbln** [comment]
@jaideraf Thanks for reporting! @mwjames For your info.

**Comment by mwjames** [comment]
>  Class 'SMW\Query\ResultFormatNotFoundException' not found

```
@@ -10,11 +10,11 @@ use SMW\Parser\RecursiveTextProcessor;
 use SMW\Query\Deferred;
 use SMW\Query\PrintRequest;
 use SMW\Query\Processor\ParamListProcessor;
 use SMW\Query\Processor\DefaultParamDefinition;
 use SMW\Query\QueryContext;
-use SMW\Query\ResultFormatNotFoundException;
+use SMW\Query\Exception\ResultFormatNotFoundException;
```

This was missed because of a missing assertion, so add one!

```
 use SMWQueryProcessor;
+use SMW\Tests\PHPUnitCompat;

 /**
  * Tests for the SMWQueryProcessor class.
  *
  * @since 1.8
@@ -22,16 +23,24 @@ use SMWQueryProcessor;
  *
  * @author Nischay Nahata
  */
 class SMWQueryProcessorTest extends MwDBaseUnitTestCase {

+	use PHPUnitCompat;
+
 	public function createQueryDataProvider() {
 		return [
 			[ '[[Modification date::+]]|?Modification date|sort=Modification
date|order=desc' ],
 		];
 	}

+	public function testGetResultPrinter_ThrowsException() {
+
+		$this->setExpectedException(
'\SMW\Query\Exception\ResultFormatNotFoundException' );
+		SMWQueryProcessor::getResultPrinter( 'unknown_format' );
+	}
+
```

PS: I wonder which format is unknown and throws an exception, anyway
we'll see after the class was changed.

**Comment by mwjames** [comment]
I have to admit I first didn't understand "When clicking on RSS" on
how this would produce an error but I came across the button on
Special:Ask labeled RSS and when clicked produces the mentioned error.

The issue is that we're missing a line that matches the alias, so
after changes to the `ResultFormatNotFoundException` part has been
applied you need to add:

```
@@ -429,10 +429,12 @@ class SMWQueryProcessor implements QueryContext {
 	 * @throws MissingResultFormatException
 	 */
 	static public function getResultPrinter( $format, $context =
self::SPECIAL_PAGE ) {
 		global $smwgResultFormats;

+		SMWParamFormat::resolveFormatAliases( $format );
```

To make sure that this is tested in future as well also extend the test with:

```
@@ -28,10 +28,30 @@ class SMWQueryProcessorTest extends MwDBaseUnitTestCase {
 		return [
 			[ '[[Modification date::+]]|?Modification date|sort=Modification
date|order=desc' ],
 		];
 	}

+	/**
+	* @dataProvider resultAliasDataProvider
+	*/
+	public function testGetResultPrinter_MatchAlias( $alias ) {
+
+		$this->assertInstanceOf(
+			'\SMW\Query\ResultPrinter',
+			SMWQueryProcessor::getResultPrinter( $alias )
+		);
+	}
+
+	public function resultAliasDataProvider() {
+
+		foreach ( $GLOBALS['smwgResultAliases'] as $format => $aliases ) {
+			foreach ( $aliases as $alias ) {
+				yield [ $alias ];
+			}
+		}
+	}
```
