### ISSUE TITLE
"PredefinedPropertyLabelMismatchException" from line 94 of "SMW_DI_Property.php"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3482]
### Setup and configuration
- MediaWiki | 1.31.1 (1f664ea)00:05, 21 September 2018
- PHP | 7.0.30-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.0.0-rc.1 (68a8409) 22:37, 22 September 2018

### Issue
"rebuildFulltextSearchTable.php" fails with:

```
[ac60fde656b2ac5f88ba566d] [no req]   SMW\Exception\PredefinedPropertyLabelMismatchException from line 94 of /../w/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php: There is no predefined property with "_RL_DEF".
```
Refs: 
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3431#issuecomment-421627511
- https://github.com/SemanticMediaWiki/SemanticNotifications/pull/25#issuecomment-423991940

## Backtrace:
```
#0 /../w/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php(488): SMW\DIProperty->__construct(string, boolean)
#1 /../w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/SearchTable.php(105): SMW\DIProperty::newFromUserLabel(string)
#2 /../w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/SearchTableRebuilder.php(291): SMW\SQLStore\QueryEngine\Fulltext\SearchTable->isExemptedPropertyById(string)
#3 /../w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/SearchTableRebuilder.php(266): SMW\SQLStore\QueryEngine\Fulltext\SearchTableRebuilder->doRebuildFromRows(SMW\SQLStore\QueryEngine\Fulltext\SearchTable, string, string, Wikimedia\Rdbms\ResultWrapper)
#4 /../w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/SearchTableRebuilder.php(207): SMW\SQLStore\QueryEngine\Fulltext\SearchTableRebuilder->doRebuildByPropertyTable(SMW\SQLStore\PropertyTableDefinition)
#5 /../w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/SearchTableRebuilder.php(114): SMW\SQLStore\QueryEngine\Fulltext\SearchTableRebuilder->doRebuild()
#6 /../w/extensions/SemanticMediaWiki/maintenance/rebuildFulltextSearchTable.php(107): SMW\SQLStore\QueryEngine\Fulltext\SearchTableRebuilder->rebuild()
#7 /../w/maintenance/doMaintenance.php(94): SMW\Maintenance\RebuildFulltextSearchTable->execute()
#8 /../w/extensions/SemanticMediaWiki/maintenance/rebuildFulltextSearchTable.php(177): require_once(string)
#9 {main}
```

**Comment by mwjames** [comment]
```
@@ -6,10 +6,11 @@ use SMW\DataTypeRegistry;
 use SMW\DIProperty;
 use SMW\DIWikiPage;
 use SMW\MediaWiki\Database;
 use SMW\SQLStore\SQLStore;
 use SMWDataItem as DataItem;
+use SMW\Exception\PredefinedPropertyLabelMismatchException;

 /**
  * @license GNU GPL v2+
  * @since 2.5
  *
@@ -99,13 +100,21 @@ class SearchTable {

 		if ( !$dataItem instanceof DIWikiPage || $dataItem->getDBKey() === '' ) {
 			return false;
 		}

-		return $this->isExemptedProperty(
-			DIProperty::newFromUserLabel( $dataItem->getDBKey() )
-		);
+		try {
+			$property = DIProperty::newFromUserLabel(
+				$dataItem->getDBKey()
+			);
+		} catch( PredefinedPropertyLabelMismatchException $e ) {
+			// The property no longer exists (or is no longer available) therefore
+			// exempt it.
+			return true;
+		}
+
+		return $this->isExemptedProperty( $property );
```
