### ISSUE TITLE
Insufficient checking of SMWDIUri type properties on entry results in DataTypeExceptions on ask

### ISSUE THREAD

**Issue by FO-nTTaX** [SemanticMediaWiki/SemanticMediaWiki#3540]
### Setup and configuration

- SMW version: 3.0.0
- MW version: 1.31.1
- PHP version: 7.0.30-0+deb9u1 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version: 10.1.26-MariaDB-0+deb9u1

### Issue
I have a property called `has site` set up like `This property [[Has type::URL|has the datatype URL]].`. The related internal class to handle this property is therefore `SMWDIUri`. If I set the property like this, SemanticMediaWiki does not complain about the input and saves the page: 
```
{{#set:
|has site=http:///
}}
```
Now If I try to ask for the data on another page like this, all I get is an exception:
```
{{#ask:[[Has site::+]]
|?has site
}}
```
The property page also displays the same `SMW\Exception\DataItemException`. 

It would probably be more sane to not store the value of this URL in the first place. In a wiki with thousands of pages, searching for the one broken one is really hard. As the main wiki where I encountered this is editable by a wide range of people, we can't always check every page 100% and the fact that the page itself shows no error makes it hard for people to check for such errors.

### Stack trace
Back trace on the asking page:
```
[97f731dbcc09075f28b86613] /wiki/index.php/SMW_Get SMW\Exception\DataItemException from line 54 of /path/to/wiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_URI.php: Illegal URI hierpart "".

Backtrace:

#0 /path/to/wiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_URI.php(155): SMWDIUri->__construct(string, string, string, string, boolean)
#1 /path/to/wiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/DIHandlers/DIUriHandler.php(151): SMWDIUri::doUnserialize(string)
#2 /path/to/wiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/StubSemanticData.php(164): SMW\SQLStore\EntityStore\DIHandlers\DIUriHandler->dataItemFromDBKeys(array)
#3 /path/to/wiki/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php(221): SMW\SQLStore\EntityStore\StubSemanticData->getPropertyValues(SMW\DIProperty)
#4 /path/to/wiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/NativeEntityLookup.php(64): SMWSQLStore3Readers->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#5 /path/to/wiki/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(194): SMW\SQLStore\EntityStore\NativeEntityLookup->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#6 /path/to/wiki/extensions/SemanticMediaWiki/src/Query/Result/ResultFieldMatchFinder.php(302): SMWSQLStore3->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#7 /path/to/wiki/extensions/SemanticMediaWiki/src/Query/Result/ResultFieldMatchFinder.php(286): SMW\Query\Result\ResultFieldMatchFinder->doFetchPropertyValues(array, SMW\DataValues\PropertyValue)
#8 /path/to/wiki/extensions/SemanticMediaWiki/src/Query/Result/ResultFieldMatchFinder.php(194): SMW\Query\Result\ResultFieldMatchFinder->getResultContent(SMW\DIWikiPage)
#9 /path/to/wiki/extensions/SemanticMediaWiki/src/Query/Result/ResultFieldMatchFinder.php(144): SMW\Query\Result\ResultFieldMatchFinder->getResultsForProperty(SMW\DIWikiPage)
#10 /path/to/wiki/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php(262): SMW\Query\Result\ResultFieldMatchFinder->findAndMatch(SMW\DIWikiPage)
#11 /path/to/wiki/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php(145): SMWResultArray->loadContent()
#12 /path/to/wiki/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php(179): SMWResultArray->getNextDataItem()
#13 /path/to/wiki/extensions/SemanticMediaWiki/src/Query/ResultPrinters/TableResultPrinter.php(241): SMWResultArray->getNextDataValue()
#14 /path/to/wiki/extensions/SemanticMediaWiki/src/Query/ResultPrinters/TableResultPrinter.php(222): SMW\Query\ResultPrinters\TableResultPrinter->getCellForPropVals(SMWResultArray, integer, string)
#15 /path/to/wiki/extensions/SemanticMediaWiki/src/Query/ResultPrinters/TableResultPrinter.php(130): SMW\Query\ResultPrinters\TableResultPrinter->getRowForSubject(array, integer, array)
#16 /path/to/wiki/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(342): SMW\Query\ResultPrinters\TableResultPrinter->getResultText(SMWQueryResult, integer)
#17 /path/to/wiki/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(307): SMW\Query\ResultPrinters\ResultPrinter->buildResult(SMWQueryResult)
#18 /path/to/wiki/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(388): SMW\Query\ResultPrinters\ResultPrinter->getResult(SMWQueryResult, array, integer)
#19 /path/to/wiki/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(344): SMWQueryProcessor::getResultFromQuery(SMWQuery, array, integer, integer)
#20 /path/to/wiki/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(183): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array, array)
#21 /path/to/wiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(385): SMW\ParserFunctions\AskParserFunction->parse(array)
#22 /path/to/wiki/includes/parser/Parser.php(3426): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string)
#23 /path/to/wiki/includes/parser/Parser.php(3127): Parser->callParserFunction(PPFrame_DOM, string, array)
#24 /path/to/wiki/includes/parser/Preprocessor_DOM.php(1277): Parser->braceSubstitution(array, PPFrame_DOM)
#25 /path/to/wiki/includes/parser/Parser.php(2942): PPFrame_DOM->expand(DOMElement, integer)
#26 /path/to/wiki/includes/parser/Parser.php(1293): Parser->replaceVariables(string)
#27 /path/to/wiki/includes/parser/Parser.php(443): Parser->internalParse(string)
#28 /path/to/wiki/includes/content/WikitextContent.php(323): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#29 /path/to/wiki/includes/content/AbstractContent.php(516): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#30 /path/to/wiki/includes/poolcounter/PoolWorkArticleView.php(144): AbstractContent->getParserOutput(Title, integer, ParserOptions)
#31 /path/to/wiki/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#32 /path/to/wiki/includes/page/Article.php(604): PoolCounterWork->execute()
#33 /path/to/wiki/includes/actions/ViewAction.php(68): Article->view()
#34 /path/to/wiki/includes/MediaWiki.php(500): ViewAction->show()
#35 /path/to/wiki/includes/MediaWiki.php(294): MediaWiki->performAction(Article, Title)
#36 /path/to/wiki/includes/MediaWiki.php(861): MediaWiki->performRequest()
#37 /path/to/wiki/includes/MediaWiki.php(524): MediaWiki->main()
#38 /path/to/wiki/index.php(42): MediaWiki->run()
#39 {main}
```
Backtrace on the property page: 
```
[d2af72e865815eb9bafc08c8] /wiki/index.php/Property:Has_site SMW\Exception\DataItemException from line 54 of /path/to/wiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_URI.php: Illegal URI hierpart "".

Backtrace:

#0 /path/to/wiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_URI.php(155): SMWDIUri->__construct(string, string, string, string, boolean)
#1 /path/to/wiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/DIHandlers/DIUriHandler.php(151): SMWDIUri::doUnserialize(string)
#2 /path/to/wiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/StubSemanticData.php(164): SMW\SQLStore\EntityStore\DIHandlers\DIUriHandler->dataItemFromDBKeys(array)
#3 /path/to/wiki/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php(221): SMW\SQLStore\EntityStore\StubSemanticData->getPropertyValues(SMW\DIProperty)
#4 /path/to/wiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/NativeEntityLookup.php(64): SMWSQLStore3Readers->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, SMW\RequestOptions)
#5 /path/to/wiki/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(194): SMW\SQLStore\EntityStore\NativeEntityLookup->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, SMW\RequestOptions)
#6 /path/to/wiki/extensions/SemanticMediaWiki/src/Page/ListBuilder/ValueListBuilder.php(279): SMWSQLStore3->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, SMW\RequestOptions)
#7 /path/to/wiki/extensions/SemanticMediaWiki/src/Page/ListBuilder/ValueListBuilder.php(175): SMW\Page\ListBuilder\ValueListBuilder->createValueList(SMW\DIProperty, SMW\DIWikiPage, array, integer, string)
#8 /path/to/wiki/extensions/SemanticMediaWiki/src/Page/PropertyPage.php(332): SMW\Page\ListBuilder\ValueListBuilder->createHtml(SMW\DIProperty, SMW\DIWikiPage, array)
#9 /path/to/wiki/extensions/SemanticMediaWiki/src/Page/PropertyPage.php(189): SMW\Page\PropertyPage->makeValueList(string)
#10 /path/to/wiki/extensions/SemanticMediaWiki/src/Page/Page.php(194): SMW\Page\PropertyPage->getHtml()
#11 /path/to/wiki/extensions/SemanticMediaWiki/src/Page/Page.php(101): SMW\Page\Page->showList()
#12 /path/to/wiki/includes/actions/ViewAction.php(68): SMW\Page\Page->view()
#13 /path/to/wiki/includes/MediaWiki.php(500): ViewAction->show()
#14 /path/to/wiki/includes/MediaWiki.php(294): MediaWiki->performAction(SMW\Page\PropertyPage, Title)
#15 /path/to/wiki/includes/MediaWiki.php(861): MediaWiki->performRequest()
#16 /path/to/wiki/includes/MediaWiki.php(524): MediaWiki->main()
#17 /path/to/wiki/index.php(42): MediaWiki->run()
#18 {main}
```

### Steps to reproduce
I have a minimal test case on my own test wiki, relevant URLs are as follows:
* Property page: https://wiki.liquipedia.space/wiki/index.php/Property:Has_site
* Setting page: https://wiki.liquipedia.space/wiki/index.php/SMW_Set
* Asking page: https://wiki.liquipedia.space/wiki/index.php/SMW_Get

**Comment by kghbln** [comment]
Thanks a lot for reporting elaborately. I also think that such values should not be stored in the first place. As an interim workaround you could use [special property "Allows pattern"](https://www.semantic-mediawiki.org/wiki/Help:Special_property_Allows_pattern) to prevent data storage or alternatively within a form (if used) via the regexp input type already at data entry.

**Comment by mwjames** [comment]
> [97f731dbcc09075f28b86613] /wiki/index.php/SMW_Get SMW\Exception\DataItemException from line 54 of /path/to/wiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_URI.php: Illegal URI hierpart "".

This is not a regression to SMW 3.0 or 2.5 given that the relevant code has been unchanged since at least 1.8.0.5 [0, 1] which isn't to say that the behaviour is correct.

We could silently apply the same `$hierpart = ltrim( $hierpart, '/' );` rule as in [0] but this would hide the fact that the user made an input error, so instead, we raise a new error during during input validation [1] while the serialization/deserialization [0] remains untouched. The deserialization error will continue to appear for old values until a page that contains the invalid value is re-parsed.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.8.0.5/includes/dataitems/SMW_DI_URI.php#L131
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.8.0.5/includes/datavalues/SMW_DV_URI.php#L106-L108
