### ISSUE TITLE
HtmlForm::getForm must be an instance of SMWQueryResult or null, string given

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3570]
### Setup and configuration

- SMW version: 3.0+
- MW version: 1.33+
- PHP version: 7.1

### Issue

Appeared in connection with a `RemoteQuest`

### Stack trace

```
[dcc3a9894a346ece712121c2] /.../index.php?title=Special:Ask& TypeError from line 141 of ...\extensions\SemanticMediaWiki\src\MediaWiki\Specials\Ask\HtmlForm.php: Argument 2 passed to SMW\MediaWiki\Specials\Ask\HtmlForm::getForm() must be an instance of SMWQueryResult or null, string given, called in ...\extensions\SemanticMediaWiki\src\MediaWiki\Specials\SpecialAsk.php on line 390

Backtrace:

#0 ...\extensions\SemanticMediaWiki\src\MediaWiki\Specials\SpecialAsk.php(390): SMW\MediaWiki\Specials\Ask\HtmlForm->getForm(SMW\MediaWiki\Specials\Ask\UrlArgs, string, string)
#1 ...\extensions\SemanticMediaWiki\src\MediaWiki\Specials\SpecialAsk.php(169): SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#2 ...\includes\specialpage\SpecialPage.php(569): SMW\MediaWiki\Specials\SpecialAsk->execute(NULL)
#3 ...\includes\specialpage\SpecialPageFactory.php(558): SpecialPage->run(NULL)
#4 ...\includes\MediaWiki.php(288): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#5 ...\includes\MediaWiki.php(862): MediaWiki->performRequest()
#6 ...\includes\MediaWiki.php(517): MediaWiki->main()
#7 ...\index.php(42): MediaWiki->run()
#8 {main}
```

**Comment by kghbln** [comment]
@mwjames I guess this could be back-ported to 3.0.x?
