### ISSUE TITLE
SPARQLStore / missing colon in `#ask` will cause BadHttpDatabaseResponseException

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#359]
```
$smwgDefaultStore = 'SMWSparqlStore';
$smwgSparqlDatabaseConnector = 'fuseki';
```
[GenericLoremIpsumTest-Mw-1-19-7.xml](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Regression/data/GenericLoremIpsumTest-Mw-1-19-7.xml) is imported for testing purpose. Create a page with (note #ask is used without colon):
```
{{#ask [[Has Url::+]]|?Has Url}}  
```
will fail with
```
Unexpected non-MediaWiki exception encountered, of type "SMW\SPARQLStore\BadHttpDatabaseResponseException"
[d40d64a6] /mw/index.php/Queries Exception from line 73 of ...\src\SPARQLStore\BadHttpResponseMapper.php: A SPARQL query error has occurred
Query: PREFIX wiki: <http://localhost:8080/mw/Special:URIResolver/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX swivt: <http://semantic-mediawiki.org/swivt/1.0#>
PREFIX property: <http://localhost:8080/mw/Special:URIResolver/Property-3A>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wikiurl: <http://localhost:8080/mw/index.php/>
INSERT DATA { 
wiki:Queries
rdf:type swivt:Subject ;
rdfs:label "Queries" ;
swivt:page <http://localhost:8080/mw/index.php/Queries> ;
rdfs:isDefinedBy <http://localhost:8080/mw/index.php/Special:ExportRDF/Queries> ;
swivt:wikiNamespace "0"^^xsd:integer ;
property:Has_Url <http://%2B> ;
swivt:wikiPageModificationDate "2014-06-27T22:05:59Z"^^xsd:dateTime ;
property:Modification_date-23aux "2456836.4208218"^^xsd:double ;
swivt:wikiPageSortKey "Queries" .

property:Modification_date
rdf:type owl:ObjectProperty ;
rdfs:label "Modification date" ;
swivt:page <http://localhost:8080/mw/index.php/Property:Modification_date> ;
rdfs:isDefinedBy <http://localhost:8080/mw/index.php/Special:ExportRDF/Property:Modification_date> ;
swivt:wikiNamespace "102"^^xsd:integer ;
swivt:wikiPageSortKey "Modification date" .

<http://semantic-mediawiki.org/swivt/1.0#page> rdf:type owl:ObjectProperty .
<http://semantic-mediawiki.org/swivt/1.0#wikiNamespace> rdf:type owl:DatatypeProperty .
<http://localhost:8080/mw/Special:URIResolver/Property-3AHas_Url> rdf:type owl:ObjectProperty .
<http://semantic-mediawiki.org/swivt/1.0#wikiPageModificationDate> rdf:type owl:DatatypeProperty .
<http://localhost:8080/mw/Special:URIResolver/Property-3AModification_date-23aux> rdf:type owl:DatatypeProperty .
<http://semantic-mediawiki.org/swivt/1.0#wikiPageSortKey> rdf:type owl:DatatypeProperty .
} 
Error: Malformed query
Endpoint: http://localhost:3030/db/update
HTTP response code: 400

Backtrace:
#0 ...\src\SPARQLStore\BadHttpResponseMapper.php(57): SMW\SPARQLStore\BadHttpResponseMapper->createResponseToHttpError(integer, string, string)
#1 ...\src\SPARQLStore\SMW_SparqlDatabase.php(514): SMW\SPARQLStore\BadHttpResponseMapper->mapResponseToHttpRequest(string, string)
#2 ...\src\SPARQLStore\SMW_SparqlDatabase.php(430): SMWSparqlDatabase->throwSparqlErrors(string, string)
#3 ...\src\SPARQLStore\SMW_SparqlDatabase.php(343): SMWSparqlDatabase->doUpdate(string)
#4 ...\src\SPARQLStore\SMW_SparqlStore.php(172): SMWSparqlDatabase->insertData(string, array)
#5 ...\storage\SMW_Store.php(218): SMWSparqlStore->doDataUpdate(SMW\SemanticData)

```

because `[[Has Url::+]]` is recognized as annotation where SPARQLStore and the Sparql backend will not understand `+` as value.

**Comment by mwjames** [comment]
This is no longer  an issue with 2.3 (was fixed somewhere a long the way).
