### ISSUE TITLE
`smw_ft_search` causes "Error: 1785 Statement violates GTID consistency: Updates to non-transactional tables ..."

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3606]
Running rebuildData.php on a system with GTID enabled, I get:

```
Wikimedia\Rdbms\DBQueryError from line 1457 of /../wiki/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading?
Query: DELETE FROM `smw_ft_search` WHERE s_id = '501'
Function: SMW\SQLStore\PropertyTableIdReferenceDisposer::cleanUpSecondaryReferencesById
Error: 1785 Statement violates GTID consistency: Updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables. (192.168.236.1)
```

Full trace:
```
#0 /../wiki/includes/libs/rdbms/database/Database.php(1184): Wikimedia\Rdbms\Database->makeQueryException('Statement viola...', 1785, 'DELETE FROM `sm...', 'SMW\\SQLStore\\Pr...')
#1 /../wiki/includes/libs/rdbms/database/Database.php(2845): Wikimedia\Rdbms\Database->query('DELETE FROM `sm...', 'SMW\\SQLStore\\Pr...')
#2 /../wiki/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(673): Wikimedia\Rdbms\Database->delete('`smw_ft_search`', 's_id = '501'', 'SMW\\SQLStore\\Pr...')
#3 /../wiki/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(248): SMW\MediaWiki\Connection\Database->delete('smw_ft_search', Array, 'SMW\\SQLStore\\Pr...')
#4 /../wiki/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(204): SMW\SQLStore\PropertyTableIdReferenceDisposer->cleanUpSecondaryReferencesById('501', false)
#5 /../wiki/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(150): SMW\SQLStore\PropertyTableIdReferenceDisposer->cleanUpReferencesById('501')
#6 /../wiki/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(132): SMW\SQLStore\PropertyTableIdReferenceDisposer->cleanUpTableEntriesById('501')
#7 /../wiki/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/EntityIdDisposerJob.php(58): SMW\SQLStore\PropertyTableIdReferenceDisposer->cleanUpTableEntriesByRow(Object(stdClass))
#8 /../wiki/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(486): SMW\MediaWiki\Jobs\EntityIdDisposerJob->dispose(Object(stdClass))
#9 /../wiki/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(264): SMW\Maintenance\DataRebuilder->dispose_outdated()
#10 /../wiki/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(182): SMW\Maintenance\DataRebuilder->rebuild_all()
#11 /../wiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php(167): SMW\Maintenance\DataRebuilder->rebuild()
#12 /../wiki/maintenance/doMaintenance.php(95): SMW\Maintenance\RebuildData->execute()
#13 /../wiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php(225): require_once('/var/www/events...')
#14 {main}
```

Platform:
* MediaWiki 1.31.1
* SMW 3.0.0
* MariaDB 10.3.11

Config:
```php
$smwgLocalConnectionConf['mw.db.queryengine'] = array(
  'read' => DB_MASTER,
  'write' => DB_MASTER
);
```

The documentation suggests to set both to DB_REPLICA, but writing to the replica is generally not possible, and if it is, it is bound to break things. It should never be done. In any case, the error does not seem to depend on what you put into $smwgLocalConnectionConf.

_Originally posted by @brightbyte in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3558#issuecomment-448619267_

**Comment by mwjames** [comment]
As noted in #3604 "smw_ft_search is classified as non-transactional because it uses MyISAM [2, 3, 4] by default and you have to adapt the smwgFulltextSearchTableOptions setting to switch to InnoDB."

[2] "... When using GTIDs, updates to tables using nontransactional storage engines such as MyISAM cannot be made in the same statement or transaction as updates to tables using transactional storage engines such as InnoDB."
[3] https://dev.mysql.com/doc/refman/5.6/en/replication-gtids-restrictions.html
[4] https://www.percona.com/blog/2013/05/21/replication-in-mysql-5-6-gtids-benefits-and-limitations-part-1/

**Comment by mwjames** [comment]
To avoid further confusion in future, #3605 will ensure that `smw_ft_search` is only created on the condition of `smwgEnabledFulltextSearch` being set leaving the user to review related documentation and settings before issues arise due to mixing MyISAM and InnoDB (#3604 explains why MyISAM is used as default).

I created this issue solely for the purpose of documenting the observation in regards to "... Statement violates GTID consistency: Updates to non-transactional tables ..." and for that matter no actions need to be taken by SMW as long as the table and options are setup accordingly.

#3605 will hopefully prevent similar issues in future where MyISAM and InnoDB are mixed..

@kghbln @jamesmontalvo3 FYI

**Comment by mwjames** [comment]
This issue has been documented and explained, further we provided an additionally cautionary measure (#3604 ) to have users read the necessary documentation before they activate the feature.
