### ISSUE TITLE
MW master/tests are broken with "ResourceLoaderModule::saveFileDependencies: failed to update DB: UnexpectedValueException: Got connection to ... but expected local domain ..."

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#3731]
MW master is broken [0] and hereby our integration tests with it, most likely happened between last and this weekend given that last week all tests did pass especially the `SMW\Tests\System\ResourcesAccessibilityTest` .

```
Using PHP 7.3.2

Semantic MediaWiki: 3.1.0-alpha, git: 37fe1db, SMWSQLStore (mysql:5.6.33-0ubuntu0.14.04.1)
MediaWiki:          1.33.0-alpha, git: 0a8a4fe (refs/heads/master), Extension vendor autoloader
Site language:      en

Execution time:     2019-02-23 09:30
Debug logs:         Disabled
Xdebug:             Disabled (or not installed)

PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.2
```
```
[resourceloader] [info] ResourceLoaderModule::saveFileDependencies: failed to update DB: UnexpectedValueException: Got connection to 'its_a_mw', but expected local domain ('its_a_mw-sunittest_'). in /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/loadbalancer/LoadBalancer.php:943
Stack trace:
#0 /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/loadbalancer/LoadBalancer.php(872): Wikimedia\Rdbms\LoadBalancer->openLocalConnection(0, 0)
#1 /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/loadbalancer/LoadBalancer.php(748): Wikimedia\Rdbms\LoadBalancer->openConnection(0, false, 0)
#2 /home/travis/build/SemanticMediaWiki/mw/includes/GlobalFunctions.php(2654): Wikimedia\Rdbms\LoadBalancer->getConnection(0, Array, false)
#3 /home/travis/build/SemanticMediaWiki/mw/includes/resourceloader/ResourceLoaderModule.php(419): wfGetDB(-1)
#4 /home/travis/build/SemanticMediaWiki/mw/includes/resourceloader/ResourceLoaderModule.php(480): ResourceLoaderModule->getFileDependencies(Object(ResourceLoaderContext))
#5 /home/travis/build/SemanticMediaWiki/mw/includes/resourceloader/ResourceLoaderFileModule.php(434): ResourceLoaderModule->saveFileDependencies(Object(ResourceLoaderContext), Array)
#6 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Integration/System/ResourcesAccessibilityTest.php(39): ResourceLoaderFileModule->getStyles(Object(ResourceLoaderContext))
#7 [internal function]: SMW\Tests\System\ResourcesAccessibilityTest->testModulesStylesFilesAreAccessible(Array, Object(ResourceLoader), Object(ResourceLoaderContext))
#8 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/src/Framework/TestCase.php(1071): ReflectionMethod->invokeArgs(Object(SMW\Tests\System\ResourcesAccessibilityTest), Array)
#9 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/src/Framework/TestCase.php(939): PHPUnit\Framework\TestCase->runTest()
#10 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/src/Framework/TestResult.php(698): PHPUnit\Framework\TestCase->runBare()
#11 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/src/Framework/TestCase.php(894): PHPUnit\Framework\TestResult->run(Object(SMW\Tests\System\ResourcesAccessibilityTest))
#12 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestCase->run(Object(MediaWikiTestResult))
#13 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestSuite->run(Object(MediaWikiTestResult))
#14 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestSuite->run(Object(MediaWikiTestResult))
#15 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestSuite->run(Object(MediaWikiTestResult))
#16 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(545): PHPUnit\Framework\TestSuite->run(Object(MediaWikiTestResult))
#17 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#18 /home/travis/build/SemanticMediaWiki/mw/tests/phpunit/phpunit.php(90): PHPUnit\TextUI\Command->run(Array, true)
#19 /home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php(94): PHPUnitMaintClass->execute()
#20 /home/travis/build/SemanticMediaWiki/mw/tests/phpunit/phpunit.php(129): require('/home/travis/bu...')
#21 {main} {"private":false}
[resourceloader] [info] ResourceLoaderModule::saveFileDependencies: failed to update DB: UnexpectedValueException: Got connection to 'its_a_mw', but expected local domain ('its_a_mw-sunittest_'). in /home/travis/build/SemanticMediaWiki/mw/includes/libs/rdbms/loadbalancer/LoadBalancer.php:943
```

[0] https://api.travis-ci.org/v3/job/497412496/log.txt

**Comment by mwjames** [comment]
I will note that the `ResourcesAccessibilityTest` hasn't been modified since 2015 and it was one of the stable tests that passed on MW 1.19, MW 1.23, MW 1.27, and MW 1.32 (and not once broke!).

**Comment by mwjames** [comment]
Somehow the error went away and I'm speculating that https://github.com/wikimedia/mediawiki/commit/285a50ca0c62c6b52159088f724c01d870cc94ec is the reason for it. Closing this for now.

**Comment by mwjames** [comment]
If for any reason the issue appears again, the following change should avoid `ResourceLoaderModule::saveFileDependencies`.

```
-			$styles = $resourceLoaderModule->getStyles( $context );
+
+			// #3731
+			// `ResourceLoaderModule::saveFileDependencies` broke with " failed to update DB ..." since
+			// `ResourceLoaderModule::getStyles` tries to save the dependencies
+			// $styles = $resourceLoaderModule->getStyles( $context );
+
+			// Copied from `ResourceLoaderModule::getStyles` without relying on
+			// `ResourceLoaderModule::saveFileDependencies` to get the styles
+			$styles = $resourceLoaderModule->readStyleFiles(
+				$resourceLoaderModule->getStyleFiles( $context ),
+				$resourceLoaderModule->getFlip( $context ),
+				$context
+			);
 
```
