### ISSUE TITLE
[ES] Index name must always be lower case

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#3938]
### Setup and configuration

- MediaWiki | 1.32.1 (3efaceb)17:46, 11. Apr. 2019
- PHP | 7.2.15-0ubuntu0.18.04.2 (apache2handler)
- MariaDB | 10.1.38-MariaDB-0ubuntu0.18.04.1
- Elasticsearch | 6.5.4
- Semantic MediaWiki | 3.1.0-alpha (a795e69) 17:50, 15. Apr. 2019

### Issue
```
...[f2cad0e0108bc88f55da3398] [no req]  
Elasticsearch\Common\Exceptions\BadRequest400 Exception from line 615 of
/../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:
{"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [smw-data-DB9907120150926-02100_-v1], must be
lowercase","index_uuid":"_na_","index":"smw-data-DB9907120150926-02100_-v1"}],"type":"invalid_index_name_exception","reason":"Invalid index name [smw-data-DB9907120150926-02100_-v1], must be
lowercase","index_uuid":"_na_","index":"smw-data-DB9907120150926-02100_-v1"},"status":400}
```

### Stack trace
Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and/or outputs:
```
#0 /../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(279): Elasticsearch\Connections\Connection->process4xxError(array, array, array)
#1 /../w/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(array)
#2 /../w/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Closure, NULL, NULL)
#3 /../w/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Closure, NULL, NULL)
#4 /../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(299): GuzzleHttp\Ring\Core::proxy(GuzzleHttp\Ring\Future\CompletedFutureArray, Closure)
#5 /../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(177): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(array, Elasticsearch\Connections\Connection, Elasticsearch\Transport, array)
#6 /../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(110): Elasticsearch\Connections\Connection->performRequest(string, string, array, string, array, Elasticsearch\Transport)
#7 /../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/AbstractNamespace.php(72): Elasticsearch\Transport->performRequest(string, string, array, string,
array)
#8 /../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(718): Elasticsearch\Namespaces\AbstractNamespace->performRequest(Elasticsearch\Endpoints\Indices\Create)
#9 /../w/extensions/SemanticMediaWiki/src/Elastic/Connection/Client.php(360): Elasticsearch\Namespaces\IndicesNamespace->create(array)
#10 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rebuilder.php(408): SMW\Elastic\Connection\Client->createIndex(string)
#11 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rebuilder.php(199): SMW\Elastic\Indexer\Rebuilder->create_index(string)
#12 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(273): SMW\Elastic\Indexer\Rebuilder->createIndices()
#13 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(155): SMW\Maintenance\RebuildElasticIndex->rebuild()
#14 /../w/maintenance/doMaintenance.php(94): SMW\Maintenance\RebuildElasticIndex->execute()
#15 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(405): require_once(string)
#16 {main}
```

### Steps to reproduce
Have an wiki ID containing and upper case letter like e.g. "DB9907120150926-02100_" and run "rebuildElasticIndex.php".

**Comment by mwjames** [comment]
> {"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [smw-data-DB9907120150926-02100_-v1], must be lowercase","index_uuid":"

https://discuss.elastic.co/t/why-cant-an-index-start-with-an-uppercase-letter/72435/6

**Comment by kghbln** [comment]
@mwjames Thanks a ton for the change. "sandbox" is elastic again. :)
