### ISSUE TITLE
InvalidArgumentException from line 75 "... DispatchContext.php: title is unknown"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4083]
### Setup and configuration

- MediaWiki | 1.33.0-rc.0 (c733c85)19:29, 7. Jun. 2019
- PHP | 7.2.19-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.40-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.1.0-alpha (371c70a) 18:09, 6. Jun. 2019

### Issue
```
InvalidArgumentException from line 75 of /../w/vendor/onoi/event-dispatcher/src/DispatchContext.php: title is unknown
```

### Stack trace
```
#0 /../w/extensions/SemanticMediaWiki/src/Events/InvalidateEntityCacheEventListener.php(39): Onoi\EventDispatcher\DispatchContext->get(string)
#1 /../w/vendor/onoi/event-dispatcher/src/Dispatcher/GenericEventDispatcher.php(144): SMW\Events\InvalidateEntityCacheEventListener->execute(Onoi\EventDispatcher\DispatchContext)
#2 /../w/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(275): Onoi\EventDispatcher\Dispatcher\GenericEventDispatcher->dispatch(string, Onoi\EventDispatcher\DispatchContext)
#3 /../w/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(171): SMW\SQLStore\PropertyTableIdReferenceDisposer->triggerCleanUpEvents(SMW\DIWikiPage)
#4 /../w/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(150): SMW\SQLStore\PropertyTableIdReferenceDisposer->cleanUpReferencesById(string)
#5 /../w/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(132): SMW\SQLStore\PropertyTableIdReferenceDisposer->cleanUpTableEntriesById(string)
#6 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/EntityIdDisposerJob.php(117): SMW\SQLStore\PropertyTableIdReferenceDisposer->cleanUpTableEntriesByRow(stdClass)
#7 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder/OutdatedDisposer.php(94): SMW\MediaWiki\Jobs\EntityIdDisposerJob->dispose(stdClass)
#8 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder/OutdatedDisposer.php(54): SMW\Maintenance\DataRebuilder\OutdatedDisposer->disposeOutdatedEntities(SMW\Iterators\ResultIterator, integer)
#9 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(510): SMW\Maintenance\DataRebuilder\OutdatedDisposer->run()
#10 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(279): SMW\Maintenance\DataRebuilder->dispose_outdated()
#11 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(197): SMW\Maintenance\DataRebuilder->rebuild_all()
#12 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(190): SMW\Maintenance\DataRebuilder->rebuild()
#13 /../w/maintenance/doMaintenance.php(96): SMW\Maintenance\RebuildData->execute()
#14 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(248): require_once(string)
#15 {main}
```

### Steps to reproduce
```
php extensions/SemanticMediaWiki/maintenance/rebuildData.php --with-maintenance-log
```

**Comment by kghbln** [comment]
@mwjames The issue is not fully mitigated. The general error is the same but the stack trace is a bit different now:

```
#0 /../w/extensions/SemanticMediaWiki/src/Elastic/ElasticFactory.php(528): Onoi\EventDispatcher\DispatchContext->get(string)
#1 [internal function]: SMW\Elastic\ElasticFactory->onInvalidateEntityCache(Onoi\EventDispatcher\DispatchContext)
#2 /../w/vendor/onoi/event-dispatcher/src/Listener/GenericCallbackEventListener.php(62): call_user_func_array(array, array)
#3 /../w/vendor/onoi/event-dispatcher/src/Dispatcher/GenericEventDispatcher.php(144): Onoi\EventDispatcher\Listener\GenericCallbackEventListener->execute(Onoi\EventDispatcher\DispatchContext)
#4 /../w/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(275): Onoi\EventDispatcher\Dispatcher\GenericEventDispatcher->dispatch(string, Onoi\EventDispatcher\DispatchContext)
#5 /../w/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(171): SMW\SQLStore\PropertyTableIdReferenceDisposer->triggerCleanUpEvents(SMW\DIWikiPage)
#6 /../w/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(150): SMW\SQLStore\PropertyTableIdReferenceDisposer->cleanUpReferencesById(string)
#7 /../w/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php(132): SMW\SQLStore\PropertyTableIdReferenceDisposer->cleanUpTableEntriesById(string)
#8 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/EntityIdDisposerJob.php(117): SMW\SQLStore\PropertyTableIdReferenceDisposer->cleanUpTableEntriesByRow(stdClass)
#9 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder/OutdatedDisposer.php(94): SMW\MediaWiki\Jobs\EntityIdDisposerJob->dispose(stdClass)
#10 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder/OutdatedDisposer.php(54): SMW\Maintenance\DataRebuilder\OutdatedDisposer->disposeOutdatedEntities(SMW\Iterators\ResultIterator, integer)
#11 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(510): SMW\Maintenance\DataRebuilder\OutdatedDisposer->run()
#12 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(279): SMW\Maintenance\DataRebuilder->dispose_outdated()
#13 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(197): SMW\Maintenance\DataRebuilder->rebuild_all()
#14 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(190): SMW\Maintenance\DataRebuilder->rebuild()
#15 /../w/maintenance/doMaintenance.php(96): SMW\Maintenance\RebuildData->execute()
#16 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(248): require_once(string)
#17 {main}
```

**Comment by mwjames** [comment]
> @mwjames The issue is not fully mitigated. The general error is the same but
> the stack trace is a bit different now:
>
> ```
> #0 /../w/extensions/SemanticMediaWiki/src/Elastic/ElasticFactory.php(528):
> Onoi\EventDispatcher\DispatchContext->get(string)
> #1 [internal function]:
> SMW\Elastic\ElasticFactory->onInvalidateEntityCache(Onoi\EventDispatcher\DispatchContext)
> #2
> /../w/vendor/onoi/event-dispatcher/src/Listener/GenericCallbackEventListener.php(62):
> call_user_func_array(array, array)

Thanks for being observant and yes, I missed a spot.

**Comment by kghbln** [comment]
@mwjames Indeed, this was it. The script is running smooth now. :)
