### ISSUE TITLE
MW 1.32+, HTMLInfoField.php: 'default' must be a FieldLayout or subclass when using 'rawrow'

### ISSUE THREAD

**Issue by reedy** [SemanticMediaWiki/SemanticMediaWiki#4091]
From upstream tasks https://phabricator.wikimedia.org/T205956 and https://phabricator.wikimedia.org/T225683

Affects MW >= 1.32, SMW >= 2.0-RC1

It's not an exception anymore, downgraded to a warning during the development cycle of 1.32

```
/wiki/Special:Preferences   Exception from line 86 of /srv/mediawiki/tags/2018-10-02_06:46:44/includes/htmlform/fields/HTMLInfoField.php: 'default' must be a FieldLayout or subclass when using 'rawrow'
#0 /srv/mediawiki/tags/2018-10-02_06:46:44/includes/htmlform/HTMLForm.php(1672): HTMLInfoField->getOOUI(string)
#1 /srv/mediawiki/tags/2018-10-02_06:46:44/includes/htmlform/HTMLForm.php(1692): HTMLForm->displaySection(array, string, string, boolean)
#2 /srv/mediawiki/tags/2018-10-02_06:46:44/includes/specials/forms/PreferencesFormOOUI.php(217): HTMLForm->displaySection(array, string, string)
#3 /srv/mediawiki/tags/2018-10-02_06:46:44/includes/htmlform/HTMLForm.php(1044): PreferencesFormOOUI->getBody()
#4 /srv/mediawiki/tags/2018-10-02_06:46:44/includes/htmlform/HTMLForm.php(1023): HTMLForm->getHTML(boolean)
#5 /srv/mediawiki/tags/2018-10-02_06:46:44/includes/htmlform/HTMLForm.php(577): HTMLForm->displayForm(boolean)
#6 /srv/mediawiki/tags/2018-10-02_06:46:44/includes/specials/SpecialPreferences.php(159): HTMLForm->show()
#7 /srv/mediawiki/tags/2018-10-02_06:46:44/includes/specialpage/SpecialPage.php(569): SpecialPreferences->execute(NULL)
#8 /srv/mediawiki/tags/2018-10-02_06:46:44/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#9 /srv/mediawiki/tags/2018-10-02_06:46:44/includes/MediaWiki.php(288): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#10 /srv/mediawiki/tags/2018-10-02_06:46:44/includes/MediaWiki.php(868): MediaWiki->performRequest()
#11 /srv/mediawiki/tags/2018-10-02_06:46:44/includes/MediaWiki.php(525): MediaWiki->main()
#12 /srv/mediawiki/tags/2018-10-02_06:46:44/index.php(42): MediaWiki->run()
#13 {main}
```

```
Deprecated: Use of 'default' parameter as a string when using 'rawrow' (must be a FieldLayout or subclass) was deprecated in MediaWiki 1.32. [Called from HTMLForm::displaySection in /home/ccmdb/ccmdb.kuality.ca/includes/htmlform/HTMLForm.php at line 1672] in /home/ccmdb/ccmdb.kuality.ca/includes/debug/MWDebug.php on line 309
```

**Comment by reedy** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/cd897b1b37c04c267afb45c9797528c2f982f686/src/MediaWiki/Hooks/GetPreferences.php#L45-L55

**Comment by kghbln** [comment]
Thanks a lot for reporting!

**Comment by mwjames** [comment]
> From upstream tasks https://phabricator.wikimedia.org/T205956 and https://phabricator.wikimedia.org/T225683

So what is the solution here, just remove `'rawrow' => 1,` and that's it? Is the previous behaviour retained? or does the output needs additional formatting now?

**Comment by reedy** [comment]
https://gerrit.wikimedia.org/r/#/c/mediawiki/extensions/BetaFeatures/+/457504/1/includes/BetaFeaturesHooks.php is an example of fixing it in other repos
