### ISSUE TITLE
ErrorException from line 177 of "NavigationLinksWidget.php": PHP Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4205]
### Setup and configuration

- MediaWiki | 1.33.0 (62dc614)08:13, 24. Jul. 2019
- PHP | 7.2.19-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.40-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.1.0-alpha (431b5aa) 21:14, 4. Aug. 2019

### Issue
```
2019-08-05 20:48:37 sulcorebutia DB9907120150926-02100_: [2faa5d0e10e3f5ffb59195b5] /w/index.php?title=Sp%C3%A9cial:Requ%C3%AAter&x=-5B-5B%7E%7Erheumatological-5D-5D%2F-3FHas-20abstract-23-2Dhl&format=broadtable&link=all&headers=show&searchlabel=...+further+results&class=sortable+wikitable+smwtable&offset=&limit=50&mainlabel=   ErrorException from line 177 of /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/NavigationLinksWidget.php: PHP Warning: A non-numeric value encountered
```

### Stack trace
```
#0 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/NavigationLinksWidget.php(177): MWExceptionHandler::handleError(integer, string, string, integer, array)
#1 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/HtmlForm.php(179): SMW\MediaWiki\Specials\Ask\NavigationLinksWidget::navigationLinks(Title, SMW\MediaWiki\Specials\Ask\UrlArgs, integer, boolean)
#2 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/HtmlForm.php(143): SMW\MediaWiki\Specials\Ask\HtmlForm->buildHTML(SMW\MediaWiki\Specials\Ask\UrlArgs, SMW\Query\QueryResult, array)
#3 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(400): SMW\MediaWiki\Specials\Ask\HtmlForm->getForm(SMW\MediaWiki\Specials\Ask\UrlArgs, SMW\Query\QueryResult, array)
#4 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(169): SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#5 /../w/includes/specialpage/SpecialPage.php(569): SMW\MediaWiki\Specials\SpecialAsk->execute(NULL)
#6 /../w/includes/specialpage/SpecialPageFactory.php(558): SpecialPage->run(NULL)
#7 /../w/includes/MediaWiki.php(288): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#8 /../w/includes/MediaWiki.php(865): MediaWiki->performRequest()
#9 /../w/includes/MediaWiki.php(515): MediaWiki->main()
#10 /../w/index.php(42): MediaWiki->run()
#11 {main}
```
### Example
See [special "Ask"](https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Requ%C3%AAter&x=-5B-5B%7E%7Erheumatological-5D-5D%2F-3FHas-20abstract-23-2Dhl&format=broadtable&link=all&headers=show&searchlabel=...+further+results&class=sortable+wikitable+smwtable&offset=&limit=50&mainlabel=)

**Comment by mwjames** [comment]
> /w/index.php?title=Sp%C3%A9cial:Requ%C3%AAter&x=-5B-5B%7E%7Erheumatological-5D-5D%2F-3FHas-20abstract-23-2Dhl&format=broadtable&link=all&headers=show&searchlabel=...+further+results&class=sortable+wikitable+smwtable&offset=&limit=50&mainlabel=
>   ErrorException from line 177 of

The offset is empty and casts as a string type therefore any
arithmetic operation (e.g. $offset + 1) will fail with the error
observed. So, ensuring that the variable contains an integer will
prevent the error which requires that you change:

src/MediaWiki/Specials/Ask/ParametersProcessor.php:

```
@@ -143,15 +143,15 @@ class ParametersProcessor {
 			$parameters['order'] = 'asc';
 			$parameters['sort'] = '';
 		}

 		if ( !array_key_exists( 'offset', $parameters ) ) {
-			$parameters['offset'] = $request->getVal( 'offset', 0 );
+			$parameters['offset'] = $request->getInt( 'offset', 0 );
 		}

 		if ( !array_key_exists( 'limit', $parameters ) ) {
-			$parameters['limit'] = $request->getVal( 'limit', self::$defaultLimit );
+			$parameters['limit'] = $request->getInt( 'limit', self::$defaultLimit );
 		}
```
