### ISSUE TITLE
Call to private method SMWWikiPageValue::getTitle() from context 'SMW\Query\ResultPrinters\AggregatablePrinter'

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4288]
### Setup and configuration

- MediaWiki | 1.31.3 (fe531ce)18:57, 21 August 2019
- PHP | 7.2.19-0ubuntu0.18.04.2 (apache2handler)
- MariaDB | 10.1.41-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.1.0-rc.1 (5623547) 10:16, 11 April 2019

### Issue
```
[fa1608066ee887d61d59bfd4] [no req]   Error from line 173 of /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/AggregatablePrinter.php: Call to private method SMWWikiPageValue::getTitle() from context 'SMW\Query\ResultPrinters\AggregatablePrinter'
```

Also happens for individual result formats by other extensions, e.g. 
```
[41d71c358fe19598aa89d5e9] [no req]   Error from line 229 of /../w/extensions/SemanticResultFormats/formats/gallery/Gallery.php: Call to private method SMWWikiPageValue::getTitle() from context 'SRF\Gallery'
```

### Stack trace
```
#0 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/AggregatablePrinter.php(147): SMW\Query\ResultPrinters\AggregatablePrinter->getDistributionResults(SMW\Query\QueryResult, integer)
#1 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/AggregatablePrinter.php(99): SMW\Query\ResultPrinters\AggregatablePrinter->getResults(SMW\Query\QueryResult, integer)
#2 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(346): SMW\Query\ResultPrinters\AggregatablePrinter->getResultText(SMW\Query\QueryResult, integer)
#3 /../w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(311): SMW\Query\ResultPrinters\ResultPrinter->buildResult(SMW\Query\QueryResult)
#4 /../w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(348): SMW\Query\ResultPrinters\ResultPrinter->getResult(SMW\Query\QueryResult, array, integer)
#5 /../w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(364): SMWQueryProcessor::getResultFromQuery(SMWQuery, array, integer, integer)
#6 /../w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(197): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array, array)
#7 /../w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse(array)
#8 /../w/includes/parser/Parser.php(3426): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string, string, string, string, string)
#9 /../w/includes/parser/Parser.php(3127): Parser->callParserFunction(PPFrame_DOM, string, array)
#10 /../w/includes/parser/Preprocessor_DOM.php(1277): Parser->braceSubstitution(array, PPFrame_DOM)
#11 /../w/includes/parser/Parser.php(2942): PPFrame_DOM->expand(DOMElement, integer)
#12 /../w/includes/parser/Parser.php(1293): Parser->replaceVariables(string)
#13 /../w/includes/parser/Parser.php(443): Parser->internalParse(string)
#14 /../w/includes/content/WikitextContent.php(323): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#15 /../w/includes/content/AbstractContent.php(516): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#16 /../w/extensions/SemanticMediaWiki/includes/ContentParser.php(186): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#17 /../w/extensions/SemanticMediaWiki/includes/ContentParser.php(145): SMW\ContentParser->fetchFromContent()
#18 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(197): SMW\ContentParser->parse()
#19 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(137): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#20 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#21 /../w/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(237): SMW\MediaWiki\Jobs\UpdateJob->run()
#22 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(423): SMW\SQLStore\Rebuilder\Rebuilder->rebuild(integer)
#23 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(349): SMW\Maintenance\DataRebuilder->do_update(integer)
#24 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(200): SMW\Maintenance\DataRebuilder->rebuild_all()
#25 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(202): SMW\Maintenance\DataRebuilder->rebuild()
#26 /../w/maintenance/doMaintenance.php(94): SMW\Maintenance\RebuildData->execute()
#27 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(261): require_once(string)
#28 {main}
```

## Steps to reproduce
Happens on [s-mw.o](https://www.semantic-mediawiki.org/w/index.php?title=Semantic_MediaWiki&curid=95&diff=71351&oldid=70751) after updating to SMW 3.1.0-rc.1 when trying to rebuild data.

**Comment by JeroenDeDauw** [comment]
Caused by https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/35780f2fba48683796aea5167d22c1fd232be706 which changes this method from public to rpivate.

**Comment by kghbln** [comment]
> Caused by 35780f2 which changes this method from public to private.

From reading https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3995 I get the impression that the result formats need an invitation to the private party since it is no longer public. The way how to get a ticket is described, too. The question is, which result formats need to be adapted, gallery is the one I know. Not sure which result format is involved with the stack trace here.

**Comment by kghbln** [comment]
Ah, did not see your pull. Well if it is that easy...
