### ISSUE TITLE
Lock wait timeout on a temporary table

### ISSUE THREAD

**Issue by alex-mashin** [SemanticMediaWiki/SemanticMediaWiki#4527]
SMW 3.1.3, MW 1.34.0, PHP 7.4.2, MariaDB 10.3.22.

On saving some heavy pages the following error occurs:
```
Wikimedia\Rdbms\DBQueryError from line 1603 of /var/www/wiki/w/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading?
Query: INSERT IGNORE INTO smw_res (id) SELECT s_id FROM `smw_fpt_subc`, smw_new WHERE o_id=id
Function: SMW\SQLStore\QueryEngine\HierarchyTempTableBuilder::buildTempTable
Error: 1205 Lock wait timeout exceeded; try restarting transaction (DB server skipped)

Backtrace:

#0 /var/www/wiki/w/includes/libs/rdbms/database/Database.php(1574): Wikimedia\Rdbms\Database->getQueryExceptionAndLog()
#1 /var/www/wiki/w/includes/libs/rdbms/database/Database.php(1152): Wikimedia\Rdbms\Database->reportQueryError()
#2 /var/www/wiki/w/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->query()
#3 /var/www/wiki/w/includes/libs/rdbms/database/DBConnRef.php(292): Wikimedia\Rdbms\DBConnRef->__call()
#4 /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(364): Wikimedia\Rdbms\DBConnRef->query()
#5 /var/www/wiki/w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/HierarchyTempTableBuilder.php(165): SMW\MediaWiki\Connection\Database->query()
#6 /var/www/wiki/w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/HierarchyTempTableBuilder.php(129): SMW\SQLStore\QueryEngine\HierarchyTempTableBuilder->buildTempTable()
#7 /var/www/wiki/w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QuerySegmentListProcessor.php(354): SMW\SQLStore\QueryEngine\HierarchyTempTableBuilder->fillTempTable()
#8 /var/www/wiki/w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QuerySegmentListProcessor.php(131): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->hierarchy()
#9 /var/www/wiki/w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QuerySegmentListProcessor.php(145): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->segment()
#10 /var/www/wiki/w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QuerySegmentListProcessor.php(121): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->table()
#11 /var/www/wiki/w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QuerySegmentListProcessor.php(145): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->segment()
#12 /var/www/wiki/w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QuerySegmentListProcessor.php(121): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->table()
#13 /var/www/wiki/w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QuerySegmentListProcessor.php(114): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->segment()
#14 /var/www/wiki/w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(198): SMW\SQLStore\QueryEngine\QuerySegmentListProcessor->process()
#15 /var/www/wiki/w/extensions/SemanticMediaWiki/src/Query/Cache/ResultCache.php(250): SMW\SQLStore\QueryEngine\QueryEngine->getQueryResult()
#16 /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1269): SMW\Query\Cache\ResultCache->getQueryResult()
#17 /var/www/wiki/w/includes/Hooks.php(174): SMW\MediaWiki\Hooks->onBeforeQueryResultLookupComplete()
#18 /var/www/wiki/w/includes/Hooks.php(202): Hooks::callHook()
#19 /var/www/wiki/w/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(361): Hooks::run()
#20 /var/www/wiki/w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(338): SMW\SQLStore\SQLStore->getQueryResult()
#21 /var/www/wiki/w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(361): SMWQueryProcessor::getResultFromQuery()
#22 /var/www/wiki/w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(196): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters()
#23 /var/www/wiki/w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse()
#24 /var/www/wiki/w/includes/parser/Parser.php(3816): SMW\ParserFunctionFactory->SMW\{closure}()
#25 /var/www/wiki/w/includes/parser/Parser.php(3519): Parser->callParserFunction()
#26 /var/www/wiki/w/includes/parser/PPFrame_Hash.php(254): Parser->braceSubstitution()
#27 /var/www/wiki/w/includes/parser/Parser.php(3330): PPFrame_Hash->expand()
#28 /var/www/wiki/w/includes/parser/Parser.php(1489): Parser->replaceVariables()
#29 /var/www/wiki/w/includes/parser/Parser.php(593): Parser->internalParse()
#30 /var/www/wiki/w/includes/content/WikitextContent.php(368): Parser->parse()
#31 /var/www/wiki/w/includes/content/AbstractContent.php(555): WikitextContent->fillParserOutput()
#32 /var/www/wiki/w/includes/Revision/RenderedRevision.php(264): AbstractContent->getParserOutput()
#33 /var/www/wiki/w/includes/Revision/RenderedRevision.php(236): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached()
#34 /var/www/wiki/w/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput()
#35 /var/www/wiki/w/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput()
#36 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}()
#37 /var/www/wiki/w/includes/Revision/RenderedRevision.php(198): call_user_func()
#38 /var/www/wiki/w/includes/poolcounter/PoolWorkArticleView.php(196): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#39 /var/www/wiki/w/includes/poolcounter/PoolCounterWork.php(125): PoolWorkArticleView->doWork()
#40 /var/www/wiki/w/includes/page/Article.php(791): PoolCounterWork->execute()
#41 /var/www/wiki/w/includes/actions/ViewAction.php(63): Article->view()
#42 /var/www/wiki/w/includes/MediaWiki.php(511): ViewAction->show()
#43 /var/www/wiki/w/includes/MediaWiki.php(302): MediaWiki->performAction()
#44 /var/www/wiki/w/includes/MediaWiki.php(900): MediaWiki->performRequest()
#45 /var/www/wiki/w/includes/MediaWiki.php(527): MediaWiki->main()
#46 /var/www/wiki/w/index.php(44): MediaWiki->run()
#47 {main}
```
What if you create a temorary table with a unique name for each query?

**Comment by akuckartz** [comment]
Can you try SMW 3.1.4 ?

**Comment by mwjames** [comment]
> Can you try SMW 3.1.4 ?

That wouldn't help!

> What if you create a temorary table with a unique name for each query?

I don't know but it would certainly not help the query performance. Not knowing where the transaction contention comes from is a factor that cannot be neglected.

> Error: 1205 Lock wait timeout exceeded; try restarting transaction

While this occurs in connection with a `INSERT IGNORE INTO smw_res `, the issue is symptomatic for MediaWiki in general [0]. To be honest I don't have a good answer because there is no easy way to create such "Lock wait timeout" deterministically with an example that would allow to test several assumptions and possible counter actions.

As for `HierarchyTempTableBuilder::buildTempTable` I have a different approach [1] in mind but I currently don't have time to bring that into shape for production use.

PS: A precautionary note to anyone attempting to mark this as a "bug", the person doing so will be expected to take responsibility in resolving this ticket and explain the necessary strategies why s(he) things proposed actions will resolve the issue.

[0] https://phabricator.wikimedia.org/search/query/89EA0_4164Ze/#R
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4319#issuecomment-542713250

**Comment by kghbln** [comment]
> the issue is symptomatic for MediaWiki in general [0].

I believe to have had this issue once too but not in connection with SMW.

Probably some database tweaking as suggested in the ["MySQL Lock Wait Timeout Exceeded Error in InnoDB Tables – How to fix it" post](https://www.ryadel.com/en/mysql-lock-wait-timeout-exceeded-error-how-to-fix-it/) may be of help.

**Comment by alex-mashin** [comment]
> Probably some database tweaking as suggested in the ["MySQL Lock Wait Timeout Exceeded Error in InnoDB Tables – How to fix it" post](https://www.ryadel.com/en/mysql-lock-wait-timeout-exceeded-error-how-to-fix-it/) may be of help.
I have `max_allowed_packet = 512M` for the sake of mysqldump.

**Comment by alex-mashin** [comment]
Is there a way to explain `SELECT s_id FROM `smw_fpt_subc`, smw_new WHERE o_id=id` query? It seems to involve a temporary table: `smw_new`.

**Comment by mwjames** [comment]
> Is there a way to explain SELECT s_id FROM smw_fpt_subc, smw_new WHERE o_id=id query? It seems to involve a temporary table: smw_new.

You have to use the complete query (which is `INSERT IGNORE INTO smw_res (id) SELECT s_id FROM `smw_fpt_subc`, smw_new WHERE o_id=id`) otherwise you create a false narrative. The query as outlined copies those ids assigned to a  `*subc` (which is the `Subcategory of` representation) to the temp table to build the inference schema for a query that involves a category with subcategories. It copies them into a temp table before the "real" query is run otherwise you wouldn't be able to find matches in the subcategory graph.

**Comment by akuckartz** [comment]
> PS: A precautionary note to anyone attempting to mark this as a "bug", ...

Maybe a tag "Bug caused by MediaWiki" could help?

**Comment by mwjames** [comment]
> Maybe a tag "Bug caused by MediaWiki" could help?

The point here is that when marking something as a bug then the person that did so has come to that conclusion based on some observable reasoning and takes responsibility based on his/her reasoning to give an appropriate feedback. Lately, I have seen issues marked as a bug without consultation or reasoning which most likely transpires to  the audience a false impression of actionable intention based on some thought of misbehaviour in SMW and its software.

In general, tagging an issue as a bug isn't an issue, tagging an issue without following up on the issue or leaving others to investigate hereby forcing them to put an effort into identifying the cause is. As for this ticket, I gave my response which let me to the conclusion that is not a bug in the strict sense of #3629. While the issue is certainly not optimal and should be resolved, I currently don't have the means to provide actions or solutions for the described situation and I won't treat it as a bug which would otherwise signal a more responsive action plan in attempting to remedy the issue.

PS: Personally, I have only a limit contingent of available volunteer time and I want give people that have solvable problems a chance to be listen to while my main purpose is to develop software based on personal needs. People can look for professional services if an issue is really buggy them but I don't provide that service for a reason and most importantly I'm not a janitor for all the WMF infused c... I have seen of late.
