### ISSUE TITLE
`InvalidArgumentException` when using `{{#info}}` with integer parameter

### ISSUE THREAD

**Issue by osnard** [SemanticMediaWiki/SemanticMediaWiki#4532]
### Setup and configuration

- SMW version: 3.1 (but also on 3.2.0-alpha)
- MW version: 1.31.6 (LTS)
- PHP version: 7.2.24
- DB system version: 10.2.12-MariaDB-10.2.12+maria~jessie

VisualeEditor as of branch `REL1_31` is enabled.

### Issue
When using a pure integer value as a parameter to the `{{#info}}` parser function a `InvalidArgumentException` is thrown.

### Stack trace
```
Exception caught: $key must be a string or an array

InvalidArgumentException at /.../includes/Message.php(260)
#0 /.../includes/GlobalFunctions.php(1356): Message->__construct(integer)
#1 [internal function]: wfMessage(integer)
#2 /.../extensions/SemanticMediaWiki/src/Setup.php(246): call_user_func_array(string, array)
#3 [internal function]: SMW\\Setup->SMW\\{closure}(array, LanguageEn)
#4 /.../extensions/SemanticMediaWiki/src/Message.php(228): call_user_func_array(Closure, array)
#5 /.../extensions/SemanticMediaWiki/src/Message.php(187): SMW\\Message::get(array, integer, integer)
#6 /.../extensions/SemanticMediaWiki/src/ProcessingErrorMsgHandler.php(85): SMW\\Message::decode(integer, integer, integer)
#7 /.../extensions/SemanticMediaWiki/src/GlobalFunctions.php(115): SMW\\ProcessingErrorMsgHandler::normalizeAndDecodeMessages(array)
#8 /.../extensions/SemanticMediaWiki/src/ParserFunctions/InfoParserFunction.php(53): smwfEncodeMessages(array, string, string, boolean)
#9 /.../vendor/mediawiki/parser-hooks/src/FunctionRunner.php(48): SMW\\ParserFunctions\\InfoParserFunction->handle(Parser, ParamProcessor\\ProcessingResult)
#10 /.../vendor/mediawiki/parser-hooks/src/HookRegistrant.php(45): ParserHooks\\FunctionRunner->run(Parser, array, PPFrame_DOM)
#11 /.../includes/parser/Parser.php(3426): ParserHooks\\HookRegistrant->ParserHooks\\{closure}(Parser, PPFrame_DOM, array)
#12 /.../includes/parser/Parser.php(3127): Parser->callParserFunction(PPFrame_DOM, string, array)
#13 /.../includes/parser/Preprocessor_DOM.php(1277): Parser->braceSubstitution(array, PPFrame_DOM)
#14 /.../includes/parser/Parser.php(2942): PPFrame_DOM->expand(DOMElement, integer)
#15 /.../includes/parser/Parser.php(1293): Parser->replaceVariables(string)
#16 /.../includes/parser/Parser.php(443): Parser->internalParse(string)
#17 /.../includes/content/WikitextContent.php(323): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#18 /.../includes/content/AbstractContent.php(516): WikitextContent->fillParserOutput(Title, NULL, ParserOptions, boolean, ParserOutput)
#19 /.../includes/page/WikiPage.php(2129): AbstractContent->getParserOutput(Title, NULL, ParserOptions)
#20 /.../includes/page/WikiPage.php(1655): WikiPage->prepareContentForEdit(WikitextContent, NULL, User, string, boolean)
#21 /.../includes/EditPage.php(2214): WikiPage->doEditContent(WikitextContent, string, integer, boolean, User, string, array, integer)
#22 /.../includes/EditPage.php(1506): EditPage->internalAttemptSave(array, boolean)
#23 /.../includes/api/ApiEditPage.php(406): EditPage->attemptSave(array)
#24 /.../includes/api/ApiMain.php(1579): ApiEditPage->execute()
#25 /.../includes/api/ApiMain.php(504): ApiMain->executeAction()
#26 /.../extensions/VisualEditor/includes/ApiVisualEditorEdit.php(69): ApiMain->execute()
#27 /.../extensions/VisualEditor/includes/ApiVisualEditorEdit.php(382): ApiVisualEditorEdit->saveWikitext(Title, string, array)
#28 /.../includes/api/ApiMain.php(1579): ApiVisualEditorEdit->execute()
#29 /.../includes/api/ApiMain.php(535): ApiMain->executeAction()
#30 /.../includes/api/ApiMain.php(506): ApiMain->executeActionWithErrorHandling()
#31 /.../api.php(94): ApiMain->execute()
#32 {main}
```

### Steps to reproduce
1. Create a page with the content `{{#info:7}}`
2. On save, the exception will occur

**Comment by kghbln** [comment]
Thanks for reporting and providing a fix including extended testing.
