### ISSUE TITLE
BadHttpEndpointResponseException  Endpoint: not specified

### ISSUE THREAD

**Issue by plegault3397** [SemanticMediaWiki/SemanticMediaWiki#4574]
### New Setup and configuration
- SMW version: 3.1.4
- MW version: 1.31.6
- PHP version:  7.2.24 (apache2handler)
- DB system MySQL 5.6.41-log

### Old Setup and configuration
- SMW version: 2.5.8
- MW version: 1.31.1
- PHP version:  7.1.30 (apache2handler)
- DB system MySQL 5.6.41-log

### Issue
I'm trying to upgrade Semantic Mediawiki and unable to connect to the endpoint, I looked through my configuration and thought I followed the instructions.

I was trying with MW 1.40.0 and was not getting anywhere so went back to 1.31.6 to try the upgrade smw. every time I try to run rebuildData I get this error. We are using virtuoso Version: 07.20.3230

```
Rebuilding property pages ...
   ... selecting 289 pages ...
   ... (1/289 0%)        Property:Has_Version
PHP Warning:  preg_match_all(): Compilation failed: recursive call could loop indefinitely at offset 20 in /app/mediawiki/extensions/SemanticMediaWiki/src/Parser/LinksEncoder.php on line 173

Warning: preg_match_all(): Compilation failed: recursive call could loop indefinitely at offset 20 in /app/mediawiki/extensions/SemanticMediaWiki/src/Parser/LinksEncoder.php on line 173
PHP Warning:  Invalid argument supplied for foreach() in /app/mediawiki/extensions/SemanticMediaWiki/src/Parser/LinksEncoder.php on line 182

Warning: Invalid argument supplied for foreach() in /app/mediawiki/extensions/SemanticMediaWiki/src/Parser/LinksEncoder.php on line 182
[4677ba5b2a15e6409e10b9f1] [no req]   SMW\SPARQLStore\Exception\BadHttpEndpointResponseException from line 429 of /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/RepositoryConnectors/GenericRepositoryConnector.php: A SPARQL query error has occurred
Query: PREFIX wiki: <http://server.com/index.php/Special:URIResolver/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX swivt: <http://semantic-mediawiki.org/swivt/1.0#>
PREFIX property: <http://server.com/index.php/Special:URIResolver/Property-3A>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT * WHERE {
owl:DatatypeProperty swivt:wikiPageSortKey ?s  OPTIONAL { owl:DatatypeProperty swivt:redirectsTo ?r }
}
LIMIT 1
Error: Required service has not been defined
Endpoint: not specified
HTTP response code: <not given>
```

### Backtrace:
```
#0 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/RepositoryConnectors/GenericRepositoryConnector.php(173): SMW\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector->doQuery(string)
#1 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/RepositoryRedirectLookup.php(124): SMW\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector->select(string, string, array, array)
#2 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/RepositoryRedirectLookup.php(99): SMW\SPARQLStore\RepositoryRedirectLookup->lookupResourceUriTargetFromDatabase(SMW\Exporter\Element\ExpNsResource)
#3 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/RepositoryRedirectLookup.php(78): SMW\SPARQLStore\RepositoryRedirectLookup->doLookupResourceUriTargetFor(SMW\Exporter\Element\ExpNsResource)
#4 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/TurtleTriplesBuilder.php(266): SMW\SPARQLStore\RepositoryRedirectLookup->findRedirectTargetResource(SMW\Exporter\Element\ExpNsResource, boolean)
#5 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/TurtleTriplesBuilder.php(235): SMW\SPARQLStore\TurtleTriplesBuilder->expandUpdateExpResource(SMW\Exporter\Element\ExpNsResource, array)
#6 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/TurtleTriplesBuilder.php(325): SMW\SPARQLStore\TurtleTriplesBuilder->expandUpdateExpElement(SMW\Exporter\Element\ExpNsResource, array)
#7 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/TurtleTriplesBuilder.php(210): SMW\SPARQLStore\TurtleTriplesBuilder->expandUpdateExpData(SMWExpData, array, boolean)
#8 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/TurtleTriplesBuilder.php(168): SMW\SPARQLStore\TurtleTriplesBuilder->prepareUpdateExpData(SMW\SemanticData)
#9 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/TurtleTriplesBuilder.php(97): SMW\SPARQLStore\TurtleTriplesBuilder->doSerialize(SMW\SemanticData)
#10 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/SPARQLStore.php(206): SMW\SPARQLStore\TurtleTriplesBuilder->doBuildTriplesFrom(SMW\SemanticData)
#11 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/SPARQLStore.php(187): SMW\SPARQLStore\SPARQLStore->doSparqlFlatDataUpdate(SMW\SemanticData, SMW\SPARQLStore\TurtleTriplesBuilder)
#12 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/SPARQLStore.php(230): SMW\SPARQLStore\SPARQLStore->doSparqlDataUpdate(SMW\SemanticData)
#13 /app/mediawiki/extensions/SemanticMediaWiki/src/Store.php(238): SMW\SPARQLStore\SPARQLStore->doDataUpdate(SMW\SemanticData)
#14 /app/mediawiki/extensions/SemanticMediaWiki/src/DataUpdater.php(403): SMW\Store->updateData(SMW\SemanticData)
#15 /app/mediawiki/extensions/SemanticMediaWiki/src/DataUpdater.php(289): SMW\DataUpdater->updateData()
#16 /app/mediawiki/extensions/SemanticMediaWiki/src/DataUpdater.php(193): SMW\DataUpdater->runUpdate()
#17 /app/mediawiki/extensions/SemanticMediaWiki/src/ParserData.php(453): SMW\DataUpdater->doUpdate()
#18 /app/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(296): SMW\ParserData->updateStore()
#19 /app/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(216): SMW\MediaWiki\Jobs\UpdateJob->updateStore(SMW\ParserData)
#20 /app/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(137): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#21 /app/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#22 /app/mediawiki/extensions/SemanticMediaWiki/src/Maintenance/DistinctEntityDataRebuilder.php(179): SMW\MediaWiki\Jobs\UpdateJob->run()
#23 /app/mediawiki/extensions/SemanticMediaWiki/src/Maintenance/DistinctEntityDataRebuilder.php(160): SMW\Maintenance\DistinctEntityDataRebuilder->doUpdate(SMW\MediaWiki\JobFactory, Title)
#24 /app/mediawiki/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(239): SMW\Maintenance\DistinctEntityDataRebuilder->doRebuild()
#25 /app/mediawiki/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(293): SMW\Maintenance\DataRebuilder->rebuild_selection()
#26 /app/mediawiki/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(200): SMW\Maintenance\DataRebuilder->rebuild_all()
#27 /app/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php(202): SMW\Maintenance\DataRebuilder->rebuild()
#28 /app/mediawiki/maintenance/doMaintenance.php(94): SMW\Maintenance\RebuildData->execute()
#29 /app/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php(261): require_once(string)
#30 {main}
```

### Steps to reproduce
Running rebuildData does it every time

**Comment by mwjames** [comment]
>#0 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/RepositoryConnectors/GenericRepositoryConnector.php(173): SMW\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector->doQuery(string)
#1 /app/mediawiki/extensions/SemanticMediaWiki/src/SPARQLStore/RepositoryRedirectLookup.php(124): SMW\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector->select(string, string, array, array)

> BadHttpEndpointResponseException Endpoint: not specified 

The exception is pretty clear as it says "Endpoint: not specified" which is raised from "SMW\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector->doQuery" [0] which means if an endpoint is not maintained or empty thenthe exception is raised.

See, also [1].

> We are using virtuoso Version: 07.20.3230

Why don't you post the related settings for this?

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/cb928a5b475e0fe7943ddb7789eb3f6947ed8f0e/src/SPARQLStore/RepositoryConnectors/GenericRepositoryConnector.php#L428-L430
[1] https://www.semantic-mediawiki.org/wiki/Help:SPARQLStore/Exception

**Comment by mwjames** [comment]
If for some reason you use an outdated setting, you'll get a warning as in case of:

![image](https://user-images.githubusercontent.com/1245473/75087496-0abee180-5539-11ea-8805-8a9da5c74e2f.png)

**Comment by mwjames** [comment]
See [0] for details about the settings we use with Virtuoso in our CI environment.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/travis/update-configuration-settings.sh#L53-L61

**Comment by plegault3397** [comment]
These are my settings

 

  $smwgDefaultStore = 'SMWSparqlStore';

  $smwgSparqlRepositoryConnector = 'virtuoso';

  $smwgSparqlEndpoint["query"] = 'http://server.com/sparql';

  $smwgSparqlEndpoint["update"] = 'http:// server.com/sparql';

  $smwgSparqlEndpoint["data"] = '';

  $smwgSparqlDefaultGraph = 'http:// server.com/index.php/Special:URIResolver/';

  enableSemantics( ' server.com' );

**Comment by mwjames** [comment]
>   $smwgSparqlDefaultGraph = 'http:// server.com/index.php/Special:URIResolver/';

That seems like an ought default graph name.

Anyway, I'm pretty sure that somewhere in your `LocalSettings.php` you are overriding required settings which is why those are empty by the time the parameters reach SMW.

PS: Our tests would fail if something would be wrong with those mentioned settings especially since we are testing Virtuoso as well in our CI. Please make an attempt to follow the links and documentation (including that of the CI) which should enable you to find the correct settings.

**Comment by plegault3397** [comment]
I'm Starting from scratch on a windows server instead of RHEL for my upgrade.
There is nothing else I can find in the Local settings that references sparql endpoint. I do believe it is something in the Local settings or our version RHEL. If I figure it out I will note it here. 

Thanks for your support.
