### ISSUE TITLE
rebuildData -f returns an error 

### ISSUE THREAD

**Issue by plegault3397** [SemanticMediaWiki/SemanticMediaWiki#4666]
#### New versions
- SMW version: 3.1.5
- MW 1.31.6
- PHP version: 7.3.15 (cgi-fcgi)
- MySQL 5.6.41-log
- Version: 07.20.3230
- Virtuoso Version: 07.20.3230

#### Old versions
- SMW version: 2.5.8
- MediaWiki 1.31.1
- PHP 7.1.30 (apache2handler)
- MySQL 5.6.10
- Virtuoso Version: 07.20.3230

### Issue
Unable to rebuildData -f to fully rebuild the Virtuoso, I have to go to the endpoint and delete the graph and then restart the rebuildData.php -v. I don't see any issues. 

### Stack trace
Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and/or outputs:

```
PS D:\xampp\htdocs\mediawiki> php .\extensions\SemanticMediaWiki\maintenance\rebuildData.php -fv

Long-running scripts may cause memory leaks, if a deteriorating
rebuild process is detected (after many pages, typically more
than 10000), please abort with CTRL-C and resume this script
at the last processed ID using the parameter -s. Continue this
until all pages have been refreshed.

The progress displayed is an estimation and is self-adjusting
during the maintenance process.

Running for storage: SPARQLStore

Deleting all stored data completely and rebuilding it again later!

Semantic data in the wiki might be incomplete for some time while
this operation runs.

NOTE: It is usually necessary to run this script ONE MORE TIME
after this operation, given that some properties and types are not
yet stored with the first run.

Abort with control-c in the next five seconds ...  0

Deleting all data ...
   ... dropping tables ...[f7f2b5160851d268949759f0] [no req]   SMW\SPARQLStore\Exception\BadHttpEndpointResponseException from line 78 of D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\HttpResponseErrorMapper.php: A SPARQL query error has occurre
d
Query: PREFIX wiki: <https://server.com/id/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX swivt: <http://semantic-mediawiki.org/swivt/1.0#>
PREFIX property: <https://server.com/id/Property-3A>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
DELETE FROM <https://server.com/graph> { ?s ?p ?o } WHERE { ?s ?p ?o }
Error: Query refused
Endpoint: http://server.jnj.com/sparql
HTTP response code: 500

Backtrace:
#0 D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\HttpResponseErrorMapper.php(55): SMW\SPARQLStore\HttpResponseErrorMapper->createResponseToHttpError(integer, string, string)
#1 D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector.php(591): SMW\SPARQLStore\HttpResponseErrorMapper->mapErrorResponse(string, string)
#2 D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\RepositoryConnectors\VirtuosoRepositoryConnector.php(169): SMW\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector->mapHttpRequestError(string, string)
#3 D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\RepositoryConnectors\VirtuosoRepositoryConnector.php(66): SMW\SPARQLStore\RepositoryConnectors\VirtuosoRepositoryConnector->doUpdate(string)
#4 D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector.php(332): SMW\SPARQLStore\RepositoryConnectors\VirtuosoRepositoryConnector->delete(string, string)
#5 D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\SPARQLStore.php(377): SMW\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector->deleteAll()
#6 D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\src\Maintenance\DataRebuilder.php(494): SMW\SPARQLStore\SPARQLStore->drop(boolean)
#7 D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\src\Maintenance\DataRebuilder.php(193): SMW\Maintenance\DataRebuilder->performFullDelete()
#8 D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\maintenance\rebuildData.php(202): SMW\Maintenance\DataRebuilder->rebuild()
#9 D:\xampp\htdocs\mediawiki\maintenance\doMaintenance.php(94): SMW\Maintenance\RebuildData->execute()
#10 D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\maintenance\rebuildData.php(261): require_once(string)
#11 {main}
PS D:\xampp\htdocs\mediawiki>
=======================================

**Comment by kghbln** [comment]
This means that if you do not try to rewrite the script runs without issues?

**Comment by plegault3397** [comment]
Yes so if I delete the graph at the endpoint. rebuildData.php works fine without any errors.
I only get the error with rebuildData.php -f

**Comment by mwjames** [comment]
>   ... dropping tables ...[f7f2b5160851d268949759f0] [no req]   SMW\SPARQLStore\Exception\BadHttpEndpointResponseException from line 78 of D:\xampp\htdocs\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\HttpResponseErrorMapper.php: A SPARQL query error has occurre
d
Query: PREFIX wiki: <https://server.com/id/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX swivt: <http://semantic-mediawiki.org/swivt/1.0#>
PREFIX property: <https://server.com/id/Property-3A>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
DELETE FROM <https://server.com/graph> { ?s ?p ?o } WHERE { ?s ?p ?o }
Error: Query refused
Endpoint: http://server.jnj.com/sparql
HTTP response code: 500

You have the response 500 which says "Error: Query refused" therefore you should try running the query directly on your backend to see whether Virtusoso has the correct rights/permissions [0] for the "DELETE FROM ..." activity or not.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/travis/virtuoso-sparql-permission.sql

**Comment by kghbln** [comment]
It appears that this issue was resolved.
