### ISSUE TITLE
TypeError from line 133 of "ParserCache.php": Argument 1 passed to `ParserCache::getETag()` must be an instance of WikiPage, instance of Article given

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4741]
### Setup and configuration

Software | Version
-- | --
MediaWiki | 1.35.0-alpha
PHP | 7.3.14-1~deb10u1 (fpm-fcgi)
MariaDB | 10.3.22-MariaDB-0+deb10u1
Semantic MediaWiki | 3.1.5

### Issue
Reported by @Abijeet on [Phabricator / T248719](https://phabricator.wikimedia.org/T248719#6079039)

```
[2020-04-22 14:58:13] exception.ERROR: [8a209061a64b161a1b7952fe] /wiki/Support   TypeError from line 133 of /srv/mediawiki/workdir/includes/parser/ParserCache.php: Argument 1 passed to ParserCache::getETag() must be an instance of WikiPage, instance of Article given, called in /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php on line 646 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to ParserCache::getETag() must be an instance of WikiPage, instance of Article given, called in /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php on line 646 at /srv/mediawiki/workdir/includes/parser/ParserCache.php:133)
```

### Stack trace

```
#0 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(646): ParserCache->getETag(Object(Article), Object(ParserOptions))
#1 /srv/mediawiki/workdir/includes/HookRunner/HookContainer.php(283): SMW\\MediaWiki\\Hooks->onArticleViewHeader(Object(Article), false, true)
#2 /srv/mediawiki/workdir/includes/HookRunner/HookContainer.php(126): MediaWiki\\HookRunner\\HookContainer->callLegacyHook('ArticleViewHead...', Array, Array, Array)
#3 /srv/mediawiki/workdir/includes/Hooks.php(135): MediaWiki\\HookRunner\\HookContainer->run('ArticleViewHead...', Array, Array)
#4 /srv/mediawiki/workdir/includes/page/Article.php(699): Hooks::run('ArticleViewHead...', Array)
#5 /srv/mediawiki/workdir/extensions/LiquidThreads/pages/TalkpageView.php(61): Article->view()
#6 /srv/mediawiki/workdir/extensions/LiquidThreads/pages/TalkpageView.php(281): TalkpageView->showHeader()
#7 /srv/mediawiki/workdir/extensions/LiquidThreads/classes/Dispatch.php(66): TalkpageView->show()
#8 /srv/mediawiki/workdir/extensions/LiquidThreads/classes/Dispatch.php(222): LqtDispatch::talkpageMain(Object(OutputPage), Object(Article), Object(Title), Object(User), Object(WebRequest))
#9 /srv/mediawiki/workdir/includes/HookRunner/HookContainer.php(283): LqtDispatch::tryPage(Object(OutputPage), Object(Article), Object(Title), Object(User), Object(WebRequest), Object(MediaWiki))
#10 /srv/mediawiki/workdir/includes/HookRunner/HookContainer.php(126): MediaWiki\\HookRunner\\HookContainer->callLegacyHook('MediaWikiPerfor...', Array, Array, Array)
#11 /srv/mediawiki/workdir/includes/Hooks.php(135): MediaWiki\\HookRunner\\HookContainer->run('MediaWikiPerfor...', Array, Array)
#12 /srv/mediawiki/workdir/includes/MediaWiki.php(491): Hooks::run('MediaWikiPerfor...', Array)
#13 /srv/mediawiki/workdir/includes/MediaWiki.php(305): MediaWiki->performAction(Object(Article), Object(Title))
#14 /srv/mediawiki/workdir/includes/MediaWiki.php(973): MediaWiki->performRequest()
#15 /srv/mediawiki/workdir/includes/MediaWiki.php(535): MediaWiki->main()
#16 /srv/mediawiki/workdir/index.php(47): MediaWiki->run()
```

### Cause
ParserCache::get remove polymorphic argument

Use WikiPage instead Page|Article|WikiPage

https://gerrit.wikimedia.org/r/c/mediawiki/core/+/577393/26/includes/parser/ParserCache.php#247

**Comment by Abijeet** [comment]
We deployed the latest patch on Transalatewiki.net and encountered the following exception,

```
[2020-04-29 15:05:16] exception.ERROR: [c94059b064d99e546a30293c] /wiki/Category:Translatewiki.net/hu-x-formal   Error from line 66 of /srv/mediawiki/tags/2020-04-29_14:58:41/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ArticleViewHeader.php: Call to undefined method WikiCategoryPage::getContext() {"exception":"[object] (Error(code: 0): Call to undefined method WikiCategoryPage::getContext() at /srv/mediawiki/tags/2020-04-29_14:58:41/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ArticleViewHeader.php:66)
[stacktrace]
#0 /srv/mediawiki/tags/2020-04-29_14:58:41/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(680): SMW\\MediaWiki\\Hooks\\ArticleViewHeader->process(Object(WikiCategoryPage), false, true)
#1 /srv/mediawiki/tags/2020-04-29_14:58:41/includes/HookContainer/HookContainer.php(283): SMW\\MediaWiki\\Hooks->onArticleViewHeader(Object(WikiCategoryPage), false, true)
#2 /srv/mediawiki/tags/2020-04-29_14:58:41/includes/HookContainer/HookContainer.php(126): MediaWiki\\HookContainer\\HookContainer->callLegacyHook('ArticleViewHead...', Array, Array, Array)
#3 /srv/mediawiki/tags/2020-04-29_14:58:41/includes/Hooks.php(135): MediaWiki\\HookContainer\\HookContainer->run('ArticleViewHead...', Array, Array)
#4 /srv/mediawiki/tags/2020-04-29_14:58:41/includes/page/Article.php(704): Hooks::run('ArticleViewHead...', Array)
#5 /srv/mediawiki/tags/2020-04-29_14:58:41/includes/page/CategoryPage.php(66): Article->view()
#6 /srv/mediawiki/tags/2020-04-29_14:58:41/includes/actions/ViewAction.php(66): CategoryPage->view()
#7 /srv/mediawiki/tags/2020-04-29_14:58:41/includes/MediaWiki.php(519): ViewAction->show()
#8 /srv/mediawiki/tags/2020-04-29_14:58:41/includes/MediaWiki.php(305): MediaWiki->performAction(Object(CategoryPage), Object(Title))
#9 /srv/mediawiki/tags/2020-04-29_14:58:41/includes/MediaWiki.php(973): MediaWiki->performRequest()
#10 /srv/mediawiki/tags/2020-04-29_14:58:41/includes/MediaWiki.php(535): MediaWiki->main()
#11 /srv/mediawiki/tags/2020-04-29_14:58:41/index.php(47): MediaWiki->run()
#12 {main}
","exception_id":"c94059b064d99e546a30293c","exception_url":"/wiki/Category:Translatewiki.net/hu-x-formal","caught_by":"mwe_handler"} []
```
The `onArticleViewHeader` hook calls `ArticleViewHeader::process` (https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/ArticleViewHeader.php#L89) which then calls `$page->getContext()`, which is present in `Article`, but not present in `WikiPage`

Ping: @mwjames

**Comment by kghbln** [comment]
Thanks for reporting back.

**Comment by mwjames** [comment]
> The onArticleViewHeader hook calls ArticleViewHeader::process (https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/ArticleViewHeader.php#L89) which then calls $page->getContext(), which is present in Article, but not present in WikiPage

Could be the following works better, it is untested.

```
@@ -641,25 +641,23 @@ class Hooks {
 	 *
 	 * @see https://www.mediawiki.org/wiki/Manual:Hooks/ArticleViewHeader
 	 */
 	public function onArticleViewHeader( &$page, &$outputDone, &$useParserCache ) {
 
-		// #4741
-		if ( $page instanceof \Article ) {
-			$page = $page->getPage();
-		}
-
 		$applicationFactory = ApplicationFactory::getInstance();
 
 		// Get the key to distinguish between an anon and logged-in user stored
 		// parser cache
 		$parserCache = $applicationFactory->create( 'ParserCache' );
 
 		$dependencyValidator = $applicationFactory->create( 'DependencyValidator' );
 
+		// #4741
+		$wikiPage = $page->getPage();
+
 		$dependencyValidator->setETag(
-			$parserCache->getETag( $page, $page->makeParserOptions( 'canonical' ) )
+			$parserCache->getETag( $wikiPage, $wikiPage->makeParserOptions( 'canonical' ) )
 		);
```
