### ISSUE TITLE
`ArticleViewHeader.php`: Call to undefined method `WikiCategoryPage::getContext`

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#4759]
### Setup and configuration

```
{
    "SMWElasticStore": {
        "mysql": "10.1.44-MariaDB-0ubuntu0.18.04.1",
        "es": "6.5.4"
    },
    "smw": "3.2.0-alpha",
    "mediawiki": "1.34.1",
    "php": "7.2.24-0ubuntu0.18.04.4"
}
```
### Issue

```
[f4b818a47effc68a14868bee] /wiki/Cat%C3%A9gorie:Sandbox Error from line 89 of /var/www/html/sbxsmw/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ArticleViewHeader.php: Call to undefined method WikiCategoryPage::getContext()

Backtrace:

#0 /var/www/html/sbxsmw/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(686): SMW\MediaWiki\Hooks\ArticleViewHeader->process(WikiCategoryPage, boolean, boolean)
#1 /var/www/html/sbxsmw/w/includes/Hooks.php(174): SMW\MediaWiki\Hooks->onArticleViewHeader(WikiCategoryPage, boolean, boolean)
#2 /var/www/html/sbxsmw/w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#3 /var/www/html/sbxsmw/w/includes/page/Article.php(693): Hooks::run(string, array)
#4 /var/www/html/sbxsmw/w/includes/page/CategoryPage.php(66): Article->view()
#5 /var/www/html/sbxsmw/w/includes/actions/ViewAction.php(63): CategoryPage->view()
#6 /var/www/html/sbxsmw/w/includes/MediaWiki.php(511): ViewAction->show()
#7 /var/www/html/sbxsmw/w/includes/MediaWiki.php(302): MediaWiki->performAction(CategoryTreeCategoryPage, Title)
#8 /var/www/html/sbxsmw/w/includes/MediaWiki.php(900): MediaWiki->performRequest()
#9 /var/www/html/sbxsmw/w/includes/MediaWiki.php(527): MediaWiki->main()
#10 /var/www/html/sbxsmw/w/index.php(44): MediaWiki->run()
#11 {main}
```

Caused by #4743

**Comment by mwjames** [comment]
Missing an integration test for the category page otherwise a failing test on #4743 would have been detected.
