### ISSUE TITLE
PropertyLabelNotResolvedException during #ask

### ISSUE THREAD

**Issue by 26** [SemanticMediaWiki/SemanticMediaWiki#4814]
### Setup and configuration

- SMW version: 3.1.4
- MW version: 1.31.6
- PHP version: 7.0.33
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.7.30, Elasticsearch 5.6.16

### Issue
When testing some things for Semantic MediaWiki, I executed the following query:

```
{{#ask: [[not:"example"]]}}
```

Which caused the fatal error given below. With "format=debug", this exception is not thrown. It also does not get thrown when I replace `not` with `in` or when multiple conditions are used (from what I have seen).

### Stack trace
Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and/or outputs:

```
[60be5effe802b62d8c375399] /index.php?title=Example/Proximity_search_test&action=submit SMW\Exception\PropertyLabelNotResolvedException from line 90 of /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php: Illegal property key "".

Backtrace:

#0 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php(498): SMW\DIProperty->__construct(string, boolean)
#1 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CacheWarmer.php(100): SMW\DIProperty::newFromUserLabel(string)
#2 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityIdManager.php(889): SMW\SQLStore\EntityStore\CacheWarmer->fillFromList(array)
#3 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1290): SMW\SQLStore\EntityStore\EntityIdManager->warmUpCache(SMW\Query\QueryResult)
#4 /data/www/devrvs.wikibase.nl/public_html/includes/Hooks.php(177): SMW\MediaWiki\Hooks->onAfterQueryResultLookupComplete(SMW\Elastic\ElasticStore, SMW\Query\QueryResult)
#5 /data/www/devrvs.wikibase.nl/public_html/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#6 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/Elastic/ElasticStore.php(219): Hooks::run(string, array)
#7 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(338): SMW\Elastic\ElasticStore->getQueryResult(SMWQuery)
#8 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(364): SMWQueryProcessor::getResultFromQuery(SMWQuery, array, integer, integer)
#9 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(197): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array, array)
#10 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse(array)
#11 /data/www/devrvs.wikibase.nl/public_html/includes/parser/Parser.php(3426): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string)
#12 /data/www/devrvs.wikibase.nl/public_html/includes/parser/Parser.php(3127): Parser->callParserFunction(PPFrame_DOM, string, array)
#13 /data/www/devrvs.wikibase.nl/public_html/includes/parser/Preprocessor_DOM.php(1277): Parser->braceSubstitution(array, PPFrame_DOM)
#14 /data/www/devrvs.wikibase.nl/public_html/includes/parser/Parser.php(2942): PPFrame_DOM->expand(DOMElement, integer)
#15 /data/www/devrvs.wikibase.nl/public_html/includes/parser/Parser.php(1293): Parser->replaceVariables(string)
#16 /data/www/devrvs.wikibase.nl/public_html/includes/parser/Parser.php(443): Parser->internalParse(string)
#17 /data/www/devrvs.wikibase.nl/public_html/includes/content/WikitextContent.php(323): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#18 /data/www/devrvs.wikibase.nl/public_html/includes/content/AbstractContent.php(516): WikitextContent->fillParserOutput(Title, NULL, ParserOptions, boolean, ParserOutput)
#19 /data/www/devrvs.wikibase.nl/public_html/includes/EditPage.php(3963): AbstractContent->getParserOutput(Title, NULL, ParserOptions)
#20 /data/www/devrvs.wikibase.nl/public_html/includes/EditPage.php(3891): EditPage->doPreviewParse(WikitextContent)
#21 /data/www/devrvs.wikibase.nl/public_html/includes/EditPage.php(2674): EditPage->getPreviewText()
#22 /data/www/devrvs.wikibase.nl/public_html/includes/EditPage.php(674): EditPage->showEditForm()
#23 /data/www/devrvs.wikibase.nl/public_html/includes/actions/EditAction.php(60): EditPage->edit()
#24 /data/www/devrvs.wikibase.nl/public_html/includes/actions/SubmitAction.php(38): EditAction->show()
#25 /data/www/devrvs.wikibase.nl/public_html/includes/MediaWiki.php(500): SubmitAction->show()
#26 /data/www/devrvs.wikibase.nl/public_html/includes/MediaWiki.php(294): MediaWiki->performAction(Article, Title)
#27 /data/www/devrvs.wikibase.nl/public_html/includes/MediaWiki.php(861): MediaWiki->performRequest()
#28 /data/www/devrvs.wikibase.nl/public_html/includes/MediaWiki.php(524): MediaWiki->main()
#29 /data/www/devrvs.wikibase.nl/public_html/index.php(42): MediaWiki->run()
#30 {main}
```

### Steps to reproduce
- Edit any page
- Insert the query `{{#ask: [[not:"example"]]}}`
- Click save or preview edit

**Comment by 26** [comment]
Some time later, I also found that `{{#ask: [[in:example~5]]}}` causes a similar exception:

```
95372d46c6bae08cafb586e5] /index.php?title=Speciaal:Vragen& SMW\Exception\PropertyLabelNotResolvedException from line 90 of /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php: Illegal property key "".

Backtrace:

#0 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php(498): SMW\DIProperty->__construct(string, boolean)
#1 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CacheWarmer.php(100): SMW\DIProperty::newFromUserLabel(string)
#2 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityIdManager.php(889): SMW\SQLStore\EntityStore\CacheWarmer->fillFromList(array)
#3 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1290): SMW\SQLStore\EntityStore\EntityIdManager->warmUpCache(SMW\Query\QueryResult)
#4 /data/www/devrvs.wikibase.nl/public_html/includes/Hooks.php(177): SMW\MediaWiki\Hooks->onAfterQueryResultLookupComplete(SMW\Elastic\ElasticStore, SMW\Query\QueryResult)
#5 /data/www/devrvs.wikibase.nl/public_html/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#6 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/Elastic/ElasticStore.php(219): Hooks::run(string, array)
#7 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(719): SMW\Elastic\ElasticStore->getQueryResult(SMWQuery)
#8 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(451): SMW\MediaWiki\Specials\SpecialAsk->fetchQueryResult(array)
#9 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(317): SMW\MediaWiki\Specials\SpecialAsk->fetchResults(SMW\Query\ResultPrinters\TableResultPrinter, NULL, SMW\Utils\UrlArgs)
#10 /data/www/devrvs.wikibase.nl/public_html/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(170): SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#11 /data/www/devrvs.wikibase.nl/public_html/includes/specialpage/SpecialPage.php(565): SMW\MediaWiki\Specials\SpecialAsk->execute(NULL)
#12 /data/www/devrvs.wikibase.nl/public_html/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#13 /data/www/devrvs.wikibase.nl/public_html/includes/MediaWiki.php(288): SpecialPageFactory::executePath(Title, RequestContext)
#14 /data/www/devrvs.wikibase.nl/public_html/includes/MediaWiki.php(861): MediaWiki->performRequest()
#15 /data/www/devrvs.wikibase.nl/public_html/includes/MediaWiki.php(524): MediaWiki->main()
#16 /data/www/devrvs.wikibase.nl/public_html/index.php(42): MediaWiki->run()
#17 {main}
```

It seems that mixing certain ES syntax with a search operator causes SMW to fail.
