### ISSUE TITLE
Exception On `Special:Browse` and some `Property:` pages

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticMediaWiki#4818]
### Setup and configuration

- SMW version: 3.1.5 (a30b089)
- MW version: 1.34.0
- PHP version: 7.3.19 (fpm-fcgi)
- DB system and version: Percona XtraDB Cluster 5.7.23-23-57-log

### Stack trace

```
2020-07-13 16:38:44 wiki.sharing.ge.com wiki-wiki1: [7115d16ac06e33bd50594872] /w/api.php   SMW\Exception\PropertyLabelNotResolvedException from line 90 of .../extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php: Illegal property key "".
#0 .../extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php(498): SMW\DIProperty->__construct(string, boolean)
#1 .../extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CacheWarmer.php(100): SMW\DIProperty::newFromUserLabel(string)
#2 .../extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityIdManager.php(889): SMW\SQLStore\EntityStore\CacheWarmer->fillFromList(SMW\Iterators\MappingIterator)
#3 .../extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityLookup.php(402): SMW\SQLStore\EntityStore\EntityIdManager->warmUpCache(SMW\Iterators\MappingIterator)
#4 .../extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(253): SMW\SQLStore\EntityStore\EntityLookup->getPropertySubjects(SMW\DIProperty, SMW\DIWikiPage, SMW\RequestOptions)
#5 .../extensions/SemanticMediaWiki/src/MediaWiki/Specials/Browse/HtmlBuilder.php(854): SMW\SQLStore\SQLStore->getPropertySubjects(SMW\DIProperty, SMW\DIWikiPage, SMW\RequestOptions)
#6 .../extensions/SemanticMediaWiki/src/MediaWiki/Specials/Browse/HtmlBuilder.php(319): SMW\MediaWiki\Specials\Browse\HtmlBuilder->getInData()
#7 .../extensions/SemanticMediaWiki/src/MediaWiki/Specials/Browse/HtmlBuilder.php(229): SMW\MediaWiki\Specials\Browse\HtmlBuilder->createHTML()
#8 .../extensions/SemanticMediaWiki/src/MediaWiki/Api/Browse/SubjectLookup.php(107): SMW\MediaWiki\Specials\Browse\HtmlBuilder->buildHTML()
#9 .../extensions/SemanticMediaWiki/src/MediaWiki/Api/Browse/SubjectLookup.php(69): SMW\MediaWiki\Api\Browse\SubjectLookup->buildHTML(array)
#10 .../extensions/SemanticMediaWiki/src/MediaWiki/Api/Browse.php(266): SMW\MediaWiki\Api\Browse\SubjectLookup->lookup(array)
#11 .../extensions/SemanticMediaWiki/src/MediaWiki/Api/Browse.php(69): SMW\MediaWiki\Api\Browse->callSubjectLookup(array)
#12 .../includes/api/ApiMain.php(1598): SMW\MediaWiki\Api\Browse->execute()
#13 .../includes/api/ApiMain.php(537): ApiMain->executeAction()
#14 .../includes/api/ApiMain.php(508): ApiMain->executeActionWithErrorHandling()
#15 .../api.php(87): ApiMain->execute()
#16 {main}

```

### Steps to reproduce
Just upgraded from 1.27.  The above stacktrace appears on some `Special:Browse` pages as well as the property pages: `Property:Is_a_new_page`, `Property:Modification_date`, `Property:Creation_date`, `Property:Last_editor_is`,

**Comment by JeroenDeDauw** [comment]
We already dealt with a bunch of issues in that class. So might well be fixed on master for a long time already. Hard to tell with a year between releases and no release notes.

**Comment by hexmode** [comment]
What "year between releases" are you talking about? SMW 3.1.5 is only 2 months older than 3.1.6.  Do you mean MW?

**Comment by hexmode** [comment]
In any case installing 3.1.6 and cherry-picking 98e4b9910a6ce5b117457d2d90ecf013483b5102 seems to have helped.  Thanks for the pointer.  Let me check some more and then I'll close this.

**Comment by hexmode** [comment]
my tests show this is working.

**Comment by JeroenDeDauw** [comment]
I mean there is a year worth of unreleased and undocumented changes on master
