### ISSUE TITLE
TransactionHandler.php: Trying to begin a new section transaction while sql/transaction/update is still active!

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticMediaWiki#4819]
### Setup and configuration

* SMW version: 3.1.6
* MW version: 1.34.0
* PHP version: 7.3.19 (fpm-fcgi)
* DB system: Percona XtraDB Cluster, 5.7.23-23-57-log

### Stack trace

```
2020-07-17 04:47:11 unknown! wiki-wiki1: [584745925fcc0c51551b2686] [no req]   RuntimeException from line 123 of ../extensions/SemanticMediaWiki/src/MediaWiki/Connection/TransactionHandler.php: Trying to begin a new section transaction while sql/transaction/update is still active!
#0 .../extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(677): SMW\MediaWiki\Connection\TransactionHandler->markSectionTransaction(string)
#1 .../extensions/SemanticMediaWiki/src/SQLStore/SQLStoreUpdater.php(195): SMW\MediaWiki\Connection\Database->beginSectionTransaction(string)
#2 .../extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(308): SMW\SQLStore\SQLStoreUpdater->doDataUpdate(SMW\SemanticData)
#3 .../extensions/SemanticMediaWiki/src/Store.php(238): SMW\SQLStore\SQLStore->doDataUpdate(SMW\SemanticData)
#4 .../extensions/SemanticMediaWiki/src/DataUpdater.php(403): SMW\Store->updateData(SMW\SemanticData)
#5 .../extensions/SemanticMediaWiki/src/DataUpdater.php(289): SMW\DataUpdater->updateData()
#6 .../extensions/SemanticMediaWiki/src/DataUpdater.php(193): SMW\DataUpdater->runUpdate()
#7 .../extensions/SemanticMediaWiki/src/ParserData.php(453): SMW\DataUpdater->doUpdate()
#8 .../extensions/SemanticMediaWiki/src/MediaWiki/Hooks/LinksUpdateConstructed.php(120): SMW\ParserData->updateStore(array)
#9 .../extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(815): SMW\MediaWiki\Hooks\LinksUpdateConstructed->process(LinksUpdate)
#10 .../includes/Hooks.php(174): SMW\MediaWiki\Hooks->onLinksUpdateConstructed(LinksUpdate)
#11 .../includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#12 .../includes/deferred/LinksUpdate.php(168): Hooks::run(string, array)
#13 .../includes/Storage/DerivedPageDataUpdater.php(1316): LinksUpdate->__construct(Title, ParserOutput, boolean)
#14 .../includes/Storage/DerivedPageDataUpdater.php(1606): MediaWiki\Storage\DerivedPageDataUpdater->getSecondaryDataUpdates(boolean)
#15 .../includes/page/WikiPage.php(2145): MediaWiki\Storage\DerivedPageDataUpdater->doSecondaryDataUpdates(array)
#16 .../includes/jobqueue/jobs/RefreshLinksJob.php(190): WikiPage->doSecondaryDataUpdates(array)
#17 .../includes/jobqueue/jobs/RefreshLinksJob.php(126): RefreshLinksJob->runForTitle(Title)
#18 .../includes/jobqueue/JobRunner.php(299): RefreshLinksJob->run()
#19 .../includes/jobqueue/JobRunner.php(192): JobRunner->executeJob(RefreshLinksJob, Wikimedia\Rdbms\LBFactorySimple, BufferingStatsdDataFactory, integer)
#20 .../maintenance/runJobs.php(92): JobRunner->run(array)
#21 .../maintenance/doMaintenance.php(99): RunJobs->execute()
#22 .../maintenance/runJobs.php(129): require_once(string)
#23 {main}
```
`unknown!` indicates a CLI job without SERVER_NAME being set.

**Comment by hexmode** [comment]
A series of the above follow after this error (which is probably caused by my Percona index mangling):
```
020-07-17 04:46:07 unknown! wiki-wiki1: [584745925fcc0c51551b2686] [no req]   Wikimedia\Rdbms\DBQueryError from line 1603 of .../includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forg
et to run your application's database schema updater after upgrading?
Query: INSERT  INTO `wiki1smw_ft_search` (s_id,p_id,o_text) VALUES ('511007','1240','')
Function: SMW\SQLStore\QueryEngine\Fulltext\SearchTableUpdater::insert
Error: 1062 Duplicate entry '511007-1240' for key 'PRIMARY' (10.141.0.55)

#0 .../includes/libs/rdbms/database/Database.php(1574): Wikimedia\Rdbms\Database->getQueryExceptionAndLog(string, integer, string, string)
#1 .../includes/libs/rdbms/database/Database.php(1152): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#2 .../includes/libs/rdbms/database/Database.php(2140): Wikimedia\Rdbms\Database->query(string, string)
#3 .../includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->insert(string, array, string, string)
#4 .../includes/libs/rdbms/database/DBConnRef.php(371): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#5 .../extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(511): Wikimedia\Rdbms\DBConnRef->insert(string, array, string, array)
#6 .../extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/SearchTableUpdater.php(186): SMW\MediaWiki\Connection\Database->insert(string, array, string)
#7 .../extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/TextChangeUpdater.php(224): SMW\SQLStore\QueryEngine\Fulltext\SearchTableUpdater->insert(string, string)
#8 .../extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/TextChangeUpdater.php(119): SMW\SQLStore\QueryEngine\Fulltext\TextChangeUpdater->doUpdateFromChangeDiff(SMW\SQLStore\ChangeOp\ChangeDiff)
#9 .../extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1247): SMW\SQLStore\QueryEngine\Fulltext\TextChangeUpdater->pushUpdates(SMW\SQLStore\ChangeOp\ChangeOp)
#10 .../includes/Hooks.php(174): SMW\MediaWiki\Hooks->onAfterDataUpdateComplete(SMW\SQLStore\SQLStore, SMW\SemanticData, SMW\SQLStore\ChangeOp\ChangeOp)
#11 .../includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#12 .../extensions/SemanticMediaWiki/src/SQLStore/SQLStoreUpdater.php(272): Hooks::run(string, array)
#13 .../extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(308): SMW\SQLStore\SQLStoreUpdater->doDataUpdate(SMW\SemanticData)
#14 .../extensions/SemanticMediaWiki/src/Store.php(238): SMW\SQLStore\SQLStore->doDataUpdate(SMW\SemanticData)
#15 .../extensions/SemanticMediaWiki/src/DataUpdater.php(403): SMW\Store->updateData(SMW\SemanticData)
#16 .../extensions/SemanticMediaWiki/src/DataUpdater.php(289): SMW\DataUpdater->updateData()
#17 .../extensions/SemanticMediaWiki/src/DataUpdater.php(193): SMW\DataUpdater->runUpdate()
#18 .../extensions/SemanticMediaWiki/src/ParserData.php(453): SMW\DataUpdater->doUpdate()
#19 .../extensions/SemanticMediaWiki/src/MediaWiki/Hooks/LinksUpdateConstructed.php(120): SMW\ParserData->updateStore(array)
#20 .../extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(815): SMW\MediaWiki\Hooks\LinksUpdateConstructed->process(LinksUpdate)
#21 .../includes/Hooks.php(174): SMW\MediaWiki\Hooks->onLinksUpdateConstructed(LinksUpdate)
#22 .../includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#23 .../includes/deferred/LinksUpdate.php(168): Hooks::run(string, array)
#24 .../includes/Storage/DerivedPageDataUpdater.php(1316): LinksUpdate->__construct(Title, ParserOutput, boolean)
#25 .../includes/Storage/DerivedPageDataUpdater.php(1606): MediaWiki\Storage\DerivedPageDataUpdater->getSecondaryDataUpdates(boolean)
#26 .../includes/page/WikiPage.php(2145): MediaWiki\Storage\DerivedPageDataUpdater->doSecondaryDataUpdates(array)
#27 .../includes/jobqueue/jobs/RefreshLinksJob.php(190): WikiPage->doSecondaryDataUpdates(array)
#28 .../includes/jobqueue/jobs/RefreshLinksJob.php(126): RefreshLinksJob->runForTitle(Title)
#29 .../includes/jobqueue/JobRunner.php(299): RefreshLinksJob->run()
#30 .../includes/jobqueue/JobRunner.php(192): JobRunner->executeJob(RefreshLinksJob, Wikimedia\Rdbms\LBFactorySimple, BufferingStatsdDataFactory, integer)
#31 .../maintenance/runJobs.php(92): JobRunner->run(array)
#32 .../maintenance/doMaintenance.php(99): RunJobs->execute()
#33 .../maintenance/runJobs.php(129): require_once(string)
#34 {main}
```

**Comment by kghbln** [comment]
Thanks for reporting. When seeing all of this it does not look good for Pecuniar.

**Comment by hexmode** [comment]
This one can be closed.  It is my own fault for creating the wrong index.

That said, I realize you are getting a negative impression for Percona because of my bug reports, but several of them (this one) don't really have anything to do with Percona.  And supporting stricter SQL standards than MySQL does by default just helps create more portable sql statements.

**Comment by kghbln** [comment]
It is less these bugs but the fear that this cannot be dealt with in quite some time. At least I suspect this when thinking of all the upcoming changes already originating from MediaWiki itself.
