### ISSUE TITLE
TypeError from line 191 of "RevisionGuard.php": Argument 1 passed to SMW\MediaWiki\RevisionGuard::getFile() must be an instance of Title, null given

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4832]
### Setup and configuration

- MediaWiki | 1.35.0-rc.2 (0d674e2)
- PHP | 7.2.24-0ubuntu0.18.04.6 (apache2handler)
- MariaDB | 10.1.44-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0-alpha (73e8341) 15:28, 24 August 2020

### Issue
When running "rebuildElasticIndex.php" I get the following error, probably due to file ingestion:
```
PHP Notice:  Uninitialized string offset: 0 in /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/DocumentCreator.php on line 309
Notice: Uninitialized string offset: 0 in /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/DocumentCreator.php on line 309

[558086a459a1facb14583ee6] [no req]   TypeError from line 191 of /../w/extensions/SemanticMediaWiki/src/MediaWiki/RevisionGuard.php: Argument 1 passed to SMW\MediaWiki\RevisionGuard::getFile() must be an instance of Title, null given, called in /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/FileIndexer.php on line 177
```

### Stack trace
```
#0 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/FileIndexer.php(177): SMW\MediaWiki\RevisionGuard->getFile(NULL, NULL)
#1 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rebuilder/Rebuilder.php(322): SMW\Elastic\Indexer\FileIndexer->index(SMW\DIWikiPage)
#2 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(482): SMW\Elastic\Indexer\Rebuilder\Rebuilder->rebuild(string, SMW\SQLStore\EntityStore\StubSemanticData)
#3 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(419): SMW\Maintenance\rebuildElasticIndex->rebuildFromRow(integer, integer, stdClass, string)
#4 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(186): SMW\Maintenance\rebuildElasticIndex->rebuild()
#5 /../w/maintenance/doMaintenance.php(107): SMW\Maintenance\rebuildElasticIndex->execute()
#6 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(552): require_once(string)
#7 {main}
```

**Comment by kghbln** [comment]
> probably due to file ingestion

Indeed, after disabling file ingestion the script is able to complete.

```json
                "experimental.file.ingest": false,
```
