### ISSUE TITLE
SMW\Exception\DataItemDeserializationException: Unserialization failed: the string "Portal_talk:Sv/" was not understood.

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#4849]
### Setup

- SMW version: 3.2.0
- MW version: 1.36.0-alpha (yes, I am aware it's not a supported combination)
- PHP version: 7.3.19-1~deb10u1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.3.23-MariaDB-0+deb10u1

### Issue

Two issues here:
* The API request has incorrect `param.subject` (truncated at a quotation mark)
* The smwtask API fails with an exception rather than a proper error message.

Stacktrace:

```
[2020-09-23 02:25:37] exception.ERROR: [790dec0f6acb9dd3d4ee9818] /w/api.php   SMW\Exception\DataItemDeserializationException from line 300 of /srv/mediawiki/tags/2020-09-16_14:32:29/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_WikiPage.php: Unserialization failed: the string "Portal_talk:Sv/" was not understood. {"exception":"[object] (SMW\\Exception\\DataItemDeserializationException(code: 0): Unserialization failed: the string \"Portal_talk:Sv/\" was not understood. at /srv/mediawiki/tags/2020-09-16_14:32:29/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_WikiPage.php:300)
[stacktrace]
#0 /srv/mediawiki/tags/2020-09-16_14:32:29/extensions/SemanticMediaWiki/src/MediaWiki/Api/Tasks/EntityExaminerTask.php(70): SMW\\DIWikiPage::doUnserialize('Portal_talk:Sv/')
#1 /srv/mediawiki/tags/2020-09-16_14:32:29/extensions/SemanticMediaWiki/src/MediaWiki/Api/Task.php(62): SMW\\MediaWiki\\Api\\Tasks\\EntityExaminerTask->process(Array)
#2 /srv/mediawiki/tags/2020-09-16_14:32:29/includes/api/ApiMain.php(1600): SMW\\MediaWiki\\Api\\Task->execute()
#3 /srv/mediawiki/tags/2020-09-16_14:32:29/includes/api/ApiMain.php(536): ApiMain->executeAction()
#4 /srv/mediawiki/tags/2020-09-16_14:32:29/includes/api/ApiMain.php(507): ApiMain->executeActionWithErrorHandling()
#5 /srv/mediawiki/tags/2020-09-16_14:32:29/api.php(90): ApiMain->execute()
#6 /srv/mediawiki/tags/2020-09-16_14:32:29/api.php(45): wfApiMain()
#7 {main}
","exception_id":"790dec0f6acb9dd3d4ee9818","exception_url":"/w/api.php","caught_by":"entrypoint"} []
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

Visit https://translatewiki.net/wiki/Thread:Portal_talk:Sv/%22Diffar%22_-_%22Skillnader%22 and inspect ajax requests. One of them is:
```
action: smwtask
format: json
task: run-entity-examiner
params: {"subject":"Portal_talk:Sv/","is_placeholder":true}
token: <censored>
```

**Comment by kghbln** [comment]
*Setup*
- MediaWiki | 1.35.0-rc.2 (5f6c9d1)21 août 2020 à 16:32
- PHP | 7.2.24-0ubuntu0.18.04.7 (apache2handler)
- MariaDB | 10.1.47-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0 (9f00861) 7 septembre 2020 à 21:43

```
2020-11-04 04:41:19 sulcorebutia DB9907220070920: [3f43a92b51ab15a7a609ed3b] /w/api.php   SMW\Exception\DataItemDeserializationException from line 300 of /../w/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_WikiPage.php: Unserialization failed: the string "Installation/Example_" was not understood.
#0 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Api/Tasks/EntityExaminerTask.php(70): SMW\DIWikiPage::doUnserialize(string)
#1 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Api/Task.php(62): SMW\MediaWiki\Api\Tasks\EntityExaminerTask->process(array)
#2 /../w/includes/api/ApiMain.php(1582): SMW\MediaWiki\Api\Task->execute()
#3 /../w/includes/api/ApiMain.php(535): ApiMain->executeAction()
#4 /../w/includes/api/ApiMain.php(506): ApiMain->executeActionWithErrorHandling()
#5 /../w/api.php(94): ApiMain->execute()
#6 {main}
```
