### ISSUE TITLE
Wikimedia\Rdbms\DBQueryError from line 1457 of "Database.php"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4879]
### Setup

- MediaWiki | 1.35.0-rc.2 (5f6c9d1)21 août 2020 à 16:32
- PHP | 7.2.24-0ubuntu0.18.04.7 (apache2handler)
- MariaDB | 10.1.47-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0 (9f00861) 7 septembre 2020 à 21:43

### Issue

```
2020-11-02 17:06:46 sulcorebutia DB9907220070920: [f989aaa5473edc78c3a630dc] /wiki/Sites_using_Semantic_MediaWiki?keyword=Philosophy   Wikimedia\Rdbms\DBQueryError from line 1457 of /../w/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
```
```
Query: INSERT  INTO `smw_query_links` (s_id,o_id) VALUES ('256233','806'),('256233','137487'),('256233','2038'),('256233','3682'),('256233','2039'),('256233','148253'),('256233','148226'),('256233','121468'),('256233','148245'),('256233','121466'),('256233','148300'),('256233','148254'),('256233','137054'),('256233','123187')
```
```
Function: SMW\SQLStore\QueryDependency\DependencyLinksTableUpdater::updateDependencyList
```
```
Error: 1213 Deadlock found when trying to get lock; try restarting transaction (localhost:5252)
```

### Backtrace
```#0 /../w/includes/libs/rdbms/database/Database.php(1427): Wikimedia\Rdbms\Database->makeQueryException(string, integer, string, string)
#1 /../w/includes/libs/rdbms/database/Database.php(1200): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#2 /../w/includes/libs/rdbms/database/Database.php(1966): Wikimedia\Rdbms\Database->query(string, string)
#3 [internal function]: Wikimedia\Rdbms\Database->insert(string, array, string, string)
#4 /../w/includes/libs/rdbms/database/DBConnRef.php(49): call_user_func_array(array, array)
#5 /../w/includes/libs/rdbms/database/DBConnRef.php(296): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#6 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(520): Wikimedia\Rdbms\DBConnRef->insert(string, array, string, array)
#7 /../w/extensions/SemanticMediaWiki/src/SQLStore/QueryDependency/DependencyLinksTableUpdater.php(195): SMW\MediaWiki\Connection\Database->insert(string, array, string)
#8 /../w/extensions/SemanticMediaWiki/src/SQLStore/QueryDependency/DependencyLinksTableUpdater.php(84): SMW\SQLStore\QueryDependency\DependencyLinksTableUpdater->updateDependencyList(integer, array)
#9 /../w/extensions/SemanticMediaWiki/src/SQLStore/QueryDependency/QueryDependencyLinksStore.php(446): SMW\SQLStore\QueryDependency\DependencyLinksTableUpdater->doUpdate()
#10 /../w/extensions/SemanticMediaWiki/src/SQLStore/QueryDependency/QueryDependencyLinksStore.php(370): SMW\SQLStore\QueryDependency\QueryDependencyLinksStore->doUpdate(SMW\Query\QueryResult, SMW\DIWikiPage, integer, string)
#11 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(348): SMW\SQLStore\QueryDependency\QueryDependencyLinksStore->SMW\SQLStore\QueryDependency\{closure}()
#12 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(246): SMW\MediaWiki\Deferred\CallableUpdate->runUpdate()
#13 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/TransactionalCallableUpdate.php(168): SMW\MediaWiki\Deferred\CallableUpdate->doUpdate()
#14 /../w/includes/deferred/DeferredUpdates.php(259): SMW\MediaWiki\Deferred\TransactionalCallableUpdate->doUpdate()
#15 /../w/includes/deferred/DeferredUpdates.php(210): DeferredUpdates::runUpdate(SMW\MediaWiki\Deferred\TransactionalCallableUpdate, Wikimedia\Rdbms\LBFactorySimple, string, integer)
#16 /../w/includes/deferred/DeferredUpdates.php(131): DeferredUpdates::execute(array, string, integer)
#17 /../w/includes/MediaWiki.php(951): DeferredUpdates::doUpdates(string)
#18 /../w/includes/MediaWiki.php(730): MediaWiki->restInPeace(string, boolean)
#19 /../w/includes/MediaWiki.php(753): MediaWiki->{closure}()
#20 /../w/includes/MediaWiki.php(557): MediaWiki->doPostOutputShutdown(string)
#21 /../w/index.php(42): MediaWiki->run()
#22 {main}
```
### Notes
Of course we did the database upgrades etc. However the call `/wiki/Sites_using_Semantic_MediaWiki?keyword=Philosophy` causing this makes me wonder. The page does not exist and the keyword part is not MediaWiki either. I guess this is a matter of adding some guard against such rogue calls to the wiki.

**Comment by krabina** [comment]
I have a similar issue on one of my wikis. 
Is it possible this has to do with the filtered format on hight traffic wikis?
In my case the datatype keyword is not used.

```
Mon Jun 2 13:47:37 CEST 2025         semwiki Error 1213 from SMW\SQLStore\QueryDependency\DependencyLinksTableUpdater::updateDependencyList, Deadlock found when trying to get lock; try restarting transaction INSERT INTO `smw_query_links` (s_id,o_id) VALUES (12913349,1481296),(12913349,921929),(12913349,1523300),(12913349,763),(12913349,1523277),(12913349,1523276) xxxx:53996
#0 wiki/includes/libs/rdbms/database/Database.php(1576): Wikimedia\Rdbms\Database->getQueryExceptionAndLog()
#1 wiki/includes/libs/rdbms/database/Database.php(952): Wikimedia\Rdbms\Database->reportQueryError()
#2 wiki/includes/libs/rdbms/database/Database.php(1838): Wikimedia\Rdbms\Database->query()
#3 wiki/includes/libs/rdbms/database/DBConnRef.php(103): Wikimedia\Rdbms\Database->insert()
#4 wiki/includes/libs/rdbms/database/DBConnRef.php(382): Wikimedia\Rdbms\DBConnRef->__call()
#5 wiki/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(527): Wikimedia\Rdbms\DBConnRef->insert()
#6 wiki/extensions/SemanticMediaWiki/src/SQLStore/QueryDependency/DependencyLinksTableUpdater.php(192): SMW\MediaWiki\Connection\Database->insert()
#7 wiki/extensions/SemanticMediaWiki/src/SQLStore/QueryDependency/DependencyLinksTableUpdater.php(84): SMW\SQLStore\QueryDependency\DependencyLinksTableUpdater->updateDependencyList()
#8 wiki/extensions/SemanticMediaWiki/src/SQLStore/QueryDependency/QueryDependencyLinksStore.php(446): SMW\SQLStore\QueryDependency\DependencyLinksTableUpdater->doUpdate()
#9 wiki/extensions/SemanticMediaWiki/src/SQLStore/QueryDependency/QueryDependencyLinksStore.php(370): SMW\SQLStore\QueryDependency\QueryDependencyLinksStore->doUpdate()
#10 wiki/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(359): SMW\SQLStore\QueryDependency\QueryDependencyLinksStore->SMW\SQLStore\QueryDependency\{closure}()
#11 wiki/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(257): SMW\MediaWiki\Deferred\CallableUpdate->runUpdate()
#12 wiki/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/TransactionalCallableUpdate.php(168): SMW\MediaWiki\Deferred\CallableUpdate->doUpdate()
#13 wiki/includes/deferred/DeferredUpdates.php(474): SMW\MediaWiki\Deferred\TransactionalCallableUpdate->doUpdate()
#14 wiki/includes/deferred/DeferredUpdates.php(399): DeferredUpdates::attemptUpdate()
#15 wiki/includes/deferred/DeferredUpdates.php(214): DeferredUpdates::run()
#16 wiki/includes/deferred/DeferredUpdatesScope.php(267): DeferredUpdates::{closure}()
#17 wiki/includes/deferred/DeferredUpdatesScope.php(196): DeferredUpdatesScope->processStageQueue()
#18 wiki/includes/deferred/DeferredUpdates.php(206): DeferredUpdatesScope->processUpdates()
#19 wiki/includes/MediaWiki.php(1104): DeferredUpdates::doUpdates()
#20 wiki/includes/MediaWiki.php(838): MediaWiki->restInPeace()
#21 wiki/includes/MediaWiki.php(587): MediaWiki->doPostOutputShutdown()
#22 wiki/index.php(50): MediaWiki->run()
#23 wiki/index.php(46): wfIndexMain()
#24 {main}
```

Software | Version
-- | --
MediaWiki | 1.39.7 (7077e6f)01:06, 14. Dez. 2022
PHP | 8.2.20 (fpm-fcgi)
MySQL | 8.0.28
Semantic MediaWiki | 4.1.3
Semantic Result Formats | 4.2.1
