### ISSUE TITLE
Maps do not load on Special:ExpandTemplates and Special:RunQuery

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#4882]
### Setup

- SMW version: 3.1.6 / 3.2.0
- MW version: 1.34.4
- PHP version: 7.3.24
- DB system (MySQL, Blazegraph, etc.) and version: 5.5.56-MariaDB
- Maps: 7.20.1

### Issue

On non-article pages, such as Special:ExpandTemplates or Special:RunQuery, the map does not load.

Running `mw.loader.load( 'ext.maps.leaflet.loader' )` on the Console makes the map appear.

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

At the time of writing:
1. Go to https://nimiarkisto.nikerabb.it/wiki/Toiminnot:Mallineiden_laajennus
2. Paste the query below and preview

```
{{#ask:[[Pistekoordinaatti::+]]
 |?Pistekoordinaatti
 |format=map
 |limit=10
}}
```

### Rant

Please set the language to English if you want people to reproduce on the sandbox.

I tried to reproduce by pasting the following query on Special:ExpandTemplates:
```
{{#ask:[[Has coordinates::*]]
 |?Has coordinates
 |format=map
}}
```

Instead I got this error:
```
[eef663560f86839b2100217c] /wiki/Sp%C3%A9cial:ExpansionDesMod%C3%A8les TypeError from line 46 of /var/www/html/sbxsmw/w/extensions/SemanticMediaWiki/includes/formatters/MessageFormatter.php: Argument 1 passed to SMW\MessageFormatter::__construct() must be an instance of Language, instance of StubUserLang given, called in /var/www/html/sbxsmw/w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php on line 133

Backtrace:

#0 /var/www/html/sbxsmw/w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(133): SMW\MessageFormatter->__construct(StubUserLang)
#1 /var/www/html/sbxsmw/w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(395): SMW\ParserFunctionFactory->newAskParserFunction(Parser)
#2 /var/www/html/sbxsmw/w/includes/parser/Parser.php(3340): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string)
#3 /var/www/html/sbxsmw/w/includes/parser/Parser.php(3047): Parser->callParserFunction(PPFrame_Hash, string, array)
#4 /var/www/html/sbxsmw/w/includes/parser/PPFrame_Hash.php(253): Parser->braceSubstitution(array, PPFrame_Hash)
#5 /var/www/html/sbxsmw/w/includes/parser/Parser.php(2887): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#6 /var/www/html/sbxsmw/w/includes/parser/Parser.php(927): Parser->replaceVariables(string, PPFrame_Hash)
#7 /var/www/html/sbxsmw/w/includes/specials/SpecialExpandTemplates.php(93): Parser->preprocess(string, Title, ParserOptions)
#8 /var/www/html/sbxsmw/w/includes/specialpage/SpecialPage.php(600): SpecialExpandTemplates->execute(NULL)
#9 /var/www/html/sbxsmw/w/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run(NULL)
#10 /var/www/html/sbxsmw/w/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath(Title, RequestContext)
#11 /var/www/html/sbxsmw/w/includes/MediaWiki.php(940): MediaWiki->performRequest()
#12 /var/www/html/sbxsmw/w/includes/MediaWiki.php(543): MediaWiki->main()
#13 /var/www/html/sbxsmw/w/index.php(53): MediaWiki->run()
#14 /var/www/html/sbxsmw/w/index.php(46): wfIndexMain()
#15 {main}
```

**Comment by JeroenDeDauw** [comment]
Actually not sure it is a Maps issue. Either maps is not extending SMW correctly or there is some more general SMW bug that causes registered resources to not be loaded in certain contexts.

**Comment by Nikerabbit** [comment]
> The pasted link gives me 404
Yeah sorry, I did not remember the DNS is wrong and even then the SSL certificate has expired.

**Comment by Nikerabbit** [comment]
https://sandbox.semantic-mediawiki.net/wiki/Sp%C3%A9cial:ExpansionDesMod%C3%A8les no longer fails with fatal error, so this issue can be reproduced there.

**Comment by JeroenDeDauw** [comment]
huh?

**Comment by Nikerabbit** [comment]
1. Go to https://sandbox.semantic-mediawiki.net/wiki/Sp%C3%A9cial:ExpansionDesMod%C3%A8les
1. Paste the query below and preview
```
{{#ask:[[Geographic location::+]]
 |?Geographic location
 |format=map
 |limit=10
}}
```

Map doesn't load.

**Comment by JeroenDeDauw** [comment]
Confirmed at https://maps.extension.wiki/wiki/Special:ExpandTemplates with

```
{{#ask:[[Coordinates::+]]
 |?Coordinates
 |format=map
 |limit=10
}}
```

**Comment by jaideraf** [comment]
Not tested, but you can try to set [`$smwgEnabledSpecialPage:`](https://www.semantic-mediawiki.org/wiki/Help:$smwgEnabledSpecialPage)

```php
$smwgEnabledSpecialPage = array(
        'ExpandTemplates',
        'RunQuery'
);
```

**Comment by kghbln** [comment]
> Not tested, but you can try to set [$smwgEnabledSpecialPage:](https://www.semantic-mediawiki.org/wiki/Help:$smwgEnabledSpecialPage)

After adding
```php
$smwgEnabledSpecialPage = [
    'Ask',
    'RunQuery',
    'ExpandTemplates'
];
```
the query
```text
{{#ask:
 [[Has coordinates::+]]
 |?Has coordinates
 |format=map
 |limit=10
}}
```
does indeed work on [Special:ExpandTemplates.](https://sandbox.semantic-mediawiki.net/wiki/Sp%C3%A9cial:ExpansionDesMod%C3%A8les)

I have not tested Special:RunQuery, but I see no reason why it should not work, either. Thus, I am closing this. Please reopen in case of continued problems.

@jaideraf, that's a Great comment. I completely forgot about this configuration parameter.

**Comment by JeroenDeDauw** [comment]
@kghbln don't think this should be closed if the behavior is broken unless you add some obscure config. 

Perhaps the default value of `$smwgEnabledSpecialPage` should be changed. It would fix this issue, though there might be a reason those pages are not in the list by default.

**Comment by kghbln** [comment]
SMW should issue some info to point people to this. The default could be extended by ExpandTemplates, but not with RunQuery since the latter must not necessarily be part of the wiki setup.
