### ISSUE TITLE
TypeError from line 75 of "TaskHandlerFactory.php": Argument 2 passed must be of the type integer, string given

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#4897]
### Setup

- MediaWiki | 1.31.10 (e071959)14:26, 15 December 2020
- PHP | 7.2.24-0ubuntu0.18.04.7 (apache2handler)
- Semantic MediaWiki | 3.2.2

### Issue

```
[3e442ea0804f07bc0c7b6ec0] /page/Special:SemanticMediaWiki TypeError from line 75 of /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Admin/TaskHandlerFactory.php: Argument 2 passed to SMW\MediaWiki\Specials\Admin\TaskHandlerFactory::newTaskHandlerRegistry() must be of the type integer, string given, called in /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAdmin.php on line 107
```

### Backtrace
```
#0 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAdmin.php(107): SMW\MediaWiki\Specials\Admin\TaskHandlerFactory->newTaskHandlerRegistry(User, string)
#1 /../w/includes/specialpage/SpecialPage.php(565): SMW\MediaWiki\Specials\SpecialAdmin->execute(NULL)
#2 /../w/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#3 /../w/includes/MediaWiki.php(288): SpecialPageFactory::executePath(Title, RequestContext)
#4 /../w/includes/MediaWiki.php(818): MediaWiki->performRequest()
#5 /../w/includes/MediaWiki.php(524): MediaWiki->main()
#6 /../w/index.php(42): MediaWiki->run()
#7 {main}
```

That's Markus homepage: https://www.korrekt.org/page/Special:SemanticMediaWiki

**Comment by kghbln** [comment]
There is something inheretnly broken here. Special:Version claims SMW 3.2.2 however if I looks as Special:SpecialPages the arrangement is clearly that of SMW 3.1.x. WOW never had something like this before. Both wikis claim SMW 3.2.2 korrekt.o is wrong for whatever reason.

korrekt.o
![grafik](https://user-images.githubusercontent.com/1104078/102277357-7048e800-3f28-11eb-98b4-0450b49f45af.png)

sandbox.s-mw.o
![grafik](https://user-images.githubusercontent.com/1104078/102277419-8eaee380-3f28-11eb-802a-225f4fb8cd00.png)

**Comment by kghbln** [comment]
Ah, this is due to the difference in MW versions. MW 1.31 as opposed to MW 1.35 - so disregard my previous comment.

**Comment by kghbln** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4964
