### ISSUE TITLE
purgeEntitycache.php throws exception on outdated IDs

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#4911]
### Setup

- SMW version: 3.1.6
- MW version:  1.31.12
- PHP version: 7.2.24/7.3
- DB system (MySQL, Blazegraph, etc.) and version:5.5.62

### Issue

running purgeEntitycache.php throws error messages in some SMW installations. This is due to outdated IDs.  In my case, the first ID that was reported was   „_SF_AF“, 
On the Special:Attributes page, I was able to identify _SF_AF has ID: 21.
With the SMW Special page I was able to query for ID 21, witht the result that this ID does not have any active links in the database. It was therfore (I hope) safe, to delete this ID.

After that, the script was able to proceed, but stops at another place:

```
   153496 (43%)[25d9ed97e84bb3bcda6483cd] [no req]   SMW\Exception\PredefinedPropertyLabelMismatchException from line 95 of extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php: There is no predefined property with "_SD_CP".
Backtrace:
#0 extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php(498): SMW\DIProperty->__construct(string, boolean)
#1 extensions/SemanticMediaWiki/maintenance/purgeEntityCache.php(131): SMW\DIProperty::newFromUserLabel(string)
#2 extensions/SemanticMediaWiki/maintenance/purgeEntityCache.php(84): SMW\Maintenance\purgeEntityCache->doPurge(Wikimedia\Rdbms\ResultWrapper)
#3 /maintenance/doMaintenance.php(94): SMW\Maintenance\purgeEntityCache->execute()
#4 /extensions/SemanticMediaWiki/maintenance/purgeEntityCache.php(166): require_once(string)
#5 {main}

```

The problen now is that the SMW special place needs an ID, if I enter "_SD_CP" or before (_SF_AF), nothing will be found. Sinde "_SD_CP" is not in the list of Attributes, I don't know how to find the ID of _SD_CP and thereore cannot remove it.

Thefore I would like to suggest

- SMW Special page should be able to find "_SD_CP" or "_SF_AF", that would help
- purgeEntitycache.php should handle outdated IDs more graceful or provide an --ignore-exceptions option

And I would like to ask which other option I have to find out the ID for _SD_CP when I don't have access to the database...

**Comment by kghbln** [comment]
Thanks for reporting. SF and SD something sound like remnants form Semantic Forms and Semantic Drilldown respectively. :(

**Comment by kghbln** [comment]
On a wiki I have `_SF_AF`, `_SF_DF` and `_SF_PDF` whatever this was in the past.
