### ISSUE TITLE
setupStore.php not enough, update.php needed

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#4916]
### Setup

- SMW version:  3.1.6
- MW version: 1.31.12
- PHP version: 7.2.24 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: MySQL | 5.5.62-log

### Issue

Following the instructions for a complete data rebuild leads to strange error messages that go away if you run update.php. 

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
Follow the instructions: https://www.semantic-mediawiki.org/wiki/Help:Repairing_SMW%27s_data#Rebuilding_everything

setupStore.php seem to run fine both times (first --delete, then without options to set it up new) withoug problems.

After then, when you run rebuildData.php on certain pages, it throws errors like this and stops (ignoring the --ignore-exceptions option)

```
[46b8717b459caf5b2c94ac91] [no req]   Wikimedia\Rdbms\DBTransactionStateError from line 1312 of includes/libs/rdbms/database/Database.php: Cannot execute query from SMW\SQLStore\Rebuilder\Rebuilder::getMaxId while transaction status is ERROR.
Backtrace:
#0 includes/libs/rdbms/database/Database.php(1095): Wikimedia\Rdbms\Database->assertTransactionStatus(string, string)
#1 includes/libs/rdbms/database/Database.php(1653): Wikimedia\Rdbms\Database->query(string, string)
#2 includes/libs/rdbms/database/Database.php(1479): Wikimedia\Rdbms\Database->select(string, string, string, string, array, array)
#3 [internal function]: Wikimedia\Rdbms\Database->selectField(string, string, string, string, array)
#4 includes/libs/rdbms/database/DBConnRef.php(49): call_user_func_array(array, array)
#5 includes/libs/rdbms/database/DBConnRef.php(241): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#6 /extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(625): Wikimedia\Rdbms\DBConnRef->selectField(string, string, string, string, array)
#7 extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(166): SMW\MediaWiki\Connection\Database->selectField(string, string, string, string)
#8 extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(353): SMW\SQLStore\Rebuilder\Rebuilder->getMaxId()
#9 extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(200): SMW\Maintenance\DataRebuilder->rebuild_all()
#10 extensions/SemanticMediaWiki/maintenance/rebuildData.php(202): SMW\Maintenance\DataRebuilder->rebuild()
#11 maintenance/doMaintenance.php(94): SMW\Maintenance\rebuildData->execute()
#12 extensions/SemanticMediaWiki/maintenance/rebuildData.php(261): require_once(string)
#13 {main}
```

You can start the script again at the next item. Sometime it will run, but soon it will stop again.

Next you run update.php, which at the end invokes setupStore.php (as far as I understand this from the output).

After that, rebuildData.php runs smootly without any errors.

So either the documentation is wrong and shoud indicate to run update.php after` setupStore.php --delete` or the setupStore.php alone is missing things that are done correctly when update.php is run.

**Comment by kghbln** [comment]
Thanks for reporting. A weird one, but one cannot beat reality I suppose. :)

**Comment by krabina** [comment]
Yes and one update: while it ran significantly better after running update.php, it was not without errors. Difference is: error every 5-10 IDs before runnding update.php, and maybe 10-20 all in all (with 70.000 ids).

**Comment by gesinn-it** [comment]
@krabina do you see the same issues with a recent version (3.2.2) of SMW?

**Comment by krabina** [comment]
Will try that but just found out that it is even harder to debug. Up to now I thought that if the error occurs, I can reproduce it with -s option and the same ID that threw the error would again trow the error.

But now it seems that this is not happening anymore. So it might be database problem occuring only somtimes.

Leave the question why --ingore-errors does not work and why it is definietly better after running update.php

**Comment by krabina** [comment]
not even a setupStore.php --delete and rebuild everything helps

**Comment by kghbln** [comment]
What we are seeing here is the result of another issue which occurred before this one. The database derailed at some point and all following queries fail as the result. The stack trace reported here is the failure as the result of the original issue. See my comment to issue https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5056#issuecomment-907761523. Same there. This issue #5056 however is about SMW trying to set the property description of arbitrary length defined with special property Property description as the sortkey rather the the property title. This obviously has to fail after a certain length is reached. In my case though MW 1.35 brought the error.
