### ISSUE TITLE
Error when trying to save a new page with 👀 in page name

### ISSUE THREAD

**Issue by kuality** [SemanticMediaWiki/SemanticMediaWiki#4917]
I have successfully made a page called "⏱ Button", but when I try to make a page called "👀 button" I get the following error (site masked). 
[YAnj3a3siTcAABYq5jYAAAAP] /index.php?title=%F0%9F%91%80_button&action=submit Error from line 80 of /xxx/xxx/xxx.xxx.ca/extensions/SemanticMediaWiki/src/MediaWiki/PageInfoProvider.php: Call to a member function getTimestamp() on null

Backtrace:

#0 /xxx/xxx/xxx.xxx.ca/extensions/SemanticMediaWiki/src/Property/Annotators/PredefinedPropertyAnnotator.php(93): SMW\MediaWiki\PageInfoProvider->getCreationDate()
#1 /xxx/xxx/xxx.xxx.ca/extensions/SemanticMediaWiki/src/Property/Annotators/PredefinedPropertyAnnotator.php(70): SMW\Property\Annotators\PredefinedPropertyAnnotator->createDataItemByPropertyId(string)
#2 /xxx/xxx/xxx.xxx.ca/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(62): SMW\Property\Annotators\PredefinedPropertyAnnotator->addPropertyValues()
#3 /xxx/xxx/xxx.xxx.ca/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(61): SMW\Property\Annotators\PropertyAnnotatorDecorator->addAnnotation()
#4 /xxx/xxx/xxx.xxx.ca/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/NewRevisionFromEditComplete.php(157): SMW\Property\Annotators\PropertyAnnotatorDecorator->addAnnotation()
#5 /xxx/xxx/xxx.xxx.ca/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/NewRevisionFromEditComplete.php(101): SMW\MediaWiki\Hooks\NewRevisionFromEditComplete->addPredefinedPropertyAnnotation(SMW\ParserData, NULL)
#6 /xxx/xxx/xxx.xxx.ca/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(624): SMW\MediaWiki\Hooks\NewRevisionFromEditComplete->process(Title)
#7 /xxx/xxx/xxx.xxx.ca/includes/HookContainer/HookContainer.php(320): SMW\MediaWiki\Hooks->onNewRevisionFromEditComplete(WikiPage, Revision, boolean, User, array)
#8 /xxx/xxx/xxx.xxx.ca/includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#9 /xxx/xxx/xxx.xxx.ca/includes/HookContainer/HookRunner.php(2681): MediaWiki\HookContainer\HookContainer->run(string, array)
#10 /xxx/xxx/xxx.xxx.ca/includes/Storage/PageUpdater.php(1246): MediaWiki\HookContainer\HookRunner->onNewRevisionFromEditComplete(WikiPage, Revision, boolean, User, array)
#11 /xxx/xxx/xxx.xxx.ca/includes/Storage/PageUpdater.php(796): MediaWiki\Storage\PageUpdater->doCreate(CommentStoreComment, User, integer)
#12 /xxx/xxx/xxx.xxx.ca/includes/page/WikiPage.php(2015): MediaWiki\Storage\PageUpdater->saveRevision(CommentStoreComment, integer)
#13 /xxx/xxx/xxx.xxx.ca/includes/EditPage.php(2456): WikiPage->doEditContent(WikitextContent, CommentStoreComment, integer, boolean, User, string, array, integer)
#14 /xxx/xxx/xxx.xxx.ca/includes/EditPage.php(1723): EditPage->internalAttemptSave(array, boolean)
#15 /xxx/xxx/xxx.xxx.ca/includes/EditPage.php(680): EditPage->attemptSave(array)
#16 /xxx/xxx/xxx.xxx.ca/includes/actions/EditAction.php(71): EditPage->edit()
#17 /xxx/xxx/xxx.xxx.ca/includes/actions/SubmitAction.php(38): EditAction->show()
#18 /xxx/xxx/xxx.xxx.ca/includes/MediaWiki.php(527): SubmitAction->show()
#19 /xxx/xxx/xxx.xxx.ca/includes/MediaWiki.php(313): MediaWiki->performAction(Article, Title)
#20 /xxx/xxx/xxx.xxx.ca/includes/MediaWiki.php(940): MediaWiki->performRequest()
#21 /xxx/xxx/xxx.xxx.ca/includes/MediaWiki.php(543): MediaWiki->main()
#22 /xxx/xxx/xxx.xxx.ca/index.php(53): MediaWiki->run()
#23 /xxx/xxx/xxx.xxx.ca/index.php(46): wfIndexMain()
#24 {main}

**Comment by JeroenDeDauw** [comment]
```php
throw new AkuckartzException( :eyes: );
```

**Comment by kghbln** [comment]
Works for me: https://sandbox.semantic-mediawiki.org/wiki/Issue/4917_%F0%9F%91%80_button and https://sandbox.semantic-mediawiki.org/wiki/Issue/4917_%E2%8F%B1_button

It may sound repetitive: What versions of MW, SMW, PHP and MySQL are you using. What are the database settings for the MySQL database when it comes to character sets. The letter may be related, may not.

**Comment by kuality** [comment]
> It may sound repetitive: What versions of MW, SMW, PHP and MySQL are you using. 
Sorry, forgot, added that info. 

> Moreover what are the database settings are used for the MySQL database when it comes to character sets. 
Would have never thought to add that, added it as well now. 

>The latter may be related or, may not. If it is a character set issue at the database end SMW should probably fail more gracefully.
It should probably fail more gracefully even if it isn't. ;-) Thanks for all the work and all the fixes!

**Comment by kghbln** [comment]
It appears that this is originating from MySQL: `utf8`/`utf8_general_ci` as opposed to `utf8mb4` [(In MySQL, never use “utf8”. Use “utf8mb4”.)](https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434): _"The “utf8” encoding only supports three bytes per character. The real UTF-8 encoding — which everybody uses, including you — needs up to four bytes per character."_ 👀 has four, ⏱ has three.

I think there could be some code in SMW filtering out this kind of issue more gracefully.

**Comment by kuality** [comment]
The "Server connection collation" in phpMyAdmin General Settings for this wiki's database is "utf8mb4_unicode_ci". Plain "utf8mb4" without a postfix is not an option in that dropdown. Maybe that's not where this is set...

**Comment by kghbln** [comment]
Here communication between the server (set in "my.cnf") and the wiki are at play but also how the tables on the server are set up (the latter is what you fiddled with). See also how you set up `$wgDBTableOptions` i.e. with "utf8" or with "binary" in the beginning. I personally would not fiddle here unless you imperatively need to operate with four bytes per character on a regular basis. In this case it might be even easier to just do a full xml dump of the wikis content and import it in a freshly set up instance (however you loose your users and you still need to check how the mysql server is set up (if you change this you may also affect everything else on the specific server using mysql). It is always a nightmare to get this sorted out. :(

**Comment by kuality** [comment]
I didn't set [$wgDBTableOptions](https://www.mediawiki.org/wiki/Manual:$wgDBTableOptions), so my wiki presumably uses the default. The wiki is over 10 years old so that this default would have changed over time according to the link. The default still isn't utf8mb4*. So, it doesn't seem reasonable to assume people would have it set up that way. Which might just mean trapping the error and giving a meaningful message. 
I was a little puzzled that the error seemed to come from SMW, I would have thought that MW would choke on it first. I just disabled SMW on one of my wikis and was able to create this page (maybe - it gives the page but says no content) but not edit it(?). No debug errors that would explain what's up.
On a newer wiki I was able to create the page even though it doesn't seem to use utf8mb4 either.

**Comment by kghbln** [comment]
SMW-Sandbox currently on:

Product 	Version
[MediaWiki](https://www.mediawiki.org/) 	[1.35.14](https://www.mediawiki.org/wiki/MediaWiki_1.35) [(ef29848)](https://gerrit.wikimedia.org/g/mediawiki/core.git/+/ef298484acd4e6fbbf4043ddb14cf9aa8a7ee262)
[PHP](https://php.net/) 	7.4.33 (apache2handler)
[MariaDB](https://mariadb.org/) 	10.5.23-MariaDB-0+deb11u1
[Semantic MediaWiki](https://www.semantic-mediawiki.org/)	4.1.2 (5c94879) 20:01, 29 July 2023

Rebuilding data stops/halts endlessly without visible errors for pages with this kind of multibyte characters:
* https://sandbox.semantic-mediawiki.net/wiki/%F0%9F%A6%89
* https://sandbox.semantic-mediawiki.net/wiki/%F0%9F%90%9D
* https://sandbox.semantic-mediawiki.net/wiki/Issue/4917_%F0%9F%91%80_button

This did not happen at the time this issue was reported. Interestingly, rebuild data continues for https://sandbox.semantic-mediawiki.net/wiki/Issue/4917_%E2%8F%B1_button.

Anyhow, I will soon upgrade the sandbox and will do another data rebuilding. Let's see how it will go.

**Comment by kghbln** [comment]
Also happening for 

### Setup

- MediaWiki | 1.39.7 (64425c7)16:12, 15 May 2024
- PHP | 7.4.33 (apache2handler)
- MariaDB | 10.5.23-MariaDB-0+deb11u1
- Elasticsearch | 7.10.2
- [Semantic MediaWiki](https://www.semantic-mediawiki.org/)	4.1.3

**Comment by kghbln** [comment]
You could test on a different database with` CHARACTER SET utf8mb4` that collates `COLLATE utf8mb4_unicode_ci`. I closed https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/6147 as invalid since the SQL database was not ready for this kind of character.
