### ISSUE TITLE
rebuildData.php gives error: BIGINT UNSIGNED value is out of range in smw_prop_stats.usage_count

### ISSUE THREAD

**Issue by Malvineous** [SemanticMediaWiki/SemanticMediaWiki#4926]
### Setup

- SMW version: 3.2.2
- MW version: 1.35.1
- PHP version: 7.3
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB 10.3.27

### Issue

I am upgrading SMW from 2.5 to 3.2.2 and upon completion the wiki came up saying I was missing an upgrade key.  I ran `populateHashField.php` which got the wiki going but the SMW elements were blank.  I thought maybe I have to rebuild the data, which I did by running `rebuildData.php` however this fails half way through each time, with or without `--auto-recovery`.

I had already run the usual `maintenance/update.php` so I tried SMW's `setupStore.php` which seemed to output much the same as `update.php` did, all of which completed without any problem.  However I still can't get rebuildData.php to complete and the copy of the wiki I am testing this on still appears to be missing data in the SMW properties.

The message is long and a bit difficult to decipher so I included it all:
```
Rebuilding semantic data ...
   ... selecting 1 to 13793 IDs ...
   ... updating ...                                     1492 / 13798 ( 11%)Wikimedia\Rdbms\DBTransactionStateError from line 1501 of /srv/web/mediawiki/w/includes/libs/rdbms/database/Database.php: Cannot execute query from SMW\SQLStore\PropertyStatisticsStore::setUsageCount while transaction status is ERROR
#0 /srv/web/mediawiki/w/includes/libs/rdbms/database/Database.php(1220): Wikimedia\Rdbms\Database->assertQueryIsCurrentlyAllowed('UPDATE  `smw_pr...', 'SMW\\SQLStore\\Pr...')
#1 /srv/web/mediawiki/w/includes/libs/rdbms/database/Database.php(2457): Wikimedia\Rdbms\Database->query('UPDATE  `smw_pr...', 'SMW\\SQLStore\\Pr...', 128)
#2 /srv/web/mediawiki/w/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->update('`smw_prop_stats...', Array, 'p_id = 13209', 'SMW\\SQLStore\\Pr...', Array)
#3 /srv/web/mediawiki/w/includes/libs/rdbms/database/DBConnRef.php(375): Wikimedia\Rdbms\DBConnRef->__call('update', Array)
#4 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(536): Wikimedia\Rdbms\DBConnRef->update('smw_prop_stats', Array, Array, 'SMW\\SQLStore\\Pr...', Array)
#5 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/PropertyStatisticsStore.php(210): SMW\MediaWiki\Connection\Database->update('smw_prop_stats', Array, Array, 'SMW\\SQLStore\\Pr...')
#6 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/PropertyStatisticsStore.php(118): SMW\SQLStore\PropertyStatisticsStore->setUsageCount(13209, Array)
#7 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/PropertyStatisticsStore.php(164): SMW\SQLStore\PropertyStatisticsStore->addToUsageCount(13209, -1)
#8 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableUpdater.php(97): SMW\SQLStore\PropertyStatisticsStore->addToUsageCounts(Array)
#9 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/SQLStoreUpdater.php(374): SMW\SQLStore\PropertyTableUpdater->update(1493, Object(SMW\Parameters))
#10 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/SQLStoreUpdater.php(226): SMW\SQLStore\SQLStoreUpdater->doFlatDataUpdate(Object(SMW\SemanticData))
#11 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(316): SMW\SQLStore\SQLStoreUpdater->doDataUpdate(Object(SMW\SemanticData))
#12 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/Store.php(234): SMW\SQLStore\SQLStore->doDataUpdate(Object(SMW\SemanticData))
#13 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/DataUpdater.php(415): SMW\Store->updateData(Object(SMW\SemanticData))
#14 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/DataUpdater.php(294): SMW\DataUpdater->updateData()
#15 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/DataUpdater.php(198): SMW\DataUpdater->runUpdate()
#16 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/ParserData.php(454): SMW\DataUpdater->doUpdate()
#17 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(303): SMW\ParserData->updateStore()
#18 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(216): SMW\MediaWiki\Jobs\UpdateJob->updateStore(Object(SMW\ParserData))
#19 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(137): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#20 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#21 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(239): SMW\MediaWiki\Jobs\UpdateJob->run()
#22 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(466): SMW\SQLStore\Rebuilder\Rebuilder->rebuild(1493)
#23 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(383): SMW\Maintenance\DataRebuilder->doUpdateById(1493)
#24 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(222): SMW\Maintenance\DataRebuilder->rebuildAll()
#25 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#26 /srv/web/mediawiki/w/maintenance/doMaintenance.php(107): SMW\Maintenance\rebuildData->execute()
#27 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once('/srv/web/mediaw...')
#28 {main}
Wikimedia\Rdbms\DBQueryError from line 1699 of /srv/web/mediawiki/w/includes/libs/rdbms/database/Database.php: Error 1690: BIGINT UNSIGNED value is out of range in '`keenwiki`.`smw_prop_stats`.`usage_count` - 1' (localhost)
Function: SMW\SQLStore\PropertyStatisticsStore::addToUsageCount
Query: UPDATE  `smw_prop_stats` SET usage_count = usage_count - 1,null_count = null_count - 0 WHERE p_id = 13209

#0 /srv/web/mediawiki/w/includes/libs/rdbms/database/Database.php(1323): Wikimedia\Rdbms\Database->getQueryException('BIGINT UNSIGNED...', 1690, 'UPDATE  `smw_pr...', 'SMW\\SQLStore\\Pr...')
#1 /srv/web/mediawiki/w/includes/libs/rdbms/database/Database.php(1223): Wikimedia\Rdbms\Database->executeQuery('UPDATE  `smw_pr...', 'SMW\\SQLStore\\Pr...', 128)
#2 /srv/web/mediawiki/w/includes/libs/rdbms/database/Database.php(2457): Wikimedia\Rdbms\Database->query('UPDATE  `smw_pr...', 'SMW\\SQLStore\\Pr...', 128)
#3 /srv/web/mediawiki/w/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->update('`smw_prop_stats...', Array, 'p_id = 13209', 'SMW\\SQLStore\\Pr...', Array)
#4 /srv/web/mediawiki/w/includes/libs/rdbms/database/DBConnRef.php(375): Wikimedia\Rdbms\DBConnRef->__call('update', Array)
#5 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(536): Wikimedia\Rdbms\DBConnRef->update('smw_prop_stats', Array, Array, 'SMW\\SQLStore\\Pr...', Array)
#6 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/PropertyStatisticsStore.php(112): SMW\MediaWiki\Connection\Database->update('smw_prop_stats', Array, Array, 'SMW\\SQLStore\\Pr...')
#7 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/PropertyStatisticsStore.php(164): SMW\SQLStore\PropertyStatisticsStore->addToUsageCount(13209, -1)
#8 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableUpdater.php(97): SMW\SQLStore\PropertyStatisticsStore->addToUsageCounts(Array)
#9 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/SQLStoreUpdater.php(374): SMW\SQLStore\PropertyTableUpdater->update(1493, Object(SMW\Parameters))
#10 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/SQLStoreUpdater.php(226): SMW\SQLStore\SQLStoreUpdater->doFlatDataUpdate(Object(SMW\SemanticData))
#11 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(316): SMW\SQLStore\SQLStoreUpdater->doDataUpdate(Object(SMW\SemanticData))
#12 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/Store.php(234): SMW\SQLStore\SQLStore->doDataUpdate(Object(SMW\SemanticData))
#13 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/DataUpdater.php(415): SMW\Store->updateData(Object(SMW\SemanticData))
#14 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/DataUpdater.php(294): SMW\DataUpdater->updateData()
#15 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/DataUpdater.php(198): SMW\DataUpdater->runUpdate()
#16 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/ParserData.php(454): SMW\DataUpdater->doUpdate()
#17 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(303): SMW\ParserData->updateStore()
#18 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(216): SMW\MediaWiki\Jobs\UpdateJob->updateStore(Object(SMW\ParserData))
#19 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(137): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#20 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#21 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(239): SMW\MediaWiki\Jobs\UpdateJob->run()
#22 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(466): SMW\SQLStore\Rebuilder\Rebuilder->rebuild(1493)
#23 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(383): SMW\Maintenance\DataRebuilder->doUpdateById(1493)
#24 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(222): SMW\Maintenance\DataRebuilder->rebuildAll()
#25 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#26 /srv/web/mediawiki/w/maintenance/doMaintenance.php(107): SMW\Maintenance\rebuildData->execute()
#27 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once('/srv/web/mediaw...')
#28 {main}
[52e992da63a5b67df4e6f3f0] [no req]   Wikimedia\Rdbms\DBTransactionError from line 1519 of /srv/web/mediawiki/w/includes/libs/rdbms/database/Database.php: Explicit transaction still active. A caller may have caught an error. Open transactions: sql/transaction/update
Backtrace:
#0 /srv/web/mediawiki/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1642): Wikimedia\Rdbms\Database->assertNoOpenTransactions()
#1 /srv/web/mediawiki/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(2150): Wikimedia\Rdbms\LoadBalancer->Wikimedia\Rdbms\{closure}(Wikimedia\Rdbms\DatabaseMysqli)
#2 /srv/web/mediawiki/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1661): Wikimedia\Rdbms\LoadBalancer->forEachOpenMasterConnection(Closure)
#3 /srv/web/mediawiki/w/includes/libs/rdbms/lbfactory/LBFactory.php(244): Wikimedia\Rdbms\LoadBalancer->approveMasterChanges(array, string, integer)
#4 /srv/web/mediawiki/w/includes/libs/rdbms/lbfactory/LBFactorySimple.php(133): Wikimedia\Rdbms\LBFactory->Wikimedia\Rdbms\{closure}(Wikimedia\Rdbms\LoadBalancer, string, array)
#5 /srv/web/mediawiki/w/includes/libs/rdbms/lbfactory/LBFactory.php(246): Wikimedia\Rdbms\LBFactorySimple->forEachLB(Closure, array)
#6 /srv/web/mediawiki/w/includes/libs/rdbms/lbfactory/LBFactory.php(305): Wikimedia\Rdbms\LBFactory->forEachLBCallMethod(string, array)
#7 /srv/web/mediawiki/w/maintenance/doMaintenance.php(135): Wikimedia\Rdbms\LBFactory->commitMasterChanges(string)
#8 /srv/web/mediawiki/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once(string)
#9 {main}
```

**Comment by akuckartz** [comment]
@Malvineous Did you follow these suggestions? https://www.semantic-mediawiki.org/wiki/Help:Upgrade/Upgrade_from_SMW_2.5_to_SMW_3.0

**Comment by Malvineous** [comment]
I did, but I'm not sure how accurate the steps are because it tells you to run `php extensions/SemanticMediaWiki/maintenance/setupStore.php -v` but when I do that it complains `Unexpected option v!`  I ran it without the `-v` which is where it came up with the same output as the end of `update.php` did, so I think `update.php` runs `setupStore.php` anyway.  That page was where I found to run `populateHashField.php` to fix the update hash error, and everything works up until I get to the `rebuildData.php` step which fails with the above exception.

**Comment by Malvineous** [comment]
I tried altering `extensions/SemanticMediaWiki/src/SQLStore/PropertyStatisticsStore.php` at line 164 where the error was, and added an extra `if` condition around it:
```
+if ($addition > 0) {
     $success = $this->addToUsageCount( $pid, $addition ) && $success;
+}
```
This fixed the error and allowed the process to complete.  Not sure exactly what it has done or the implications of skipping that line for the negative values.

**Comment by cure** [comment]
> I did, but I'm not sure how accurate the steps are because it tells you to run `php extensions/SemanticMediaWiki/maintenance/setupStore.php -v` but when I do that it complains `Unexpected option v!`

I ran into the same problem. Documentation bug?

**Comment by kghbln** [comment]
Indeed, "setupStore.php" does not have a `v` option. Sorry for this. [Amended in the docu.](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AUpgrade%2FUpgrade_from_SMW_2.5_to_SMW_3.0&type=revision&diff=80841&oldid=73414)

**Comment by robis24** [comment]
I had the same error, 
Fixed it by rebuilding everything with running 
`php setupStore.php --delete`

After this, proceed as if re-installing SMW anew by first running
`php setupStore.php`

**Comment by krabina** [comment]
We ran into the same problem and improved the situation by adding the following code in line 110 https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/23b1044854f34f48f393a817fd071819df41d788/src/SQLStore/PropertyStatisticsStore.php#L110
```
                                        'p_id' => $pid,
                                        'usage_count + 10000000' . ( $usageVal > 0 ? '+ ' : '- ' ) . $this->connection->addQuotes( abs( $usageVal ) ) . ' >= 10000000',
                                        'null_count + 10000000' . ( $nullVal > 0 ? '+ ' : '- ' ) . $this->connection->addQuotes( abs( $nullVal ) ) . ' >= 10000000'
```

Maybe someone can test this or come up with an even better solution?

**Comment by kghbln** [comment]
Got this on https://sandbox.semantic-mediawiki.net/wiki/Utilisateur:WinfredGeake28 for the following setup:

Product 	Version
[MediaWiki](https://www.mediawiki.org/) 	[1.35.14](https://www.mediawiki.org/wiki/MediaWiki_1.35) [(ef29848)](https://gerrit.wikimedia.org/g/mediawiki/core.git/+/ef298484acd4e6fbbf4043ddb14cf9aa8a7ee262)
[PHP](https://php.net/) 	7.4.33 (apache2handler)
[MariaDB](https://mariadb.org/) 	10.5.23-MariaDB-0+deb11u1
[Semantic MediaWiki](https://www.semantic-mediawiki.org/)	4.1.2 (5c94879) 20:01, 29 July 2023
