### ISSUE TITLE
Multiple errors in EntityExaminerTask

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#4934]
### Setup

- SMW version: 4.0.0-alpha (fb5a0a8775d69649b0edd667d1c7719a595b22b7)
- MW version: 1.36.0-alpha
- PHP version: 7.3.19-1~deb10u1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.3.27-MariaDB-0+deb10u1

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

```
[2021-02-17T02:59:06.681015+00:00] error.ERROR: [1532c5f5b1359bb8d1738899] /w/api.php   ErrorException: PHP Notice: Undefined index: subject {"exception":"[object] (ErrorException(code: 0): PHP Notice: Undefined index: subject at /srv/mediawiki/tags/2021-02-10_14:54:04/extensions/SemanticMediaWiki/src/MediaWiki/Api/Tasks/EntityExaminerTask.php:65)
[stacktrace]
#0 /srv/mediawiki/tags/2021-02-10_14:54:04/extensions/SemanticMediaWiki/src/MediaWiki/Api/Tasks/EntityExaminerTask.php(65): MWExceptionHandler::handleError(8, 'Undefined index...', '/srv/mediawiki/...', 65, Array)
#1 /srv/mediawiki/tags/2021-02-10_14:54:04/extensions/SemanticMediaWiki/src/MediaWiki/Api/Task.php(62): SMW\\MediaWiki\\Api\\Tasks\\EntityExaminerTask->process(Array)
#2 /srv/mediawiki/tags/2021-02-10_14:54:04/includes/api/ApiMain.php(1612): SMW\\MediaWiki\\Api\\Task->execute()
#3 /srv/mediawiki/tags/2021-02-10_14:54:04/includes/api/ApiMain.php(592): ApiMain->executeAction()
#4 /srv/mediawiki/tags/2021-02-10_14:54:04/includes/api/ApiMain.php(563): ApiMain->executeActionWithErrorHandling()
#5 /srv/mediawiki/tags/2021-02-10_14:54:04/api.php(90): ApiMain->execute()
#6 /srv/mediawiki/tags/2021-02-10_14:54:04/api.php(45): wfApiMain()
#7 {main}
","exception_url":"/w/api.php","reqId":"1532c5f5b1359bb8d1738899","caught_by":"mwe_handler"} []
[17-Feb-2021 02:59:06 UTC] PHP Notice:  Undefined index: subject in /srv/mediawiki/tags/2021-02-10_14:54:04/extensions/SemanticMediaWiki/src/MediaWiki/Api/Tasks/EntityExaminerTask.php on line 65
[2021-02-17T02:59:06.681358+00:00] error.ERROR: [1532c5f5b1359bb8d1738899] /w/api.php   ErrorException: PHP Notice: Undefined index: subject {"exception":"[object] (ErrorException(code: 0): PHP Notice: Undefined i
ndex: subject at /srv/mediawiki/tags/2021-02-10_14:54:04/extensions/SemanticMediaWiki/src/MediaWiki/Api/Tasks/EntityExaminerTask.php:70)
[stacktrace]
#0 /srv/mediawiki/tags/2021-02-10_14:54:04/extensions/SemanticMediaWiki/src/MediaWiki/Api/Tasks/EntityExaminerTask.php(70): MWExceptionHandler::handleError(8, 'Undefined index...', '/srv/mediawiki/...', 70, Array)
#1 /srv/mediawiki/tags/2021-02-10_14:54:04/extensions/SemanticMediaWiki/src/MediaWiki/Api/Task.php(62): SMW\\MediaWiki\\Api\\Tasks\\EntityExaminerTask->process(Array)
#2 /srv/mediawiki/tags/2021-02-10_14:54:04/includes/api/ApiMain.php(1612): SMW\\MediaWiki\\Api\\Task->execute()
#3 /srv/mediawiki/tags/2021-02-10_14:54:04/includes/api/ApiMain.php(592): ApiMain->executeAction()
#4 /srv/mediawiki/tags/2021-02-10_14:54:04/includes/api/ApiMain.php(563): ApiMain->executeActionWithErrorHandling()
#5 /srv/mediawiki/tags/2021-02-10_14:54:04/api.php(90): ApiMain->execute()
#6 /srv/mediawiki/tags/2021-02-10_14:54:04/api.php(45): wfApiMain()
#7 {main}
","exception_url":"/w/api.php","reqId":"1532c5f5b1359bb8d1738899","caught_by":"mwe_handler"} []
[17-Feb-2021 02:59:06 UTC] PHP Notice:  Undefined index: subject in /srv/mediawiki/tags/2021-02-10_14:54:04/extensions/SemanticMediaWiki/src/MediaWiki/Api/Tasks/EntityExaminerTask.php on line 70
[2021-02-17T02:59:06.683238+00:00] exception.ERROR: [1532c5f5b1359bb8d1738899] /w/api.php   SMW\Exception\DataItemDeserializationException: Unserialization failed: the string "" was not understood. {"exception":"[object] (SMW\\Exception\\DataItemDeserializationException(code: 0): Unserialization failed: the string \"\" was not understood. at /srv/mediawiki/tags/2021-02-10_14:54:04/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_WikiPage.php:300)
[stacktrace]
#0 /srv/mediawiki/tags/2021-02-10_14:54:04/extensions/SemanticMediaWiki/src/MediaWiki/Api/Tasks/EntityExaminerTask.php(70): SMW\\DIWikiPage::doUnserialize(NULL)
#1 /srv/mediawiki/tags/2021-02-10_14:54:04/extensions/SemanticMediaWiki/src/MediaWiki/Api/Task.php(62): SMW\\MediaWiki\\Api\\Tasks\\EntityExaminerTask->process(Array)
#2 /srv/mediawiki/tags/2021-02-10_14:54:04/includes/api/ApiMain.php(1612): SMW\\MediaWiki\\Api\\Task->execute()
#3 /srv/mediawiki/tags/2021-02-10_14:54:04/includes/api/ApiMain.php(592): ApiMain->executeAction()
#4 /srv/mediawiki/tags/2021-02-10_14:54:04/includes/api/ApiMain.php(563): ApiMain->executeActionWithErrorHandling()
#5 /srv/mediawiki/tags/2021-02-10_14:54:04/api.php(90): ApiMain->execute()
#6 /srv/mediawiki/tags/2021-02-10_14:54:04/api.php(45): wfApiMain()
#7 {main}
","exception_url":"/w/api.php","reqId":"1532c5f5b1359bb8d1738899","caught_by":"entrypoint"} []

```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

Not known. This is an API request so if it is a POST it is impossible to know the parameters with normal debugging.

Do note that this is similar but not the same as e.g. #4849

**Comment by JeroenDeDauw** [comment]
I wonder if there is a way to just turn off the entire entity examinations stuff if you don't need it.

**Comment by kghbln** [comment]
I guess the smwtask module is involved. I do not think that one would like not to have [entity examinations](https://www.semantic-mediawiki.org/wiki/Help:Entity_examinations)
