### ISSUE TITLE
Unit tests fail to work because smw_ft_search cannot be re-created fulltext on temp table

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticMediaWiki#4946]
### Setup

- SMW version: 3.2.2
- MW version: 1.34
- PHP version: 7.3
- DB system and version: percona 5.7

### Issue

Attempting to run the unit tests in MediaWiki results in an error:

```
$ php7.3 phpunit.php --testdox wiki includes/config/ConfigFactoryTest.php
Using PHP 7.3.19-1~deb10u1
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Wikimedia\Rdbms\DBQueryError from line 1603 of .../mediawiki/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: CREATE TEMPORARY  TABLE `unittest_smw_ft_search` (LIKE `wiki1smw_ft_search`)
Function: Wikimedia\Rdbms\DatabaseMysqlBase::duplicateTableStructure
Error: 1796 Cannot create FULLTEXT index on temporary InnoDB table (127.0.0.1:3307)

#0 .../mediawiki/includes/libs/rdbms/database/Database.php(1574): Wikimedia\Rdbms\Database->getQueryExceptionAndLog('Cannot create F...', 1796, 'CREATE TEMPORAR...', 'Wikimedia\\Rdbms...')
#1 .../mediawiki/includes/libs/rdbms/database/Database.php(1152): Wikimedia\Rdbms\Database->reportQueryError('Cannot create F...', 1796, 'CREATE TEMPORAR...', 'Wikimedia\\Rdbms...', false)
#2 .../mediawiki/includes/libs/rdbms/database/DatabaseMysqlBase.php(1419): Wikimedia\Rdbms\Database->query('CREATE TEMPORAR...', 'Wikimedia\\Rdbms...', 2)
#3 .../mediawiki/includes/db/CloneDatabase.php(110): Wikimedia\Rdbms\DatabaseMysqlBase->duplicateTableStructure('`wiki1smw_ft_se...', '`unittest_smw_f...', true)
#4 .../mediawiki/tests/phpunit/MediaWikiIntegrationTestCase.php(1463): CloneDatabase->cloneTableStructure()
#5 .../mediawiki/tests/phpunit/MediaWikiIntegrationTestCase.php(1533): MediaWikiIntegrationTestCase::setupDatabaseWithTestPrefix(Object(MediaWiki\Extension\PerconaDB\Database), 'unittest_')
#6 .../mediawiki/tests/phpunit/MediaWikiIntegrationTestCase.php(1486): MediaWikiIntegrationTestCase::setupTestDB(Object(MediaWiki\Extension\PerconaDB\Database), 'unittest_')
#7 .../mediawiki/tests/phpunit/MediaWikiIntegrationTestCase.php(438): MediaWikiIntegrationTestCase->setupAllTestDBs()
#8 .../mediawiki/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): MediaWikiIntegrationTestCase->run(Object(MediaWikiTestResult))
#9 .../mediawiki/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(545): PHPUnit\Framework\TestSuite->run(Object(MediaWikiTestResult))
#10 .../mediawiki/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#11 .../mediawiki/tests/phpunit/phpunit.php(97): PHPUnit\TextUI\Command->run(Array, true)
#12 .../mediawiki/maintenance/doMaintenance.php(99): PHPUnitMaintClass->execute()
#13 .../mediawiki/tests/phpunit/phpunit.php(136): require('/home/mah/clien...')
#14 {main}
PHP Fatal error:  Uncaught UnexpectedValueException: Got connection to 'wiki_d-unittest_', but expected local domain ('wiki_d-wiki1') in .../mediawiki/includes/libs/rdbms/loadbalancer/LoadBalancer.php:1113
Stack trace:
#0 .../mediawiki/includes/libs/rdbms/loadbalancer/LoadBalancer.php(926): Wikimedia\Rdbms\LoadBalancer->getLocalConnection(0, 4)
#1 .../mediawiki/includes/libs/rdbms/loadbalancer/LoadBalancer.php(898): Wikimedia\Rdbms\LoadBalancer->getServerConnection(0, 'wiki_d-wiki1', 4)
#2 .../mediawiki/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1043): Wikimedia\Rdbms\LoadBalancer->getConnection(-2, Array, 'wiki_d-wiki1', 4)
#3 .../mediawiki/includes/GlobalFunctions.php(2575): Wikimedia\Rdbms\LoadBalancer->getMaintenanceConnectionRef(-2, Array, 'wiki_d-wiki1')
#4 .../conf/extensions/AbuseFilter/includes/AbuseFilterHooks.php(1112): wfGetDB(-2)
#5 .../media in .../mediawiki/includes/libs/rdbms/loadbalancer/LoadBalancer.php on line 1113
PHP Stack trace:
PHP   1. {main}() .../mediawiki/tests/phpunit/phpunit.php:0
PHP   2. require() .../mediawiki/tests/phpunit/phpunit.php:136
```

**Comment by hexmode** [comment]
Seems to be percona related since switching to mysql does not show the issue.

**Comment by jaideraf** [comment]
> Nevermind...

So I am closing it.
