### ISSUE TITLE
PHP Deprecated: Use of Revision::getId/getUser was deprecated in MediaWiki 1.31. [Called from SMW\DataUpdater::addAnnotations

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#4980]
### Setup

- SMW version: 4.0.0-alpha (6b0280b)
- MW version: 1.37.0-alpha (f005492)
- PHP version: 7.3.27-1~deb10u1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.3.27-MariaDB-0+deb10u1

### Issue

This issue is frequent and spams the error log.

Suggested replacement: "use RevisionRecord, RevisionStore, and BlobStore instead."

```
#0 [internal function]: MWExceptionHandler::handleError(16384, 'Use of Revision...', '/srv/mediawiki/...', '324', Array)
#1 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/debug/MWDebug.php(376): trigger_error('Use of Revision...', 16384)
#2 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/debug/MWDebug.php(350): MWDebug::sendRawDeprecated('Use of Revision...', true, 'SMW\\\\DataUpdater...')
#3 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/debug/MWDebug.php(230): MWDebug::deprecatedMsg('Use of Revision...', '1.31', 'MediaWiki', 4)
#4 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/GlobalFunctions.php(1036): MWDebug::deprecated('Revision::getId', '1.31', 'MediaWiki', 3)
#5 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/Revision.php(451): wfDeprecated('Revision::getId', '1.31')
#6 /srv/mediawiki/tags/2021-04-21_08:43:17/extensions/SemanticMediaWiki/src/DataUpdater.php(324): Revision->getId()
#7 /srv/mediawiki/tags/2021-04-21_08:43:17/extensions/SemanticMediaWiki/src/DataUpdater.php(284): SMW\\DataUpdater->addAnnotations(Object(Title), Object(WikiPage), Object(Revision), Object(User))
#8 /srv/mediawiki/tags/2021-04-21_08:43:17/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(348): SMW\\DataUpdater->runUpdate()
#9 /srv/mediawiki/tags/2021-04-21_08:43:17/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(323): SMW\\MediaWiki\\Deferred\\CallableUpdate->runUpdate()
#10 /srv/mediawiki/tags/2021-04-21_08:43:17/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(244): SMW\\MediaWiki\\Deferred\\CallableUpdate->attemptUpdate()
#11 /srv/mediawiki/tags/2021-04-21_08:43:17/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/TransactionalCallableUpdate.php(168): SMW\\MediaWiki\\Deferred\\CallableUpdate->doUpdate()
#12 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/deferred/DeferredUpdates.php(513): SMW\\MediaWiki\\Deferred\\TransactionalCallableUpdate->doUpdate()
#13 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/deferred/DeferredUpdates.php(390): DeferredUpdates::attemptUpdate(Object(SMW\\MediaWiki\\Deferred\\TransactionalCallableUpdate), Object(Wikimedia\\Rdbms\\LBFactorySimple))
#14 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/deferred/DeferredUpdates.php(221): DeferredUpdates::run(Object(SMW\\MediaWiki\\Deferred\\TransactionalCallableUpdate), Object(Wikimedia\\Rdbms\\LBFactorySimple), Object(Monolog\\Logger), Object(BufferingStatsdDataFactory), 'get')
#15 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/deferred/DeferredUpdatesScope.php(267): DeferredUpdates::{closure}(Object(SMW\\MediaWiki\\Deferred\\TransactionalCallableUpdate), 2)
#16 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/deferred/DeferredUpdatesScope.php(196): DeferredUpdatesScope->processStageQueue(2, 2, Object(Closure))
#17 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/deferred/DeferredUpdates.php(242): DeferredUpdatesScope->processUpdates(0, Object(Closure))
#18 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/MediaWiki.php(1132): DeferredUpdates::doUpdates('run')
#19 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/MediaWiki.php(837): MediaWiki->restInPeace()
#20 /srv/mediawiki/tags/2021-04-21_08:43:17/includes/MediaWiki.php(575): MediaWiki->doPostOutputShutdown()
#21 /srv/mediawiki/tags/2021-04-21_08:43:17/index.php(53): MediaWiki->run()
#22 /srv/mediawiki/tags/2021-04-21_08:43:17/index.php(46): wfIndexMain()
#23 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

Check your logs and ensure deprecation warnings are enabled by setting $wgDevelopmentWarnings = true;

**Comment by Abijeet** [comment]
This was fixed in: #5046 and 4e0aed2f8084b71442e94c05598c8f71cfb922f0
