### ISSUE TITLE
Exception on rebuildElasticIndex.php

### ISSUE THREAD

**Issue by Seb35** [SemanticMediaWiki/SemanticMediaWiki#4990]
### Setup

- SMW version: 3.1.3
- MW version: 1.33
- PHP version: 7.3.23
- DB version: MariaDB 10.2.36
- Elasticsearch version: 6.5.4

### Issue

When I setup Elasticsearch as query store as documented on [ElasticStore](https://www.semantic-mediawiki.org/wiki/Help:ElasticStore) and execute `extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php`, I obtain the following exception:
```
Rebuilding indices ...
   ... creating required indices and aliases ...
   ... updating document                           100% (8471606/8471622)
   ... updating settings and mappings ...
   ... *data* index ... [dd116763e3bb38c2e12ebf64] [no req]   Elasticsearch\Common\Exceptions\NoNodesAvailableException from line 53 of /tmp/mediawiki/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php: No alive nodes found in your cluster
Backtrace:
#0 /tmp/mediawiki/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(78): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection()
#1 /tmp/mediawiki/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(96): Elasticsearch\Transport->getConnection()
#2 /tmp/mediawiki/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/BooleanRequestWrapper.php(40): Elasticsearch\Transport->performRequest(string, string, array, NULL, array)
#3 /tmp/mediawiki/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(40): Elasticsearch\Namespaces\BooleanRequestWrapper::performRequest(Elasticsearch\Endpoints\Indices\Exists, Elasticsearch\Transport)
#4 /tmp/mediawiki/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rollover.php(56): Elasticsearch\Namespaces\IndicesNamespace->exists(array)
#5 /tmp/mediawiki/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rebuilder.php(446): SMW\Elastic\Indexer\Rollover->rollover(string, string)
#6 /tmp/mediawiki/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rebuilder.php(363): SMW\Elastic\Indexer\Rebuilder->rolloverByTypeAndVersion(string, string)
#7 /tmp/mediawiki/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rebuilder.php(214): SMW\Elastic\Indexer\Rebuilder->setDefaultByType(string)
#8 /tmp/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(338): SMW\Elastic\Indexer\Rebuilder->setDefaults()
#9 /tmp/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(163): SMW\Maintenance\RebuildElasticIndex->rebuild()
#10 /tmp/mediawiki/maintenance/doMaintenance.php(96): SMW\Maintenance\RebuildElasticIndex->execute()
#11 /tmp/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(437): require_once(string)
#12 {main}
```

It should be noted that the step `updating document` took about 10-15 hours.

The exact configuration is:
```php
$GLOBALS['smwgDefaultStore'] = 'SMWElasticStore';
$GLOBALS['smwgElasticsearchEndpoints'] = [ [ 'host' => 'search.internal', 'port' => 9200, 'scheme' => 'http' ] ];
```

BTW: I had an error sooner if $smwgElasticsearchEndpoints was only a dictionary instead of a list of dictionaries, I will double-check the logic about this configuration parameter and will perhaps open an issue about this.

**Comment by Seb35** [comment]
A work hypothesis is that the failing step uses a connection from the ConnectionPool initialized at the beginning of the script and this connection was dropped the many hours later.

**Comment by jaideraf** [comment]
I don't know PHP, but my configuration syntax in LocalSettings.php is a little bit different:

```php
$smwgDefaultStore = 'SMWElasticStore';
$smwgElasticsearchEndpoints = [ 'localhost:9200' ];
```

**Comment by Seb35** [comment]
Thanks @jaideraf, I was able to setup ElasticStore without issue on a small wiki with this configuration, but the error still occur on the bigger wiki with your configuration (I added [a pair of parenthesis in the official doc](https://www.semantic-mediawiki.org/wiki/Help:$smwgElasticsearchEndpoints)).

I’m enclined to think there are connections initialized at the beginning of the script, and these connections timed out after the long step "updating document". I didn’t dive very deep in the ConnectionManager for now, but I will investigate about the retry mechnism since there is [such parameter](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3054/files#diff-acad302d75c387b0b35e25566662337ad4939dc0f5f67c93a391d6dcf32978c7R1943).

**Comment by Seb35** [comment]
I am retrying using a different, [more reliable](https://github.com/elastic/elasticsearch-php/blob/master/docs/connection-pool.asciidoc), ConnectionPool: StaticConnectionPool instead of StaticNoPingConnectionPool. I did so by directly modifying SMW (I didn’t see a parameter for that) in the file `src/Elastic/Connection/ConnectionProvider.php`:
```diff
diff --git a/src/Elastic/Connection/ConnectionProvider.php b/src/Elastic/Connection/ConnectionProvider.php
index cd84d33407cf..bb1aeba1d7be 100644
--- a/src/Elastic/Connection/ConnectionProvider.php
+++ b/src/Elastic/Connection/ConnectionProvider.php
@@ -79,6 +79,7 @@ class ConnectionProvider implements IConnectionProvider {
                                // controls the original connection timeout duration
                                'connect_timeout' => $this->options->dotGet( 'connection.connect_timeout', 30 )
                        ]
+                       'connectionPool' => '\Elasticsearch\ConnectionPool\StaticConnectionPool',
 
                        // Use `singleHandler` if you know you will never need async capabilities,
                        // since it will save a small amount of overhead by reducing indirection
```

Also, if I’m not mistaken, the `client` array passed to Elasticsearch\ClientBuilder::fromParams() must be wrapped in a `connectionParams` array to be effective + I added a key `'never_retry' => false` (see [code of Elasticsearch\Connections\Connection](https://github.com/elastic/elasticsearch-php/blob/9ba89f905ebf699e72dacffa410331c7fecc8255/src/Elasticsearch/Connections/Connection.php#L251-L252)) (else the default timeout in Elasticsearch library is 1 second without retry):
```diff
diff --git a/src/Elastic/Connection/ConnectionProvider.php b/src/Elastic/Connection/ConnectionProvider.php
index bb1aeba1d7be..fd998cf37653 100644
--- a/src/Elastic/Connection/ConnectionProvider.php
+++ b/src/Elastic/Connection/ConnectionProvider.php
@@ -71,14 +71,18 @@ class ConnectionProvider implements IConnectionProvider {
                        'hosts' => $endpoints,
                        'retries' => $this->options->dotGet( 'connection.retries', 1 ),
 
-                       'client' => [
-
-                               // controls the request timeout
-                               'timeout' => $this->options->dotGet( 'connection.timeout', 30 ),
-
-                               // controls the original connection timeout duration
-                               'connect_timeout' => $this->options->dotGet( 'connection.connect_timeout', 30 )
-                       ]
+                       'connectionParams' => [
+                               'client' => [
+
+                                       // controls the request timeout
+                                       'timeout' => $this->options->dotGet( 'connection.timeout', 30 ),
+
+                                       // controls the original connection timeout duration
+                                       'connect_timeout' => $this->options->dotGet( 'connection.connect_timeout', 30 ),
+                                       'never_retry' => false,
+                               ],
+                       ],
                        'connectionPool' => '\Elasticsearch\ConnectionPool\StaticConnectionPool',
 
                        // Use `singleHandler` if you know you will never need async capabilities,
```

I am waiting the result, will report here. When it will work, I will write a few PR.

**Comment by Seb35** [comment]
Update: it fails even with StaticConnectionPool, and I retried on a standalone server (instead of the managed infrastructure) with the same versions and with the Elasticsearch on localhost and it works (it was longer (23h) since it was a cheap server).

Consequently the core issue is somewhere between the server executing the PHP and the Elasticsearch server, and is more probably an operational issue and not a SMW issue, even if it would be better to improve a bit SMW around ElasticStore as said above.

**Comment by Seb35** [comment]
It finally worked: the main issue was that **the Elasticsearch server (v6.5.4) was not powerful enough**.

After some time ingesting data, ES does some internal stuff (merging Lucene segments if I understand correctly, and/or GC operations) and refuses connections during this time. But rebuildElasticIndex.php skips semantic objects when ES refuses the connection, so these semantic objects are not indexed (imho it is an issue: the script should stop in this case to restart from this object).

The original issue (NoNodesAvailableException at the end) is probably because ES is very busy at the end of the script and the requested operation (closing the index) is probably very resource-consuming, so ES fails to answer before the timeout.

----

At the end, I have the following remarks/propositions of change in the code:
1. [bug] the second patch [above](#issuecomment-851589670),
2. but, to take into account the first patch [above](#issuecomment-851589670), I propose to let the sysadmin free of specifying the array 'connection' in `$smwgElasticsearchConfig` mainly used in [ConnectionProvider](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/3.0.x/src/Elastic/Connection/ConnectionProvider.php#L64-L87), possibly with some forced parameters like the hosts, so that s/he can specify the connectionPool, the handler, etc.
3. I remarked SMW\Elastic\Connection\Client::ping() puts in some cache the first ping to ES: it is an expected behaviour for most Web requests (lasting at most a few seconds), but it should be retried every minute or so for long-running scripts (I say that, but I’m not sure where this specific method is used, given there are other "ping()" functions in the underlying library, it is a bit difficult to follow)
4. during indexing, retry harder when ES refuses the connection or returns a 500 error (it happened a few times); perhaps a parameter could be added to wait X seconds before retrying Y times in these cases (currently the retries are immediately after the first fail), or another parameter to stop the script instead of skipping the semantic object.

----

Also, a possible warning in the documentation: on a wiki where CirrusSearch is installed, there could be twice the [elasticsearch/elasticsearch library](https://packagist.org/packages/elasticsearch/elasticsearch), possibly in different versions (one copy in `extensions/Elastica/vendor` and one copy in the global `vendor`); it was the case on the specific wiki. I’m not sure if it could lead to issues, but it not a sane situation.

The better situation would be to use the version in the "global vendor", probably by specifying the "extensions/Elastica/composer.json" in the global "composer.local.json" (and removing the slightly-forked version 6.0.1 in Elastica <= REL1_33, see [its composer.json](https://github.com/wikimedia/mediawiki-extensions-Elastica/blob/REL1_33/composer.json)) – it is what I did given the wiki is currently in 1.33.

I’m not sure if/how it should be documented; it is probably not an issue for most users, although it could be a difficult one if it occurs.

**Comment by jaideraf** [comment]
@Seb35 Did you get Elasticsearch 6.8.18 (the last one of the 6.x series), MW 1.35.3 (the last LTS) and SMW master working together? I could not make it to work. I know you are experimenting Elasticsearch so I wonder if you could help me with it. The `setupStore.php` just don't work after I change to `$smwgDefaultStore = 'SMWElasticStore';`

**Comment by Seb35** [comment]
> @Seb35 Did you get Elasticsearch 6.8.18 (the last one of the 6.x series), MW 1.35.3 (the last LTS) and SMW master working together? I could not make it to work.
@jaideraf No, I did not try for now, I stay conservative with Wikimedia for the CirrusSearch extension. I guess you can open an issue about the problems you experiences, the recent versions of Elasticsearch should be tested anyway.
