### ISSUE TITLE
Error 1406: Data too long for column 'smw_sortkey' at row 1 (localhost)

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#5056]
### Setup

Software | Version
-- | --
MediaWiki | 1.35.3 (aeda3d3)20. Aug. 2021, 07:01
PHP | 7.3.29-1~deb10u1 (apache2handler)
MariaDB | 10.3.29-MariaDB-0+deb10u1
ICU | 63.1
Semantic MediaWiki | 3.2.3

### Issue
This issue only started after upgrading MediaWiki 1.31.x to MediaWiki 1.35.x leaving Semantic MediaWiki untouched at 3.2.3.

When running ```php rebuildData.php -v --shallow-update --ignore-exceptions --with-maintenance-log --exception-log=/var/tmp/``` I get the following database error:

**Property:** P_Hat_QID-Kennung
**Error 1406:** ```Data too long for column 'smw_sortkey' at row 1 (localhost)```
**Function:** ```SMW\SQLStore\TableFieldUpdater::updateSortField```
**Query:** ```UPDATE  `smw_object_ids` SET smw_sortkey = 'P Hat QID-Kennung#Speichert die QID-Kennung zu einer Person, die auf einen Eintrag einer Person bei [[wikipedia:de:Wikidata|Wikidata]] verweist. Muster und Formatierungsanweisung entsprechen den Angaben zu Wikidata-Attribut [[wd:Property:P6307|„QID”]].;d',smw_sort = 'P Hat QID-Kennung#Speichert die QID-Kennung zu einer Person, die auf einen Eintrag einer Person bei [[wikipedia:de:Wikidata|Wikidata]] verweist. Muster und Formatierungsanweisung entsprechen den Angaben zu Wikidata-Attribut [[wd:Property:P6307|„QID”]].;d',smw_touched = '20210828141440' WHERE smw_id = 25472```

For all other properties I get ```Cannot execute query from MediaWiki\Revision\RevisionStore::fetchRevisionRowFromConds while transaction status is ERROR``` due to the preceding database error.

### Stack trace
```
#0 /../w/includes/libs/rdbms/database/Database.php(1683): Wikimedia\Rdbms\Database->getQueryException('Data too long f...', 1406, 'UPDATE  `smw_ob...', 'SMW\\SQLStore\\Ta...')
#1 /../w/includes/libs/rdbms/database/Database.php(1658): Wikimedia\Rdbms\Database->getQueryExceptionAndLog('Data too long f...', 1406, 'UPDATE  `smw_ob...', 'SMW\\SQLStore\\Ta...')
#2 /../w/includes/libs/rdbms/database/Database.php(1227): Wikimedia\Rdbms\Database->reportQueryError('Data too long f...', 1406, 'UPDATE  `smw_ob...', 'SMW\\SQLStore\\Ta...', false)
#3 /../w/includes/libs/rdbms/database/Database.php(2457): Wikimedia\Rdbms\Database->query('UPDATE  `smw_ob...', 'SMW\\SQLStore\\Ta...', 128)
#4 /../w/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->update('`smw_object_ids...', Array, 'smw_id = 25472', 'SMW\\SQLStore\\Ta...', Array)
#5 /../w/includes/libs/rdbms/database/DBConnRef.php(375): Wikimedia\Rdbms\DBConnRef->__call('update', Array)
#6 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(536): Wikimedia\Rdbms\DBConnRef->update('smw_object_ids', Array, Array, 'SMW\\SQLStore\\Ta...', Array)
#7 /../w/extensions/SemanticMediaWiki/src/SQLStore/TableFieldUpdater.php(85): SMW\MediaWiki\Connection\Database->update('smw_object_ids', Array, Array, 'SMW\\SQLStore\\Ta...')
#8 /../w/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityIdManager.php(696): SMW\SQLStore\TableFieldUpdater->updateSortField(25472, 'P Hat QID-Kennu...')
#9 /../w/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityIdManager.php(611): SMW\SQLStore\EntityStore\EntityIdManager->makeDatabaseId('P_Hat_QID-Kennu...', 102, '', '_ML34f43a3437fc...', true, 'P Hat QID-Kennu...', true)
#10 /../w/extensions/SemanticMediaWiki/src/SQLStore/SQLStoreUpdater.php(335): SMW\SQLStore\EntityStore\EntityIdManager->makeSMWPageID('P_Hat_QID-Kennu...', 102, '', '_ML34f43a3437fc...', true, 'P Hat QID-Kennu...', true)
#11 /../w/extensions/SemanticMediaWiki/src/SQLStore/SQLStoreUpdater.php(242): SMW\SQLStore\SQLStoreUpdater->doFlatDataUpdate(Object(SMW\DataModel\ContainerSemanticData))
#12 /../w/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(316): SMW\SQLStore\SQLStoreUpdater->doDataUpdate(Object(SMW\SemanticData))
#13 /../w/extensions/SemanticMediaWiki/src/Store.php(234): SMW\SQLStore\SQLStore->doDataUpdate(Object(SMW\SemanticData))
#14 /../w/extensions/SemanticMediaWiki/src/DataUpdater.php(415): SMW\Store->updateData(Object(SMW\SemanticData))
#15 /../w/extensions/SemanticMediaWiki/src/DataUpdater.php(294): SMW\DataUpdater->updateData()
#16 /../w/extensions/SemanticMediaWiki/src/DataUpdater.php(198): SMW\DataUpdater->runUpdate()
#17 /../w/extensions/SemanticMediaWiki/src/ParserData.php(454): SMW\DataUpdater->doUpdate()
#18 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(303): SMW\ParserData->updateStore()
#19 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(216): SMW\MediaWiki\Jobs\UpdateJob->updateStore(Object(SMW\ParserData))
#20 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(137): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#21 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#22 /../w/extensions/SemanticMediaWiki/src/Maintenance/DistinctEntityDataRebuilder.php(197): SMW\MediaWiki\Jobs\UpdateJob->run()
#23 /../w/extensions/SemanticMediaWiki/src/Maintenance/DistinctEntityDataRebuilder.php(170): SMW\Maintenance\DistinctEntityDataRebuilder->doUpdate(Object(SMW\MediaWiki\JobFactory), Object(Title))
#24 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(267): SMW\Maintenance\DistinctEntityDataRebuilder->doRebuild()
#25 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(318): SMW\Maintenance\DataRebuilder->rebuildFromSelection(Array)
#26 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(222): SMW\Maintenance\DataRebuilder->rebuildAll()
#27 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#28 /../w/maintenance/doMaintenance.php(107): SMW\Maintenance\rebuildData->execute()
#29 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once('/var/www/htdocs...')
#30 {main}
```

### Comment
What wonders me is why Semantic MediaWiki all of a sudden thinks that the property description I additionally set with a user defined property of type Multilingual text should be used as the sortkey? MediaWiki still believes that the sortkey equals the page name.

**Comment by kghbln** [comment]
This is another one resulting from this error:

```
   ... updating 12603     [S: Datei:002_Bau_Drei_Linden_Mai_1974.jpg]
Wikimedia\Rdbms\DBTransactionStateError from line 1501 of /../w/includes/libs/rdbms/database/Database.php: Cannot execute query from SMW\SQLStore\Rebuilder\Rebuilder::getMaxId while transaction status is ERROR
#0 /../w/includes/libs/rdbms/database/Database.php(1220): Wikimedia\Rdbms\Database->assertQueryIsCurrentlyAllowed('SELECT  MAX(pag...', 'SMW\\SQLStore\\Re...')
#1 /../w/includes/libs/rdbms/database/Database.php(1907): Wikimedia\Rdbms\Database->query('SELECT  MAX(pag...', 'SMW\\SQLStore\\Re...', 32)
#2 /../w/includes/libs/rdbms/database/Database.php(1746): Wikimedia\Rdbms\Database->select('page', 'MAX(page_id)', '', 'SMW\\SQLStore\\Re...', Array, Array)
#3 /../w/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->selectField('page', 'MAX(page_id)', '', 'SMW\\SQLStore\\Re...', Array)
#4 /../w/includes/libs/rdbms/database/DBConnRef.php(300): Wikimedia\Rdbms\DBConnRef->__call('selectField', Array)
#5 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(634): Wikimedia\Rdbms\DBConnRef->selectField('page', 'MAX(page_id)', '', 'SMW\\SQLStore\\Re...', Array)
#6 /../w/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(168): SMW\MediaWiki\Connection\Database->selectField('page', 'MAX(page_id)', '', 'SMW\\SQLStore\\Re...')
#7 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(388): SMW\SQLStore\Rebuilder\Rebuilder->getMaxId()
#8 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(222): SMW\Maintenance\DataRebuilder->rebuildAll()
#9 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#10 /../w/maintenance/doMaintenance.php(107): SMW\Maintenance\rebuildData->execute()
#11 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once('/var/www/htdocs...')
#12 {main}
```
Wikimedia\Rdbms\DBQueryError from line 16```9 of /../w/includes/libs/rdbms/database/Database.php: Error 1406: Data too long for column 'smw_sortkey' at row 1 (localhost)```
**Function:** SMW\SQLStore\TableFieldUpdater::updateSortField
**Query:** ```UPDATE  `smw_object_ids` SET smw_sortkey = 'Audio#Dieses Widget ermöglicht das Einbinden einer bei \'\'\'[https://github.com/etianen/html5media HTML5-Audiodatei]\'\'\'. Es wurde von [https://www.wikihoster.net Karsten Hoffmeyer] erstellt. Das Einbinden erfolgt mit Hilfe der [[Vorlage:Audio|Vorlage „Audi',smw_sort = 'Audio#Dieses Widget ermöglicht das Einbinden einer bei \'\'\'[https://github.com/etianen/html5media HTML5-Audiodatei]\'\'\'. Es wurde von [https://www.wikihoster.net Karsten Hoffmeyer] erstellt. Das Einbinden erfolgt mit Hilfe der [[Vorlage:Audio|Vorlage „Audi',smw_touched = '20210828092514' WHERE smw_id = 17793```

#### Backtrace
```
#0 /../w/includes/libs/rdbms/database/Database.php(1323): Wikimedia\Rdbms\Database->getQueryException('Data too long f...', 1406, 'UPDATE  `smw_ob...', 'SMW\\SQLStore\\Ta...')
#1 /../w/includes/libs/rdbms/database/Database.php(1223): Wikimedia\Rdbms\Database->executeQuery('UPDATE  `smw_ob...', 'SMW\\SQLStore\\Ta...', 128)
#2 /../w/includes/libs/rdbms/database/Database.php(2457): Wikimedia\Rdbms\Database->query('UPDATE  `smw_ob...', 'SMW\\SQLStore\\Ta...', 128)
#3 /../w/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->update('`smw_object_ids...', Array, 'smw_id = 17793', 'SMW\\SQLStore\\Ta...', Array)
#4 /../w/includes/libs/rdbms/database/DBConnRef.php(375): Wikimedia\Rdbms\DBConnRef->__call('update', Array)
#5 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(536): Wikimedia\Rdbms\DBConnRef->update('smw_object_ids', Array, Array, 'SMW\\SQLStore\\Ta...', Array)
#6 /../w/extensions/SemanticMediaWiki/src/SQLStore/TableFieldUpdater.php(85): SMW\MediaWiki\Connection\Database->update('smw_object_ids', Array, Array, 'SMW\\SQLStore\\Ta...')
#7 /../w/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityIdManager.php(696): SMW\SQLStore\TableFieldUpdater->updateSortField(17793, 'Audio#Dieses Wi...')
#8 /../w/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityIdManager.php(611): SMW\SQLStore\EntityStore\EntityIdManager->makeDatabaseId('Audio', 274, '', '_MLf156154fc8d8...', true, 'Audio#Dieses Wi...', true)
#9 /../w/extensions/SemanticMediaWiki/src/SQLStore/SQLStoreUpdater.php(335): SMW\SQLStore\EntityStore\EntityIdManager->makeSMWPageID('Audio', 274, '', '_MLf156154fc8d8...', true, 'Audio#Dieses Wi...', true)
#10 /../w/extensions/SemanticMediaWiki/src/SQLStore/SQLStoreUpdater.php(242): SMW\SQLStore\SQLStoreUpdater->doFlatDataUpdate(Object(SMW\DataModel\ContainerSemanticData))
#11 /../w/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(316): SMW\SQLStore\SQLStoreUpdater->doDataUpdate(Object(SMW\SemanticData))
#12 /../w/extensions/SemanticMediaWiki/src/Store.php(234): SMW\SQLStore\SQLStore->doDataUpdate(Object(SMW\SemanticData))
#13 /../w/extensions/SemanticMediaWiki/src/DataUpdater.php(415): SMW\Store->updateData(Object(SMW\SemanticData))
#14 /../w/extensions/SemanticMediaWiki/src/DataUpdater.php(294): SMW\DataUpdater->updateData()
#15 /../w/extensions/SemanticMediaWiki/src/DataUpdater.php(198): SMW\DataUpdater->runUpdate()
#16 /../w/extensions/SemanticMediaWiki/src/ParserData.php(454): SMW\DataUpdater->doUpdate()
#17 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(303): SMW\ParserData->updateStore()
#18 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(216): SMW\MediaWiki\Jobs\UpdateJob->updateStore(Object(SMW\ParserData))
#19 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(137): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#20 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#21 /../w/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(239): SMW\MediaWiki\Jobs\UpdateJob->run()
#22 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(470): SMW\SQLStore\Rebuilder\Rebuilder->rebuild(12603)
#23 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(383): SMW\Maintenance\DataRebuilder->doUpdateById(12603)
#24 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(222): SMW\Maintenance\DataRebuilder->rebuildAll()
#25 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#26 /../w/maintenance/doMaintenance.php(107): SMW\Maintenance\rebuildData->execute()
#27 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once('/var/www/htdocs...')
#28 {main}
[788ed46eb8bc88099310f942] [no req]   Wikimedia\Rdbms\DBTransactionError from line 1519 of /../w/includes/libs/rdbms/database/Database.php: Explicit transaction still active. A caller may have caught an error. Open transactions: sql/transaction/update
```
#### Backtrace:
```
#0 /../w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1642): Wikimedia\Rdbms\Database->assertNoOpenTransactions()
#1 /../w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(2150): Wikimedia\Rdbms\LoadBalancer->Wikimedia\Rdbms\{closure}(Wikimedia\Rdbms\DatabaseMysqli)
#2 /../w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1661): Wikimedia\Rdbms\LoadBalancer->forEachOpenMasterConnection(Closure)
#3 /../w/includes/libs/rdbms/lbfactory/LBFactory.php(244): Wikimedia\Rdbms\LoadBalancer->approveMasterChanges(array, string, integer)
#4 /../w/includes/libs/rdbms/lbfactory/LBFactorySimple.php(133): Wikimedia\Rdbms\LBFactory->Wikimedia\Rdbms\{closure}(Wikimedia\Rdbms\LoadBalancer, string, array)
#5 /../w/includes/libs/rdbms/lbfactory/LBFactory.php(246): Wikimedia\Rdbms\LBFactorySimple->forEachLB(Closure, array)
#6 /../w/includes/libs/rdbms/lbfactory/LBFactory.php(305): Wikimedia\Rdbms\LBFactory->forEachLBCallMethod(string, array)
#7 /../w/maintenance/doMaintenance.php(135): Wikimedia\Rdbms\LBFactory->commitMasterChanges(string)
#8 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once(string)
#9 {main}
```

**Comment by kghbln** [comment]
To mitigate I reduced the text annotated to properties of type Monolingual Text and special properties which utilize this datatype to a maximum of 255 characters. Now the issue no longer appears though I personally rate this bug as critical since it basically kills respective properties from being useful.

**Comment by JeroenDeDauw** [comment]
@hexmode that sounds like the issue you recently where asking about on Matrix

**Comment by hexmode** [comment]
This does sound similar, but unless @kghbln was seeing "improper assignments" on the property page, I don't think it is the same.

**Comment by kghbln** [comment]
I cannot tell since I was so much consume by the errors coming from the script. However this issue should be easy to replicate.

**Comment by hexmode** [comment]
@kghbln when I saw "imporoper assignments" on the property page, there were other errors but the problematic property only showed up when it went past 256 chars.  If you have a small dataset where this shows up, that would help.

**Comment by kghbln** [comment]
This should create the issue. I will also update my test wiki and see if I can replicate to confirm the dataset.

Page **Property:Has property note**

`{{#set: Has type=Monolingual text }}`

Page **Test Page**

`{{#set:Has property note=Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.@la}}`

`{{#set:Has property description=Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.@la}}`

**Comment by kghbln** [comment]
Ref: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5056#issuecomment-907843951

This is nasty. Even after adapting the property page to something shorter the error occurs. The offending semantic ID needs to be deleted. Only after doing so it is possible to rebuild data without getting the error even if the property page is already on a rectified version.
