### ISSUE TITLE
Strict GROUP_BY causes  'wiki.smw_object_ids.smw_title' isn't in GROUP BY

### ISSUE THREAD

**Issue by Abijeet** [SemanticMediaWiki/SemanticMediaWiki#5071]
### Setup

- SMW version: 4.0.0-alpha (2960825)
- MW version: 1.38.0-alpha (8bf7a07) (Should happen with lower versions too)
- PHP version: 7.4.21 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.5.11-MariaDB-1

### Issue

With `ONLY_FULL_GROUP_BY` / Strict `GROUP_BY` enabled.

```
Error 1055: 'wiki.smw_object_ids.smw_title' isn't in GROUP BY (localhost)
Function: SMW\SQLStore\EntityStore\PropertySubjectsLookup::fetchFromTable
Query: SELECT smw_id, smw_title, smw_namespace, smw_iw, smw_subobject, smw_sortkey, smw_sort FROM `smw_object_ids` INNER JOIN `smw_fpt_dtitle` AS t1 ON t1.s_id=smw_id WHERE (smw_iw!=':smw') AND (smw_iw!=':smw-delete') AND (smw_iw!=':smw-redi') GROUP BY smw_sort, smw_id LIMIT 21

Backtrace:

from /home/developer/mediawiki/workdir/includes/libs/rdbms/database/Database.php(1809)
#0 /home/developer/mediawiki/workdir/includes/libs/rdbms/database/Database.php(1793): Wikimedia\Rdbms\Database->getQueryException()
#1 /home/developer/mediawiki/workdir/includes/libs/rdbms/database/Database.php(1768): Wikimedia\Rdbms\Database->getQueryExceptionAndLog()
#2 /home/developer/mediawiki/workdir/includes/libs/rdbms/database/Database.php(1327): Wikimedia\Rdbms\Database->reportQueryError()
#3 /home/developer/mediawiki/workdir/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->query()
#4 /home/developer/mediawiki/workdir/includes/libs/rdbms/database/DBConnRef.php(297): Wikimedia\Rdbms\DBConnRef->__call()
#5 /home/developer/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(417): Wikimedia\Rdbms\DBConnRef->query()
#6 /home/developer/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(329): SMW\MediaWiki\Connection\Database->executeQuery()
#7 /home/developer/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/PropertySubjectsLookup.php(331): SMW\MediaWiki\Connection\Database->query()
#8 /home/developer/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/PropertySubjectsLookup.php(75): SMW\SQLStore\EntityStore\PropertySubjectsLookup->doFetch()
#9 /home/developer/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityLookup.php(389): SMW\SQLStore\EntityStore\PropertySubjectsLookup->fetchFromTable()
#10 /home/developer/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityLookup.php(415): SMW\SQLStore\EntityStore\EntityLookup->getPropertySubjects()
#11 /home/developer/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(273): SMW\SQLStore\EntityStore\EntityLookup->getAllPropertySubjects()
#12 /home/developer/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Page/ListBuilder/ValueListBuilder.php(164): SMW\SQLStore\SQLStore->getAllPropertySubjects()
#13 /home/developer/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Page/PropertyPage.php(413): SMW\MediaWiki\Page\ListBuilder\ValueListBuilder->createHtml()
#14 /home/developer/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Page/PropertyPage.php(213): SMW\MediaWiki\Page\PropertyPage->makeValueList()
#15 /home/developer/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Page/Page.php(185): SMW\MediaWiki\Page\PropertyPage->getHtml()
#16 /home/developer/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Page/Page.php(101): SMW\MediaWiki\Page\Page->showList()
#17 /home/developer/mediawiki/workdir/includes/actions/ViewAction.php(74): SMW\MediaWiki\Page\Page->view()
#18 /home/developer/mediawiki/workdir/includes/MediaWiki.php(538): ViewAction->show()
#19 /home/developer/mediawiki/workdir/includes/MediaWiki.php(320): MediaWiki->performAction()
#20 /home/developer/mediawiki/workdir/includes/MediaWiki.php(925): MediaWiki->performRequest()
#21 /home/developer/mediawiki/workdir/includes/MediaWiki.php(559): MediaWiki->main()
#22 /home/developer/mediawiki/workdir/index.php(53): MediaWiki->run()
#23 /home/developer/mediawiki/workdir/index.php(46): wfIndexMain()
#24 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
1. Enable `ONLY_FULL_GROUP_BY` / Strict `GROUP_BY`
2. Browse Properties for a page (Eg: https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Parcourir/:Main_Page)

**Comment by wgevaert** [comment]
Has been introduced in [this pull request](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3142).
According to MySql docs, one should add `ANY_VALUE` functions to the other fields.
The postgres solution cannot be used for mysql, because `DISTINCT ON` is a postgres construct.

**Comment by c-holtermann** [comment]
In the mediawiki docker development environment in includes/DevelopmentSettings.php there is a setting $wgSQLMode = 'STRICT_ALL_TABLES,ONLY_FULL_GROUP_BY'; This can be overrridden in LocalSettings.php by $wgSQLMode = '';
