### ISSUE TITLE
Error from line 531 of SMW_DataValue.php: Call to a member function getDescriptionBuilderRegistry() on null

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#5090]
### Setup

- SMW version: 3.2.3
- MW version: 1.35.4
- PHP version: 7.4.24
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB

### Issue

When doing a full rebuild with "rebuildData.php" we get the following error:

```
[50553c8a365ff98f6bd7d134] [no req]   Error from line 531 of /.../w/extensions/SemanticMediaWiki/includes/datavalues/SMW_DataValue.php: Call to a member function getDescriptionBuilderRegistry() on null
```
The wiki is using a copy of [this page on s-mw.o](https://www.semantic-mediawiki.org/wiki/Help:Format_cat%C3%A9gorie). On the wiki we get a warning from SMW `"-" is not a number.` via the tooltip.

### Backtrace
```
#0 /../w/extensions/SemanticMediaWiki/src/Query/Parser/DescriptionProcessor.php(146): SMWDataValue->getQueryDescription()
#1 /../w/extensions/SemanticMediaWiki/src/Query/Parser/LegacyParser.php(645): SMW\Query\Parser\DescriptionProcessor->newDescriptionForPropertyObjectValue()
#2 /../w/extensions/SemanticMediaWiki/src/Query/Parser/LegacyParser.php(439): SMW\Query\Parser\LegacyParser->getPropertyDescription()
#3 /../w/extensions/SemanticMediaWiki/src/Query/Parser/LegacyParser.php(326): SMW\Query\Parser\LegacyParser->getLinkDescription()
#4 /../w/extensions/SemanticMediaWiki/src/Query/Parser/LegacyParser.php(270): SMW\Query\Parser\LegacyParser->getSubqueryDescription()
#5 /../w/extensions/SemanticMediaWiki/src/Query/Processor/QueryCreator.php(115): SMW\Query\Parser\LegacyParser->getQueryDescription()
#6 /../w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(176): SMW\Query\Processor\QueryCreator->create()
#7 /../w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(268): SMWQueryProcessor::createQuery()
#8 /../w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(296): SMWQueryProcessor::getQueryAndParamsFromFunctionParams()
#9 /../w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(196): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters()
#10 /../w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse()
#11 /../w/includes/parser/Parser.php(3340): SMW\ParserFunctionFactory->SMW{closure}()
#12 /../w/includes/parser/Parser.php(3047): Parser->callParserFunction()
#13 /../w/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution()
#14 /../w/includes/parser/Parser.php(2887): PPFrame_Hash->expand()
#15 /../w/includes/parser/Parser.php(1556): Parser->replaceVariables()
#16 /../w/includes/parser/Parser.php(651): Parser->internalParse()
#17 /../w/includes/content/WikitextContent.php(374): Parser->parse()
#18 /../w/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput()
#19 /../w/extensions/SemanticMediaWiki/includes/ContentParser.php(161): AbstractContent->getParserOutput()
#20 /../w/extensions/SemanticMediaWiki/includes/ContentParser.php(128): SMW\ContentParser->fetchFromContent()
#21 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(197): SMW\ContentParser->parse()
#22 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(137): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#23 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#24 /../w/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(239): SMW\MediaWiki\Jobs\UpdateJob->run()
#25 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(470): SMW\SQLStore\Rebuilder\Rebuilder->rebuild()
#26 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(383): SMW\Maintenance\DataRebuilder->doUpdateById()
#27 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(222): SMW\Maintenance\DataRebuilder->rebuildAll()
#28 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#29 /../w/maintenance/doMaintenance.php(107): SMW\Maintenance\rebuildData->execute()
#30 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once(string)
#31 {main}
```

**Comment by kghbln** [comment]
I suspect that is due to the Maps extension not being installed in the wiki which is holding maps extension related content: distance query examples, query maps examples.

**Comment by JeroenDeDauw** [comment]
I do not see anything Maps related in the error. Plus if Maps is not installed/enabled, pages with content relying on it will just have that content be ignored.

**Comment by kghbln** [comment]
It is a wild guess. Anyhow good to be able rule it out. Still a nasty bug though.
