### ISSUE TITLE
Postgresql DB error for queries which select on a boolean property

### ISSUE THREAD

**Issue by mdoggydog** [SemanticMediaWiki/SemanticMediaWiki#5093]
### Setup

- SMW version: 3.2.3
- MW version: 1.35.3
- PHP version: 7.4.21 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: PostgreSQL 13.3 (Debian 13.3-1)

### Issue

Attempting to perform a query that selects on a boolean property results in a database error, e.g.,
`[[Some boolean property::true]]` results in:
```
[28499ecea8c02310033c8e95] /index.php?title=Special:Ask& RuntimeException from line 291 of /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php: Error 42883: ERROR: operator does not exist: boolean = integer
LINE 1: ..." AS t1 ON t0.smw_id=t1.s_id WHERE ((t1.o_value=1) AND t1...
^
HINT: No operator matches the given name and argument types. You might need to add explicit type casts.
```
I have not looked into the SMW code, but I suspect that the query's boolean parameter (e.g., `true`) is being transformed into an integer in the DB query (e.g., `1`), but the corresponding column is typed as `boolean` and PostgreSQL does not permit comparison of boolean against integer.  I imagine that the same query happens to work in MariaDB/MySQL because that DB engine is more permissive (lax) and just goes ahead and casts the integer to boolean (or boolean to integer, who knows).

Here is a complete stack trace from such an error:
```
[a2fe5fdbc7cfd309f625e011] /index.php?title=Special:Ask& RuntimeException from line 291 of /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php: Error 42883: ERROR: operator does not exist: boolean = integer
LINE 1: ..." AS t1 ON t0.smw_id=t1.s_id WHERE ((t1.o_value=1) AND t1...
^
HINT: No operator matches the given name and argument types. You might need to add explicit type casts.

Function: SMW\SQLStore\QueryEngine\QueryEngine::getInstanceQueryResult
Query: SELECT DISTINCT t0.smw_id AS id,t0.smw_title AS t,t0.smw_namespace AS ns,t0.smw_iw AS iw,t0.smw_subobject AS so,t0.smw_sortkey AS sortkey,t0.smw_sort FROM "smw_object_ids" AS t0 INNER JOIN "smw_di_bool" AS t1 ON t0.smw_id=t1.s_id WHERE ((t1.o_value=1) AND t1.p_id=683) AND t0.smw_iw!=':smw' AND t0.smw_iw!=':smw-delete' AND t0.smw_iw!=':smw-redi' ORDER BY t0.smw_sort ASC LIMIT 55 OFFSET 0

#0 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/libs/rdbms/database/Database.php(1683): Wikimedia\Rdbms\Database->getQueryException()
#1 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/libs/rdbms/database/Database.php(1658): Wikimedia\Rdbms\Database->getQueryExceptionAndLog()
#2 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/libs/rdbms/database/Database.php(1227): Wikimedia\Rdbms\Database->reportQueryError()
#3 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/libs/rdbms/database/Database.php(1907): Wikimedia\Rdbms\Database->query()
#4 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->select()
#5 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/libs/rdbms/database/DBConnRef.php(313): Wikimedia\Rdbms\DBConnRef->__call()
#6 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(283): Wikimedia\Rdbms\DBConnRef->select()
#7 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(414): SMW\MediaWiki\Connection\Database->select()
#8 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(225): SMW\SQLStore\QueryEngine\QueryEngine->getInstanceQueryResult()
#9 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(388): SMW\SQLStore\QueryEngine\QueryEngine->getQueryResult()
#10 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(376): SMW\SQLStore\SQLStore->fetchQueryResult()
#11 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(719): SMW\SQLStore\SQLStore->getQueryResult()
#12 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(451): SMW\MediaWiki\Specials\SpecialAsk->fetchQueryResult()
#13 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(315): SMW\MediaWiki\Specials\SpecialAsk->fetchResults()
#14 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(170): SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#15 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/specialpage/SpecialPage.php(600): SMW\MediaWiki\Specials\SpecialAsk->execute()
#16 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run()
#17 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#18 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/MediaWiki.php(940): MediaWiki->performRequest()
#19 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/MediaWiki.php(543): MediaWiki->main()
#20 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/index.php(53): MediaWiki->run()
#21 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/index.php(46): wfIndexMain()
#22 {main}

Backtrace:

#0 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(414): SMW\MediaWiki\Connection\Database->select()
#1 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(225): SMW\SQLStore\QueryEngine\QueryEngine->getInstanceQueryResult()
#2 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(388): SMW\SQLStore\QueryEngine\QueryEngine->getQueryResult()
#3 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(376): SMW\SQLStore\SQLStore->fetchQueryResult()
#4 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(719): SMW\SQLStore\SQLStore->getQueryResult()
#5 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(451): SMW\MediaWiki\Specials\SpecialAsk->fetchQueryResult()
#6 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(315): SMW\MediaWiki\Specials\SpecialAsk->fetchResults()
#7 /srv/ctap-sunshinepps/Mediawiki/mediawiki-local/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(170): SMW\MediaWiki\Specials\SpecialAsk->makeHTMLResult()
#8 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/specialpage/SpecialPage.php(600): SMW\MediaWiki\Specials\SpecialAsk->execute()
#9 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run()
#10 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#11 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/MediaWiki.php(940): MediaWiki->performRequest()
#12 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/includes/MediaWiki.php(543): MediaWiki->main()
#13 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/index.php(53): MediaWiki->run()
#14 /srv/ctap-sunshinepps/Mediawiki/mediawiki-1.35.3/index.php(46): wfIndexMain()
#15 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

For example:
 1. Create a SMW property, e.g. "Has boolean" typed as Boolean.
 2. Go to "Special:Ask" and give `[[Has boolean::true]]` as the Condition.
 3. Hit "Find results".

(FYI, this works fine at https://sandbox.semantic-mediawiki.org, but the sandbox uses MariaDB.)

**Comment by mdoggydog** [comment]
I went ahead and looked at the SMW code, and it looks like the "PostgreSQL versus Boolean" issue was partially addressed in `DIBooleanHandler.php` a couple of years ago.  `getInsertValues()` was fixed, but `getWhereConds()` was overlooked.  I just submitted a pull request (#5098) to take care of that.  (And it does appear to work on my wiki.)
