### ISSUE TITLE
getFirstRevision() error when saving new page

### ISSUE THREAD

**Issue by squirrelslair** [SemanticMediaWiki/SemanticMediaWiki#5138]
### Setup

- SMW version:4.0.0-alpha
- MW version:1.37.0
- PHP version:7.4.25 (cgi-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 5.7.29-log

### Issue

If I create a new page on the wiki, I get an error 
`[YZfKQvwxgZh0q3dwBo18NAAAAAU] /index.php?title=SMW_Test&action=submit Error: Call to undefined method Title::getFirstRevision()`

Steps: create the new page by search --> create page, and error happens on save, i.e. when `&action=submit` is in address bar. 

If I then try to go back to the page I get 
`There is currently no text in this page. You can search for this page title in other pages, search the related logs, or create this page. `

**Comment by squirrelslair** [comment]
```
[YZfLxduY5EmA-KTtEkD60gAAAII] /index.php?title=SMW_Test2&action=submit Error: Call to undefined method Title::getFirstRevision()

Backtrace:

from /home/<...my wiki directory...>/extensions/SemanticMediaWiki/src/MediaWiki/PageInfoProvider.php(86)
#0 /home/<...my wiki directory...>/extensions/SemanticMediaWiki/src/Property/Annotators/PredefinedPropertyAnnotator.php(93): SMW\MediaWiki\PageInfoProvider->getCreationDate()
#1 /home/<...my wiki directory...>/extensions/SemanticMediaWiki/src/Property/Annotators/PredefinedPropertyAnnotator.php(70): SMW\Property\Annotators\PredefinedPropertyAnnotator->createDataItemByPropertyId(string)
#2 /home/<...my wiki directory...>/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(62): SMW\Property\Annotators\PredefinedPropertyAnnotator->addPropertyValues()
#3 /home/<...my wiki directory...>/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(61): SMW\Property\Annotators\PropertyAnnotatorDecorator->addAnnotation()
#4 /home/<...my wiki directory...>/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/RevisionFromEditComplete.php(157): SMW\Property\Annotators\PropertyAnnotatorDecorator->addAnnotation()
#5 /home/<...my wiki directory...>/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/RevisionFromEditComplete.php(101): SMW\MediaWiki\Hooks\RevisionFromEditComplete->addPredefinedPropertyAnnotation(SMW\ParserData, NULL)
#6 /home/<...my wiki directory...>/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(632): SMW\MediaWiki\Hooks\RevisionFromEditComplete->process(Title)
#7 /home/<...my wiki directory...>/includes/HookContainer/HookContainer.php(338): SMW\MediaWiki\Hooks->onRevisionFromEditComplete(WikiPage, MediaWiki\Revision\RevisionStoreRecord, boolean, User, array)
#8 /home/<...my wiki directory...>/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#9 /home/<...my wiki directory...>/includes/HookContainer/HookRunner.php(3191): MediaWiki\HookContainer\HookContainer->run(string, array)
#10 /home/<...my wiki directory...>/includes/Storage/PageUpdater.php(1384): MediaWiki\HookContainer\HookRunner->onRevisionFromEditComplete(WikiPage, MediaWiki\Revision\RevisionStoreRecord, boolean, User, array)
#11 /home/<...my wiki directory...>/includes/Storage/PageUpdater.php(835): MediaWiki\Storage\PageUpdater->doCreate(CommentStoreComment, User, integer)
#12 /home/<...my wiki directory...>/includes/page/WikiPage.php(1994): MediaWiki\Storage\PageUpdater->saveRevision(CommentStoreComment, integer)
#13 /home/<...my wiki directory...>/includes/EditPage.php(2349): WikiPage->doUserEditContent(WikitextContent, User, CommentStoreComment, integer, boolean, array, integer)
#14 /home/<...my wiki directory...>/includes/EditPage.php(1685): EditPage->internalAttemptSave(array, boolean)
#15 /home/<...my wiki directory...>/includes/EditPage.php(665): EditPage->attemptSave(array)
#16 /home/<...my wiki directory...>/includes/actions/EditAction.php(71): EditPage->edit()
#17 /home/<...my wiki directory...>/includes/actions/SubmitAction.php(38): EditAction->show()
#18 /home/<...my wiki directory...>/includes/MediaWiki.php(538): SubmitAction->show()
#19 /home/<...my wiki directory...>/includes/MediaWiki.php(320): MediaWiki->performAction(Article, Title)
#20 /home/<...my wiki directory...>/includes/MediaWiki.php(925): MediaWiki->performRequest()
#21 /home/<...my wiki directory...>/includes/MediaWiki.php(559): MediaWiki->main()
#22 /home/<...my wiki directory...>/index.php(53): MediaWiki->run()
#23 /home/<...my wiki directory...>/index.php(46): wfIndexMain()
#24 {main}

```

**Comment by squirrelslair** [comment]
According to Logs, nothing is created or deleted. 

However when I go to the page again I get the following error: 
```
The revision #0 of the page named "SMW Test2" does not exist.

This is usually caused by following an outdated history link to a page that has been deleted. Details can be found in the deletion log.
```

**Comment by squirrelslair** [comment]
I also get the error when my cron jobs run RebuildData.php

[e434b0573292cf22d2bc6e23] [no req]   Error: Call to undefined method Title::getFirstRevision()

**Comment by gesinn-it-gea** [comment]
From [MW 1.35 release notes](https://www.mediawiki.org/wiki/Release_notes/1.35):

The following methods were deprecated:
- `Title::getFirstRevision` (hard deprecated)
- `Title::getEarliestRevTime`
- `WikiPage::getOldestRevision` (hard deprecated)
- `Article::getOldestRevision` (hard deprecated)

 Use `RevisionStore::getFirstRevision` instead.

**Comment by gesinn-it-gea** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?q=getfirstrevision
