### ISSUE TITLE
Class 'SMW\Tests\JsonTestCaseScriptRunner' not found

### ISSUE THREAD

**Issue by YOUR1** [SemanticMediaWiki/SemanticMediaWiki#5143]
### Setup

- SMW version: 3.2.3
- MW version: 1.35.3
- PHP version: 7.3.33-1+ubuntu18.04.1+deb.sury.org+1 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB (10.4.22-MariaDB-1:10.4.22+maria~bionic-log)

### Issue

Whenever I try to run MediaWiki's unit test through tests/phpunit/phpunit.php I get an exception: 
```
[bbc36d40a41ae834ae3cce20] [no req]   Error from line 18 of /var/platform/wikifarm-3.0.x/crow/20211124-114902/extensions/SemanticMediaWiki/tests/phpunit/Benchmark/BenchmarkJsonScriptRunnerTest.php: Class 'SMW\Tests\JsonTestCaseScriptRunner' not found
Backtrace:
#0 /var/platform/wikifarm-3.0.x/crow/20211124-114902/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once()
#1 /var/platform/wikifarm-3.0.x/crow/20211124-114902/vendor/phpunit/phpunit/src/Util/FileLoader.php(54): PHPUnit\Util\FileLoader::load(string)
#2 /var/platform/wikifarm-3.0.x/crow/20211124-114902/vendor/phpunit/phpunit/src/Framework/TestSuite.php(384): PHPUnit\Util\FileLoader::checkAndLoad(string)
#3 /var/platform/wikifarm-3.0.x/crow/20211124-114902/vendor/phpunit/phpunit/src/Framework/TestSuite.php(482): PHPUnit\Framework\TestSuite->addTestFile(string)
#4 /var/platform/cores/1_35/20211122-113301/tests/phpunit/suites/ExtensionsTestSuite.php(31): PHPUnit\Framework\TestSuite->addTestFiles(array)
#5 /var/platform/cores/1_35/20211122-113301/tests/phpunit/suites/ExtensionsTestSuite.php(43): ExtensionsTestSuite->__construct()
#6 [internal function]: ExtensionsTestSuite::suite(string)
#7 /var/platform/wikifarm-3.0.x/crow/20211124-114902/vendor/phpunit/phpunit/src/Framework/TestSuite.php(463): ReflectionMethod->invoke(NULL, string)
#8 /var/platform/wikifarm-3.0.x/crow/20211124-114902/vendor/phpunit/phpunit/src/Util/Configuration.php(1061): PHPUnit\Framework\TestSuite->addTestFile(string)
#9 /var/platform/wikifarm-3.0.x/crow/20211124-114902/vendor/phpunit/phpunit/src/Util/Configuration.php(907): PHPUnit\Util\Configuration->getTestSuite(DOMElement, array)
#10 /var/platform/wikifarm-3.0.x/crow/20211124-114902/vendor/phpunit/phpunit/src/TextUI/Command.php(963): PHPUnit\Util\Configuration->getTestSuiteConfiguration(string)
#11 /var/platform/wikifarm-3.0.x/crow/20211124-114902/vendor/phpunit/phpunit/src/TextUI/Command.php(202): PHPUnit\TextUI\Command->handleArguments(array)
#12 /workspace/vendor/core/REL1_35/tests/phpunit/phpunit.php(76): PHPUnit\TextUI\Command->run(array, boolean)
#13 /var/platform/cores/1_35/20211122-113301/maintenance/doMaintenance.php(107): PHPUnitMaintClass->execute()
#14 /workspace/vendor/core/REL1_35/tests/phpunit/phpunit.php(135): require(string)
#15 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
Run the MediaWiki's phpunit wrapper

**Comment by gesinn-it-gea** [comment]
please try with SMW dev-master since it better supports MW 1.35

**Comment by jaideraf** [comment]
@YOUR1 maybe you should see https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/README.md#running-tests
and try the development version "mediawiki/semantic-media-wiki": "dev-master" in composer.
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/INSTALL.md#installation-of-development-versions-and-release-candidates
3.2.3 is becoming old...

**Comment by JeroenDeDauw** [comment]
@YOUR1 make sure SMW is enabled (shown on special:version). Also: did you install SMW via composer? If not, you might need to add it to composer.local.json

**Comment by YOUR1** [comment]
Setting stuff to dev-master won't help me; since it requires atleast php 7.4, we're running 7.3 as mentioned in the opening ticket. 

@JeroenDeDauw I'm laoding stuff through composer yeah; and also configured in composer.local.json. I also see SMW enabled when I visit Special:Version. SMW works fine if not running unit tests :-)

**Comment by gesinn-it-gea** [comment]
Please try: to run all PHPUnit tests, change to directory _extensions/SemanticMediaWiki_ and execute _composer phpunit_

**Comment by gesinn-it-gea** [comment]
Show all available test groups (from MediaWiki install path):
```
 php tests/phpunit/phpunit.php --list-groups
 ```
 
 Maybe you can name the tests to run explicitly (excluding SMW) like:
 
 ```
 php tests/phpunit/phpunit.php --group API
 ```

**Comment by YOUR1** [comment]
> Please try: to run all PHPUnit tests, change to directory _extensions/SemanticMediaWiki_ and execute _composer phpunit_
> 
> If the above works, then at least you know that SMW tests are working.

I think you misunderstand my issue; SMW breaks unit testing while wanting to unit test other extensions. I don't want to run SMW specifically. Listing groups ect. also breaks; because of the missing class.

**Comment by gesinn-it-gea** [comment]
indeed, misunderstood your issue. Sorry for confusion.

**Comment by YOUR1** [comment]
Its no biggy. Any other thoughts you might wanna share? Thanks anyways for the troubles!

**Comment by jaideraf** [comment]
I guess this is outdated and the tests are now passing, so I am closing it. If the issue is still valid on master (or SMW 7.0.0), please reopen it.
