### ISSUE TITLE
 Is there new release plan to support SMW 1.37 in future

### ISSUE THREAD

**Issue by Hetystars** [SemanticMediaWiki/SemanticMediaWiki#5155]
### Setup

- SMW version: 1.37
- MW version: 3.2.3
- PHP version: 7.3
- DB system (MySQL.) and version: 5.7

### Issue

2021-12-08 03:25:24 : [7d736fc773e2735e33de1888] /wiki/resources/assets/poweredby_mediawiki_176x62.png   Error: Class 'Revision' not found
```
#0 wiki/extensions/SemanticMediaWiki/includes/ContentParser.php(200): SMW\MediaWiki\RevisionGuard->getRevision(Title, NULL)
#1 wiki/extensions/SemanticMediaWiki/includes/ContentParser.php(144): SMW\ContentParser->getRevision()
#2 wiki/extensions/SemanticMediaWiki/includes/ContentParser.php(128): SMW\ContentParser->fetchFromContent()
#3 wiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/LinksUpdateConstructed.php(153): SMW\ContentParser->parse()
#4 wiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/LinksUpdateConstructed.php(143): SMW\MediaWiki\Hooks\LinksUpdateConstructed->reparseAndFetchSemanticData(Title)
#5 wiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/LinksUpdateConstructed.php(97): SMW\MediaWiki\Hooks\LinksUpdateConstructed->updateSemanticData(SMW\ParserData, Title, string)
#6 wiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(879): SMW\MediaWiki\Hooks\LinksUpdateConstructed->process(LinksUpdate)
#7 wiki/includes/HookContainer/HookContainer.php(338): SMW\MediaWiki\Hooks->onLinksUpdateConstructed(LinksUpdate)
#8 wiki/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#9 wiki/includes/HookContainer/HookRunner.php(2335): MediaWiki\HookContainer\HookContainer->run(string, array)
#10 wiki/includes/deferred/LinksUpdate.php(166): MediaWiki\HookContainer\HookRunner->onLinksUpdateConstructed(LinksUpdate)
#11 wiki/includes/Storage/DerivedPageDataUpdater.php(1425): LinksUpdate->__construct(Title, ParserOutput, boolean)
#12 wiki/includes/deferred/RefreshSecondaryDataUpdate.php(84): MediaWiki\Storage\DerivedPageDataUpdater->getSecondaryDataUpdates(boolean)
#13 wiki/includes/deferred/DeferredUpdates.php(515): RefreshSecondaryDataUpdate->doUpdate()
#14 wiki/includes/Storage/DerivedPageDataUpdater.php(1747): DeferredUpdates::attemptUpdate(RefreshSecondaryDataUpdate, Wikimedia\Rdbms\LBFactorySimple)
#15 wiki/includes/page/WikiPage.php(2204): MediaWiki\Storage\DerivedPageDataUpdater->doSecondaryDataUpdates(array)
#16 wiki/includes/jobqueue/jobs/RefreshLinksJob.php(209): WikiPage->doSecondaryDataUpdates(array)
#17 wiki/includes/jobqueue/jobs/RefreshLinksJob.php(136): RefreshLinksJob->runForTitle(Title)
#18 wiki/includes/jobqueue/JobRunner.php(373): RefreshLinksJob->run()
#19 wiki/includes/jobqueue/JobRunner.php(334): JobRunner->doExecuteJob(RefreshLinksJob)
#20 wiki/includes/jobqueue/JobRunner.php(247): JobRunner->executeJob(RefreshLinksJob)
#21 wiki/includes/MediaWiki.php(1212): JobRunner->run(array)
#22 wiki/includes/MediaWiki.php(662): MediaWiki->triggerSyncJobs(integer)
#23 wiki/includes/deferred/TransactionRoundDefiningUpdate.php(26): MediaWiki->{closure}()
#24 wiki/includes/deferred/DeferredUpdates.php(515): TransactionRoundDefiningUpdate->doUpdate()
#25 wiki/includes/deferred/DeferredUpdates.php(391): DeferredUpdates::attemptUpdate(TransactionRoundDefiningUpdate, Wikimedia\Rdbms\LBFactorySimple)
#26 wiki/includes/deferred/DeferredUpdates.php(221): DeferredUpdates::run(TransactionRoundDefiningUpdate, Wikimedia\Rdbms\LBFactorySimple, MediaWiki\Logger\LegacyLogger, BufferingStatsdDataFactory, string)
#27 wiki/includes/deferred/DeferredUpdatesScope.php(267): DeferredUpdates::{closure}(TransactionRoundDefiningUpdate, integer)
#28 wiki/includes/deferred/DeferredUpdatesScope.php(196): DeferredUpdatesScope->processStageQueue(integer, integer, Closure)
#29 wiki/includes/deferred/DeferredUpdates.php(242): DeferredUpdatesScope->processUpdates(integer, Closure)
#30 wiki/includes/MediaWiki.php(1164): DeferredUpdates::doUpdates(string)
#31 wiki/includes/MediaWiki.php(869): MediaWiki->restInPeace()
#32 wiki/includes/MediaWiki.php(601): MediaWiki->doPostOutputShutdown()
#33 wiki/index.php(53): MediaWiki->run()
#34 wiki/index.php(46): wfIndexMain()
```
when our program update SMW version: to 1.37，here is some unsupported problem，including Revision class not found. Is there new release plan to support SMW 1.37 in future

**Comment by malberts** [comment]
Many 1.37 issues have already been fixed. You need to use the latest master branch until version 4.0.0 is released. [According to the release notes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/releasenotes/RELEASE-NOTES-4.0.0.md) there is support for 1.37 in version 4 (#4870).

**Comment by Hetystars** [comment]
Yeah，thanks
