### ISSUE TITLE
PHP Deprecated:  Use of Wikimedia\Rdbms\DBConnRef::freeResult was deprecated in MediaWiki 1.38

### ISSUE THREAD

**Issue by Abijeet** [SemanticMediaWiki/SemanticMediaWiki#5204]
### Setup

- SMW version: master (0a233c2)
- MW version: 1.38
- PHP version: 7.4.25
- DB system (MySQL, Blazegraph, etc.) and version: 10.5.12-MariaDB

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

```
[2022-01-12T13:50:19.440811+00:00] error.WARNING: [773672df62fbd8c7c324ece2] /wiki/User:Abijeet_Patro   PHP Deprecated: Use of Wikimedia\Rdbms\DBConnRef::freeResult was deprecated in MediaWiki 1.38. [Called from SMW\MediaWiki\Connection\Database::freeResult] {"exception":"[object] (ErrorException(code: 0): PHP Deprecated: Use of Wikimedia\\Rdbms\\DBConnRef::freeResult was deprecated in MediaWiki 1.38. [Called from SMW\\MediaWiki\\Connection\\Database::freeResult] at /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php:248)
[stacktrace]
#0 [internal function]: MWExceptionHandler::handleError()
#1 /srv/mediawiki/workdir/includes/debug/MWDebug.php(377): trigger_error()
#2 /srv/mediawiki/workdir/includes/debug/MWDebug.php(351): MWDebug::sendRawDeprecated()
#3 /srv/mediawiki/workdir/includes/debug/MWDebug.php(232): MWDebug::deprecatedMsg()
#4 /srv/mediawiki/workdir/includes/GlobalFunctions.php(1005): MWDebug::deprecated()
#5 /srv/mediawiki/workdir/includes/libs/rdbms/database/DBConnRef.php(275): wfDeprecated()
#6 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(248): Wikimedia\\Rdbms\\DBConnRef->freeResult()
#7 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/SemanticDataLookup.php(606): SMW\\MediaWiki\\Connection\\Database->freeResult()
#8 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/SemanticDataLookup.php(371): SMW\\SQLStore\\EntityStore\\SemanticDataLookup->fetchFromTable()
#9 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CachingSemanticDataLookup.php(308): SMW\\SQLStore\\EntityStore\\SemanticDataLookup->fetchSemanticDataFromTable()
#10 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CachingSemanticDataLookup.php(279): SMW\\SQLStore\\EntityStore\\CachingSemanticDataLookup->fetchFromCache()
#11 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityLookup.php(293): SMW\\SQLStore\\EntityStore\\CachingSemanticDataLookup->getSemanticData()
#12 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(231): SMW\\SQLStore\\EntityStore\\EntityLookup->getPropertyValues()
#13 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Store.php(171): SMW\\SQLStore\\SQLStore->getPropertyValues()
#14 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Property/Annotators/CategoryPropertyAnnotator.php(207): SMW\\Store->getRedirectTarget()
#15 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Property/Annotators/CategoryPropertyAnnotator.php(147): SMW\\Property\\Annotators\\CategoryPropertyAnnotator->getRedirectTarget()
#16 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Property/Annotators/CategoryPropertyAnnotator.php(137): SMW\\Property\\Annotators\\CategoryPropertyAnnotator->modifySemanticData()
#17 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(62): SMW\\Property\\Annotators\\CategoryPropertyAnnotator->addPropertyValues()
#18 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(61): SMW\\Property\\Annotators\\PropertyAnnotatorDecorator->addAnnotation()
#19 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(61): SMW\\Property\\Annotators\\PropertyAnnotatorDecorator->addAnnotation()
#20 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(61): SMW\\Property\\Annotators\\PropertyAnnotatorDecorator->addAnnotation()
#21 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(61): SMW\\Property\\Annotators\\PropertyAnnotatorDecorator->addAnnotation()
#22 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(61): SMW\\Property\\Annotators\\PropertyAnnotatorDecorator->addAnnotation()
#23 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(61): SMW\\Property\\Annotators\\PropertyAnnotatorDecorator->addAnnotation()
#24 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(256): SMW\\Property\\Annotators\\PropertyAnnotatorDecorator->addAnnotation()
#25 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(184): SMW\\MediaWiki\\Hooks\\ParserAfterTidy->addPropertyAnnotations()
#26 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ParserAfterTidy.php(104): SMW\\MediaWiki\\Hooks\\ParserAfterTidy->performUpdate()
#27 /srv/mediawiki/workdir/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(366): SMW\\MediaWiki\\Hooks\\ParserAfterTidy->process()
#28 /srv/mediawiki/workdir/includes/HookContainer/HookContainer.php(338): SMW\\MediaWiki\\Hooks->onParserAfterTidy()
#29 /srv/mediawiki/workdir/includes/HookContainer/HookContainer.php(137): MediaWiki\\HookContainer\\HookContainer->callLegacyHook()
```
This error occurs when visiting the user page.

There could be other functions that are being used that were deprecated in,

751858: rdbms: Hard-deprecate legacy cruft from introduction of ResultWrapper | https://gerrit.wikimedia.org/r/c/mediawiki/core/+/751858

Edit: Fixed the stacktrace to point SMW error.

**Comment by JeroenDeDauw** [comment]
> freeResult was deprecated

Why do MediaWiki devs hate freedom so much?

(Sorry I will see myself out)
