### ISSUE TITLE
SMW uses once depreciated and now (since 1.39) removed MediaWiki\Connection\Database->freeResult()

### ISSUE THREAD

**Issue by calebgcooper** [SemanticMediaWiki/SemanticMediaWiki#5230]
According to release notes for 1.39 found here:
https://github.com/wikimedia/mediawiki/blob/master/RELEASE-NOTES-1.39

=== Breaking changes in 1.39 ===
* The following methods, deprecated since 1.37, have been removed from IDatabase
  - ::fetchObject()
  - ::fetchRow()
  - ::numRows()
  - ::freeResult()

Tested with SMW 4.0.1 and MediaWiki 1.39.0-alpha (0827d5f)

Backtrace:

```
from /var/lib/mediawiki/includes/libs/rdbms/database/DBConnRef.php(68)
#0 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(248): Wikimedia\Rdbms\DBConnRef->__call()
#1 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/SemanticDataLookup.php(606): SMW\MediaWiki\Connection\Database->freeResult()
#2 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/SemanticDataLookup.php(371): SMW\SQLStore\EntityStore\SemanticDataLookup->fetchFromTable()
#3 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CachingSemanticDataLookup.php(308): SMW\SQLStore\EntityStore\SemanticDataLookup->fetchSemanticDataFromTable()
#4 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CachingSemanticDataLookup.php(279): SMW\SQLStore\EntityStore\CachingSemanticDataLookup->fetchFromCache()
#5 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityLookup.php(293): SMW\SQLStore\EntityStore\CachingSemanticDataLookup->getSemanticData()
#6 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(231): SMW\SQLStore\EntityStore\EntityLookup->getPropertyValues()
#7 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/Property/SpecificationLookup.php(136): SMW\SQLStore\SQLStore->getPropertyValues()
#8 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/Schema/SchemaFinder.php(117): SMW\Property\SpecificationLookup->getSpecification()
#9 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/DataModel/SequenceMap.php(52): SMW\Schema\SchemaFinder->newSchemaList()
#10 /var/lib/mediawiki/extensions/SemanticMediaWiki/includes/SemanticData.php(497): SMW\DataModel\SequenceMap::canMap()
#11 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/Property/Annotators/PredefinedPropertyAnnotator.php(74): SMW\SemanticData->addPropertyObjectValue()
#12 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(62): SMW\Property\Annotators\PredefinedPropertyAnnotator->addPropertyValues()
#13 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(61): SMW\Property\Annotators\PropertyAnnotatorDecorator->addAnnotation()
#14 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/RevisionFromEditComplete.php(157): SMW\Property\Annotators\PropertyAnnotatorDecorator->addAnnotation()
#15 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/RevisionFromEditComplete.php(101): SMW\MediaWiki\Hooks\RevisionFromEditComplete->addPredefinedPropertyAnnotation()
#16 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(608): SMW\MediaWiki\Hooks\RevisionFromEditComplete->process()
#17 /var/lib/mediawiki/includes/HookContainer/HookContainer.php(338): SMW\MediaWiki\Hooks->onRevisionFromEditComplete()
#18 /var/lib/mediawiki/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#19 /var/lib/mediawiki/includes/HookContainer/HookRunner.php(3200): MediaWiki\HookContainer\HookContainer->run()
#20 /var/lib/mediawiki/includes/Storage/PageUpdater.php(1476): MediaWiki\HookContainer\HookRunner->onRevisionFromEditComplete()
#21 /var/lib/mediawiki/includes/Storage/PageUpdater.php(911): MediaWiki\Storage\PageUpdater->doCreate()
#22 /var/lib/mediawiki/includes/page/WikiPage.php(1994): MediaWiki\Storage\PageUpdater->saveRevision()
#23 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(167): WikiPage->doUserEditContent()
#24 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(142): SMW\Importer\ContentCreators\TextContentCreator->doCreateContent()
#25 /var/lib/mediawiki/includes/libs/rdbms/database/Database.php(4148): SMW\Importer\ContentCreators\TextContentCreator->SMW\Importer\ContentCreators\{closure}()
#26 /var/lib/mediawiki/includes/libs/rdbms/database/Database.php(4059): Wikimedia\Rdbms\Database->runOnTransactionIdleCallbacks()
#27 /var/lib/mediawiki/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->onTransactionCommitOrIdle()
#28 /var/lib/mediawiki/includes/libs/rdbms/database/DBConnRef.php(568): Wikimedia\Rdbms\DBConnRef->__call()
#29 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(822): Wikimedia\Rdbms\DBConnRef->onTransactionCommitOrIdle()
#30 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(143): SMW\MediaWiki\Connection\Database->onTransactionIdle()
#31 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/DispatchingContentCreator.php(75): SMW\Importer\ContentCreators\TextContentCreator->create()
#32 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/Importer/Importer.php(142): SMW\Importer\ContentCreators\DispatchingContentCreator->create()
#33 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/Importer/Importer.php(120): SMW\Importer\Importer->doImport()
#34 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1472): SMW\Importer\Importer->runImport()
#35 /var/lib/mediawiki/includes/HookContainer/HookContainer.php(338): SMW\MediaWiki\Hooks->onAfterCreateTablesComplete()
#36 /var/lib/mediawiki/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#37 /var/lib/mediawiki/includes/Hooks.php(137): MediaWiki\HookContainer\HookContainer->run()
#38 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/HookDispatcher.php(276): Hooks::run()
#39 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(279): SMW\MediaWiki\HookDispatcher->onInstallerAfterCreateTablesComplete()
#40 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(451): SMW\SQLStore\Installer->install()
#41 /var/lib/mediawiki/extensions/SemanticMediaWiki/src/Store.php(489): SMW\SQLStore\SQLStore->setup()
#42 /var/lib/mediawiki/includes/installer/DatabaseUpdater.php(533): SMW\Store::setupStore()
#43 /var/lib/mediawiki/includes/installer/DatabaseUpdater.php(501): DatabaseUpdater->runUpdates()
#44 /var/lib/mediawiki/maintenance/update.php(193): DatabaseUpdater->doUpdates()
#45 /var/lib/mediawiki/maintenance/doMaintenance.php(114): UpdateMediaWiki->execute()
#46 /var/lib/mediawiki/maintenance/update.php(264): require_once(string)
#47 {main}
```

**Comment by Nikerabbit** [comment]
Yeah.
