### ISSUE TITLE
HTTP response code: 503 while running rebuilddata

### ISSUE THREAD

**Issue by plegault3397** [SemanticMediaWiki/SemanticMediaWiki#5233]
### Setup
MediaWiki | 1.35.5
PHP | 7.4.15
Semantic MediaWiki | 4.0.1
MySQL | 8.0.23
Virtuoso Version: 07.20.3233

### Issue

SMW\SPARQLStore\Exception\BadHttpEndpointResponseException from line 83 of D:\app\www\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\HttpResponseErrorMapper.php: A SPARQL query error has occurred
Query: PREFIX wiki: <https://dvl-datamap.jnj.com/id/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX swivt: <http://semantic-mediawiki.org/swivt/1.0#>
PREFIX property: <https://dvl-datamap.jnj.com/id/Property-3A>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?result WHERE {
?result swivt:wikiPageSortKey ?resultsk .
?result property:Is_archived "no" .
?result property:Has_business_owner wiki:Epsilon .
 OPTIONAL { ?result swivt:redirectsTo ?o3 } .
 FILTER ( !bound( ?o3 ) ) .

}
ORDER BY ASC(?resultsk)
OFFSET 0
LIMIT 501
Error: Unkown error
Endpoint: http://awsacrnval0003.jnj.com/sparql
HTTP response code: 503

#0 D:\app\www\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\HttpResponseErrorMapper.php(55): SMW\SPARQLStore\HttpResponseErrorMapper->createResponseToHttpError()
#1 D:\app\www\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector.php(642): SMW\SPARQLStore\HttpResponseErrorMapper->mapErrorResponse()
#2 D:\app\www\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector.php(497): SMW\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector->mapHttpRequestError()
#3 D:\app\www\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector.php(215): SMW\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector->doQuery()
#4 D:\app\www\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\QueryEngine\QueryEngine.php(181): SMW\SPARQLStore\RepositoryConnectors\GenericRepositoryConnector->select()
#5 D:\app\www\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\QueryEngine\QueryEngine.php(118): SMW\SPARQLStore\QueryEngine\QueryEngine->getInstanceQueryResult()
#6 D:\app\www\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\SPARQLStore.php(310): SMW\SPARQLStore\QueryEngine\QueryEngine->getQueryResult()
#7 D:\app\www\mediawiki\extensions\SemanticMediaWiki\src\SPARQLStore\SPARQLStore.php(299): SMW\SPARQLStore\SPARQLStore->fetchQueryResult()
#8 D:\app\www\mediawiki\extensions\SemanticMediaWiki\includes\query\SMW_QueryProcessor.php(338): SMW\SPARQLStore\SPARQLStore->getQueryResult()
#9 D:\app\www\mediawiki\extensions\SemanticMediaWiki\src\ParserFunctions\AskParserFunction.php(364): SMWQueryProcessor::getResultFromQuery()
#10 D:\app\www\mediawiki\extensions\SemanticMediaWiki\src\ParserFunctions\AskParserFunction.php(196): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters()
#11 D:\app\www\mediawiki\extensions\SemanticMediaWiki\src\ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse()
#12 D:\app\www\mediawiki\includes\parser\Parser.php(3340): SMW\ParserFunctionFactory->SMW\{closure}()
#13 D:\app\www\mediawiki\includes\parser\Parser.php(3047): Parser->callParserFunction()
#14 D:\app\www\mediawiki\includes\parser\PPFrame_Hash.php(263): Parser->braceSubstitution()
#15 D:\app\www\mediawiki\includes\parser\Parser.php(3225): PPFrame_Hash->expand()
#16 D:\app\www\mediawiki\includes\parser\PPFrame_Hash.php(263): Parser->braceSubstitution()
#17 D:\app\www\mediawiki\includes\parser\Parser.php(3225): PPFrame_Hash->expand()
#18 D:\app\www\mediawiki\includes\parser\PPFrame_Hash.php(263): Parser->braceSubstitution()
#19 D:\app\www\mediawiki\includes\parser\Parser.php(2887): PPFrame_Hash->expand()
#20 D:\app\www\mediawiki\includes\parser\Parser.php(1556): Parser->replaceVariables()
```
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
[MySQL](https://www.mysql.com/)	8.0.23

run rebuilddata for longer than an hr

Provided details and have workaround from virtuoso:
https://github.com/openlink/virtuoso-opensource/issues/1029

**Comment by plegault3397** [comment]
I'm not sure what the issue is with the latest build from git hub however I downloaded the tar instead and now it work as it should.
