### ISSUE TITLE
Fatal error on some queries against ElasticStore

### ISSUE THREAD

**Issue by wgevaert** [SemanticMediaWiki/SemanticMediaWiki#5237]
### Setup

- SMW version: 4.0.0
- MW version: 1.34
- PHP version: 7.4
- DB system and version: ElasticSearch

### Issue
When running the query `[[-Has subobject.someproperty::SomeValue]]` against an `ElasticStore` backend we get this error:
```
[b6885e36d97dd155cd0733f0] /TestPage Error from line 417 of 
/path/to/mediawiki/extensions/SemanticMediaWiki/src/Elastic/QueryEngine/DescriptionInterpreters/SomePropertyInterpreter.php: Call to a member function 
toArray() on array

Backtrace:

#0 /path/to/mediawiki/extensions/SemanticMediaWiki/src/Elastic/QueryEngine/DescriptionInterpreters/SomePropertyInterpreter.php(152): 
SMW\Elastic\QueryEngine\DescriptionInterpreters\SomePropertyInterpreter->interpretChain()
#1 /path/to/mediawiki/extensions/SemanticMediaWiki/src/Elastic/QueryEngine/ConditionBuilder.php(414): 
SMW\Elastic\QueryEngine\DescriptionInterpreters\SomePropertyInterpreter->interpretDescription()
#2 /path/to/mediawiki/extensions/SemanticMediaWiki/src/Elastic/QueryEngine/ConditionBuilder.php(341): 
SMW\Elastic\QueryEngine\ConditionBuilder->interpretDescription()
#3 /path/to/mediawiki/extensions/SemanticMediaWiki/src/Elastic/QueryEngine/QueryEngine.php(144): 
SMW\Elastic\QueryEngine\ConditionBuilder->makeFromDescription()
#4 /path/to/mediawiki/extensions/SemanticMediaWiki/src/Elastic/ElasticStore.php(217): SMW\Elastic\QueryEngine\QueryEngine->getQueryResult()
#5 /path/to/mediawiki/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(338): SMW\Elastic\ElasticStore->getQueryResult()
#6 /path/to/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(361): SMWQueryProcessor::getResultFromQuery()
#7 /path/to/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(196): 
SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters()
#8 /path/to/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse()
#9 /path/to/mediawiki/includes/parser/Parser.php(3340): SMW\ParserFunctionFactory->SMW\{closure}()
#10 /path/to/mediawiki/includes/parser/Parser.php(3047): Parser->callParserFunction()
#11 /path/to/mediawiki/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution()
#12 /path/to/mediawiki/includes/parser/Parser.php(2887): PPFrame_Hash->expand()
#13 /path/to/mediawiki/includes/parser/Parser.php(1556): Parser->replaceVariables()
#14 /path/to/mediawiki/includes/parser/Parser.php(651): Parser->internalParse()
#15 /path/to/mediawiki/includes/content/WikitextContent.php(374): Parser->parse()
#16 /path/to/mediawiki/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput()
#17 /path/to/mediawiki/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput()
#18 /path/to/mediawiki/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached()
#19 /path/to/mediawiki/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput()
#20 /path/to/mediawiki/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput()
#21 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}()
#22 /path/to/mediawiki/includes/Revision/RenderedRevision.php(197): call_user_func()
#23 /path/to/mediawiki/includes/poolcounter/PoolWorkArticleView.php(216): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#24 /path/to/mediawiki/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleView->doWork()
#25 /path/to/mediawiki/includes/page/Article.php(810): PoolCounterWork->execute()
#26 /path/to/mediawiki/includes/actions/ViewAction.php(80): Article->view()
#27 /path/to/mediawiki/includes/MediaWiki.php(532): ViewAction->show()
#28 /path/to/mediawiki/includes/MediaWiki.php(313): MediaWiki->performAction()
#29 /path/to/mediawiki/includes/MediaWiki.php(945): MediaWiki->performRequest()
#30 /path/to/mediawiki/includes/MediaWiki.php(548): MediaWiki->main()
#31 /path/to/mediawiki/index.php(53): MediaWiki->run()
#32 /path/to/mediawiki/index.php(46): wfIndexMain()
#33 {main}
```

See also [this pull request](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5236)

**Comment by wgevaert** [comment]
Has been merged, thanks!
