### ISSUE TITLE
PHP Deprecated: Use of AbstractContent::getParserOutput was deprecated in MediaWiki 1.38

### ISSUE THREAD

**Issue by Abijeet** [SemanticMediaWiki/SemanticMediaWiki#5266]
### Setup

- SMW version: master
- MW version: 1.39.0-alpha
- PHP version: 7.4.28 
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB (10.5.15-MariaDB-0+deb11u1)

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

```
[2022-06-25T13:41:15.403104+00:00] error.WARNING: [b473aa833ff0d385e7556a26] /wiki/smw/schema:Group:Predefined_properties   PHP Deprecated: Use of AbstractContent::getParserOutput was deprecated in MediaWiki 1.38. [Called from ContentHandler::callDeprecatedContentGPO] {"exception":"[object] (ErrorException(code: 0): PHP Deprecated: Use of AbstractContent::getParserOutput was deprecated in MediaWiki 1.38. [Called from ContentHandler::callDeprecatedContentGPO] at /srv/mediawiki/tags/2022-06-22_15:03:25/includes/content/ContentHandler.php:1860)
[stacktrace]
#0 [internal function]: MWExceptionHandler::handleError()
#1 /srv/mediawiki/tags/2022-06-22_15:03:25/includes/debug/MWDebug.php(381): trigger_error()
#2 /srv/mediawiki/tags/2022-06-22_15:03:25/includes/debug/MWDebug.php(352): MWDebug::sendRawDeprecated()
#3 /srv/mediawiki/tags/2022-06-22_15:03:25/includes/debug/MWDebug.php(233): MWDebug::deprecatedMsg()
#4 /srv/mediawiki/tags/2022-06-22_15:03:25/includes/GlobalFunctions.php(770): MWDebug::deprecated()
#5 /srv/mediawiki/tags/2022-06-22_15:03:25/includes/content/AbstractContent.php(540): wfDeprecated()
#6 /srv/mediawiki/tags/2022-06-22_15:03:25/includes/content/ContentHandler.php(1860): AbstractContent->getParserOutput()
#7 /srv/mediawiki/tags/2022-06-22_15:03:25/includes/content/ContentHandler.php(1683): ContentHandler->callDeprecatedContentGPO()
#8 /srv/mediawiki/tags/2022-06-22_15:03:25/includes/content/Renderer/ContentRenderer.php(47): ContentHandler->getParserOutput()
#9 /srv/mediawiki/tags/2022-06-22_15:03:25/includes/Revision/RenderedRevision.php(266): MediaWiki\\Content\\Renderer\\ContentRenderer->getParserOutput()
#10 /srv/mediawiki/tags/2022-06-22_15:03:25/includes/Revision/RenderedRevision.php(237): MediaWiki\\Revision\\RenderedRevision->getSlotParserOutputUncached()
#11 /srv/mediawiki/tags/2022-06-22_15:03:25/includes/Revision/RevisionRenderer.php(221): MediaWiki\\Revision\\RenderedRevision->getSlotParserOutput()
#12 /srv/mediawiki/tags/2022-06-22_15:03:25/includes/Revision/RevisionRenderer.php(158): MediaWiki\\Revision\\RevisionRenderer->combineSlotOutput()
#13 [internal function]: MediaWiki\\Revision\\RevisionRenderer->MediaWiki\\Revision\\{closure}()
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

Cannot reproduce it on the sandbox. Instead go to: /wiki/smw/schema:Group:Predefined_properties, and ensure you are not loading a cached version of the page

**Comment by paladox** [comment]
This was fixed.
