### ISSUE TITLE
Postgresql setup fails with Error: Call to undefined method Wikimedia\Rdbms\DatabasePostgres::onTransactionIdle()

### ISSUE THREAD

**Issue by someone-somenet-org** [SemanticMediaWiki/SemanticMediaWiki#5287]
### Setup

- SMW version: 4.0.2
- MW version: 1.38.2
- PHP version: PHP 7.4.30 (cli) (built: Jul  7 2022 15:51:43)
- DB system and version: PostgreSQL 13.7 (Debian 13.7-0+deb11u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Issue
I created the database and applied this:
```
CREATE EXTENSION IF NOT EXISTS citext;
ALTER DATABASE wiki_fsinf_at SET bytea_output = 'escape';
```
Then setting up a new mediawiki instance with smw fails. Using this command:
```
php maintenance/install.php Wiki Admin --pass=... --dbtype=postgres --dbschema=public --dbserver=... --dbname=... --dbuser=... --dbpass=...
mv LocalSettings.php.orig LocalSettings.php
php maintenance/update.php --quick
```

Will lead during the execution of ``php maintenance/update.php --quick;`` to this:

```
--- Post-creation examination ---------------------------------------------

Checking selected fixed properties IDs ...
   ... done.
Checking internal properties border ...
   ... space for internal properties allocated ...                        ✓
   ... done.
Checking predefined properties ...
   ... initialize predefined properties ...
   ... done.
Checking smw_hash field consistency ...
   ... updating the setup file key ...                                    ✓
   ... done.
Checking smw_sortkey, smw_sort fields ...
   ... done.
Checking smw_touched field ...
   ... done.
Checking smw_countmap field consistency ...                               ✓
   ... done.
Checking entity collation type ...                                        ✓
   ... done.
Checking `smw_id` sequence consistency ...
[56aab62775d239fe82fd93f2] [no req]   Error: Call to undefined method Wikimedia\Rdbms\DatabasePostgres::onTransactionIdle()
Backtrace:
from /var/www/[...]/includes/libs/rdbms/database/DBConnRef.php(69)
#0 /var/www/[...]/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Sequence.php(86): Wikimedia\Rdbms\DBConnRef->__call()
#1 /var/www/[...]/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/PostgresTableBuilder.php(488): SMW\MediaWiki\Connection\Sequence->restart()
#2 /var/www/[...]/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/PostgresTableBuilder.php(474): SMW\SQLStore\TableBuilder\PostgresTableBuilder->doCheckOnPostCreation()
#3 /var/www/[...]/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/TableBuildExaminer.php(171): SMW\SQLStore\TableBuilder\PostgresTableBuilder->checkOn()
#4 /var/www/[...]/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(239): SMW\SQLStore\TableBuilder\TableBuildExaminer->checkOnPostCreation()
#5 /var/www/[...]/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(451): SMW\SQLStore\Installer->install()
#6 /var/www/[...]/extensions/SemanticMediaWiki/src/Store.php(489): SMW\SQLStore\SQLStore->setup()
#7 /var/www/[...]/includes/installer/DatabaseUpdater.php(533): SMW\Store::setupStore()
#8 /var/www/[...]/includes/installer/DatabaseUpdater.php(501): DatabaseUpdater->runUpdates()
#9 /var/www/[...]/maintenance/update.php(193): DatabaseUpdater->doUpdates()
#10 /var/www/[...]/maintenance/doMaintenance.php(114): UpdateMediaWiki->execute()
#11 /var/www/[...]/maintenance/update.php(264): require_once(string)
#12 {main}

```

**Comment by someone-somenet-org** [comment]
Any updates on this one?

**Comment by efedoso** [comment]
Not optimum, but I've been able to circumvent this error copying the function from DBConnRef.php in Mediawiki 1.37 to the same file in 1.38:
 .../mediawiki/includes/libs/rdbms/database/DBConnRef.php
In line 616:
public function onTransactionIdle( callable $callback, $fname = __METHOD__ ) {
		return $this->onTransactionCommitOrIdle( $callback, $fname );
	}

**Comment by someone-somenet-org** [comment]
Any updates on this one? ;)

**Comment by whitten** [comment]
Did you have any troubles with the copy from 37 ?

**Comment by someone-somenet-org** [comment]
> Did you have any troubles with the copy from 37 ?

unsure what you mean?

**Comment by fleminra** [comment]
> Any updates on this one? ;)
> 
> It seems to me this can be actually search/replace replaced from `->onTransactionIdle(` to `->onTransactionCommitOrIdle(`, but dunno. Maybe somebody more knowledgeable about SMW check it out?

I did this and it worked (so far!). Specifically:

```
find /usr/share/mediawiki/extensions/SemanticMediaWiki -type f -print0 | xargs -0 sed -i 's/onTransactionIdle(/onTransactionCommitOrIdle(/g'
```

I won't do a pull request just because I don't know any of the relevant code (nor PHP), so don't know whether it's the correct change to make.

**Comment by someone-somenet-org** [comment]
OK, srsly, you win... im creating the PR by myself.
