### ISSUE TITLE
[SQLite] Database.php: Error 1: near "_indexpri": syntax error

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5384]
### Setup

- SMW version: dev-master (2023-01-02)
- MW version: 1.39
- PHP version:
- DB system (MySQL, Blazegraph, etc.) and version: SQLite

### Issue
During CI run vor SESP:

```
Checking index structures for table smw_object_ids ...
Wikimedia\Rdbms\DBQueryError from line 1618 of /var/www/html/includes/libs/rdbms/database/Database.php: Error 1: near "_indexpri": syntax error
Function: SMW\SQLStore\TableBuilder\SQLiteTableBuilder::doCreateIndex
Query: CREATE UNIQUE INDEX "smw_object_ids"_indexpri ON "smw_object_ids" (smw_id)
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/actions/runs/3821673721/jobs/6501048515#step:6:215

**Comment by turnstyyle** [comment]
I also am affected by this issue, using MediaWiki 1.39.2 with SQLite and Semantic MediaWiki 4.1.0.

I previously had gotten the same error with MediaWiki 1.39.1 and Semantic MediaWiki 4.0.2. At the time, I chalked it up to [a lack of compatibility](https://www.semantic-mediawiki.org/wiki/Help:Compatibility) of SMW 4.0.x with MediaWiki 1.39.x. But the problem persists with SMW 4.1.x, which is supposed to be compatible with MediaWiki 1.39.x.

My last successful upgrade was to Semantic MediaWiki 4.0.2 and MediaWiki 1.38.5.

```
$ php maintenance/update.php
...
=== Semantic MediaWiki ====================================================

Semantic MediaWiki:                                                   4.1.0
MediaWiki:                                                           1.39.2

--- Database setup --------------------------------------------------------

Storage engine:                                                SMWSQLStore3
Database (type/version):                                    sqlite (3.34.1)

Checking version requirement ...
   ... done.

------------------------------------------------------ Core table(s) ------

Checking table smw_object_ids ...
   Table already exists, checking structure ...
   ... field smw_id is fine.
   ... field smw_namespace is fine.
   ... field smw_title is fine.
   ... field smw_iw is fine.
   ... field smw_subobject is fine.
   ... field smw_sortkey is fine.
   ... field smw_sort is fine.
   ... field smw_proptable_hash is fine.
   ... field smw_hash is fine.
   ... field smw_rev is fine.
   ... field smw_touched is fine.
   ... done.
Checking index structures for table smw_object_ids ...
   ... removing index smw_object_ids_index9 ...done.
   ... removing index smw_object_ids_index8 ...done.
   ... removing index smw_object_ids_index7 ...done.
   ... removing index smw_object_ids_index6 ...done.
   ... removing index smw_object_ids_index5 ...done.
   ... removing index smw_object_ids_index4 ...done.
   ... removing index smw_object_ids_index3 ...done.
   ... removing index smw_object_ids_index2 ...done.
   ... removing index smw_object_ids_index1 ...done.
   ... removing index smw_object_ids_index0 ...done.
   ... removing index smw_object_ids_indexpri ...done.
   ... creating new UNIQUE INDEX smw_id ...Wikimedia\Rdbms\DBQueryError from line 1618 of /var/www/mediawiki/w/includes/libs/rdbms/database/Database.php: Error 1: near "_indexpri": syntax error
Function: SMW\SQLStore\TableBuilder\SQLiteTableBuilder::doCreateIndex
Query: CREATE UNIQUE INDEX "smw_object_ids"_indexpri ON "smw_object_ids" (smw_id)

#0 /var/www/mediawiki/w/includes/libs/rdbms/database/Database.php(1602): Wikimedia\Rdbms\Database->getQueryException()
#1 /var/www/mediawiki/w/includes/libs/rdbms/database/Database.php(1576): Wikimedia\Rdbms\Database->getQueryExceptionAndLog()
#2 /var/www/mediawiki/w/includes/libs/rdbms/database/Database.php(952): Wikimedia\Rdbms\Database->reportQueryError()
#3 /var/www/mediawiki/w/includes/libs/rdbms/database/DBConnRef.php(103): Wikimedia\Rdbms\Database->query()
#4 /var/www/mediawiki/w/includes/libs/rdbms/database/DBConnRef.php(293): Wikimedia\Rdbms\DBConnRef->__call()
#5 /var/www/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/SQLiteTableBuilder.php(356): Wikimedia\Rdbms\DBConnRef->query()
#6 /var/www/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/SQLiteTableBuilder.php(294): SMW\SQLStore\TableBuilder\SQLiteTableBuilder->doCreateIndex()
#7 /var/www/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/TableBuilder.php(167): SMW\SQLStore\TableBuilder\SQLiteTableBuilder->doCreateIndices()
#8 /var/www/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(229): SMW\SQLStore\TableBuilder\TableBuilder->create()
#9 /var/www/mediawiki/w/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(451): SMW\SQLStore\Installer->install()
#10 /var/www/mediawiki/w/extensions/SemanticMediaWiki/src/Store.php(489): SMW\SQLStore\SQLStore->setup()
#11 /var/www/mediawiki/w/includes/installer/DatabaseUpdater.php(547): SMW\Store::setupStore()
#12 /var/www/mediawiki/w/includes/installer/DatabaseUpdater.php(515): DatabaseUpdater->runUpdates()
#13 /var/www/mediawiki/w/maintenance/update.php(202): DatabaseUpdater->doUpdates()
#14 /var/www/mediawiki/w/maintenance/includes/MaintenanceRunner.php(309): UpdateMediaWiki->execute()
#15 /var/www/mediawiki/w/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#16 /var/www/mediawiki/w/maintenance/update.php(312): require_once('/var/www/mediaw...')
#17 {main}
```
