### ISSUE TITLE
Setup::initExtension(): Argument #1 ($vars) cannot be passed by reference

### ISSUE THREAD

**Issue by grantiago** [SemanticMediaWiki/SemanticMediaWiki#5385]
fail smw 4.0.2 
after not being able to get smw to run on an update I tried a clean install of media wiki 1.39.1 and after failing there according to the notes on mediawik I tried 1.39.0 
I see it is marked as closed here https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5202
still happening on my dev server; ubuntu 20.04 I have tried php 8.0 8.1 and 8.2. fatal all

### Issue

```
Setup::initExtension(): Argument #1 ($vars) cannot be passed by reference in /mnt/www/wiki/public_html/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php:
```

 composer run successfully
 successful -- maintenance/update.php on both.
wiki runs fine with any other extension. 
fails upon enabling smw 
wfLoadExtension( 'SemanticMediaWiki' );
enableSemantics( 'wiki.lan' );
### Setup

MediaWiki | 1.39.0
PHP | 8.1.14 (fpm-fcgi) 
and 8.2
get a warning on 8.0 even if smw isn't enabled in the LocalSettings.php
MySQL | 8.0.31-0ubuntu0.20.04.2
ICU | 66.1

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
Product	Version
[MediaWiki](https://www.mediawiki.org/)	1.39.0
[PHP](https://php.net/)	8.1.14 (fpm-fcgi)
[MySQL](https://www.mysql.com/)	8.0.31-0ubuntu0.20.04.2
[ICU](https://icu.unicode.org/)	66.1

### composer output
```
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
  - Downgrading pear/mail (v1.5.0 => v1.4.1)
  - Downgrading wikimedia/xmp-reader (0.8.6 => 0.8.5)
Writing lock file
Installing dependencies from lock file
Package operations: 20 installs, 4 updates, 7 removals
  - Downloading wikimedia/parsoid (v0.16.1)
  - Removing wikimedia/equivset (1.4.3)
  - Removing wikimedia/dodo (v0.4.0)
  - Removing symfony/polyfill-php81 (v1.26.0)
  - Removing psr/simple-cache (1.0.1)
  - Removing opis/json-schema (1.1.0)
  - Removing jakobo/hotp-php (v2.0.0)
  - Removing christian-riesen/base32 (1.6.0)
  - Installing composer/installers (v1.12.0): Extracting archive
  - Upgrading guzzlehttp/promises (1.5.1 => 1.5.2): Extracting archive
  - Upgrading guzzlehttp/psr7 (2.4.0 => 2.4.3): Extracting archive
  - Installing wikimedia/textcat (2.0.0): Extracting archive
  - Installing symfony/css-selector (v5.4.17): Extracting archive
  - Installing serialization/serialization (4.0.0): Extracting archive
  - Installing seld/jsonlint (1.8.3): Extracting archive
  - Installing data-values/interfaces (1.0.0): Extracting archive
  - Installing data-values/data-values (3.1.0): Extracting archive
  - Installing data-values/validators (1.0.0): Extracting archive
  - Installing data-values/common (1.1.0): Extracting archive
  - Installing param-processor/param-processor (1.12.0): Extracting archive
  - Installing onoi/shared-resources (0.4.3): Extracting archive
  - Installing onoi/message-reporter (1.4.2): Extracting archive
  - Installing onoi/cache (1.2.0): Extracting archive
  - Installing onoi/http-request (1.3.1): Extracting archive
  - Installing onoi/event-dispatcher (1.1.0): Extracting archive
  - Installing onoi/callback-container (2.0.0): Extracting archive
  - Installing onoi/blob-store (1.2.1): Extracting archive
  - Installing mediawiki/parser-hooks (1.6.1): Extracting archive
  - Installing jeroen/file-fetcher (6.1.0): Extracting archive
  - Installing mediawiki/semantic-media-wiki (4.0.2): Extracting archive
  - Upgrading symfony/deprecation-contracts (v2.5.1 => v3.2.0): Extracting archive
  - Upgrading wikimedia/parsoid (v0.16.0-a21 => v0.16.1): Extracting archive
  0/23 [>---------------------------]   0%    Skipped installation of bin bin/jsonlint for package seld/jsonlint: name conflicts with an existing file
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
```
### apache log
```
[Sat Jan 07 16:39:02.583262 2023] [proxy_fcgi:error] [pid 145276:tid 281471889699216] [client 192.168.1.222:49776] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: SMW\\Setup::initExtension(): Argument #1 ($vars) cannot be passed by reference in /mnt/tera/www/wikifresh/public_html/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php:46\nStack trace:\n#0 /mnt/tera/www/wikifresh/public_html/includes/registration/ExtensionRegistry.php(527): SemanticMediaWiki::initExtension()\n#1 /mnt/tera/www/wikifresh/public_html/includes/registration/ExtensionRegistry.php(279): ExtensionRegistry->exportExtractedData()\n#2 /mnt/tera/www/wikifresh/public_html/includes/Setup.php(278): ExtensionRegistry->loadFromQueue()\n#3 /mnt/tera/www/wikifresh/public_html/includes/WebStart.php(86): require_once('...')\n#4 /mnt/tera/www/wikifresh/public_html/index.php(44): require('...')\n#5 {main}\n  thrown in /mnt/tera/www/wikifresh/public_html/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php on line 46', referer: http://wikifresh.lan/index.php?title=Special:SpecialPages
```

**Comment by malberts** [comment]
You need to use the latest master branch of SMW. Since you're already using composer, just change the version number to `dev-master`.

**Comment by grantiago** [comment]
That was easy. Thank You
