### ISSUE TITLE
Unparsed SMW queries and empty or incomplete query results possibly being caused by CirrusSearch

### ISSUE THREAD

**Issue by justinclloyd** [SemanticMediaWiki/SemanticMediaWiki#5392]
### Setup

- SMW version: 4.0.2
- MW version: 1.38.2
- PHP version: 7.4.33-1+ubuntu20.04.1+deb.sury.org+1
- DB system: Amazon Aurora 5.7.mysql_aurora.2.10.2

#### Problem Description

(**Note:** This issue was originally reported on November 28, 2022 as [Phabricator task T323959](https://phabricator.wikimedia.org/T323959), but it was recommended to me to open a bug report here.)

Following our upgrades of MediaWiki (1.36.4 to 1.38.2) and Semantic MediaWiki (3.2.3 to 4.0.2) on September 12, 2022, we started seeing pages often showing unparsed SMW inline queries as wikitext in the HTML output that is ultimately shown to users, as well as SMW queries sometimes returning empty or incomplete results. These SMW queries are typically defined in templates.

Extensive further details can be found here:

- [Empty or incomplete SMW queries](https://wiki.guildwars2.com/wiki/Guild_Wars_2_Wiki:Reporting_wiki_bugs#Empty_or_incomplete_SMW_queries)
- [Unparsed pages after null edit](https://wiki.guildwars2.com/wiki/Guild_Wars_2_Wiki:Reporting_wiki_bugs#Unparsed_pages_after_null_edit)

#### Troubleshooting

Initial troubleshooting included removing most extensions by commenting out their loading from LocalSettings.php. Removing CirrusSearch and Elastica, which seemed related to timing issues, caused the unparsed query issue to disappear, However, through further testing we found a way to mitigate that problem without having to remove CirrusSearch and Elastica.

Our mitigation involved making a change to how our MediaWiki job runners worked. We have four SMW-enabled wikis, each with its own job runner systemd service, where the service is a shell script that runs `runJobs.php` with `--wait --maxjobs=1000 --procs=3` to parallelize the processing and limit the script's runtime to avoid memory leaks, etc. This is basically as recommended by https://www.mediawiki.org/wiki/Manual:Job_queue. The changes made involved removing the use of `--procs` to cause the jobs to be run completely sequentially, as well as grouping together jobs in the queue by type for each iteration of the infinite loop. 

```
job_types="
enotifNotify
cirrusSearchLinksUpdatePrioritized
cirrusSearchElasticaWrite
cirrusSearchLinksUpdate
cirrusSearchIncomingLinkCount
recentChangesUpdate
htmlCacheUpdate
refreshLinks
"

maxjobs=1000 memlimit="512M"

while true; do
    for job_type in ${job_types}; do
        while [[ $(/usr/bin/php ./maintenance/showJobs.php --type ${job_type} --list | wc -l) -gt 0 ]]; do
            /usr/bin/php ./maintenance/runJobs.php --maxjobs=${maxjobs} --memory-limit=${memlimit} --type ${job_type}
        done
    done
    /usr/bin/php ./maintenance/runJobs.php --maxjobs=${maxjobs} --memory-limit=${memlimit} --wait
done
```

Our testing only showed this to "fix" the display of unparsed queries but not the problem of empty/incomplete query results.

I have deployed the above runner logic change to our production wiki environment and continue to work with our editors to monitor the wikis for these problems. However, it is quite unclear as to why this problem suddenly started after our aforementioned upgrades and why the runner logic change seems to fix part of the problem.

**Comment by Nikerabbit** [comment]
Having the same problem in tieteentermipankki.fi, and we also recently installed CirrusSearch.

**Comment by cicalese** [comment]
We are experiencing frequent, debilitating database deadlocks while trying to rebuild wikiapiary's semantic data with SMW 4.1.1 (MediaWiki 1.39). CirrusSearch is not enabled, but the symptoms seem related to those mentioned on this issue. If we try to run multiple rebuildData scripts simultaneously or run the wikiapiary bumble bee bot at the same time as rebuildData, rebuildData will fail with a database deadlock. When I ran multiple rebuildData scripts telling it to ignore exceptions, we ended up with many pages with ids that had been processed by the scripts but that were lacking any semantic properties. I'm concerned that, even if we manage to single thread our way through rebuilding the semantic data (which will take roughly a month and a half), issues will arise once the wikiapiary bots and other bots that hit the site become active.
Do you think these symptoms are related? Is there a problem with SMW's database access layer related to access from scripts or jobs? Has anybody tried switching to a different backend (e.g. ElasticStore) to see if that avoids the issue?

**Comment by gesinn-it-gea** [comment]
@justinclloyd When you talk about missing results, is this caused by the pages in question having no properties? I have seen this in some of our wikis. Running `?action=purge` on the those pages usually fixes the issue. We also use Cirrus but did not see a relation (yet).

**Comment by justinclloyd** [comment]
> @justinclloyd When you talk about missing results, is this caused by the pages in question having no properties? I have seen this in some of our wikis. Running `?action=purge` on the those pages usually fixes the issue. We also use Cirrus but did not see a relation (yet).

Yes, that is my understanding. See, for example, the latest report of this issue still occurring back in May: https://wiki.guildwars2.com/wiki/Guild_Wars_2_Wiki:Reporting_wiki_bugs#May_2023

**Comment by cicalese** [comment]
Purging the pages in question (or the subpages that hold the data used to create the properties) worked in our case as well. So, the problem is not with the data itself.

**Comment by gesinn-it-gea** [comment]
Is the "CategoryWatch" extension active on one of the affected wikis by any chance?

**Comment by justinclloyd** [comment]
> Is the "CategoryWatch" extension active on one of the affected wikis by any chance?

Not on any of ours. I wasn't even aware of that extension.

**Comment by gesinn-it-gea** [comment]
CategoryWatch uses Echo which uses the JobQueue. Cirrus also uses the JobQeue. Maybe something happens, so that SMW's jobs can't make it to the Queue in the case of the error.

I have a setup here where I can reliably provoke the effect shown as soon as the CategoryWatch extension is activated. We will try to identify possible causes next week.

**Comment by cicalese** [comment]
Wikiapiary does not use CategoryWatch, but your description sounds plausible. I sense that the problem is in SMW itself, but it is exacerbated when other extensions are causing concurrent activity. In the case of Wikiapiary, I believe that it is simply that there is a huge volume of data being processed, and this leads to concurrent writing of properties, triggering deadlock.

**Comment by gesinn-it-gea** [comment]
could it be, that something with purge is not working as expected? Something in this area: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/08e30ceeb1ddca88722c0b297ebc89cb94615cf4/src/Store.php#L256

Here, we see a sequence of tasks including purge:
		$pageUpdater = $applicationFactory->newPageUpdater();

		$pageUpdater->addPage( $subject->getTitle() );
		$pageUpdater->waitOnTransactionIdle();
		$pageUpdater->markAsPending();
		$pageUpdater->setOrigin( __METHOD__ );

		$pageUpdater->doPurgeParserCache();
		$pageUpdater->doPurgeHtmlCache();
		$pageUpdater->pushUpdate();

**Comment by gesinn-it-gea** [comment]
The suspicion that the Echo Extension could play a causal role seems to be growing stronger. In our case, we had not set the variable `$wgEchoUseJobQueue`. This is set to false by default, so that Echo runs jobs "deferred". If there are delays in the notification (e.g. due to e-mail configuration), the entire processing of "deferred" is blocked.

@justinclloyd @cicalese can you check `$wgEchoUseJobQueue` in your wikis and check setting `$wgEchoUseJobQueue=true;`

See:

- https://github.com/wikimedia/mediawiki-extensions-Echo/blob/c82f9d046fc13fb385b4b83e608dc08aaa0c3976/includes/Model/Event.php#L207
- https://github.com/wikimedia/mediawiki-extensions-Echo/blob/c82f9d046fc13fb385b4b83e608dc08aaa0c3976/includes/Controller/NotificationController.php#L110

**Comment by cicalese** [comment]
@gesinn-it-gea Wikiapiary does not use Echo, so Echo is not the issue at least for it. Perhaps, of course, there may be multiple issues.

**Comment by justinclloyd** [comment]
> @justinclloyd @cicalese can you check `$wgEchoUseJobQueue` in your wikis and check setting `$wgEchoUseJobQueue=true;`

We do have Echo but only because it is required by Thanks, which was added to our wikis in March 2018. AbuseFilter also looks like it can make use of Echo, though we've had AF for pretty much the entire history of our wikis.

That said, given your comments about notifications delays, such as emails, I do often see a handful of notification emails (mainly watchlist notifications) get delayed in the remote SMTP server deferred queue (I manage those mail servers), but I wouldn't think that sort of delay is what you meant.

**Comment by gesinn-it-gea** [comment]
@justinclloyd I think delayed SMTP is one possible reason. Can you check the setting of `$wgEchoUseJobQueue` in your wiki as well as setting it to true in case it is false or unset.

**Comment by justinclloyd** [comment]
We have never set that value, so it will be using the default `false` value. However, I wouldn't want to make that change in our live environment before testing it in dev, but changes in dev don't send emails except for changes to pages on my account's watchlist due to a script I run to disable all other user emails. So I'm really not sure how to go about safely making the change and attempting to reproduce the problem without breaking pages in live that would all need to be fixed.

**Comment by freephile** [comment]
@justinclloyd FYI, you can use [MailHog](https://github.com/mailhog/MailHog) or a service like Mailtrap in your DEV environment (QA too) so that email works and is testable without spamming real users. Just vary the settings for $wgSMTP based on hostname.

**Comment by cicalese** [comment]
> Has anybody tried switching to a different backend (e.g. ElasticStore) to see if that avoids the issue?

Just to follow up on my earlier comment, I did try switching to ElasticStore as the backend and found that this does not solve the problem for our use case. When using ElasticStore, Semantic MediaWiki still populates the mysql database tables and then replicates the data to Elasticsearch from there. So, any deadlocks that prevent writing semantic properties to the mysql datastore would still occur.

Has anybody made any more progress on trying to isolate the database deadlock issue that is at the core of the failure to write properties?

**Comment by gesinn-it-gea** [comment]
What I can say is, that SMW might not be the root cause but any deffered job, that is blocking / breaking. This could be e.g. Echo not being able to send e-mail notifications with Echo configured to use Jobs or SemanticDependencyUpdater not using jobs or other extensions you are using. It's tricky to debug deferred jobs while running a stress test against your setup...

**Comment by Designburo** [comment]
What is the current status?

**Comment by gesinn-it-gea** [comment]
In our experience, SMW is the victim, not the perpetrator. Make sure that none of the other extensions are faulty (especially regarding deferred updates) or use jobs. Debugging is difficult even with debugger. Try to deactivate all other extensions as far as possible and reactivate them until the error occurs.

**Comment by StarHeartHunt** [comment]
Same issues on prts.wiki and fgo.wiki, we have encountered incomplete query result output and data missing for about a month.

and elk captured logs like below (may be related to the problem?):

```json
{
  "@timestamp": "2023-12-12T10:04:09.261149+08:00",
  "@version": 1,
  "host": "5b4010c4670e",
  "message": "Wikimedia\\Rdbms\\Platform\\SQLPlatform::tableName: use of subqueries is not supported this way",
  "type": "mediawiki",
  "channel": "DBQuery",
  "level": "WARNING",
  "monolog_level": 300,
  "url": "/w/%E7%94%A8%E6%88%B7%E8%AE%A8%E8%AE%BA:%E6%9C%89%E4%BA%BA%E8%AF%B4%E4%B8%8D%E7%AE%A1%E7%94%A8%E4%BB%80%E4%B9%88%E7%94%A8%E6%88%B7%E5%90%8D%E6%B3%A8%E5%86%8C%E9%83%BD%E4%BC%9A%E6%8F%90%E7%A4%BA%E9%87%8D%E5%A4%8D",
  "ip": "172.22.0.1",
  "http_method": "GET",
  "server": "prts.wiki",
  "referrer": null,
  "uid": "0bb30ef",
  "process_id": 2348930,
  "wiki": "ak-ak",
  "mwversion": "1.39.4",
  "reqId": "2ec4ad68d39a7d81a378b4b1",
  "exception": {
    "class": "RuntimeException",
    "message": "",
    "code": 0,
    "file": "/var/www/html/prts.wiki/includes/libs/rdbms/platform/SQLPlatform.php:983",
    "trace": "from /var/www/html/prts.wiki/includes/libs/rdbms/platform/SQLPlatform.php(983)\n#0 /var/www/html/prts.wiki/includes/libs/rdbms/platform/SQLPlatform.php(935): Wikimedia\\Rdbms\\Platform\\SQLPlatform->tableName()\n#1 /var/www/html/prts.wiki/includes/libs/rdbms/platform/SQLPlatform.php(836): Wikimedia\\Rdbms\\Platform\\SQLPlatform->tableNameWithAlias()\n#2 /var/www/html/prts.wiki/includes/libs/rdbms/platform/SQLPlatform.php(667): Wikimedia\\Rdbms\\Platform\\SQLPlatform->tableNamesWithIndexClauseOrJOIN()\n#3 /var/www/html/prts.wiki/includes/libs/rdbms/database/Database.php(3842): Wikimedia\\Rdbms\\Platform\\SQLPlatform->selectSQLText()\n#4 /var/www/html/prts.wiki/includes/libs/rdbms/database/DatabaseMysqlBase.php(1254): Wikimedia\\Rdbms\\Database->selectSQLText()\n#5 /var/www/html/prts.wiki/includes/libs/rdbms/database/Database.php(1704): Wikimedia\\Rdbms\\DatabaseMysqlBase->selectSQLText()\n#6 /var/www/html/prts.wiki/includes/libs/rdbms/database/DBConnRef.php(103): Wikimedia\\Rdbms\\Database->select()\n#7 /var/www/html/prts.wiki/includes/libs/rdbms/database/DBConnRef.php(326): Wikimedia\\Rdbms\\DBConnRef->__call()\n#8 /var/www/html/prts.wiki/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(246): Wikimedia\\Rdbms\\DBConnRef->select()\n#9 /var/www/html/prts.wiki/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(414): SMW\\MediaWiki\\Connection\\Database->select()\n#10 /var/www/html/prts.wiki/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(225): SMW\\SQLStore\\QueryEngine\\QueryEngine->getInstanceQueryResult()\n#11 /var/www/html/prts.wiki/extensions/SemanticMediaWiki/src/Query/Cache/ResultCache.php(250): SMW\\SQLStore\\QueryEngine\\QueryEngine->getQueryResult()\n#12 /var/www/html/prts.wiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1405): SMW\\Query\\Cache\\ResultCache->getQueryResult()\n#13 /var/www/html/prts.wiki/includes/HookContainer/HookContainer.php(338): SMW\\MediaWiki\\Hooks->onBeforeQueryResultLookupComplete()\n#14 /var/www/html/prts.wiki/includes/HookContainer/HookContainer.php(137): MediaWiki\\HookContainer\\HookContainer->callLegacyHook()\n#15 /var/www/html/prts.wiki/includes/Hooks.php(137): MediaWiki\\HookContainer\\HookContainer->run()\n#16 /var/www/html/prts.wiki/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(376): Hooks::run()\n#17 /var/www/html/prts.wiki/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(338): SMW\\SQLStore\\SQLStore->getQueryResult()\n#18 /var/www/html/prts.wiki/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(367): SMWQueryProcessor::getResultFromQuery()\n#19 /var/www/html/prts.wiki/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(202): SMW\\ParserFunctions\\AskParserFunction->doFetchResultsFromFunctionParameters()\n#20 /var/www/html/prts.wiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\\ParserFunctions\\AskParserFunction->parse()\n#21 /var/www/html/prts.wiki/includes/parser/Parser.php(3437): SMW\\ParserFunctionFactory->SMW\\{closure}()\n#22 /var/www/html/prts.wiki/includes/parser/Parser.php(3122): Parser->callParserFunction()\n#23 /var/www/html/prts.wiki/includes/parser/PPFrame_Hash.php(275): Parser->braceSubstitution()\n#24 /var/www/html/prts.wiki/includes/parser/PPTemplateFrame_Hash.php(97): PPFrame_Hash->expand()\n#25 /var/www/html/prts.wiki/includes/parser/Parser.php(3310): PPTemplateFrame_Hash->cachedExpand()\n#26 /var/www/html/prts.wiki/includes/parser/PPFrame_Hash.php(275): Parser->braceSubstitution()\n#27 /var/www/html/prts.wiki/includes/parser/Parser.php(2951): PPFrame_Hash->expand()\n#28 /var/www/html/prts.wiki/includes/parser/Parser.php(1609): Parser->replaceVariables()\n#29 /var/www/html/prts.wiki/includes/parser/Parser.php(723): Parser->internalParse()\n#30 /var/www/html/prts.wiki/includes/language/MessageCache.php(1411): Parser->parse()\n#31 /var/www/html/prts.wiki/includes/language/Message.php(1427): MessageCache->parse()\n#32 /var/www/html/prts.wiki/includes/language/Message.php(1004): Message->parseText()\n#33 /var/www/html/prts.wiki/includes/language/Message.php(1042): Message->format()\n#34 /var/www/html/prts.wiki/extensions/VectorMenuSidebar/VectorMenuSidebar.class.php(16): Message->parse()\n#35 /var/www/html/prts.wiki/includes/HookContainer/HookContainer.php(338): VectorMenuSidebar::BeforePageDisplay()\n#36 /var/www/html/prts.wiki/includes/HookContainer/HookContainer.php(137): MediaWiki\\HookContainer\\HookContainer->callLegacyHook()\n#37 /var/www/html/prts.wiki/includes/HookContainer/HookRunner.php(945): MediaWiki\\HookContainer\\HookContainer->run()\n#38 /var/www/html/prts.wiki/includes/OutputPage.php(2871): MediaWiki\\HookContainer\\HookRunner->onBeforePageDisplay()\n#39 /var/www/html/prts.wiki/includes/MediaWiki.php(922): OutputPage->output()\n#40 /var/www/html/prts.wiki/includes/MediaWiki.php(562): MediaWiki->main()\n#41 /var/www/html/prts.wiki/index.php(50): MediaWiki->run()\n#42 /var/www/html/prts.wiki/index.php(46): wfIndexMain()\n#43 {main}"
  },
  "db_log_category": "sql"
}
```

**Comment by revansx** [comment]
Not sure if I am asking this correctly, but could this issue be related to certain libraries not being loaded in time when a specific function tries to do something that depends on it?

For example, We had a problem with HeaderTabs failing to render that was ultimately solved by adding the SMW resources "ext.smw.tooltips" and "ext.smw.style" as dependencies in the HeaderTabs.hooks.php file and that seems to have solved the issue.. Could SMW possibly be needing some resource to be loaded explicitly in the SMW hooks content that it is used to getting loaded by another extension?

Does this make sense?

**Comment by Nikerabbit** [comment]
More of a note to self: I updated a few pages using Special:ReplaceText and they all got broken. If this is consistently reproducible, it may help to debug this issue.
![image](https://github.com/SemanticMediaWiki/SemanticMediaWiki/assets/1109395/f008dea5-33c5-4d61-8097-c6913bddc731)

**Comment by alistair3149** [comment]
We have a similar issue with empty and incomplete query result that has been plaguing our [production wiki](https://starcitizen.tools/) for close to a year, and we have a consistent way to reproduce it on our wiki:
1. Edit any template/module/TemplateStyles linked to [Module:Vehicle](https://starcitizen.tools/Module:Vehicle)
2. Wait a few minutes for the change to propagate to pages using the Module:Vehicle ([example page](https://starcitizen.tools/Hull_A))
3. Click `Browser properties` and observe the page, you can see Module:Vehicle successfully set the SMW properties on the page
4. Query the page in SMW using the properties. Often times there are no results.

We discovered that not only SMW queries are not returning results, some `pageprop` values such as `pageimage` (from Extension:PageImage) and `description` (from Extension:ShortDescription) are not set on the page as well.

Based on the observations above, our guess is that there might be a timeout or race condition somewhere when changes are propagating. Module:Vehicle is a somewhat laggy module because it is used on so many pages, calls an API, and have SMW self-referencing, so it might have make the matter worse.

**Comment by alistair3149** [comment]
@revansx may I ask for an example of the query that you're using and how are those SMW properties being set on the page?

**Comment by revansx** [comment]
It's a mixture of both the `[[PropertyName::Value]]` syntax as well as the `{{#set: ... }}` parser function. We haven't seen any noticeable difference in the frequency of the issue that corresponds with the way we set properties. It might be worth pointing out that all of our properties are set via template calls.

**Comment by alistair3149** [comment]
This bug seems to be critical enough that needed to be looked into. Is anyone familiar with the `CallableUpdate` class mentioned in #5923?

**Comment by ZoruaFox** [comment]
It seems that this bug still persists in the current version and continues to affect page properties. I recently updated the MediaWiki version from 1.41.x to 1.43, and this problem appeared again.

**Comment by gesinn-it-gea** [comment]
Please check, if setting `$wgForceDeferredUpdatesPreSend` to `true` changes something for you.

**Comment by ZoruaFox** [comment]
> Please check, if setting `$wgForceDeferredUpdatesPreSend` to `true` changes something for you.

I temporarily changed this configuration to true and nothing changed. My wiki (youshou.wiki) is using MW1.43.0 and SMW5.0.0alpha and uses git to manage all extensions(include modified extensions), skins and MediaWiki itself. almost all backend codes are in [this MediaWiki repository](https://github.com/TopRealm/MediaWiki) and [this extension rrepository](https://github.com/TopRealm/YsArchives-Extensions), they include all configurations in LocalSettings.php(except keys and secrets), I hope this will help you.($wgForceDeferredUpdatesPreSend are set to true but not shown in LocalSettings.php in my repo, please be advised).

I upgraded my wiki several days ago, and all my wiki's properties began to crash. In https://youshou.wiki/wiki/Special:Properties all my critical properties are identified as "page" instead of their true properties.
