### ISSUE TITLE
Declaring SMWResultPrinter::$maxRecursionDepth in LocalSettings.php results in an error 500

### ISSUE THREAD

**Issue by bertrandgorge** [SemanticMediaWiki/SemanticMediaWiki#5402]
### Setup

- SMW version: 4.0.2
- MW version: 1.37.6
- PHP version: 7.4.33

### Issue
Tried to declare `SMWResultPrinter::$maxRecursionDepth` as in https://www.semantic-mediawiki.org/wiki/Help:$maxRecursionDepth

```
[20-Jan-2023 16:50:06 UTC] PHP Fatal error:  Uncaught Exception: Not an actual source file in /var/www/html/extensions/SemanticMediaWiki/includes/IdeAliases.php:15
Stack trace:
#0 /var/www/html/vendor/composer/ClassLoader.php(444): include()
#1 /var/www/html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/v...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('SMWResultPrinte...')
#3 /var/www/config/LocalSettings.php(226): spl_autoload_call('SMWResultPrinte...')
#4 /var/www/html/includes/Setup.php(145): require_once('/var/www/config...')
#5 /var/www/html/maintenance/doMaintenance.php(90): require_once('/var/www/html/i...')
#6 /var/www/html/maintenance/runJobs.php(134): require_once('/var/www/html/m...')
#7 {main}
  thrown in /var/www/html/extensions/SemanticMediaWiki/includes/IdeAliases.php on line 15
```

**Comment by bertrandgorge** [comment]
The file `IdeAliases.php` should not be picked up by composer at all...

**Comment by D-Groenewegen** [comment]
Just mentioning here than I can confirm this (MW 1.35).

**Comment by gesinn-it-gea** [comment]
Needs to be set as follows in LocalSettings:

```
\SMW\Query\ResultPrinters\ResultPrinter::$maxRecursionDepth = 40;
```

(also fixed docu https://www.semantic-mediawiki.org/wiki/Help:$maxRecursionDepth#Changing_the_default_setting)

**Comment by bertrandgorge** [comment]
Thanks a lot @gesinn-it-gea !
