### ISSUE TITLE
TypeError: SMW\MediaWiki\JobFactory::newUpdateJob(): Argument #1 ($title) must be of type Title, null given

### ISSUE THREAD

**Issue by MPThLee** [SemanticMediaWiki/SemanticMediaWiki#5405]
### Setup

- SMW version: 4.1.0
- MW version: 1.39.1
- PHP version: 8.1.14
- DB system (MySQL, Blazegraph, etc.) and version: 10.6.10-MariaDB-log

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

Trying to block CIDR range of IP.

```
[911931142b00aaa526a6d3d2] /wiki/Special:Block TypeError: SMW\MediaWiki\JobFactory::newUpdateJob(): Argument #1 ($title) must be of type Title, null given, called in /srv/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/UserChange.php on line 74

Backtrace:

from /srv/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/JobFactory.php(112)
#0 /srv/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/UserChange.php(74): SMW\MediaWiki\JobFactory->newUpdateJob()
#1 /srv/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1288): SMW\MediaWiki\Hooks\UserChange->process()
#2 /srv/wiki/w/includes/HookContainer/HookContainer.php(338): SMW\MediaWiki\Hooks->onBlockIpComplete()
#3 /srv/wiki/w/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#4 /srv/wiki/w/includes/HookContainer/HookRunner.php(1039): MediaWiki\HookContainer\HookContainer->run()
#5 /srv/wiki/w/includes/block/BlockUser.php(604): MediaWiki\HookContainer\HookRunner->onBlockIpComplete()
#6 /srv/wiki/w/includes/block/BlockUser.php(532): MediaWiki\Block\BlockUser->placeBlockInternal()
#7 /srv/wiki/w/includes/block/BlockUser.php(466): MediaWiki\Block\BlockUser->placeBlockUnsafe()
#8 /srv/wiki/w/includes/specials/SpecialBlock.php(922): MediaWiki\Block\BlockUser->placeBlock()
#9 /srv/wiki/w/includes/specials/SpecialBlock.php(1036): SpecialBlock::processFormInternal()
#10 /srv/wiki/w/includes/htmlform/HTMLForm.php(725): SpecialBlock->onSubmit()
#11 /srv/wiki/w/includes/htmlform/HTMLForm.php(615): HTMLForm->trySubmit()
#12 /srv/wiki/w/includes/htmlform/HTMLForm.php(631): HTMLForm->tryAuthorizedSubmit()
#13 /srv/wiki/w/includes/specialpage/FormSpecialPage.php(209): HTMLForm->show()
#14 /srv/wiki/w/includes/specialpage/SpecialPage.php(701): FormSpecialPage->execute()
#15 /srv/wiki/w/includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run()
#16 /srv/wiki/w/includes/MediaWiki.php(316): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#17 /srv/wiki/w/includes/MediaWiki.php(904): MediaWiki->performRequest()
#18 /srv/wiki/w/includes/MediaWiki.php(562): MediaWiki->main()
#19 /srv/wiki/w/index.php(50): MediaWiki->run()
#20 /srv/wiki/w/index.php(46): wfIndexMain()
#21 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
Block on `Special:Block`

**Comment by malberts** [comment]
This looks like #5263.

**Comment by MPThLee** [comment]
@malberts Yep. Same issue. closing this issue.
