### ISSUE TITLE
SMW compatibility issue Azure MySQL 8: Error 1235: This version of MySQL doesn't yet support 'existing primary key drop without adding a new primary key

### ISSUE THREAD

**Issue by BarisKamis** [SemanticMediaWiki/SemanticMediaWiki#5475]
### Setup

- SMW version: 4.1.1
- MW version: 1.39.1
- PHP version: 8
- DB system (MySQL, Blazegraph, etc.) and version: MYSQL 8.0.31 

### Issue
Hi. I am using mediawiki 1.39.1, while creating from image, I am getting DROP 'PRIMARY' error. It started giving this error yesterday. In the previous weeks it was deploying with smw.

Thanks in advance.

The full track is here.
```
Checking table smw_object_ids ...
   Table already exists, checking structure ...
   ... changing type of field smw_id from 'INT UNSIGNED NOT NULL AUTO_INCREMENT' to 'INT(11) UNSIGNED NOT NULL KEY AUTO_INCREMENT' ... Wikimedia\Rdbms\DBQueryError from line 1618 of /var/www/html/includes/libs/rdbms/database/Database.php: Error 1091: Can't DROP 'PRIMARY'; check that column/key exists
Function: SMW\SQLStore\TableBuilder\MySQLTableBuilder::doUpdateFieldType
Query: ALTER TABLE `smw_object_ids` DROP PRIMARY KEY
```
```
#0 /var/www/html/includes/libs/rdbms/database/Database.php(1602): Wikimedia\Rdbms\Database->getQueryException('Can't DROP 'PRI...', 1091, 'ALTER TABLE `sm...', 'SMW\\SQLStore\\Ta...')
#1 /var/www/html/includes/libs/rdbms/database/Database.php(1576): Wikimedia\Rdbms\Database->getQueryExceptionAndLog('Can't DROP 'PRI...', 1091, 'ALTER TABLE `sm...', 'SMW\\SQLStore\\Ta...')
#2 /var/www/html/includes/libs/rdbms/database/Database.php(952): Wikimedia\Rdbms\Database->reportQueryError('Can't DROP 'PRI...', 1091, 'ALTER TABLE `sm...', 'SMW\\SQLStore\\Ta...', false)
#3 /var/www/html/includes/libs/rdbms/database/DBConnRef.php(103): Wikimedia\Rdbms\Database->query('ALTER TABLE `sm...', 'SMW\\SQLStore\\Ta...', 0)
#4 /var/www/html/includes/libs/rdbms/database/DBConnRef.php(293): Wikimedia\Rdbms\DBConnRef->__call('query', Array)
#5 /var/www/html/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/MySQLTableBuilder.php(231): Wikimedia\Rdbms\DBConnRef->query('ALTER TABLE `sm...', 'SMW\\SQLStore\\Ta...')
#6 /var/www/html/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/MySQLTableBuilder.php(201): SMW\SQLStore\TableBuilder\MySQLTableBuilder->doUpdateFieldType('`smw_object_ids...', 'smw_id', 'FIRST', 'INT UNSIGNED NO...', 'INT(11) UNSIGNE...')
#7 /var/www/html/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/MySQLTableBuilder.php(131): SMW\SQLStore\TableBuilder\MySQLTableBuilder->doUpdateField('`smw_object_ids...', 'smw_id', 'INT(11) UNSIGNE...', Array, 'FIRST', Array)
#8 /var/www/html/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/TableBuilder.php(159): SMW\SQLStore\TableBuilder\MySQLTableBuilder->doUpdateTable('`smw_object_ids...', Array)
#9 /var/www/html/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(229): SMW\SQLStore\TableBuilder\TableBuilder->create(Object(SMW\SQLStore\TableBuilder\Table))
#10 /var/www/html/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(452): SMW\SQLStore\Installer->install(Object(SMW\Options))
#11 /var/www/html/extensions/SemanticMediaWiki/src/Store.php(488): SMW\SQLStore\SQLStore->setup(Object(SMW\Options))
#12 /var/www/html/includes/installer/DatabaseUpdater.php(547): SMW\Store::setupStore(true, Object(SMW\Options))
#13 /var/www/html/includes/installer/DatabaseUpdater.php(515): DatabaseUpdater->runUpdates(Array, true)
#14 /var/www/html/maintenance/update.php(202): DatabaseUpdater->doUpdates(Array)
#15 /var/www/html/maintenance/includes/MaintenanceRunner.php(309): UpdateMediaWiki->execute()
#16 /var/www/html/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#17 /var/www/html/maintenance/update.php(312): require_once('/var/www/html/m...')
#18 {main}
The command '/bin/sh -c php /var/www/html/maintenance/update.php --conf=/var/www/html/LocalSettings.php' returned a non-zero code: 1
```

**Comment by WolfgangFahl** [comment]
A bit more context would be helpful. What's the content of wiki - e.g. how many pages / properties - has it been migrated or is this a clean start? It would be great to get some way of reproducability in your situation. Did you try e.g. modifying the database to a MariaDB instead of the (IMHO notoriously buggy) mySQL?

**Comment by vgangt** [comment]
Hi,
is there any further update on this issue?
I am also getting same error while running update.php script. 

Previously, I was getting below error while running update.php. This is happing for MW 1.39.5 with Mysql 8.0.32
"
This version of MySQL doesn't yet support 'existing primary key drop without adding a new primary key. In @@sql_generate_invisible_primary_key=ON mode table should have a primary key. Please add a new primary key to be able to drop existing primary key.' Function: SMW\SQLStore\TableBuilder\MySQLTableBuilder::doUpdateFieldType Query: ALTER TABLE `smw_object_ids` DROP PRIMARY KEY "

I had to drop the smw_object_ids table from db, then update script is running. To solve this I tried to set 'sql_generate_invisible_primary_key=OFF' in Mysql DB, which caused me the error in the original post.

Anybody else got similar issue?

**Comment by WolfgangFahl** [comment]
@vgangt - very good that you are giving more context. What migration did you try? What was the previous version and what is the new version of the wiki? Are you able to share the database content e.g. a backup or part of it?

**Comment by vgangt** [comment]
Hi,
Actually this is private wiki, I cannot share content due to security policy.

This was DB taken from MW 1.35.3 and put into Azure MySQL for MW 1.39.x
Since beginning we had this issue. but When we upgrade existing thing from 1.35.3 to 1.39.x within same server we did not face any issue, the prod is running fine.
But the issue is with the one we put into Azure Mysql.

**Comment by WolfgangFahl** [comment]
I find the Can't DROP 'PRIMARY' very fishy. You should be able to DROP a PRIMARY key and the server should not consider 'PRIMARY' as a table name or something. Is that a broken SQL installation that doesn't undertand proper SQL?

**Comment by WolfgangFahl** [comment]
in any case this might be an upstream issue since SMW uses standard table updating procedures provided by MediaWiki

**Comment by vgangt** [comment]
Thanks for your reply.
Does it mean that, we have to restoring the db or re-installing? Or is there another option to fix it?

**Comment by vgangt** [comment]
I found something related to primary key here. https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-limitations
We are also having Azure mySql db. But not sure if this will help in our situation.

**Comment by vgangt** [comment]
Hi,
I fixed this problem by setting the Server parameter (sql_generate_invisible_primary_key=OFF) for Azure MySQL DB. 
Earlier I was setting it in CLI, did not help. But Server parameter did the actual setting. 
Thanks..
