### ISSUE TITLE
Call to undefined method DatabasePostgres::onTransactionIdle() when upgrade to mediawiki 1.35

### ISSUE THREAD

**Issue by aburayyanjeffry** [SemanticMediaWiki/SemanticMediaWiki#5495]
### Setup

- SMW version: 1.4.1
- MW version: 1.39.3
- PHP version: 8.0
- DB system (MySQL, Blazegraph, etc.) and version: PostgreSQL 15

### Issue
Get this error when php maintenance/update.php

```
[b3fe91be197ea513080c3e6f] [no req]   Error: Call to undefined method Wikimedia\Rdbms\DatabasePostgres::onTransactionIdle()
Backtrace:
from /home/wiki/htdocs/test_mediawiki/includes/libs/rdbms/database/DBConnRef.php(103)
#0 /home/wiki/htdocs/test_mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Sequence.php(86): Wikimedia\Rdbms\DBConnRef->__call()
#1 /home/wiki/htdocs/test_mediawiki/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/PostgresTableBuilder.php(488): SMW\MediaWiki\Connection\Sequence->restart()
#2 /home/wiki/htdocs/test_mediawiki/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/PostgresTableBuilder.php(474): SMW\SQLStore\TableBuilder\PostgresTableBuilder->doCheckOnPostCreation()
#3 /home/wiki/htdocs/test_mediawiki/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/TableBuildExaminer.php(171): SMW\SQLStore\TableBuilder\PostgresTableBuilder->checkOn()
#4 /home/wiki/htdocs/test_mediawiki/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(239): SMW\SQLStore\TableBuilder\TableBuildExaminer->checkOnPostCreation()
#5 /home/wiki/htdocs/test_mediawiki/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(452): SMW\SQLStore\Installer->install()
#6 /home/wiki/htdocs/test_mediawiki/extensions/SemanticMediaWiki/src/Store.php(488): SMW\SQLStore\SQLStore->setup()
#7 /home/wiki/htdocs/test_mediawiki/includes/installer/DatabaseUpdater.php(547): SMW\Store::setupStore()
#8 /home/wiki/htdocs/test_mediawiki/includes/installer/DatabaseUpdater.php(515): DatabaseUpdater->runUpdates()
#9 /home/wiki/htdocs/test_mediawiki/maintenance/update.php(202): DatabaseUpdater->doUpdates()
#10 /home/wiki/htdocs/test_mediawiki/maintenance/includes/MaintenanceRunner.php(309): UpdateMediaWiki->execute()
#11 /home/wiki/htdocs/test_mediawiki/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#12 /home/wiki/htdocs/test_mediawiki/maintenance/update.php(312): require_once(string)
#13 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
see above

This issue happens because semantic-mediawiki is refering a deprecated functions "onTransactionIdle()". 

Please refer to this mediawiki bug report
https://phabricator.wikimedia.org/T338490

**Comment by Nikerabbit** [comment]
Title says 1.35, but the info you provided is 1.39. Which is correct? Also there is no SMW version 1.4.1

**Comment by someone-somenet-org** [comment]
duplicate of #5287 :)

I have proposed a fix, but the devs seem to not care :(

**Comment by paladox** [comment]
The issue was closed as resolved and was fixed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/48fbe9c2d46ab67f991c2de4ab49e7821fd3d2e6
