### ISSUE TITLE
Class "SMW\DataValues\PropertyValue" not found 

### ISSUE THREAD

**Issue by er-pooja** [SemanticMediaWiki/SemanticMediaWiki#5506]
### Setup

- SMW version:  4.1.1
- MW version: 1.39.4
- PHP version: 8.1
- Using Docker Image [https://hub.docker.com/_/mediawiki/](https://hub.docker.com/_/mediawiki/)
- DB system (MySQL, Blazegraph, etc.) and version: Azure Mysql

### Issue

A detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

After adding SemanticMediaWiki in Localsetting.php
```
**Fatal error: Uncaught Error: Class "SMWDataValue" not found in** /var/www/html/extensions/SemanticMediaWiki/src/DataValues/PropertyValue.php:44 Stack trace: #0 /var/www/html/includes/AutoLoader.php(244): require()
```
```
#1 [internal function]: AutoLoader::autoload('SMW\\DataValues\\...')
#2 /var/www/html/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php(214): class_alias('SMW\\DataValues\\...', 'SMWPropertyValu...')
#3 /var/www/html/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php(30): SemanticMediaWiki::setupAliases()
#4 /var/www/html/includes/registration/ExtensionRegistry.php(527): SemanticMediaWiki::initExtension(Array)
#5 /var/www/html/includes/registration/ExtensionRegistry.php(279): ExtensionRegistry->exportExtractedData(Array)
#6 /var/www/html/includes/Setup.php(278): ExtensionRegistry->loadFromQueue()
#7 /var/www/html/includes/WebStart.php(86): require_once('/var/www/html/i...')
#8 /var/www/html/index.php(44): require('/var/www/html/i...')
#9 {main} thrown in /var/www/html/extensions/SemanticMediaWiki/src/DataValues/PropertyValue.php on line 44
```

**Comment by er-pooja** [comment]
<img width="857" alt="image" src="https://github.com/SemanticMediaWiki/SemanticMediaWiki/assets/18166833/25afd211-6598-4439-a089-c3c442b0e5c0">
Also i can see latest patch is not successful for 1.39

**Comment by voronind** [comment]
- SMW version: 4.1.2
- MW version: 1.39.4
- PHP version: 8.1.22
- Using Docker Image https://hub.docker.com/_/mediawiki/
- DB system (MySQL, Blazegraph, etc.) and version: MariaDB

```console
$ docker-compose exec mediawiki  php maintenance/update.php
Warning: Class "SMW\DataValues\PropertyValue" not found in /var/www/html/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php on line 214
Fatal error: Uncaught Error: Class "SMWDataValue" not found in /var/www/html/extensions/SemanticMediaWiki/src/DataValues/PropertyValue.php:45
Stack trace:
#0 /var/www/html/includes/AutoLoader.php(244): require()
#1 [internal function]: AutoLoader::autoload('SMW\\DataValues\\...')
#2 /var/www/html/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php(214): class_alias('SMW\\DataValues\\...', 'SMWPropertyValu...')
#3 /var/www/html/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php(30): SemanticMediaWiki::setupAliases()
#4 /var/www/html/includes/registration/ExtensionRegistry.php(527): SemanticMediaWiki::initExtension(Array)
#5 /var/www/html/includes/registration/ExtensionRegistry.php(279): ExtensionRegistry->exportExtractedData(Array)
#6 /var/www/html/includes/Setup.php(278): ExtensionRegistry->loadFromQueue()
#7 /var/www/html/maintenance/doMaintenance.php(83): require_once('/var/www/html/i...')
#8 /var/www/html/maintenance/update.php(312): require_once('/var/www/html/m...')
#9 {main}
  thrown in /var/www/html/extensions/SemanticMediaWiki/src/DataValues/PropertyValue.php on line 45
```

**Comment by eurodomenii** [comment]
In my case, the error was generated due to missing smw tables during installation. Following ad litteram the instructions from https://www.semantic-mediawiki.org/wiki/Help:Installation/Using_Composer_with_MediaWiki_1.25%2B, I ran the maintenance script before enabling  wfLoadExtension( 'SemanticMediaWiki' ); to LocalSettings.php. 

Visual inspecting the output of php maintenance/update.php, I didn't notice any table being created. So, you need to enable first wfLoadExtension( 'SemanticMediaWiki' ); before running the maintenance script, in order to populate the smw tables. However, the correct order is listed at https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/INSTALL.md

**Comment by voronind** [comment]
> In my case, the error was generated due to missing smw tables during installation. Following ad litteram the instructions from https://www.semantic-mediawiki.org/wiki/Help:Installation/Using_Composer_with_MediaWiki_1.25%2B, I ran the maintenance script before enabling wfLoadExtension( 'SemanticMediaWiki' ); to LocalSettings.php.
> 
> Visual inspecting the output of php maintenance/update.php, I didn't notice any table being created. So, you need to enable first wfLoadExtension( 'SemanticMediaWiki' ); before running the maintenance script, in order to populate the smw tables. However, the correct order is listed at https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/INSTALL.md

Are you trying with docker and SMW 4.1+? IMHO it's not working.

**Comment by eurodomenii** [comment]
I'm on unprivileged LXC under Proxmox , Ubuntu 22, SMW 4.1.2

**Comment by voronind** [comment]
> * SMW version: 4.1.2
> * MW version: 1.39.4
> * PHP version: 8.1.22
> * Using Docker Image https://hub.docker.com/_/mediawiki/
> * DB system (MySQL, Blazegraph, etc.) and version: MariaDB
> 
> ```
> $ docker-compose exec mediawiki  php maintenance/update.php
> Warning: Class "SMW\DataValues\PropertyValue" not found in /var/www/html/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php on line 214
> Fatal error: Uncaught Error: Class "SMWDataValue" not found in /var/www/html/extensions/SemanticMediaWiki/src/DataValues/PropertyValue.php:45
> Stack trace:
> #0 /var/www/html/includes/AutoLoader.php(244): require()
> #1 [internal function]: AutoLoader::autoload('SMW\\DataValues\\...')
> #2 /var/www/html/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php(214): class_alias('SMW\\DataValues\\...', 'SMWPropertyValu...')
> #3 /var/www/html/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php(30): SemanticMediaWiki::setupAliases()
> #4 /var/www/html/includes/registration/ExtensionRegistry.php(527): SemanticMediaWiki::initExtension(Array)
> #5 /var/www/html/includes/registration/ExtensionRegistry.php(279): ExtensionRegistry->exportExtractedData(Array)
> #6 /var/www/html/includes/Setup.php(278): ExtensionRegistry->loadFromQueue()
> #7 /var/www/html/maintenance/doMaintenance.php(83): require_once('/var/www/html/i...')
> #8 /var/www/html/maintenance/update.php(312): require_once('/var/www/html/m...')
> #9 {main}
>   thrown in /var/www/html/extensions/SemanticMediaWiki/src/DataValues/PropertyValue.php on line 45
> ```

Same for SMW 4.2

**Comment by kleinesfilmroellchen** [comment]
This is still an issue.

**Comment by paladox** [comment]
This was fixed with https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/f4bb97047970f797f9765d867df4354edc914ad4

There's a duplicate issue https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5442 which was closed as resolved.
