### ISSUE TITLE
Search profile error: Call to undefined method User::isLoggedIn() 

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#5538]
### Setup
Software|Version
-- | --
MediaWiki | 1.39.4
PHP | 8.0.27 (litespeed)
MySQL | 8.0.32
SMW|4.1.2 

### Issue
Trying to use a search profile with SMW/Schema:Simple_search_profile results in an error on MediaWiki 1.39

```
[f809b18118ac12808738ab6f] /index.php?title=Spezial:Suche&profile=smw&search=test&fulltext=1 Error: Call to undefined method User::isLoggedIn()

Backtrace:

from /extensions/SemanticMediaWiki/src/MediaWiki/Search/ProfileForm/Forms/NamespaceForm.php(119)
#0 /extensions/SemanticMediaWiki/src/MediaWiki/Search/ProfileForm/ProfileForm.php(296): SMW\MediaWiki\Search\ProfileForm\Forms\NamespaceForm->checkNamespaceEditToken()
#1 /extensions/SemanticMediaWiki/src/MediaWiki/Search/ProfileForm/ProfileForm.php(203): SMW\MediaWiki\Search\ProfileForm\ProfileForm->buildNamespaceForm()
#2 /extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(556): SMW\MediaWiki\Search\ProfileForm\ProfileForm->buildForm()
#3 /includes/HookContainer/HookContainer.php(338): SMW\MediaWiki\Hooks->onSpecialSearchProfileForm()
#4 /includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#5 /includes/HookContainer/HookRunner.php(3760): MediaWiki\HookContainer\HookContainer->run()
#6 /includes/search/searchwidgets/SearchFormWidget.php(255): MediaWiki\HookContainer\HookRunner->onSpecialSearchProfileForm()
#7 /includes/search/searchwidgets/SearchFormWidget.php(98): MediaWiki\Search\SearchWidgets\SearchFormWidget->optionsHtml()
#8 /includes/specials/SpecialSearch.php(475): MediaWiki\Search\SearchWidgets\SearchFormWidget->render()
#9 /includes/specials/SpecialSearch.php(229): SpecialSearch->showResults()
#10 /includes/specialpage/SpecialPage.php(701): SpecialSearch->execute()
#11 /includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run()
#12 /includes/MediaWiki.php(316): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#13 /includes/MediaWiki.php(904): MediaWiki->performRequest()
#14 /includes/MediaWiki.php(562): MediaWiki->main()
#15 /index.php(50): MediaWiki->run()
#16 /index.php(46): wfIndexMain()
#17 {main}
```

Since sandbox is an older version 1:35, cannot recreate it there.

It happens here:
https://test.knowledge.wiki/SMW/Schema:Simple_search_profile
https://test.knowledge.wiki/index.php?title=Spezial:Suche (as soon as you select "Extra", whicih results in:
https://test.knowledge.wiki/index.php?title=Spezial:Suche&profile=smw&search=&fulltext=1

Problem will probably be here: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/544b2da94705d29213bfbc2fd7cb2b48155239d1/src/MediaWiki/Search/ProfileForm/Forms/NamespaceForm.php#L119

**Comment by kghbln** [comment]
Commenting `$wgSearchType = 'SMWSearch';` preliminary helped me out of this situation. Cool that a fix is already committed.
