### ISSUE TITLE
Error 1091: Can't DROP 'PRIMARY'

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#5547]
### Setup

- SMW version: 4.1.2
- MW version: 1.39
- PHP version:7.4
- DB system (MySQL, Blazegraph, etc.) and version: MySQL

### Issue

On a wiki that was already upgraded to 1.39 I changed an extension via composer.local.json. Had to delete the vendor directory due to the composer issue described [here ](https://github.com/SemanticMediaWiki/SemanticMetaTags/issues/76)

On update.php (setupStore.php) the following error shows

```
... changing type of field smw_id from 'INT UNSIGNED NOT NULL AUTO_INCREMENT' to 'INT(11) UNSIGNED NOT NULL KEY AUTO_INCREMENT' ... Wikimedia\Rdbms\DBQueryError from line 1618 of /includes/libs/rdbms/database/Database.php: Error 1091: Can't DROP 'PRIMARY'; check that column/key exists
Function: SMW\SQLStore\TableBuilder\MySQLTableBuilder::doUpdateFieldType
Query: ALTER TABLE `smw_object_ids` DROP PRIMARY KEY

#0 /includes/libs/rdbms/database/Database.php(1602): Wikimedia\Rdbms\Database->getQueryException()
#1 /includes/libs/rdbms/database/Database.php(1576): Wikimedia\Rdbms\Database->getQueryExceptionAndLog()
#2 /includes/libs/rdbms/database/Database.php(952): Wikimedia\Rdbms\Database->reportQueryError()
#3 /includes/libs/rdbms/database/DBConnRef.php(103): Wikimedia\Rdbms\Database->query()
#4 /includes/libs/rdbms/database/DBConnRef.php(293): Wikimedia\Rdbms\DBConnRef->__call()
#5 /extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/MySQLTableBuilder.php(231): Wikimedia\Rdbms\DBConnRef->query()
#6 /extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/MySQLTableBuilder.php(201): SMW\SQLStore\TableBuilder\MySQLTableBuilder->doUpdateFieldType()
#7 /extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/MySQLTableBuilder.php(131): SMW\SQLStore\TableBuilder\MySQLTableBuilder->doUpdateField()
#8 /extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/TableBuilder.php(159): SMW\SQLStore\TableBuilder\MySQLTableBuilder->doUpdateTable()
#9 /extensions/SemanticMediaWiki/src/SQLStore/Installer.php(229): SMW\SQLStore\TableBuilder\TableBuilder->create()
#10 /extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(456): SMW\SQLStore\Installer->install()
#11 /extensions/SemanticMediaWiki/src/Store.php(490): SMW\SQLStore\SQLStore->setup()
#12 /includes/installer/DatabaseUpdater.php(547): SMW\Store::setupStore()
#13 /includes/installer/DatabaseUpdater.php(515): DatabaseUpdater->runUpdates()
#14 /maintenance/update.php(209): DatabaseUpdater->doUpdates()
#15 /maintenance/includes/MaintenanceRunner.php(309): UpdateMediaWiki->execute()
#16 /maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#17 /maintenance/update.php(319): require_once('/srv/ma01/wiki/...')
#18 {main}

```

This is unfortunate, since probalby a setupStore.php --delete will help, but after that the whole structure has to be rebuilt again.

**Comment by krabina** [comment]
indeed, deleting the store fixed the problem, but now everything has to be rebuildt again

**Comment by krabina** [comment]
correction. After setupStore --delete, a update.php (that will incluse setupStore.php) is sufficient. If no data has change, no rebuild is required.

**Comment by osnard** [comment]
FYI: I am having the same issue. Going to go with the `setupStore.php --delete` workaround. Thanks for sharing.
