### ISSUE TITLE
API call to `run-entity-examiner` throws exception

### ISSUE THREAD

**Issue by octfx** [SemanticMediaWiki/SemanticMediaWiki#5555]
### Setup

- SMW version: 4.1.2 (master branch)
- MW version: 1.39.5
- PHP version: 8.1
- DB system (MySQL, Blazegraph, etc.) and version: MariaDb

### Issue

Page views try to run the `run-entity-examiner` task. This call started failing with the following exception approx. 2 months ago (?):

```
Exception caught: Invalid language code "{{uselang}}"

MWException at /var/www/html/includes/language/LanguageFactory.php(158)from /var/www/html/includes/language/LanguageFactory.php(158)
#0 /var/www/html/includes/language/LanguageFactory.php(144): MediaWiki\Languages\LanguageFactory->newFromCode(string)
#1 /var/www/html/includes/libs/MapCacheLRU.php(274): MediaWiki\Languages\LanguageFactory->MediaWiki\Languages\{closure}()
#2 /var/www/html/includes/language/LanguageFactory.php(145): MapCacheLRU->getWithSetCallback(string, Closure)
#3 /var/www/html/includes/language/LanguageFactory.php(128): MediaWiki\Languages\LanguageFactory->getRawLanguage(string)
#4 /var/www/html/includes/language/Message.php(840): MediaWiki\Languages\LanguageFactory->getLanguage(string)
#5 /var/www/html/extensions/SemanticMediaWiki/src/Setup.php(243): Message->inLanguage(string)
#6 [internal function]: SMW\Setup->SMW\{closure}(array, string)
#7 /var/www/html/extensions/SemanticMediaWiki/src/Localizer/Message.php(233): call_user_func_array(Closure, array)
#8 /var/www/html/extensions/SemanticMediaWiki/src/Localizer/MessageLocalizerTrait.php(44): SMW\Localizer\Message::get(array, integer, string)
#9 /var/www/html/extensions/SemanticMediaWiki/src/Indicator/EntityExaminerIndicators/EntityExaminerDeferrableCompositeIndicatorProvider.php(229): SMW\Indicator\EntityExaminerIndicators\EntityExaminerDeferrableCompositeIndicatorProvider->msg(string, integer, string)
#10 /var/www/html/extensions/SemanticMediaWiki/src/Indicator/EntityExaminerIndicators/EntityExaminerDeferrableCompositeIndicatorProvider.php(179): SMW\Indicator\EntityExaminerIndicators\EntityExaminerDeferrableCompositeIndicatorProvider->buildHTML(SMW\DIWikiPage, array, array)
#11 /var/www/html/extensions/SemanticMediaWiki/src/Indicator/EntityExaminerIndicators/EntityExaminerDeferrableCompositeIndicatorProvider.php(113): SMW\Indicator\EntityExaminerIndicators\EntityExaminerDeferrableCompositeIndicatorProvider->checkIndicators(SMW\DIWikiPage, array)
#12 /var/www/html/extensions/SemanticMediaWiki/src/Indicator/EntityExaminerIndicators/EntityExaminerCompositeIndicatorProvider.php(142): SMW\Indicator\EntityExaminerIndicators\EntityExaminerDeferrableCompositeIndicatorProvider->hasIndicator(SMW\DIWikiPage, array)
#13 /var/www/html/extensions/SemanticMediaWiki/src/Indicator/EntityExaminerIndicators/EntityExaminerCompositeIndicatorProvider.php(121): SMW\Indicator\EntityExaminerIndicators\EntityExaminerCompositeIndicatorProvider->checkIndicators(SMW\DIWikiPage, array)
#14 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Api/Tasks/EntityExaminerTask.php(82): SMW\Indicator\EntityExaminerIndicators\EntityExaminerCompositeIndicatorProvider->hasIndicator(SMW\DIWikiPage, array)
#15 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Api/Task.php(64): SMW\MediaWiki\Api\Tasks\EntityExaminerTask->process(array)
#16 /var/www/html/includes/api/ApiMain.php(1900): SMW\MediaWiki\Api\Task->execute()
#17 /var/www/html/includes/api/ApiMain.php(875): ApiMain->executeAction()
#18 /var/www/html/includes/api/ApiMain.php(846): ApiMain->executeActionWithErrorHandling()
#19 /var/www/html/api.php(90): ApiMain->execute()
#20 /var/www/html/api.php(45): wfApiMain()
#21 {main}
```

I've purged all caches and rebuild my SMW data, but the error persists. Any clues?

**Comment by paladox** [comment]
We have the same issue.
