### ISSUE TITLE
Invalid language code "{{uselang}}"

### ISSUE THREAD

**Issue by paladox** [SemanticMediaWiki/SemanticMediaWiki#5563]
### Setup

- SMW version: 4.1.2 (e91f265)
- MW version: 1.40.1
- PHP version: 7.4
- DB system (MySQL, Blazegraph, etc.) and version: mariadb 10.5

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

I'm seeing a lot of the below in the log:

```
Invalid language code "{{uselang}}"
from /srv/mediawiki/w/includes/language/LanguageFactory.php(184)
#0 /srv/mediawiki/w/includes/language/LanguageFactory.php(170): MediaWiki\Languages\LanguageFactory->newFromCode(string)
#1 /srv/mediawiki/w/includes/libs/MapCacheLRU.php(273): MediaWiki\Languages\LanguageFactory->MediaWiki\Languages\{closure}()
#2 /srv/mediawiki/w/includes/language/LanguageFactory.php(171): MapCacheLRU->getWithSetCallback(string, Closure)
#3 /srv/mediawiki/w/includes/language/LanguageFactory.php(152): MediaWiki\Languages\LanguageFactory->getRawLanguage(string)
#4 /srv/mediawiki/w/includes/language/Message.php(843): MediaWiki\Languages\LanguageFactory->getLanguage(string)
#5 /srv/mediawiki/w/extensions/SemanticMediaWiki/src/Setup.php(243): Message->inLanguage(string)
#6 [internal function]: SMW\Setup->SMW\{closure}(array, string)
#7 /srv/mediawiki/w/extensions/SemanticMediaWiki/src/Localizer/Message.php(233): call_user_func_array(Closure, array)
#8 /srv/mediawiki/w/extensions/SemanticMediaWiki/src/Localizer/MessageLocalizerTrait.php(44): SMW\Localizer\Message::get(array, integer, string)
#9 /srv/mediawiki/w/extensions/SemanticMediaWiki/src/Indicator/EntityExaminerIndicators/EntityExaminerDeferrableCompositeIndicatorProvider.php(229): SMW\Indicator\EntityExaminerIndicators\EntityExaminerDeferrableCompositeIndicatorProvider->msg(string, integer, string)
#10 /srv/mediawiki/w/extensions/SemanticMediaWiki/src/Indicator/EntityExaminerIndicators/EntityExaminerDeferrableCompositeIndicatorProvider.php(179): SMW\Indicator\EntityExaminerIndicators\EntityExaminerDeferrableCompositeIndicatorProvider->buildHTML(SMW\DIWikiPage, array, array)
#11 /srv/mediawiki/w/extensions/SemanticMediaWiki/src/Indicator/EntityExaminerIndicators/EntityExaminerDeferrableCompositeIndicatorProvider.php(113): SMW\Indicator\EntityExaminerIndicators\EntityExaminerDeferrableCompositeIndicatorProvider->checkIndicators(SMW\DIWikiPage, array)
#12 /srv/mediawiki/w/extensions/SemanticMediaWiki/src/Indicator/EntityExaminerIndicators/EntityExaminerCompositeIndicatorProvider.php(142): SMW\Indicator\EntityExaminerIndicators\EntityExaminerDeferrableCompositeIndicatorProvider->hasIndicator(SMW\DIWikiPage, array)
#13 /srv/mediawiki/w/extensions/SemanticMediaWiki/src/Indicator/EntityExaminerIndicators/EntityExaminerCompositeIndicatorProvider.php(121): SMW\Indicator\EntityExaminerIndicators\EntityExaminerCompositeIndicatorProvider->checkIndicators(SMW\DIWikiPage, array)
#14 /srv/mediawiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Api/Tasks/EntityExaminerTask.php(82): SMW\Indicator\EntityExaminerIndicators\EntityExaminerCompositeIndicatorProvider->hasIndicator(SMW\DIWikiPage, array)
#15 /srv/mediawiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Api/Task.php(64): SMW\MediaWiki\Api\Tasks\EntityExaminerTask->process(array)
#16 /srv/mediawiki/w/includes/api/ApiMain.php(1903): SMW\MediaWiki\Api\Task->execute()
#17 /srv/mediawiki/w/includes/api/ApiMain.php(880): ApiMain->executeAction()
#18 /srv/mediawiki/w/includes/api/ApiMain.php(851): ApiMain->executeActionWithErrorHandling()
#19 /srv/mediawiki/w/api.php(91): ApiMain->execute()
#20 /srv/mediawiki/w/api.php(46): wfApiMain()
#21 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

I'm not sure how to reproduce. The log states it happens on /api.php but just visiting that doesn't trigger it.

**Comment by jaideraf** [comment]
See also: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5555
