### ISSUE TITLE
rebuilding data should not fail when geojson is involved

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#5590]
### Setup

- [MediaWiki](https://www.mediawiki.org/) 	[1.39.6](https://www.mediawiki.org/wiki/MediaWiki_1.39) [(0aca08f)](https://gerrit.wikimedia.org/g/mediawiki/core.git/+/0aca08f86e948be73956298c6677a0d4af23b3a6) 16:49, 16. Jan. 2024
- [PHP](https://php.net/) 	7.4.33 (apache2handler)
- [MariaDB](https://mariadb.org/) 	10.5.21-MariaDB-0+deb11u1
- [Semantic MediaWiki](https://www.semantic-mediawiki.org/)	4.1.2
- [Maps](https://maps.extension.wiki/)	10.1.1

### Issue
```
[no req]   ParseError: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)
```
Happens when trying to rebuild https://smwtest.wikihoster.net/w/index.php?title=GeoJson:20201101&action=edit

Perhaps https://github.com/ProfessionalWiki/Maps/issues/734 is at play.

### Backtrace
from /../w/extensions/Maps/src/GeoJsonPages/Semantic/SubObjectBuilder.php(25)
```
#0 [internal function]: AutoLoader::autoload()
#1 /../w/extensions/Maps/src/MapsFactory.php(243): spl_autoload_call()
#2 /../w/extensions/Maps/src/GeoJsonPages/GeoJsonContentHandler.php(50): Maps\MapsFactory->newSemanticGeoJsonStore()
#3 /../w/includes/content/ContentHandler.php(1721): Maps\GeoJsonPages\GeoJsonContentHandler->fillParserOutput()
#4 /../w/includes/content/Renderer/ContentRenderer.php(47): ContentHandler->getParserOutput()
#5 /../w/extensions/SemanticMediaWiki/includes/ContentParser.php(168): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput()
#6 /../w/extensions/SemanticMediaWiki/includes/ContentParser.php(130): SMW\ContentParser->fetchFromContent()
#7 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(199): SMW\ContentParser->parse()
#8 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(139): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#9 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#10 /../w/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(247): SMW\MediaWiki\Jobs\UpdateJob->run()
#11 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(472): SMW\SQLStore\Rebuilder\Rebuilder->rebuild()
#12 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(385): SMW\Maintenance\DataRebuilder->doUpdateById()
#13 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(224): SMW\Maintenance\DataRebuilder->rebuildAll()
#14 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#15 /../w/maintenance/includes/MaintenanceRunner.php(309): SMW\Maintenance\rebuildData->execute()
#16 /../w/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#17 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once(string)
#18 {main}
```

**Comment by Nikerabbit** [comment]
I assume this got fixed in the Maps extension(?).
