### ISSUE TITLE
2024-04-16 05:22:52: 类型“Error”的致命异常

### ISSUE THREAD

**Issue by Zacharia2** [SemanticMediaWiki/SemanticMediaWiki#5626]
### Setup

- SMW version:4.1
- MW version:1.41.1
- PHP version:php8.0.2nts
- DB system (MySQL, Blazegraph, etc.) and version:MySQL8.0.12

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

![image](https://github.com/SemanticMediaWiki/SemanticMediaWiki/assets/32425955/12954bce-303f-4459-9684-c51cadb8550e)

After installing MW, I used `composer require mediawiki/semantic-media-wiki` to install SMW. After the installation was complete, I encountered an error when logging into my account.

安装完成MW之后，使用`composer require mediawiki/semantic-media-wiki`安装SMW，安装完成之后登录账户时发生错误。

```
[26e8d7eb41f1ea506fc22336] 2024-04-16 05:22:52: 类型“Error”的致命异常
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

1. I installed MW 1.41.1 and configured it. Then I logged in, and everything was normal.
2. Then I executed `composer require mediawiki/semantic-media-wiki` and restarted the server. After that, I opened MediaWiki and clicked on the login button.
3. An error occurred [26e8d7eb41f1ea506fc22336] 2024-04-16 05:22:52: A fatal error of type "Error".

1. 新安装MW1.41.1，配置好，登录。这时候是正常的。
2. 然后执行`composer require mediawiki/semantic-media-wiki`重启服务器，打开mw，点击登录
3. 问题发生[26e8d7eb41f1ea506fc22336] 2024-04-16 05:22:52: 类型“Error”的致命异常

**Comment by Nikerabbit** [comment]
See https://www.mediawiki.org/wiki/Manual:How_to_debug

**Comment by Zacharia2** [comment]
thanks

**Comment by Zacharia2** [comment]
The issue has been resolved. I opened the debug and found that the problem was caused by the AbuseFilter. It works normally after I turn it off.


```php
$wgShowExceptionDetails = true;
$wgDebugToolbar = true;
// $wgDevelopmentWarnings = true;
```

```php
wfLoadExtension( 'AbuseFilter' );
```

```
[b546434537af67b87a2cd065] /index.php?title=%E7%89%B9%E6%AE%8A:%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95&returnto=%E9%A6%96%E9%A1%B5 Error: Class "Wikimedia\Equivset\Equivset" not found

Backtrace:

from D:\phpstudy_pro\mediawiki-1.41.1\extensions\AbuseFilter\includes\ServiceWiring.php(125)
#0 D:\phpstudy_pro\mediawiki-1.41.1\vendor\wikimedia\services\src\ServiceContainer.php(447): Wikimedia\Services\ServiceContainer::{closure}()
#1 D:\phpstudy_pro\mediawiki-1.41.1\vendor\wikimedia\services\src\ServiceContainer.php(411): Wikimedia\Services\ServiceContainer->createService()
#2 D:\phpstudy_pro\mediawiki-1.41.1\includes\MediaWikiServices.php(351): Wikimedia\Services\ServiceContainer->getService()
#3 D:\phpstudy_pro\mediawiki-1.41.1\vendor\wikimedia\services\src\ServiceContainer.php(419): MediaWiki\MediaWikiServices->getService()
#4 D:\phpstudy_pro\mediawiki-1.41.1\extensions\AbuseFilter\includes\ServiceWiring.php(292): Wikimedia\Services\ServiceContainer->get()
#5 D:\phpstudy_pro\mediawiki-1.41.1\vendor\wikimedia\services\src\ServiceContainer.php(447): Wikimedia\Services\ServiceContainer::{closure}()
#6 D:\phpstudy_pro\mediawiki-1.41.1\vendor\wikimedia\services\src\ServiceContainer.php(411): Wikimedia\Services\ServiceContainer->createService()
#7 D:\phpstudy_pro\mediawiki-1.41.1\includes\MediaWikiServices.php(351): Wikimedia\Services\ServiceContainer->getService()
#8 D:\phpstudy_pro\mediawiki-1.41.1\vendor\wikimedia\services\src\ServiceContainer.php(419): MediaWiki\MediaWikiServices->getService()
#9 D:\phpstudy_pro\mediawiki-1.41.1\vendor\wikimedia\object-factory\src\ObjectFactory.php(204): Wikimedia\Services\ServiceContainer->get()
#10 D:\phpstudy_pro\mediawiki-1.41.1\vendor\wikimedia\object-factory\src\ObjectFactory.php(149): Wikimedia\ObjectFactory\ObjectFactory::getObjectFromSpec()
#11 D:\phpstudy_pro\mediawiki-1.41.1\includes\auth\AuthManager.php(2496): Wikimedia\ObjectFactory\ObjectFactory->createObject()
#12 D:\phpstudy_pro\mediawiki-1.41.1\includes\auth\AuthManager.php(2528): MediaWiki\Auth\AuthManager->providerArrayFromSpecs()
#13 D:\phpstudy_pro\mediawiki-1.41.1\includes\auth\AuthManager.php(2213): MediaWiki\Auth\AuthManager->getPreAuthenticationProviders()
#14 D:\phpstudy_pro\mediawiki-1.41.1\includes\specialpage\AuthManagerSpecialPage.php(290): MediaWiki\Auth\AuthManager->getAuthenticationRequests()
#15 D:\phpstudy_pro\mediawiki-1.41.1\includes\specialpage\LoginSignupSpecialPage.php(160): MediaWiki\SpecialPage\AuthManagerSpecialPage->loadAuth()
#16 D:\phpstudy_pro\mediawiki-1.41.1\includes\specialpage\LoginSignupSpecialPage.php(252): MediaWiki\SpecialPage\LoginSignupSpecialPage->load()
#17 D:\phpstudy_pro\mediawiki-1.41.1\includes\specialpage\SpecialPage.php(727): MediaWiki\SpecialPage\LoginSignupSpecialPage->execute()
#18 D:\phpstudy_pro\mediawiki-1.41.1\includes\specialpage\SpecialPageFactory.php(1621): MediaWiki\SpecialPage\SpecialPage->run()
#19 D:\phpstudy_pro\mediawiki-1.41.1\includes\MediaWiki.php(357): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#20 D:\phpstudy_pro\mediawiki-1.41.1\includes\MediaWiki.php(960): MediaWiki->performRequest()
#21 D:\phpstudy_pro\mediawiki-1.41.1\includes\MediaWiki.php(613): MediaWiki->main()
#22 D:\phpstudy_pro\mediawiki-1.41.1\index.php(50): MediaWiki->run()
#23 D:\phpstudy_pro\mediawiki-1.41.1\index.php(46): wfIndexMain()
#24 {main}
```

**Comment by Zacharia2** [comment]
Thank you very much for your advice.
