### ISSUE TITLE
MediaWiki 1.43 DBAL compatibility

### ISSUE THREAD

**Issue by osnard** [SemanticMediaWiki/SemanticMediaWiki#5634]
### Setup

- SMW version: master branch at #f6b3855f
- MW version: 1.43.0-wmf.2 (pre-release)
- PHP version: 8.1.20 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.11.4-MariaDB-1:10.11.4+maria~ubu2204

### Issue

During the Wikimedia Hackathon 2024, I tried to run the latest version of Semantic MediaWiki on a pre-release version of MediaWiki 1.43 (upcomming LTS). The goal was to identify issues and maybe provide patches right away. Unfortunately, the available time will not allow to provide a fix, therefore I document the issue here. 

First: Installation (running `maintenance/run.php update`) and activation of the extension ran smoothly, No immediate error.

But when trying to access `Special:Browse` the API call with the parameters

```
action: smwbrowse
format: json
browse: subject
params: {"subject":"Main_Page","ns":0,"iw":"","subobject":"","options":{"dir":null,"lang":"en","group":null,"printable":null,"offset":null,"including":false,"showInverse":false,"showAll":true,"showGroup":true,"showSort":false,"api":true,"valuelistlimit.out":"30","valuelistlimit.in":"20"},"type":"html"}
```

failed with the error
```
Exception caught: Table name component contains unexpected quote or dot character

"Wikimedia\\Rdbms\\DBLanguageError at /includes/libs/rdbms/platform/SQLPlatform.php(1051)
from /includes/libs/rdbms/platform/SQLPlatform.php(1051)
#0 /includes/libs/rdbms/platform/SQLPlatform.php(991): Wikimedia\\Rdbms\\Platform\\SQLPlatform->extractTableNameComponents(string)
#1 /includes/libs/rdbms/platform/SQLPlatform.php(957): Wikimedia\\Rdbms\\Platform\\SQLPlatform->qualifiedTableComponents(string)
#2 /includes/libs/rdbms/platform/SQLPlatform.php(936): Wikimedia\\Rdbms\\Platform\\SQLPlatform->tableName(string)
#3 /includes/libs/rdbms/platform/SQLPlatform.php(837): Wikimedia\\Rdbms\\Platform\\SQLPlatform->tableNameWithAlias(string, string)
#4 /includes/libs/rdbms/platform/SQLPlatform.php(666): Wikimedia\\Rdbms\\Platform\\SQLPlatform->tableNamesWithIndexClauseOrJOIN(array, array, array, array)
#5 /includes/libs/rdbms/database/Database.php(3335): Wikimedia\\Rdbms\\Platform\\SQLPlatform->selectSQLText(string, string, string, string, array, array)
#6 /includes/libs/rdbms/database/DatabaseMySQL.php(730): Wikimedia\\Rdbms\\Database->selectSQLText(string, string, string, string, array, array)
#7 /includes/libs/rdbms/database/Database.php(1342): Wikimedia\\Rdbms\\DatabaseMySQL->selectSQLText(string, string, string, string, array, array)
#8 /includes/libs/rdbms/database/DBConnRef.php(126): Wikimedia\\Rdbms\\Database->select(string, string, string, string, array, array)
#9 /includes/libs/rdbms/database/DBConnRef.php(358): Wikimedia\\Rdbms\\DBConnRef->__call(string, array)
#10 /extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(247): Wikimedia\\Rdbms\\DBConnRef->select(string, string, string, string, array, array)
#11 /extensions/SemanticMediaWiki/src/SQLStore/EntityStore/TraversalPropertyLookup.php(97): SMW\\MediaWiki\\Connection\\Database->select(string, string, string, string, array)
#12 /extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityLookup.php(437): SMW\\SQLStore\\EntityStore\\TraversalPropertyLookup->fetchFromTable(SMW\\SQLStore\\PropertyTableDefinition, SMW\\DIWikiPage, SMW\\RequestOptions)
#13 /extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(289): SMW\\SQLStore\\EntityStore\\EntityLookup->getInProperties(SMW\\DIWikiPage, SMW\\RequestOptions)
#14 /extensions/SemanticMediaWiki/src/MediaWiki/Specials/Browse/HtmlBuilder.php(876): SMW\\SQLStore\\SQLStore->getInProperties(SMW\\DIWikiPage, SMW\\RequestOptions)
#15 /extensions/SemanticMediaWiki/src/MediaWiki/Specials/Browse/HtmlBuilder.php(355): SMW\\MediaWiki\\Specials\\Browse\\HtmlBuilder->getInData()
#16 /extensions/SemanticMediaWiki/src/MediaWiki/Specials/Browse/HtmlBuilder.php(263): SMW\\MediaWiki\\Specials\\Browse\\HtmlBuilder->createHTML()
#17 /extensions/SemanticMediaWiki/src/MediaWiki/Api/Browse/SubjectLookup.php(107): SMW\\MediaWiki\\Specials\\Browse\\HtmlBuilder->buildHTML()
#18 /extensions/SemanticMediaWiki/src/MediaWiki/Api/Browse/SubjectLookup.php(69): SMW\\MediaWiki\\Api\\Browse\\SubjectLookup->buildHTML(array)
#19 /extensions/SemanticMediaWiki/src/MediaWiki/Api/Browse.php(268): SMW\\MediaWiki\\Api\\Browse\\SubjectLookup->lookup(array)
#20 /extensions/SemanticMediaWiki/src/MediaWiki/Api/Browse.php(71): SMW\\MediaWiki\\Api\\Browse->callSubjectLookup(array)
#21 /includes/api/ApiMain.php(1948): SMW\\MediaWiki\\Api\\Browse->execute()
#22 /includes/api/ApiMain.php(924): ApiMain->executeAction()
#23 /includes/api/ApiMain.php(895): ApiMain->executeActionWithErrorHandling()
#24 /includes/api/ApiEntryPoint.php(158): ApiMain->execute()
#25 /includes/MediaWikiEntryPoint.php(199): MediaWiki\\Api\\ApiEntryPoint->execute()
#26 /api.php(44): MediaWiki\\MediaWikiEntryPoint->run()
```

Apparently the code at

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/f6b3855f83faefb9c0f085486c0a2fd8f8a1f95a/src/SQLStore/EntityStore/TraversalPropertyLookup.php#L96-L102

gets called with `$from = "`smw_object_ids` INNER JOIN ( SELECT p_id FROM `smw_di_wikipage`  WHERE o_id=0  GROUP BY p_id ) AS t1 ON t1.p_id=smw_id"`, which is not allowed in the MediaWiki 1.43 DBAL anymore.

Wikimedia engineer Ladsgroup recommended to use the new "query builder" (in this particular case `SelectQueryBuilder`, see https://www.mediawiki.org/wiki/Manual:Database_access#SelectQueryBuilder) implementation of MediaWiki.

I can not tell how much code in Semantic MediaWiki is actually affected by this, but there are ~27 files that contain the `INNER JOIN` syntax.

**Comment by osnard** [comment]
I have created the draft PR #5636
It does not work yet, but roughly shows the direction. I believe the task contains two main items:
1. Make new MW43 DBAL factory methods (`new*QueryBuilder()`) available from `SMW\Connection\ConnectionRef` or `SMW\MediaWiki\Connection\Database`
2. Rewrite all problematic queries (most likely the ones with an `INNER JOIN` on a subquery) to MW43 DBAL

**Comment by Nikerabbit** [comment]
FYI: SelectQueryBuilder was introduced long time ago: https://gerrit.wikimedia.org/r/c/mediawiki/core/+/566127. It's only now that everything is getting migrated over. The other query builders or some special features have been introduced later.

**Comment by kghbln** [comment]
This has already started to be an issue with MW 1.42.x (#5663)

**Comment by Sheep-y** [comment]
Got similar error when testing a simple #ask on a new setup.
No join, just simple alias.  The table string is built like this:

    $qobj = $this->querySegmentList[$rootid];
    $connection->tableName( $qobj->joinTable ) . " AS $qobj->alias" . $qobj->from
    // Result: `mw_smw_object_ids` AS t0

MediaWiki 1.42.1
Semantic MediaWiki 4.1.3
PHP 8.3.6

Stacktrace:

```
Wikimedia\Rdbms\DBLanguageError: Table name component contains unexpected quote or dot character

Backtrace:

from \includes\libs\rdbms\platform\SQLPlatform.php(1051)
#0 \includes\libs\rdbms\platform\SQLPlatform.php(991): Wikimedia\Rdbms\Platform\SQLPlatform->extractTableNameComponents(string)
#1 \includes\libs\rdbms\platform\SQLPlatform.php(957): Wikimedia\Rdbms\Platform\SQLPlatform->qualifiedTableComponents(string)
#2 \includes\libs\rdbms\platform\SQLPlatform.php(936): Wikimedia\Rdbms\Platform\SQLPlatform->tableName(string)
#3 \includes\libs\rdbms\platform\SQLPlatform.php(837): Wikimedia\Rdbms\Platform\SQLPlatform->tableNameWithAlias(string, string)
#4 \includes\libs\rdbms\platform\SQLPlatform.php(665): Wikimedia\Rdbms\Platform\SQLPlatform->tableNamesWithIndexClauseOrJOIN(array, array, array, array)
#5 \includes\libs\rdbms\database\Database.php(3334): Wikimedia\Rdbms\Platform\SQLPlatform->selectSQLText(string, string, string, string, array, array)
#6 \includes\libs\rdbms\database\DatabaseMySQL.php(730): Wikimedia\Rdbms\Database->selectSQLText(string, string, string, string, array, array)
#7 \includes\libs\rdbms\database\Database.php(1342): Wikimedia\Rdbms\DatabaseMySQL->selectSQLText(string, string, string, string, array, array)
#8 \includes\libs\rdbms\database\DBConnRef.php(119): Wikimedia\Rdbms\Database->select(string, string, string, string, array, array)
#9 \includes\libs\rdbms\database\DBConnRef.php(351): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#10 \extensions\SemanticMediaWiki\src\MediaWiki\Connection\Database.php(246): Wikimedia\Rdbms\DBConnRef->select(string, string, string, string, array, array)
#11 \extensions\SemanticMediaWiki\src\SQLStore\QueryEngine\QueryEngine.php(413): SMW\MediaWiki\Connection\Database->select(string, string, string, string, array)
#12 \extensions\SemanticMediaWiki\src\SQLStore\QueryEngine\QueryEngine.php(225): SMW\SQLStore\QueryEngine\QueryEngine->getInstanceQueryResult(SMWQuery, integer)
#13 \extensions\SemanticMediaWiki\src\SQLStore\SQLStore.php(393): SMW\SQLStore\QueryEngine\QueryEngine->getQueryResult(SMWQuery)
#14 \extensions\SemanticMediaWiki\src\SQLStore\SQLStore.php(381): SMW\SQLStore\SQLStore->fetchQueryResult(SMWQuery)
#15 \extensions\SemanticMediaWiki\includes\query\SMW_QueryProcessor.php(338): SMW\SQLStore\SQLStore->getQueryResult(SMWQuery)
#16 \extensions\SemanticMediaWiki\src\ParserFunctions\AskParserFunction.php(366): SMWQueryProcessor::getResultFromQuery(SMWQuery, array, integer, integer)
#17 \extensions\SemanticMediaWiki\src\ParserFunctions\AskParserFunction.php(201): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array, array)
#18 \extensions\SemanticMediaWiki\src\ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse(array)
#19 \includes\parser\Parser.php(3445): SMW\ParserFunctionFactory->SMW\{closure}(MediaWiki\Parser\Parser, string, string)
#20 \includes\parser\Parser.php(3130): MediaWiki\Parser\Parser->callParserFunction(PPFrame_Hash, string, array)
#21 \includes\parser\PPFrame_Hash.php(275): MediaWiki\Parser\Parser->braceSubstitution(array, PPFrame_Hash)
#22 \includes\parser\Parser.php(2964): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#23 \includes\parser\Parser.php(1614): MediaWiki\Parser\Parser->replaceVariables(string)
#24 \includes\parser\Parser.php(722): MediaWiki\Parser\Parser->internalParse(string)
#25 \includes\content\WikitextContentHandler.php(376): MediaWiki\Parser\Parser->parse(string, MediaWiki\Title\Title, ParserOptions, boolean, boolean, NULL)
#26 \includes\content\ContentHandler.php(1663): WikitextContentHandler->fillParserOutput(WikitextContent, MediaWiki\Content\Renderer\ContentParseParams, MediaWiki\Parser\ParserOutput)
#27 \includes\content\Renderer\ContentRenderer.php(67): ContentHandler->getParserOutput(WikitextContent, MediaWiki\Content\Renderer\ContentParseParams)
#28 \includes\editpage\EditPage.php(4167): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput(WikitextContent, MediaWiki\Title\Title, NULL, ParserOptions)
#29 \includes\editpage\EditPage.php(4070): MediaWiki\EditPage\EditPage->doPreviewParse(WikitextContent)
#30 \includes\editpage\EditPage.php(2950): MediaWiki\EditPage\EditPage->getPreviewText()
#31 \includes\editpage\EditPage.php(769): MediaWiki\EditPage\EditPage->showEditForm()
#32 \includes\actions\EditAction.php(66): MediaWiki\EditPage\EditPage->edit()
#33 \includes\actions\SubmitAction.php(38): EditAction->show()
#34 \includes\actions\ActionEntryPoint.php(733): SubmitAction->show()
#35 \includes\actions\ActionEntryPoint.php(510): MediaWiki\Actions\ActionEntryPoint->performAction(SMW\MediaWiki\Page\PropertyPage, MediaWiki\Title\Title)
#36 \includes\actions\ActionEntryPoint.php(145): MediaWiki\Actions\ActionEntryPoint->performRequest()
#37 \includes\MediaWikiEntryPoint.php(199): MediaWiki\Actions\ActionEntryPoint->execute()
#38 \index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#39 {main}
```

**Comment by Disgustedorite** [comment]
Miraheze just updated to MediaWiki 1.43 yesterday, breaking every single wiki that uses SMW, and they say they cannot downgrade the affected wikis. Is there an ETA on if or when this issue might be fixed?

**Comment by Sheep-y** [comment]
> Miraheze just updated yesterday, breaking every single wiki that uses SMW, and they say they cannot downgrade the affected wikis; it appears to be the same issue as this. Is there an ETA on if or when this issue might be fixed?

Here is a fork that I've been working on for a few days.
https://github.com/Sheep-y/SemanticMediaWiki-MW14

A few caveats:
* It is based on SMW `master` branch, meaning it is not based on a stable release.
* Can't get unit test to work.  MW tests can run, but not SMW tests.
* Manual test covered all prop types, and/or/</>/~/!~, sub properties/object/query, property chain etc.
* Tested on MW 1.39.8 and MW 1.42.1, but not the in-betweens.  SMW extensions not tested.
* `format=debug` and `format=count` has been refactored to share the same query code as other formats.

How to update:
* I just download and overwrite SMW code, then run update.php and rebuildData.php.
* There may be deprecated warnings, but they don't break the wiki and are more difficult to fix.

**Comment by Disgustedorite** [comment]
The miraheze staff are telling me the only issue is the use of backticks.

**Comment by Sheep-y** [comment]
> The miraheze staff are telling me the only issue is the use of backticks.

Backticks are required to property quote table names.  Table prefix is customisable, the names must be quoted, or the query need to be built with Rdbms (which does the quoting).  If it's a simple query on a single table then it is a simple change, but SMW #ask can generate pretty complicated joins which cannot just "remove backticks", and it's the focus of my fix.

**Comment by Disgustedorite** [comment]
> > The miraheze staff are telling me the only issue is the use of backticks.
> 
> Backticks are required to property quote table names. Table prefix is customisable, so the names must be quoted one way or the other. If it's a simple query on a single table then yes the quoting can be easily removed for the first param of `Database->select`, which would do it for us. But SMW #ask can generate pretty complicated joins which cannot just "remove backticks", and it's the focus of my fix.

Apologies if I'm not understanding something fundamental, but other mediawiki extensions appear to use regular apostrophes for this and have not been broken by the update. Is there a reason that isn't an option here?

**Comment by Sheep-y** [comment]
> Apologies if I'm not understanding something fundamental, but other mediawiki extensions appear to use regular apostrophes for this and have not been broken by the update. Is there a reason that isn't an option here?

Yes it is something fundamental.  May be try this?
https://stackoverflow.com/questions/11321491/when-to-use-single-quotes-double-quotes-and-backticks-in-mysql

Do note that MW and it extensions don't (shouldn't) hardcode backticks in the queries, because it's only used by MySQL clones and MW/SMW needs to support other databases.  Each major database linage has their own way to quote identifiers, and it is a burden on extensions, which Rdbms is trying to solve.

**Comment by physikerwelt** [comment]
I checked out #5679, and it solved my problem. For example, the page https://wiki.physikerwelt.de/wiki/Kernunfall did lead to a fatal 500 before. Now, it only has a warning and some detailed problems (which is not unexpected as the last version was created more than ten years ago).

**Comment by Sheep-y** [comment]
> I checked out #5679, and it solved my problem. For example, the page https://wiki.physikerwelt.de/wiki/Kernunfall did lead to a fatal 500 before. Now, it only has a warning and some detailed problems (which is not unexpected as the last version was created more than ten years ago).

The deprecation warning is easily to fixed with a version check, or on your own wiki change the line from `->getConnectionRef(` to `->getConnection(`.  I'm holding off pushing my change, to see if I have time to review some of the failed tests.

Otherwise the page looks decent.  Semantic properties (from template) are defined, and the raw code `{{arraymap:...}}` should be solvable by installing the [Page Forms](https://www.mediawiki.org/wiki/Extension:Page_Forms) extension and adding a hash (i.e. `{{#arraymap:...}}`).

**Comment by cambks** [comment]
Will the fix be packaged into a new release? Or should I not wait and clone the repo with the fix?

I'm running MW 1.42.0, SMW 4.2.0, and PHP 8.2.20 and an "ask" is throwing the error "[9b1a954a260e1fb8f89c1c10] /index.php?title=Semantic_Test_2&action=submit Wikimedia\Rdbms\DBLanguageError: Table name component contains unexpected quote or dot character".

**Comment by squirrelslair** [comment]
Has the fix been added to the main version of SMW, and if not, do we know when that will happen? Thanks!

**Comment by krabina** [comment]
The fix was merged into master, so you can test the master branch and let us know if it fixes it for you.

**Comment by reschultzed** [comment]
> The fix was merged into master, so you can test the master branch and let us know if it fixes it for you.

It was? #5679 is still open, and I don't see any recent commits that would relate.

**Comment by krabina** [comment]
sorry, my mistake. It was not merged.

**Comment by xXBlackHawkXx** [comment]
Is there any progress on this?

**Comment by JeroenDeDauw** [comment]
Someone just needs to rebase this and open a new PR

**Comment by Seb35** [comment]
Last Friday, I reviewed all calls to `SMW\MediaWiki\Connection\Database::select()` in SMW 4.2.0, there are 60 calls in 48 files. Most of them are compatible with MW 1.42 because they use simple table names without JOINs, only 3 calls are problematic:
* [src/SQLStore/EntityStore/TraversalPropertyLookup.php](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/4.2.0/src/SQLStore/EntityStore/TraversalPropertyLookup.php)
* [src/SQLStore/RedirectStore.php](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/4.2.0/src/SQLStore/RedirectStore.php)
* [src/SQLStore/QueryEngine/QueryEngine.php](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/4.2.0/src/SQLStore/QueryEngine/QueryEngine.php) indirectly with the SQL query created by QuerySegment

I prepared an alternative PR trying not to use the MW QueryBuilder to stick to `SMW\MediaWiki\Connection\Database::select()`, at least in the short-term to reuse most of the existing SMW database wrapper, it is almost possible except for TraversalPropertyLookup where a `Wikimedia\Rdbms\Subquery` is needed. To construct the SQL query for QueryEngine, I added two properties in QuerySegment (`string[] fromTables` and `string[][] joinConditions`) to pass these parameters to `select()`.

I adapt my PR to SMW master and send it.

**Comment by Seb35** [comment]
> Last Friday, I reviewed all calls to `SMW\MediaWiki\Connection\Database::select()` in SMW 4.2.0, there are 60 calls in 48 files.
I my review, I noted also the following details, which could be changed independently of this issue:
* for the first parameter of `SMW\MediaWiki\Connection::select()`, it is sometimes used `$db->tableName( $tableName )` and sometimes just `$tableName`: both values are equivalent since MediaWiki manages the escape + table prefix
* there are multiple calls to `select()` where the table name is a string like `'myTableName AS myAlias'`: it may be converted to `[ 'myAlias' => 'myTableName' ]`
* the second parameter of `select()` is sometimes a string like `'page_id,page_title,page_namespace'`, it may be converted to `[ 'page_id', 'page_title', 'page_namespace' ]`
* in the longer term and when it will be sufficiently stable in MW, the WHERE conditions may be converted to `Wikimedia\Rdbms\IExpression`, it was introduced in MW 1.42, see [this task](https://phabricator.wikimedia.org/T210206) for details.

**Comment by Seb35** [comment]
Given the PR #5715 was merged, it works now with MW 1.42 and 1.43. It does not use the QueryBuilder, but it may be introduced if desired.

**Comment by osnard** [comment]
Looks like legacy constant `DB_MASTER` has also been removed (https://gerrit.wikimedia.org/r/c/mediawiki/core/+/1065983)

```
root@cd00e484f8c6:/data/codebase/w# php maintenance/run update --quick --skip-config-validation
PHP Fatal error:  Uncaught Error: Undefined constant "DB_MASTER" in /data/codebase/w/extensions/SemanticMediaWiki/includes/DefaultSettings.php:185
Stack trace:
#0 /data/codebase/w/extensions/SemanticMediaWiki/includes/DefaultSettings.php(2516): SemanticMediaWiki::{closure}()
#1 /data/codebase/w/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php(668): include('...')
#2 /data/codebase/w/extensions/SemanticMediaWiki/includes/SemanticMediaWiki.php(680): SemanticMediaWiki::getDefaultSettings()
#3 /data/codebase/w/extensions/SemanticMediaWiki/includes/GlobalFunctions.php(222): SemanticMediaWiki::setupGlobals()
#4 /data/codebase/w/LocalSettings.php(134): enableSemantics()
#5 /data/codebase/w/includes/Setup.php(219): require_once('...')
#6 /data/codebase/w/maintenance/run.php(49): require_once('...')
#7 /data/codebase/w/maintenance/run(3): require('...')
#8 {main}
  thrown in /data/codebase/w/extensions/SemanticMediaWiki/includes/DefaultSettings.php on line 185
```
I'll provide a patch. Should I create a dedicated issue for this?

**Comment by jaideraf** [comment]
@cambks in your `composer.local.json` file, set 

`"mediawiki/semantic-media-wiki": "dev-master"`

then, in your MediaWiki directory, run `composer update --no-dev` 

and maybe run `php maintenance/run.php update.php` after

**Comment by cambks** [comment]
@jaideraf Yes! That worked to do the upgrade and the upgrade worked to clear the bug.

One small question - Special:Version still shows SMW at version 4.2.0. I guess the master is still 4.2.0 until packaged into a new release, right?

Okay, I'm in business now. Thank you for your help.

**Comment by Ferdi265** [comment]
Apparently #5715 forgot one file: DependencyLinksValidator.php.

When enabling `$smwgEnabledQueryDependencyLinksStore = true;` on MW 1.42.x this leads to an error complaining about quotes in table names.

```patch
diff --git a/src/SQLStore/QueryDependency/DependencyLinksValidator.php b/src/SQLStore/QueryDependency/DependencyLinksValidator.php
index a4fdb53c..0b4393e9 100644
--- a/src/SQLStore/QueryDependency/DependencyLinksValidator.php
+++ b/src/SQLStore/QueryDependency/DependencyLinksValidator.php
@@ -119,7 +119,7 @@ class DependencyLinksValidator {
                $id_table = $connection->tableName( SQLStore::ID_TABLE );
 
                $rows = $connection->select(
-                       [ $proptables[$tableid]->getName(), $id_table . ' AS p', $id_table . ' AS v' ],
+                       [ $proptables[$tableid]->getName(), "p" => SQLStore::ID_TABLE, "v" => SQLStore::ID_TABLE ],
                        [
                                'v.smw_id', 'v.smw_subobject', 'v.smw_touched'
                        ],
@@ -169,7 +169,7 @@ class DependencyLinksValidator {
                $links_table = $connection->tableName( SQLStore::QUERY_LINKS_TABLE );
 
                $row = $connection->selectRow(
-                       [ SQLStore::ID_TABLE, $links_table . ' AS p' ],
+                       [ SQLStore::ID_TABLE, "p" => SQLStore::QUERY_LINKS_TABLE ],
                        [
                                'smw_id'
                        ],
```

**Comment by reschultzed** [comment]
Is there any sense of what still needs to be done to implement this fix in a stable release version? Some SMW users, including myself and the entire Miraheze community, are unable to apply patches locally.

**Comment by paladox** [comment]
@kghbln / @JeroenDeDauw can we release a new version please?

**Comment by JeroenDeDauw** [comment]
I put a task on my TODO list to prep for the 5.0 release

**Comment by paladox** [comment]
> I put a task on my TODO list to prep for the 5.0 release

Can we create a minor release containing the fix as well please :)?

**Comment by JeroenDeDauw** [comment]
Why? Can't you use 5.0?

**Comment by reschultzed** [comment]
Would a minor release be available sooner than waiting for 5.0? I think that's the concern that some of us have, since not all of us can install a patch and have been waiting for a release that fixes this

**Comment by paladox** [comment]
> Why? Can't you use 5.0?

5.0 sounds like a major upgrade and wasn’t sure if it would be easily upgraded without needing to do sql or any other changes.

**Comment by gesinn-it-gea** [comment]
This project follows https://semver.org/ In case there has been breaking changes committed already, 5.x is required. This helps others to understand the release. The numbering is not simply arbitrary.

**Comment by alistair3149** [comment]
I can still produce the `Exception caught: Table name component contains unexpected quote or dot character` issue on c20d220d9b7d34b0f402b587b85781a917e0d705 of the 5.0 release. There isn't a stack trace attached so I don't know where to look for the error, but perhaps #5953 will fix it.

**Comment by jaideraf** [comment]
@alistair3149 can't you test the `feat-querybuilder` branch to confirm if it fixes?

**Comment by alistair3149** [comment]
> @alistair3149 can't you test the `feat-querybuilder` branch to confirm if it fixes?

It is an issue on our production and we don't have a dev environment to test it unfortunately

**Comment by theinterwiki** [comment]
Are there any plans to fix this? I'm using 1.43 and dev-master. I recently tried to add SRF (Sematic Results Format), and it wont work with dev-master. I don't want to go back to 1.39. 1.41 is not supported, and 1.42 is buggy with it as well.

**Comment by JeroenDeDauw** [comment]
> RuntimeException: Identifier must not contain quote, dot or null characters: got '`de_smw_fpt_subp`'

Relevant code from `QuerySegmentListProcessor`

Getting the `$smwtable` var: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/QueryEngine/QuerySegmentListProcessor.php#L19

First use (should not be escaped, but is): https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/908110f7d493294dfff3fa2076c07bda0a7e2361/src/SQLStore/QueryEngine/QuerySegmentListProcessor.php#L342-L343

Second/final use (should be escaped) https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/908110f7d493294dfff3fa2076c07bda0a7e2361/src/SQLStore/QueryEngine/QuerySegmentListProcessor.php#L360

**Comment by stefahn** [comment]
Thanks for pushing this forward, Jeroen.

I did get this error on another wiki as well. But on a third wiki there is no error, even on pages that use SMW and ask queries...

Does anyone know if this error only appears when properties have a certain name or something else?

**Comment by JeroenDeDauw** [comment]
Is this an SMW issue then? Or a MW issue?

**Comment by dogsbody** [comment]
We have just upgraded our MediWiki install from 1.43.1 to 1.43.2 and hit this issue. We have had to roll back for now.

    SMW version: 5.0.2
    MW version: 1.43.2
    PHP version: 8.3.22 (fpm-fcgi)
    DB system: MySQL 8.0.42-33

**Comment by Oldiesmann** [comment]
Same here. My wiki isn't officially launched yet (I've mentioned it to some but am still finishing up some templates and such before I start on the main content) but it looks like I'm going back to 1.43.1 until this is fixed as I still want a working wiki.

**Comment by eidsnessje-nih** [comment]
I've been puzzling over this whole scenario, recently and I am starting to wonder if MW upstream project even meant to cause this many problems?

I was trying to prepare an SMW patch (and I may, yet) but still rebuildData.php jobs have been crashing just further down in the process and it's like whack-a-mole.

This is a mediawiki patch that seems like it may keep us in business a little more effectively, but as you will see, I don't have perspective. I don't know what MW is trying to achieve with this change in the first place, or what secondary problems were prevented by introducing this one. BUT, getting it to accept an already-quoted string instead of crashing 


diff --git a/includes/libs/rdbms/platform/SQLPlatform.php b/includes/libs/rdbms/platform/SQLPlatform.php
index 6e4f6de7df1..30673fdf030 100644
--- a/includes/libs/rdbms/platform/SQLPlatform.php
+++ b/includes/libs/rdbms/platform/SQLPlatform.php
@@ -88,12 +88,16 @@ class SQLPlatform implements ISQLPlatform {
        }

        public function addIdentifierQuotes( $s ) {
-               if ( strcspn( $s, "\0\"`'." ) !== strlen( $s ) ) {
+               $quoteChar = $this->getIdentifierQuoteChar();
+               if ( $s[0] === $quoteChar && $s[0] === $s[-1] &&
+                               strcspn( substr($s,1), "\0\"`'." )+2  == strlen($s) ) {
+                       wfDeprecatedMsg("MW SQLPlatform adds quotation marks, you already had the right ones. Do we really need to throw a DBLanguageError here?", '1.42' );
+                       return $s;
+               } else if ( strcspn( $s, "\0\"`'." ) !== strlen( $s ) ) {
                        throw new DBLanguageError(
                                "Identifier must not contain quote, dot or null characters: got '$s'"
                        );
                }
-               $quoteChar = $this->getIdentifierQuoteChar();
                return $quoteChar . $s . $quoteChar;
        }


While I'm talking about perspective... I've been reading through these issues, and I feel like I must be missing something. I'm not quite sure how it is that 5.0 has been marked compatible with 1.43, under these circumstances, for example. Is this actually not affecting very many 5.0+1.43 users, with SQLStore back end?

**Comment by jaideraf** [comment]
> SMW 5.0 has been marked compatible with MW 1.43 under these circumstances.

SMW 5.0 was tested against MW 1.43.0. This problems is in MW 1.43.2, right?

**Comment by dogsbody** [comment]
Does anyone know if the newly released SMW v5.1.0 (or even v6.0.0) fixes this issue please?

I can't see anything either way in the release notes.

I'm just trying to save myself having to try it and roll back :-) Thank you

**Comment by alistair3149** [comment]
The issue is resolved in 6.0.0.
If you're on MW 1.43.0+, it is recommended to use 6.0.0 over 5.X.X due to the compatibility issues.

**Comment by SuperSandro2000** [comment]
If the issue is resolved in 6.0.0, why is this issue then still open?
