### ISSUE TITLE
Error: Call to undefined method Wikimedia\Rdbms\LBFactorySimple::getReplicaDatabase()

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMediaWiki#5643]
### Setup

- MediaWiki | 1.39.7 (64425c7)16:12, 15 May 2024
- PHP | 7.4.33 (apache2handler)
- MariaDB | 10.5.23-MariaDB-0+deb11u1
- Elasticsearch | 7.10.2
- [Semantic MediaWiki](https://www.semantic-mediawiki.org/)	4.1.3

### Issue
Happening on https://sandbox.semantic-mediawiki.net/

Then running `php extensions/SemanticMediaWiki/maintenance/rebuildData.php -v --ignore-exceptions --with-maintenance-log`:

```
... updating 252347    [S: Utilisateur:Kghbln/Sandbox]
[97e6de1675e61a3e10c398e6] [no req]   Error: Call to undefined method Wikimedia\Rdbms\LBFactorySimple::getReplicaDatabase()
```
### Backtrace:
```
from /../w/extensions/Editcount/src/Editcount.php(103)
#0 /../w/extensions/Editcount/src/Editcount.php(34): Editcount->editsInNs()
#1 /../w/includes/specialpage/SpecialPage.php(701): Editcount->execute()
#2 /../w/includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run()
#3 /../w/includes/specialpage/SpecialPageFactory.php(1490): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#4 /../w/includes/parser/Parser.php(3221): MediaWiki\SpecialPage\SpecialPageFactory->capturePath()
#5 /../w/includes/parser/PPFrame_Hash.php(275): Parser->braceSubstitution()
#6 /../w/includes/parser/Parser.php(2953): PPFrame_Hash->expand()
#7 /../w/includes/parser/Parser.php(1609): Parser->replaceVariables()
#8 /../w/includes/parser/Parser.php(723): Parser->internalParse()
#9 /../w/includes/content/WikitextContentHandler.php(301): Parser->parse()
#10 /../w/includes/content/ContentHandler.php(1721): WikitextContentHandler->fillParserOutput()
#11 /../w/includes/content/Renderer/ContentRenderer.php(47): ContentHandler->getParserOutput()
#12 /../w/extensions/SemanticMediaWiki/includes/ContentParser.php(168): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput()
#13 /../w/extensions/SemanticMediaWiki/includes/ContentParser.php(130): SMW\ContentParser->fetchFromContent()
#14 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(199): SMW\ContentParser->parse()
#15 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(139): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#16 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#17 /../w/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(247): SMW\MediaWiki\Jobs\UpdateJob->run()
#18 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(472): SMW\SQLStore\Rebuilder\Rebuilder->rebuild()
#19 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(385): SMW\Maintenance\DataRebuilder->doUpdateById()
#20 /../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(224): SMW\Maintenance\DataRebuilder->rebuildAll()
#21 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#22 /../w/maintenance/includes/MaintenanceRunner.php(309): SMW\Maintenance\rebuildData->execute()
#23 /../w/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#24 /../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once(string)
#25 {main}
```
The `--ignore-exceptions' flag to "rebuildData.php" was not working, so I had to restart rebuilding data manually with the `-s` flag.

**Comment by Nikerabbit** [comment]
That's an error, not an exception. It seems to be coming from EditCount extension not from SMW.

**Comment by kghbln** [comment]
> That's an error, not an exception. It seems to be coming from EditCount extension not from SMW.

To be honest, as a sysadmin, I expect the script to continue under all circumstances when using the `--ingnore-exceptions` since the difference between error and exception is, in a sense, none of my business. Anyhow, I get what you mean and probably should have used the `--force-update` flag in this situation. Wondering if this one will really help here.

The reported issue is indeed an issue of the Editcount extension, I should have seen this, and was already reported with task https://phabricator.wikimedia.org/T359770

Thanks a bunch for the pointers.
