### ISSUE TITLE
[Special:Ask] Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by YvarRavy** [SemanticMediaWiki/SemanticMediaWiki#5745]
### Setup

- SMW version: 4.2.0
- MW version: 1.39
- PHP version: 7.4

### Issue
notices in the logs, it doesn't seem to break anything but i've noticed mutiple of these notices inside my logs which are quite annoying
Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:
```
PHP Notice: Trying to access array offset on value of type null
#0 /var/platform/mediawiki/1.39/core/20241101082131/extensions/SemanticMediaWiki/src/Query/Processor/ParamListProcessor.php(115): MWExceptionHandler::handleError(integer, string, string, integer, array)
#1 /var/platform/mediawiki/1.39/core/20241101082131/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(237): SMW\Query\Processor\ParamListProcessor->preprocess(array, boolean)
#2 /var/platform/mediawiki/1.39/core/20241101082131/extensions/SemanticMediaWiki/src/MediaWiki/Specials/Ask/ParametersProcessor.php(82): SMWQueryProcessor::getComponentsFromFunctionParams(array, boolean)
#3 /var/platform/mediawiki/1.39/core/20241101082131/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(283): SMW\MediaWiki\Specials\Ask\ParametersProcessor::process(WebRequest, string)
#4 /var/platform/mediawiki/1.39/core/20241101082131/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php(150): SMW\MediaWiki\Specials\SpecialAsk->extractQueryParameters(string)
#5 /var/platform/mediawiki/1.39/core/20241101082131/includes/specialpage/SpecialPage.php(701): SMW\MediaWiki\Specials\SpecialAsk->execute(string)
#6 /var/platform/mediawiki/1.39/core/20241101082131/includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run(string)
#7 /var/platform/mediawiki/1.39/core/20241101082131/includes/MediaWiki.php(316): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, RequestContext)
#8 /var/platform/mediawiki/1.39/core/20241101082131/includes/MediaWiki.php(904): MediaWiki->performRequest()
#9 /var/platform/mediawiki/1.39/core/20241101082131/includes/MediaWiki.php(562): MediaWiki->main()
#10 /var/platform/mediawiki/1.39/core/20241101082131/index.php(50): MediaWiki->run()
#11 /var/platform/mediawiki/1.39/core/20241101082131/index.php(46): wfIndexMain()
#12 /var/platform/mediawiki/1.39/core/20241101082131/wikiroot/index.php(7): require(string)
#13 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

**Comment by jaideraf** [comment]
Fixed on https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5746
