### ISSUE TITLE
Failed asserting that exception of type "TypeError" matches expected exception "\SMW\Exception\ClassNotFoundException".

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/SemanticMediaWiki#5869]
## Bug Report: TypeError in `SearchEngineFactoryTest` with MediaWiki 1.41

**Summary**  
When running tests against MediaWiki 1.41, the `SearchEngineFactoryTest` fails with a `TypeError` instead of the expected `RuntimeException`. This issue does not occur in MediaWiki 1.40.

**Error**  
```
TypeError: SearchEngineFactory::getSearchEngineClass(): Argument #1 ($dbProvider) must be of type Wikimedia\Rdbms\IConnectionProvider, Mock_Database_e328ae58 given
```

**Suspected Root Cause**  
In MediaWiki 1.41, the `SearchEngineFactory::getSearchEngineClass()` method enforces stricter type requirements, requiring an argument of type `Wikimedia\Rdbms\IConnectionProvider`. The test uses a mock object (`Mock_Database`) that does not implement this interface.

**Suggested Fix**  
Update the test to use a mock object that implements the `Wikimedia\Rdbms\IConnectionProvider` interface. Example:  

```php
$mockDbProvider = $this->createMock(\Wikimedia\Rdbms\IConnectionProvider::class);
```

This should resolve the TypeError and allow the test to behave as intended.

**Comment by gesinn-it-gea** [comment]
@paladox is this issue something you like to take care of?

**Comment by gesinn-it-gea** [comment]
If we fix this, we are close to getting "green lights" for MW 1.41

**Comment by paladox** [comment]
There's already an issue for this: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5782

I had looked into it but I couldn't figure it out. So was leaving it to someone who knows more.

I left a comment here https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5782#issuecomment-2542401548

**Comment by gesinn-it-gea** [comment]
Maybe something like this (untested pseudo code):

```
public function testInvalidFallbackSearchEngineThrowsException() {
    // Create a mock for IConnectionProvider
    $mockDbProvider = $this->createMock(\Wikimedia\Rdbms\IConnectionProvider::class);
    
    // Set up the expected behavior of the mock if necessary
    // $mockDbProvider->method('methodName')->willReturn(...);

    // Ensure the factory method is called with a valid mock
    $this->expectException(\RuntimeException::class);
    $this->expectExceptionMessage('Expected exception message here');

    $factory = new \SearchEngineFactory();
    $factory->getSearchEngineClass($mockDbProvider); // Pass the valid mock
}
```

**Comment by paladox** [comment]
The main code is broken as well: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/eb398136b22f3377c8dcb9253edc69f241e07697/src/MediaWiki/Search/SearchEngineFactory.php#L35

**Comment by gesinn-it-gea** [comment]
@JeroenDeDauw @Seb35 can you help with that?

**Comment by jaideraf** [comment]
I don't know it it helps, but this is the stack shown when we visit Special:Search:

```
[bb8aa6178af615de0478c5c6] /w/index.php?search=test&title=Special%3ASearch&go=Ir 
TypeError: SearchEngineFactory::getSearchEngineClass(): Argument #1 ($dbProvider) 
must be of type Wikimedia\Rdbms\IConnectionProvider, Wikimedia\Rdbms\DBConnRef given, 
called in /extensions/SemanticMediaWiki/src/Services/mediawiki.php on line 148

Backtrace:

from /includes/search/SearchEngineFactory.php(80)
#0 /extensions/SemanticMediaWiki/src/Services/mediawiki.php(148): SearchEngineFactory::getSearchEngineClass(Wikimedia\Rdbms\DBConnRef)
#1 [internal function]: Onoi\CallbackContainer\CallbackContainerBuilder->SMW\Services\{closure}(Onoi\CallbackContainer\CallbackContainerBuilder, Wikimedia\Rdbms\DBConnRef)
#2 /vendor/onoi/callback-container/src/CallbackContainerBuilder.php(260): call_user_func_array(Closure, array)
#3 /vendor/onoi/callback-container/src/CallbackContainerBuilder.php(181): Onoi\CallbackContainer\CallbackContainerBuilder->getReturnValueFromCallbackHandlerFor(string, array)
#4 /extensions/SemanticMediaWiki/src/Services/ServicesFactory.php(175): Onoi\CallbackContainer\CallbackContainerBuilder->create(string, Wikimedia\Rdbms\DBConnRef)
#5 /extensions/SemanticMediaWiki/src/MediaWiki/Search/SearchEngineFactory.php(39): SMW\Services\ServicesFactory->create(string, Wikimedia\Rdbms\DBConnRef)
#6 /extensions/SemanticMediaWiki/src/MediaWiki/Search/ExtendedSearchEngine.php(43): SMW\MediaWiki\Search\SearchEngineFactory->newFallbackSearchEngine(Wikimedia\Rdbms\DBConnRef)
#7 /vendor/wikimedia/object-factory/src/ObjectFactory.php(240): SMW\MediaWiki\Search\ExtendedSearchEngine->__construct()
#8 /includes/search/SearchEngineFactory.php(69): Wikimedia\ObjectFactory\ObjectFactory::getObjectFromSpec(array, array)
#9 /includes/specials/SpecialSearch.php(841): SearchEngineFactory->create(NULL)
#10 /includes/specials/SpecialSearch.php(298): MediaWiki\Specials\SpecialSearch->getSearchEngine()
#11 /includes/specials/SpecialSearch.php(205): MediaWiki\Specials\SpecialSearch->load()
#12 /includes/specialpage/SpecialPage.php(719): MediaWiki\Specials\SpecialSearch->execute(NULL)
#13 /includes/specialpage/SpecialPageFactory.php(1669): MediaWiki\SpecialPage\SpecialPage->run(NULL)
#14 /includes/actions/ActionEntryPoint.php(504): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, MediaWiki\Context\RequestContext)
#15 /includes/actions/ActionEntryPoint.php(145): MediaWiki\Actions\ActionEntryPoint->performRequest()
#16 /includes/MediaWikiEntryPoint.php(199): MediaWiki\Actions\ActionEntryPoint->execute()
#17 /index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#18 {main}
```

**Comment by paladox** [comment]
I think the solution to this is to change

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/eb398136b22f3377c8dcb9253edc69f241e07697/src/MediaWiki/Search/SearchEngineFactory.php#L35

to `$connection = MediaWiki\ MediaWikiServices::getInstance()-> getDBLoadBalancer();`

I'm not entirely sure if we need to do this here https://github.com/SemanticMediaWiki/SemanticMediaWiki/blame/9e344b00df65cb932eac40dc937df04ebe9340cd/src/Setup.php#L191 or why we have that. Would using `MediaWiki\ MediaWikiServices::getInstance()-> getDBLoadBalancer();` be fine @gesinn-it-gea ?

Ofc version check it to do it on MW 1.41+ only.

And remove the type check in the function and instead we could do something like:

```
		if ( $connection !== null &&
			!$connection instanceof IConnectionProvider &&
			!$connection instanceof IDatabase
		) {
			// TODO: Once MW 1.39 support is dropped, we can put the type as IConnectionProvider.
			throw new RuntimeException( 'Expected $connection be instanceof either IConnectionProvider or IDatabase' );
		}
```

**Comment by gesinn-it-gea** [comment]
@JeroenDeDauw can you please have a look. You definitely have more experience with the storage backend...

**Comment by jaideraf** [comment]
We do not support MediaWiki 1.41 anymore, and I suspect this is solved somehow (even if the feature is not present anymore). So I am closing it.
