### ISSUE TITLE
SQLStore / sqlite, postgres RAND() is an unknown function

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#764]
SMW 2.2-alpha/sqlite doing something like:
```
{{#ask:[[Page content language::+]]
|?Page content language
|format=broadtable
|limit=1
|link=all
|order=random
|headers=show
|mainlabel=-
|searchlabel=… その他の結果
|class=sortable wikitable smwtable
}}
```
will yield
```
Unexpected non-MediaWiki exception encountered, of type "RuntimeException"
[fd2cf2a3] /sandbox-import/index.php?title=%E7%89%B9%E5%88%A5%3A%E5%95%8F%E3%81%84%E5%90%88%E3%82%8F%E3%81%9B&q=%5B%5BPage+content+language%3A%3A%2B%5D%5D&po=%3FPage+content+language%0D%0A&eq=yes&p%5Bformat%5D=broadtable&sort_num=&order_num=ASC&p%5Blimit%5D=1&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Border%5D%5Brandom%5D=1&p%5Bheaders%5D=show&p%5Bmainlabel%5D=-&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=%E2%80%A6+%E3%81%9D%E3%81%AE%E4%BB%96%E3%81%AE%E7%B5%90%E6%9E%9C&p%5Bdefault%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&eq=yes Exception from line 176 of C:\xampp\htdocs\sandbox-import\extensions\SemanticMediaWiki\includes\src\MediaWiki\Database.php: A database error has occurred. Did you forget to run maintenance/update.php after upgrading? See: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
Query: SELECT DISTINCT t2.smw_id AS id,t2.smw_title AS t,t2.smw_namespace AS ns,t2.smw_iw AS iw,t2.smw_subobject AS so,t2.smw_sortkey AS sortkey FROM smw_object_ids AS t2 INNER JOIN smw_di_blob AS t0 ON t2.smw_id=t0.s_id WHERE (t0.p_id='262') ORDER BY RAND() LIMIT 6 
Function: SMW::getQueryResult
Error: 1 no such function: RAND

#0 ...\includes\db\Database.php(1182): DatabaseBase->reportQueryError('no such functio...', 1, 'SELECT DISTINC...', 'SMW::getQueryRe...', false)
#1 ...\includes\db\Database.php(1650): DatabaseBase->query('SELECT DISTINC...', 'SMW::getQueryRe...')
#2 ...\extensions\SemanticMediaWiki\includes\src\MediaWiki\Database.php(174): DatabaseBase->select('smw_object_ids ...', 'DISTINCT t2.smw...', '(t0.p_id='262')', 'SMW::getQueryRe...', Array)
#3 ...\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3_Queries.php(472): SMW\MediaWiki\Database->select('smw_object_ids ...', 'DISTINCT t2.smw...', '(t0.p_id='262')', 'SMW::getQueryRe...', Array)
#4 ...\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3_Queries.php(350): SMWSQLStore3QueryEngine->getInstanceQueryResult(Object(SMWQuery), 2)
#5 ...\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3.php(349): SMWSQLStore3QueryEngine->getQueryResult(Object(SMWQuery))
#6 ...\extensions\SemanticMediaWiki\includes\storage\SQLStore\SMW_SQLStore3.php(339): SMWSQLStore3->fetchQueryResult(Object(SMWQuery))
```

because of (see [0])
```
$result['ORDER BY'] = ( array_key_exists( 'ORDER BY', $result ) ? $result['ORDER BY'] . ', ' : '' ) . ' RAND() ';
```

[0] http://stackoverflow.com/questions/1253561/sqlite-order-by-rand

**Comment by mwjames** [comment]
Add the following to:

`SMW\MediaWiki\Database::select`

```php
		if ( $this->getType() == 'sqlite' ) {
			...
			if ( isset( $options['ORDER BY'] ) ) {
				$options['ORDER BY'] = str_replace( 'RAND', 'random', $options['ORDER BY'] );
			}
		}
```
`SMW\MediaWiki\Database::query`:
```php
		if ( $this->getType() == 'sqlite' ) {
			...
			$sql = str_replace( 'RAND', 'random', $sql );
		}
```

**Comment by JeroenDeDauw** [comment]
@mwjames are you waiting on feedback? Looks good to me.

**Comment by mwjames** [comment]
> are you waiting on feedback? Looks good to me.

It required a test with postgres complaining as well.

```
SMW\Tests\Integration\Query\RandomQueryResultOrderIntegrationTest::testRandomOrder
pg_query(): Query failed: ERROR:  function rand() does not exist
LINE 1: ....smw_id=t0.s_id  WHERE (t0.p_id='134')  ORDER BY  RAND()  LI...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by JeroenDeDauw** [comment]
We should add a "has a lot of labels" label :)
